-- PG-002 learned-deck metadata canonicalization package
-- Generated from learned_deck_metadata_canonicalization_pg002_dryrun_20260620_0718.json
-- Scope: commander_learned_decks.metadata only, active learned decks only.
-- Rows in package: 59
-- Do not execute without explicit Rafael approval for the exact command.
-- Rollback restores metadata captured before PG-002 apply.
BEGIN;
WITH plan(row_id, source_ref, commander_name, metadata_before) AS (
  VALUES
  ('174b989b-f25f-4eb9-b224-80585824ba53'::uuid, 'learned_deck:105', 'Aang, at the Crossroads', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('0d9058af-51f1-4e2c-9dfa-d813880ae91c'::uuid, 'learned_deck:112', 'Akiri, Line-Slinger', '{"board_wipe_count":0,"combined_commander_color_identity":["G","R","U","W"],"commander_identity_model":{"base_color_identity":["R","W"],"combined_color_identity":["G","R","U","W"],"declared_deck_name":"Akiri, Line-Slinger + Thrasios, Triton Hero","identity_components":[{"color_identity":["G","U"],"name":"Thrasios, Triton Hero","source":"deck_name_commander_component"}],"primary_commander_name":"Akiri, Line-Slinger","requires_first_class_persistence":true,"source":"deck_name_commander_component","status":"combined_identity_inferred"},"draw_count":0,"engine_count":0,"partner_identity_backfill":{"mode":"dry_run_plan_only","requires_explicit_postgresql_mutation_approval":true,"source":"learned_deck_partner_identity_inference_2026_06_20","source_ref":"learned_deck:112"},"partner_identity_candidates":[{"color_identity":["G","U"],"name":"Thrasios, Triton Hero","reason":"deck_name_commander_component"}],"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('ca6a6b16-c841-498f-8601-180767d04cae'::uuid, 'learned_deck:135', 'Arcum Dagsson', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('9e517819-587f-4341-ad95-1da24e535b13'::uuid, 'learned_deck:5', 'Atraxa, Praetors'' Voice', '{"board_wipe_count":0,"draw_count":12,"engine_count":7,"protection_count":6,"ramp_count":14,"recursion_count":2,"removal_count":7,"total_lands":36,"tutor_count":0,"wincon_count":1}'::jsonb),
  ('55262e78-24f8-4a79-b4f9-4da7000e6530'::uuid, 'learned_deck:150', 'Brigid, Clachan''s Heart', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('b8221a6b-af2b-4f7e-89c3-cea07e2d071f'::uuid, 'learned_deck:93', 'Dargo, the Shipwrecker', '{"board_wipe_count":0,"combined_commander_color_identity":["B","R","W"],"commander_identity_model":{"base_color_identity":["R"],"combined_color_identity":["B","R","W"],"declared_deck_name":"Dargo, the Shipwrecker + Tymna the Weaver","identity_components":[{"color_identity":["B","W"],"name":"Tymna the Weaver","source":"deck_name_commander_component"}],"primary_commander_name":"Dargo, the Shipwrecker","requires_first_class_persistence":true,"source":"deck_name_commander_component","status":"combined_identity_inferred"},"draw_count":0,"engine_count":0,"partner_identity_backfill":{"mode":"dry_run_plan_only","requires_explicit_postgresql_mutation_approval":true,"source":"learned_deck_partner_identity_inference_2026_06_20","source_ref":"learned_deck:93"},"partner_identity_candidates":[{"color_identity":["B","W"],"name":"Tymna the Weaver","reason":"deck_name_commander_component"}],"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('a95ca55c-be27-4a42-ba91-afcdf2184983'::uuid, 'learned_deck:111', 'Dihada, Binder of Wills', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('8a857008-cb5c-4138-a179-ec6a9856b70b'::uuid, 'learned_deck:178', 'Elsha of the Infinite', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('2ca3d1b2-2028-44e9-9c23-76fe2493729e'::uuid, 'learned_deck:149', 'Etali, Primal Conqueror', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('c61c7754-e363-406c-8514-85359f88eac6'::uuid, 'learned_deck:125', 'Falco Spara, Pactweaver', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('3912c893-f099-4d18-87f1-869705fa1e08'::uuid, 'learned_deck:6', 'Grand Arbiter Augustin IV', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('899acd46-e64b-410f-8676-7a8a32783bf1'::uuid, 'learned_deck:148', 'Grist, the Hunger Tide', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('77c57f06-2064-44a7-a4f9-3809d118a107'::uuid, 'learned_deck:147', 'Gwen Stacy', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('809809cd-3dc3-46c7-8575-25bf6f51f032'::uuid, 'learned_deck:126', 'Inalla, Archmage Ritualist', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('7a7001a1-aebe-4963-830f-31031f92c105'::uuid, 'learned_deck:110', 'Ishai, Ojutai Dragonspeaker', '{"board_wipe_count":0,"combined_commander_color_identity":["R","U","W"],"commander_identity_model":{"base_color_identity":["U","W"],"combined_color_identity":["R","U","W"],"declared_deck_name":"Ishai, Ojutai Dragonspeaker + Rograkh, Son of Rohgahh","identity_components":[{"color_identity":["R"],"name":"Rograkh, Son of Rohgahh","source":"deck_name_commander_component"}],"primary_commander_name":"Ishai, Ojutai Dragonspeaker","requires_first_class_persistence":true,"source":"deck_name_commander_component","status":"combined_identity_inferred"},"draw_count":0,"engine_count":0,"partner_identity_backfill":{"mode":"dry_run_plan_only","requires_explicit_postgresql_mutation_approval":true,"source":"learned_deck_partner_identity_inference_2026_06_20","source_ref":"learned_deck:110"},"partner_identity_candidates":[{"color_identity":["R"],"name":"Rograkh, Son of Rohgahh","reason":"deck_name_commander_component"}],"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('de69e590-452b-4e2d-bc64-df7145a930f3'::uuid, 'learned_deck:100', 'Jeska, Thrice Reborn', '{"board_wipe_count":0,"combined_commander_color_identity":["B","R","W"],"commander_identity_model":{"base_color_identity":["R"],"combined_color_identity":["B","R","W"],"declared_deck_name":"Jeska, Thrice Reborn + Tymna the Weaver","identity_components":[{"color_identity":["B","W"],"name":"Tymna the Weaver","source":"deck_name_commander_component"}],"primary_commander_name":"Jeska, Thrice Reborn","requires_first_class_persistence":true,"source":"deck_name_commander_component","status":"combined_identity_inferred"},"draw_count":0,"engine_count":0,"partner_identity_backfill":{"mode":"dry_run_plan_only","requires_explicit_postgresql_mutation_approval":true,"source":"learned_deck_partner_identity_inference_2026_06_20","source_ref":"learned_deck:100"},"partner_identity_candidates":[{"color_identity":["B","W"],"name":"Tymna the Weaver","reason":"deck_name_commander_component"}],"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('421b13ef-c325-42e4-821c-8123dea59d15'::uuid, 'learned_deck:116', 'K-9, Mark I', '{"board_wipe_count":0,"combined_commander_color_identity":["G","R","U","W"],"commander_identity_model":{"base_color_identity":["U"],"combined_color_identity":["G","R","U","W"],"declared_deck_name":"K-9, Mark I + The Fourteenth Doctor","identity_components":[{"color_identity":["G","R","U","W"],"name":"The Fourteenth Doctor","source":"deck_name_commander_component"}],"primary_commander_name":"K-9, Mark I","requires_first_class_persistence":true,"source":"deck_name_commander_component","status":"combined_identity_inferred"},"draw_count":0,"engine_count":0,"partner_identity_backfill":{"mode":"dry_run_plan_only","requires_explicit_postgresql_mutation_approval":true,"source":"learned_deck_partner_identity_inference_2026_06_20","source_ref":"learned_deck:116"},"partner_identity_candidates":[{"color_identity":["G","R","U","W"],"name":"The Fourteenth Doctor","reason":"deck_name_commander_component"}],"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('0bfa4377-4e94-42e6-9188-c7a96ac858e3'::uuid, 'learned_deck:194', 'Kefka, Court Mage', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('9bb7b8d0-76b0-40af-aa2e-a6df04e37a81'::uuid, 'learned_deck:88', 'Kefka, Court Mage // Kefka, Ruler of Ruin', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('a2f617f8-12d0-4fff-8fbc-019cb054024f'::uuid, 'learned_deck:195', 'Kenrith, the Returned King', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('3cb341d3-ff67-4337-9d07-982e8a133743'::uuid, 'learned_deck:3', 'Kinnan, Bonder Prodigy', '{"board_wipe_count":0,"draw_count":3,"engine_count":2,"protection_count":3,"ramp_count":4,"recursion_count":0,"removal_count":3,"total_lands":29,"tutor_count":1,"wincon_count":0}'::jsonb),
  ('01a1c848-04ef-4c48-b1eb-e69b8836a9cd'::uuid, 'learned_deck:7', 'Korvold, Fae-Cursed King', '{"board_wipe_count":0,"draw_count":1,"engine_count":3,"protection_count":0,"ramp_count":3,"recursion_count":1,"removal_count":1,"total_lands":25,"tutor_count":1,"wincon_count":0}'::jsonb),
  ('2d18afa2-561b-4c69-ad89-ce4bfb432770'::uuid, 'learned_deck:173', 'Krark, the Thumbless', '{"board_wipe_count":0,"combined_commander_color_identity":["R","U"],"commander_identity_model":{"base_color_identity":["R"],"combined_color_identity":["R","U"],"declared_deck_name":"Krark, the Thumbless + Sakashima of a Thousand Faces","identity_components":[{"color_identity":["U"],"name":"Sakashima of a Thousand Faces // Sakashima of a Thousand Faces","source":"deck_name_commander_component"}],"primary_commander_name":"Krark, the Thumbless","requires_first_class_persistence":true,"source":"deck_name_commander_component","status":"combined_identity_inferred"},"draw_count":0,"engine_count":0,"partner_identity_backfill":{"mode":"dry_run_plan_only","requires_explicit_postgresql_mutation_approval":true,"source":"learned_deck_partner_identity_inference_2026_06_20","source_ref":"learned_deck:173"},"partner_identity_candidates":[{"color_identity":["U"],"name":"Sakashima of a Thousand Faces // Sakashima of a Thousand Faces","reason":"deck_name_commander_component"}],"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('367003b1-36f2-42ec-a015-fa605d0a9b97'::uuid, 'learned_deck:89', 'Kraum, Ludevic''s Opus', '{"board_wipe_count":0,"combined_commander_color_identity":["B","R","U","W"],"commander_identity_model":{"base_color_identity":["R","U"],"combined_color_identity":["B","R","U","W"],"declared_deck_name":"Kraum, Ludevic''s Opus + Tymna the Weaver","identity_components":[{"color_identity":["B","W"],"name":"Tymna the Weaver","source":"deck_name_commander_component"}],"primary_commander_name":"Kraum, Ludevic''s Opus","requires_first_class_persistence":true,"source":"deck_name_commander_component","status":"combined_identity_inferred"},"draw_count":0,"engine_count":0,"partner_identity_backfill":{"mode":"dry_run_plan_only","requires_explicit_postgresql_mutation_approval":true,"source":"learned_deck_partner_identity_inference_2026_06_20","source_ref":"learned_deck:89"},"partner_identity_candidates":[{"color_identity":["B","W"],"name":"Tymna the Weaver","reason":"deck_name_commander_component"}],"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('a4f31814-8d01-4b58-baec-d572a2465e85'::uuid, 'learned_deck:1', 'Krenko, Mob Boss', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('3568a90a-cd07-48b1-b4e9-c4f2c8d31f15'::uuid, 'learned_deck:98', 'Leonardo, the Balance', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('62efa366-2995-4ec3-9ea1-9cecce242f93'::uuid, 'learned_deck:131', 'Lumra, Bellow of the Woods', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('bbd57b33-c813-460a-addb-4a8da24299d5'::uuid, 'learned_deck:153', 'Magda, Brazen Outlaw', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('5e6d0cbe-6b58-4bbd-8f2f-62aa03bf0cd9'::uuid, 'learned_deck:90', 'Malcolm, Keen-Eyed Navigator', '{"board_wipe_count":0,"combined_commander_color_identity":["B","R","U"],"commander_identity_model":{"base_color_identity":["U"],"combined_color_identity":["B","R","U"],"declared_deck_name":"Malcolm, Keen-Eyed Navigator + Vial Smasher the Fierce","identity_components":[{"color_identity":["B","R"],"name":"Vial Smasher the Fierce","source":"deck_name_commander_component"},{"color_identity":["R"],"name":"Kediss, Emberclaw Familiar","source":"partner_text"}],"primary_commander_name":"Malcolm, Keen-Eyed Navigator","requires_first_class_persistence":true,"source":"mixed_commander_identity_inference","status":"combined_identity_inferred"},"draw_count":0,"engine_count":0,"partner_identity_backfill":{"mode":"dry_run_plan_only","requires_explicit_postgresql_mutation_approval":true,"source":"learned_deck_partner_identity_inference_2026_06_20","source_ref":"learned_deck:90"},"partner_identity_candidates":[{"color_identity":["B","R"],"name":"Vial Smasher the Fierce","reason":"deck_name_commander_component"},{"color_identity":["R"],"name":"Kediss, Emberclaw Familiar","reason":"partner_text"}],"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('95973355-dc62-46b3-90d5-7a96cc1c24d9'::uuid, 'learned_deck:146', 'Marneus Calgar', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('b11978f5-ef2c-455d-8316-9916034b5fb0'::uuid, 'learned_deck:193', 'Najeela, the Blade-Blossom', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('d4315b96-c01d-4894-950d-e840345e14a4'::uuid, 'learned_deck:91', 'Norman Osborn // Green Goblin', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('b46615ce-7b4b-4fbe-9fd9-8fc9f4be56ca'::uuid, 'learned_deck:83', 'Ob Nixilis, Captive Kingpin', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('6a8999d9-bc1d-4c3a-9d24-07812b65d2c5'::uuid, 'learned_deck:108', 'Prismari, the Inspiration', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('d50716d0-2991-4a2e-ae7d-7d050fb024c6'::uuid, 'learned_deck:104', 'Ral, Monsoon Mage', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('5242b94b-954e-4a32-abc6-8b5fa2a4cabb'::uuid, 'learned_deck:85', 'Rograkh, Son of Rohgahh', '{"board_wipe_count":0,"combined_commander_color_identity":["B","R","U"],"commander_identity_model":{"base_color_identity":["R"],"combined_color_identity":["B","R","U"],"declared_deck_name":"Rograkh, Son of Rohgahh + Silas Renn, Seeker Adept","identity_components":[{"color_identity":["B","U"],"name":"Silas Renn, Seeker Adept","source":"deck_name_commander_component"}],"primary_commander_name":"Rograkh, Son of Rohgahh","requires_first_class_persistence":true,"source":"deck_name_commander_component","status":"combined_identity_inferred"},"draw_count":0,"engine_count":0,"partner_identity_backfill":{"mode":"dry_run_plan_only","requires_explicit_postgresql_mutation_approval":true,"source":"learned_deck_partner_identity_inference_2026_06_20","source_ref":"learned_deck:85"},"partner_identity_candidates":[{"color_identity":["B","U"],"name":"Silas Renn, Seeker Adept","reason":"deck_name_commander_component"}],"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('c4fb511d-254d-4b39-a717-7c8c4c4f308e'::uuid, 'learned_deck:114', 'Rowan, Scion of War', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('17431e39-a9de-4d0e-9ee6-0efdc54830bc'::uuid, 'learned_deck:127', 'Sauron, Lord of the Rings', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('ca8797e7-8c85-4e20-8fce-a35287250e0a'::uuid, 'learned_deck:118', 'Scion of the Ur-Dragon', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('3da8a228-b5b6-4cdf-85da-801bd4f49006'::uuid, 'learned_deck:137', 'Selvala, Explorer Returned', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('afe260d7-5718-495a-910c-79bce89b145a'::uuid, 'learned_deck:84', 'Sisay, Weatherlight Captain', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('6bf0548b-615d-454b-9ead-39b740961042'::uuid, 'learned_deck:122', 'Tannuk, Memorial Ensign', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('f8b99946-cf5b-4449-8f6f-e79fc6874a24'::uuid, 'learned_deck:107', 'Tayam, Luminous Enigma', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('a4c67ed8-8d32-46e3-9a22-13e1f89c5030'::uuid, 'learned_deck:170', 'Terra, Magical Adept', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('e046866b-cf26-4764-8df3-a9666f26ea06'::uuid, 'learned_deck:129', 'The Cabbage Merchant', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('67d83d52-4ef8-40c1-9f22-cfd44dff3459'::uuid, 'learned_deck:124', 'The Emperor of Palamecia', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('7d1a46ce-a543-49ed-9a13-7d049d45d927'::uuid, 'learned_deck:160', 'The Gitrog Monster', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('9c0a710f-a5b6-48ce-8173-37a387de4bc4'::uuid, 'learned_deck:102', 'The Wandering Minstrel', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('0e37c8b3-f931-47b9-9eec-7d4b755ccd78'::uuid, 'learned_deck:87', 'Thrasios, Triton Hero', '{"board_wipe_count":0,"combined_commander_color_identity":["G","U","W"],"commander_identity_model":{"base_color_identity":["G","U"],"combined_color_identity":["G","U","W"],"declared_deck_name":"Thrasios, Triton Hero + Yoshimaru, Ever Faithful","identity_components":[{"color_identity":["W"],"name":"Yoshimaru, Ever Faithful","source":"deck_name_commander_component"}],"primary_commander_name":"Thrasios, Triton Hero","requires_first_class_persistence":true,"source":"deck_name_commander_component","status":"combined_identity_inferred"},"draw_count":0,"engine_count":0,"partner_identity_backfill":{"mode":"dry_run_plan_only","requires_explicit_postgresql_mutation_approval":true,"source":"learned_deck_partner_identity_inference_2026_06_20","source_ref":"learned_deck:87"},"partner_identity_candidates":[{"color_identity":["W"],"name":"Yoshimaru, Ever Faithful","reason":"deck_name_commander_component"}],"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('73dfe88a-0ca7-4f94-9bd9-d04c53959c98'::uuid, 'learned_deck:96', 'Tivit, Seller of Secrets', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('4e00fcc2-85c6-4fc5-b564-e3f82b751054'::uuid, 'learned_deck:196', 'Umbris, Fear Manifest', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('0fd589ad-e9f8-4b5e-9201-dc352add73de'::uuid, 'learned_deck:4', 'Urza, Lord High Artificer', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('8bb2a367-4879-4713-80ed-e481e20ba17c'::uuid, 'learned_deck:181', 'Vivi Ornitier', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('fb28acf0-c575-435a-be90-45c096a579ff'::uuid, 'learned_deck:2', 'Winota, Joiner of Forces', '{"board_wipe_count":1,"draw_count":3,"engine_count":10,"protection_count":10,"ramp_count":10,"recursion_count":2,"removal_count":8,"total_lands":34,"tutor_count":1,"wincon_count":3}'::jsonb),
  ('e5a68229-3b7e-4325-8d0e-2616113225fd'::uuid, 'learned_deck:120', 'Yorion, Sky Nomad', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('9a605ed4-06ad-42ff-b0b4-939e2206b83f'::uuid, 'learned_deck:152', 'Y''shtola, Night''s Blessed', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('ca8db21f-a848-490e-892e-3bcd06852abc'::uuid, 'learned_deck:95', 'Yuriko, the Tiger''s Shadow', '{"board_wipe_count":0,"draw_count":14,"engine_count":8,"protection_count":5,"ramp_count":8,"recursion_count":4,"removal_count":9,"total_lands":33,"tutor_count":4,"wincon_count":0}'::jsonb),
  ('ed4de7c7-d2ab-4dde-b630-2756309e3dd1'::uuid, 'learned_deck:128', 'Zhulodok, Void Gorger', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb),
  ('8492c554-0f19-475c-a600-0823da757fac'::uuid, 'learned_deck:151', 'Zirda, the Dawnwaker', '{"board_wipe_count":0,"draw_count":0,"engine_count":0,"protection_count":0,"ramp_count":0,"recursion_count":0,"removal_count":0,"total_lands":0,"tutor_count":0,"wincon_count":0}'::jsonb)
)
UPDATE commander_learned_decks AS cld
SET metadata = plan.metadata_before,
    updated_at = NOW()
FROM plan
WHERE cld.id = plan.row_id
  AND cld.source_ref = plan.source_ref
  AND cld.is_active IS TRUE
RETURNING
  cld.id,
  cld.source_ref,
  cld.commander_name,
  cld.metadata ->> 'total_lands' AS restored_total_lands;
COMMIT;
