BEGIN;

CREATE SCHEMA IF NOT EXISTS manaloom_deploy_audit;

CREATE TABLE manaloom_deploy_audit.pg294_xmage_creature_etb_life_gain_wave_20260701_100228 AS
SELECT *
FROM public.card_battle_rules
WHERE normalized_name IN ('amateur hero', 'angel of mercy', 'arashin cleric', 'arborback stomper', 'aven battle priest', 'aven of enduring hope', 'bulwark giant', 'cathedral sanctifier', 'centaur healer', 'courier griffin', 'dawning angel', 'devout monk', 'healer of the glade', 'hill giant herdgorger', 'honey mammoth', 'inspiring cleric', 'jedit''s dragoons', 'kemba''s skyguard', 'koala-sheep', 'lone missionary', 'mesa cavalier', 'mossbeard ancient', 'peace strider', 'primordial pachyderm', 'ravenous lindwurm', 'savannah sage', 'shu grain caravan', 'shu soldier-farmers', 'spiritual guardian', 'springmane cervin', 'staunch defenders', 'sylvan brushstrider', 'temple acolyte', 'teroh''s faithful', 'tireless missionaries', 'turntimber ascetic', 'venerable monk')
   OR normalized_name LIKE 'amateur hero // %'
   OR normalized_name LIKE 'angel of mercy // %'
   OR normalized_name LIKE 'arashin cleric // %'
   OR normalized_name LIKE 'arborback stomper // %'
   OR normalized_name LIKE 'aven battle priest // %'
   OR normalized_name LIKE 'aven of enduring hope // %'
   OR normalized_name LIKE 'bulwark giant // %'
   OR normalized_name LIKE 'cathedral sanctifier // %'
   OR normalized_name LIKE 'centaur healer // %'
   OR normalized_name LIKE 'courier griffin // %'
   OR normalized_name LIKE 'dawning angel // %'
   OR normalized_name LIKE 'devout monk // %'
   OR normalized_name LIKE 'healer of the glade // %'
   OR normalized_name LIKE 'hill giant herdgorger // %'
   OR normalized_name LIKE 'honey mammoth // %'
   OR normalized_name LIKE 'inspiring cleric // %'
   OR normalized_name LIKE 'jedit''s dragoons // %'
   OR normalized_name LIKE 'kemba''s skyguard // %'
   OR normalized_name LIKE 'koala-sheep // %'
   OR normalized_name LIKE 'lone missionary // %'
   OR normalized_name LIKE 'mesa cavalier // %'
   OR normalized_name LIKE 'mossbeard ancient // %'
   OR normalized_name LIKE 'peace strider // %'
   OR normalized_name LIKE 'primordial pachyderm // %'
   OR normalized_name LIKE 'ravenous lindwurm // %'
   OR normalized_name LIKE 'savannah sage // %'
   OR normalized_name LIKE 'shu grain caravan // %'
   OR normalized_name LIKE 'shu soldier-farmers // %'
   OR normalized_name LIKE 'spiritual guardian // %'
   OR normalized_name LIKE 'springmane cervin // %'
   OR normalized_name LIKE 'staunch defenders // %'
   OR normalized_name LIKE 'sylvan brushstrider // %'
   OR normalized_name LIKE 'temple acolyte // %'
   OR normalized_name LIKE 'teroh''s faithful // %'
   OR normalized_name LIKE 'tireless missionaries // %'
   OR normalized_name LIKE 'turntimber ascetic // %'
   OR normalized_name LIKE 'venerable monk // %';

DO $$
DECLARE
  v_missing jsonb;
BEGIN
  WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('amateur hero', 'Amateur Hero', 'bb3fdc4473671cde3f7974fb0c0f529a', 'battle_rule_v1:cf6345f2abe140852d655085e4562ae7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AmateurHero translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('angel of mercy', 'Angel of Mercy', 'e67201c53659f5c13214d1a60cd8f652', 'battle_rule_v1:30e3eacd02324c36a9a41cf3acd50557', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"flying":true,"keywords":["flying"],"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AngelOfMercy translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('arashin cleric', 'Arashin Cleric', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ArashinCleric translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('arborback stomper', 'Arborback Stomper', '00e8e649110944d7dbb9caed64963c9d', 'battle_rule_v1:c6f31c0433a39bd78ef052af1fe0b283', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":5,"keywords":["trample"],"trample":true,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ArborbackStomper translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('aven battle priest', 'Aven Battle Priest', '73dfd66d4c0f4fb5bfec001e3bdae115', 'battle_rule_v1:30e3eacd02324c36a9a41cf3acd50557', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"flying":true,"keywords":["flying"],"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AvenBattlePriest translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('aven of enduring hope', 'Aven of Enduring Hope', 'e67201c53659f5c13214d1a60cd8f652', 'battle_rule_v1:30e3eacd02324c36a9a41cf3acd50557', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"flying":true,"keywords":["flying"],"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AvenOfEnduringHope translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('bulwark giant', 'Bulwark Giant', '91e4ebb70108ac28b8b2aa69c368c7fe', 'battle_rule_v1:3d4be448c3bec2a64b00f8715c06a9f0', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":5,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BulwarkGiant translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('cathedral sanctifier', 'Cathedral Sanctifier', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CathedralSanctifier translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('centaur healer', 'Centaur Healer', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CentaurHealer translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('courier griffin', 'Courier Griffin', '5056c99d38870fb6c25d19751fd4fc6c', 'battle_rule_v1:555b4bb607ddb2350704f9a3e8af4722', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"flying":true,"keywords":["flying"],"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CourierGriffin translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('dawning angel', 'Dawning Angel', 'd657843ed983bb78a6e0b9b873452707', 'battle_rule_v1:2c5f7ab0179980518450381bd1485079', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"flying":true,"keywords":["flying"],"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DawningAngel translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('devout monk', 'Devout Monk', '7cef052ccec7a163a8f0213a747ca352', 'battle_rule_v1:f86776aef50052a914dda15e0b1f4e31', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":1,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DevoutMonk translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('healer of the glade', 'Healer of the Glade', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HealerOfTheGlade translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('hill giant herdgorger', 'Hill Giant Herdgorger', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HillGiantHerdgorger translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('honey mammoth', 'Honey Mammoth', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HoneyMammoth translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('inspiring cleric', 'Inspiring Cleric', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class InspiringCleric translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('jedit''s dragoons', 'Jedit''s Dragoons', '4d1d6845d3cb2d0dddd2bb2f2216d769', 'battle_rule_v1:b7a72609ddc5b60963738cec88f76326', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"keywords":["vigilance"],"trigger":"enters_battlefield","vigilance":true,"xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class JeditsDragoons translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('kemba''s skyguard', 'Kemba''s Skyguard', '5056c99d38870fb6c25d19751fd4fc6c', 'battle_rule_v1:555b4bb607ddb2350704f9a3e8af4722', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"flying":true,"keywords":["flying"],"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class KembasSkyguard translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('koala-sheep', 'Koala-Sheep', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class KoalaSheep translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('lone missionary', 'Lone Missionary', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class LoneMissionary translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('mesa cavalier', 'Mesa Cavalier', '5056c99d38870fb6c25d19751fd4fc6c', 'battle_rule_v1:555b4bb607ddb2350704f9a3e8af4722', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"flying":true,"keywords":["flying"],"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MesaCavalier translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('mossbeard ancient', 'Mossbeard Ancient', '00e8e649110944d7dbb9caed64963c9d', 'battle_rule_v1:c6f31c0433a39bd78ef052af1fe0b283', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":5,"keywords":["trample"],"trample":true,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MossbeardAncient translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('peace strider', 'Peace Strider', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PeaceStrider translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('primordial pachyderm', 'Primordial Pachyderm', '0f6491e5b9cea210c7c33662a6aec0ac', 'battle_rule_v1:9a6a4ae5c12e41985cc8d1e9998cef65', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"keywords":["reach","trample"],"reach":true,"trample":true,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PrimordialPachyderm translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('ravenous lindwurm', 'Ravenous Lindwurm', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class RavenousLindwurm translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('savannah sage', 'Savannah Sage', 'bb3fdc4473671cde3f7974fb0c0f529a', 'battle_rule_v1:cf6345f2abe140852d655085e4562ae7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SavannahSage translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('shu grain caravan', 'Shu Grain Caravan', 'bb3fdc4473671cde3f7974fb0c0f529a', 'battle_rule_v1:cf6345f2abe140852d655085e4562ae7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ShuGrainCaravan translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('shu soldier-farmers', 'Shu Soldier-Farmers', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ShuSoldierFarmers translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('spiritual guardian', 'Spiritual Guardian', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SpiritualGuardian translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('springmane cervin', 'Springmane Cervin', 'bb3fdc4473671cde3f7974fb0c0f529a', 'battle_rule_v1:cf6345f2abe140852d655085e4562ae7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SpringmaneCervin translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('staunch defenders', 'Staunch Defenders', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class StaunchDefenders translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sylvan brushstrider', 'Sylvan Brushstrider', 'bb3fdc4473671cde3f7974fb0c0f529a', 'battle_rule_v1:cf6345f2abe140852d655085e4562ae7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SylvanBrushstrider translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('temple acolyte', 'Temple Acolyte', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TempleAcolyte translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('teroh''s faithful', 'Teroh''s Faithful', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TerohsFaithful translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('tireless missionaries', 'Tireless Missionaries', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TirelessMissionaries translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('turntimber ascetic', 'Turntimber Ascetic', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TurntimberAscetic translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('venerable monk', 'Venerable Monk', 'bb3fdc4473671cde3f7974fb0c0f529a', 'battle_rule_v1:cf6345f2abe140852d655085e4562ae7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class VenerableMonk translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
  counts AS (
    SELECT
      p.card_name,
      p.normalized_name,
      p.oracle_hash,
      count(c.id) AS target_card_rows,
      min(c.id::text)::uuid AS canonical_card_id
    FROM proposed p
    LEFT JOIN public.cards c
      ON (
           lower(c.name) = p.normalized_name
           OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
         )
     AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
    GROUP BY p.card_name, p.normalized_name, p.oracle_hash
  )
  SELECT jsonb_agg(counts ORDER BY card_name)
    INTO v_missing
  FROM counts
  WHERE target_card_rows < 1;

  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION 'XMage batch package abort: expected at least one Oracle-hash-matched card row for every proposed card: %', v_missing;
  END IF;
END $$;

WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('amateur hero', 'Amateur Hero', 'bb3fdc4473671cde3f7974fb0c0f529a', 'battle_rule_v1:cf6345f2abe140852d655085e4562ae7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AmateurHero translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('angel of mercy', 'Angel of Mercy', 'e67201c53659f5c13214d1a60cd8f652', 'battle_rule_v1:30e3eacd02324c36a9a41cf3acd50557', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"flying":true,"keywords":["flying"],"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AngelOfMercy translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('arashin cleric', 'Arashin Cleric', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ArashinCleric translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('arborback stomper', 'Arborback Stomper', '00e8e649110944d7dbb9caed64963c9d', 'battle_rule_v1:c6f31c0433a39bd78ef052af1fe0b283', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":5,"keywords":["trample"],"trample":true,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ArborbackStomper translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('aven battle priest', 'Aven Battle Priest', '73dfd66d4c0f4fb5bfec001e3bdae115', 'battle_rule_v1:30e3eacd02324c36a9a41cf3acd50557', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"flying":true,"keywords":["flying"],"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AvenBattlePriest translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('aven of enduring hope', 'Aven of Enduring Hope', 'e67201c53659f5c13214d1a60cd8f652', 'battle_rule_v1:30e3eacd02324c36a9a41cf3acd50557', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"flying":true,"keywords":["flying"],"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AvenOfEnduringHope translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('bulwark giant', 'Bulwark Giant', '91e4ebb70108ac28b8b2aa69c368c7fe', 'battle_rule_v1:3d4be448c3bec2a64b00f8715c06a9f0', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":5,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BulwarkGiant translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('cathedral sanctifier', 'Cathedral Sanctifier', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CathedralSanctifier translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('centaur healer', 'Centaur Healer', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CentaurHealer translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('courier griffin', 'Courier Griffin', '5056c99d38870fb6c25d19751fd4fc6c', 'battle_rule_v1:555b4bb607ddb2350704f9a3e8af4722', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"flying":true,"keywords":["flying"],"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CourierGriffin translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('dawning angel', 'Dawning Angel', 'd657843ed983bb78a6e0b9b873452707', 'battle_rule_v1:2c5f7ab0179980518450381bd1485079', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"flying":true,"keywords":["flying"],"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DawningAngel translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('devout monk', 'Devout Monk', '7cef052ccec7a163a8f0213a747ca352', 'battle_rule_v1:f86776aef50052a914dda15e0b1f4e31', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":1,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DevoutMonk translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('healer of the glade', 'Healer of the Glade', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HealerOfTheGlade translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('hill giant herdgorger', 'Hill Giant Herdgorger', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HillGiantHerdgorger translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('honey mammoth', 'Honey Mammoth', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HoneyMammoth translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('inspiring cleric', 'Inspiring Cleric', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class InspiringCleric translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('jedit''s dragoons', 'Jedit''s Dragoons', '4d1d6845d3cb2d0dddd2bb2f2216d769', 'battle_rule_v1:b7a72609ddc5b60963738cec88f76326', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"keywords":["vigilance"],"trigger":"enters_battlefield","vigilance":true,"xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class JeditsDragoons translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('kemba''s skyguard', 'Kemba''s Skyguard', '5056c99d38870fb6c25d19751fd4fc6c', 'battle_rule_v1:555b4bb607ddb2350704f9a3e8af4722', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"flying":true,"keywords":["flying"],"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class KembasSkyguard translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('koala-sheep', 'Koala-Sheep', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class KoalaSheep translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('lone missionary', 'Lone Missionary', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class LoneMissionary translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('mesa cavalier', 'Mesa Cavalier', '5056c99d38870fb6c25d19751fd4fc6c', 'battle_rule_v1:555b4bb607ddb2350704f9a3e8af4722', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"flying":true,"keywords":["flying"],"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MesaCavalier translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('mossbeard ancient', 'Mossbeard Ancient', '00e8e649110944d7dbb9caed64963c9d', 'battle_rule_v1:c6f31c0433a39bd78ef052af1fe0b283', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":5,"keywords":["trample"],"trample":true,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MossbeardAncient translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('peace strider', 'Peace Strider', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PeaceStrider translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('primordial pachyderm', 'Primordial Pachyderm', '0f6491e5b9cea210c7c33662a6aec0ac', 'battle_rule_v1:9a6a4ae5c12e41985cc8d1e9998cef65', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"keywords":["reach","trample"],"reach":true,"trample":true,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PrimordialPachyderm translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('ravenous lindwurm', 'Ravenous Lindwurm', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class RavenousLindwurm translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('savannah sage', 'Savannah Sage', 'bb3fdc4473671cde3f7974fb0c0f529a', 'battle_rule_v1:cf6345f2abe140852d655085e4562ae7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SavannahSage translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('shu grain caravan', 'Shu Grain Caravan', 'bb3fdc4473671cde3f7974fb0c0f529a', 'battle_rule_v1:cf6345f2abe140852d655085e4562ae7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ShuGrainCaravan translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('shu soldier-farmers', 'Shu Soldier-Farmers', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ShuSoldierFarmers translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('spiritual guardian', 'Spiritual Guardian', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SpiritualGuardian translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('springmane cervin', 'Springmane Cervin', 'bb3fdc4473671cde3f7974fb0c0f529a', 'battle_rule_v1:cf6345f2abe140852d655085e4562ae7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SpringmaneCervin translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('staunch defenders', 'Staunch Defenders', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class StaunchDefenders translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sylvan brushstrider', 'Sylvan Brushstrider', 'bb3fdc4473671cde3f7974fb0c0f529a', 'battle_rule_v1:cf6345f2abe140852d655085e4562ae7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SylvanBrushstrider translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('temple acolyte', 'Temple Acolyte', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TempleAcolyte translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('teroh''s faithful', 'Teroh''s Faithful', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TerohsFaithful translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('tireless missionaries', 'Tireless Missionaries', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TirelessMissionaries translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('turntimber ascetic', 'Turntimber Ascetic', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TurntimberAscetic translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('venerable monk', 'Venerable Monk', 'bb3fdc4473671cde3f7974fb0c0f529a', 'battle_rule_v1:cf6345f2abe140852d655085e4562ae7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class VenerableMonk translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
deprecated AS (
  UPDATE public.card_battle_rules r
  SET
    review_status = 'deprecated',
    execution_status = 'disabled',
    updated_at = now(),
    notes = concat_ws(E'\n', nullif(r.notes, ''), 'XMage batch package: deprecated stale shadow before curated batch rule upsert.')
  FROM proposed p
  WHERE (
        r.normalized_name = p.normalized_name
        OR r.normalized_name LIKE p.normalized_name || ' // %'
      )
    AND p.shadow_handling <> 'preserve_existing_rows'
    AND r.logical_rule_key <> p.logical_rule_key
  RETURNING r.*
)
SELECT count(*) AS deprecated_shadow_rows FROM deprecated;

WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('amateur hero', 'Amateur Hero', 'bb3fdc4473671cde3f7974fb0c0f529a', 'battle_rule_v1:cf6345f2abe140852d655085e4562ae7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AmateurHero translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('angel of mercy', 'Angel of Mercy', 'e67201c53659f5c13214d1a60cd8f652', 'battle_rule_v1:30e3eacd02324c36a9a41cf3acd50557', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"flying":true,"keywords":["flying"],"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AngelOfMercy translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('arashin cleric', 'Arashin Cleric', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ArashinCleric translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('arborback stomper', 'Arborback Stomper', '00e8e649110944d7dbb9caed64963c9d', 'battle_rule_v1:c6f31c0433a39bd78ef052af1fe0b283', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":5,"keywords":["trample"],"trample":true,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ArborbackStomper translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('aven battle priest', 'Aven Battle Priest', '73dfd66d4c0f4fb5bfec001e3bdae115', 'battle_rule_v1:30e3eacd02324c36a9a41cf3acd50557', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"flying":true,"keywords":["flying"],"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AvenBattlePriest translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('aven of enduring hope', 'Aven of Enduring Hope', 'e67201c53659f5c13214d1a60cd8f652', 'battle_rule_v1:30e3eacd02324c36a9a41cf3acd50557', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"flying":true,"keywords":["flying"],"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AvenOfEnduringHope translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('bulwark giant', 'Bulwark Giant', '91e4ebb70108ac28b8b2aa69c368c7fe', 'battle_rule_v1:3d4be448c3bec2a64b00f8715c06a9f0', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":5,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BulwarkGiant translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('cathedral sanctifier', 'Cathedral Sanctifier', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CathedralSanctifier translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('centaur healer', 'Centaur Healer', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CentaurHealer translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('courier griffin', 'Courier Griffin', '5056c99d38870fb6c25d19751fd4fc6c', 'battle_rule_v1:555b4bb607ddb2350704f9a3e8af4722', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"flying":true,"keywords":["flying"],"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CourierGriffin translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('dawning angel', 'Dawning Angel', 'd657843ed983bb78a6e0b9b873452707', 'battle_rule_v1:2c5f7ab0179980518450381bd1485079', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"flying":true,"keywords":["flying"],"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DawningAngel translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('devout monk', 'Devout Monk', '7cef052ccec7a163a8f0213a747ca352', 'battle_rule_v1:f86776aef50052a914dda15e0b1f4e31', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":1,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DevoutMonk translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('healer of the glade', 'Healer of the Glade', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HealerOfTheGlade translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('hill giant herdgorger', 'Hill Giant Herdgorger', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HillGiantHerdgorger translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('honey mammoth', 'Honey Mammoth', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HoneyMammoth translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('inspiring cleric', 'Inspiring Cleric', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class InspiringCleric translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('jedit''s dragoons', 'Jedit''s Dragoons', '4d1d6845d3cb2d0dddd2bb2f2216d769', 'battle_rule_v1:b7a72609ddc5b60963738cec88f76326', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"keywords":["vigilance"],"trigger":"enters_battlefield","vigilance":true,"xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class JeditsDragoons translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('kemba''s skyguard', 'Kemba''s Skyguard', '5056c99d38870fb6c25d19751fd4fc6c', 'battle_rule_v1:555b4bb607ddb2350704f9a3e8af4722', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"flying":true,"keywords":["flying"],"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class KembasSkyguard translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('koala-sheep', 'Koala-Sheep', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class KoalaSheep translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('lone missionary', 'Lone Missionary', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class LoneMissionary translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('mesa cavalier', 'Mesa Cavalier', '5056c99d38870fb6c25d19751fd4fc6c', 'battle_rule_v1:555b4bb607ddb2350704f9a3e8af4722', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"flying":true,"keywords":["flying"],"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MesaCavalier translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('mossbeard ancient', 'Mossbeard Ancient', '00e8e649110944d7dbb9caed64963c9d', 'battle_rule_v1:c6f31c0433a39bd78ef052af1fe0b283', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":5,"keywords":["trample"],"trample":true,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MossbeardAncient translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('peace strider', 'Peace Strider', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PeaceStrider translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('primordial pachyderm', 'Primordial Pachyderm', '0f6491e5b9cea210c7c33662a6aec0ac', 'battle_rule_v1:9a6a4ae5c12e41985cc8d1e9998cef65', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"keywords":["reach","trample"],"reach":true,"trample":true,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PrimordialPachyderm translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('ravenous lindwurm', 'Ravenous Lindwurm', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class RavenousLindwurm translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('savannah sage', 'Savannah Sage', 'bb3fdc4473671cde3f7974fb0c0f529a', 'battle_rule_v1:cf6345f2abe140852d655085e4562ae7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SavannahSage translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('shu grain caravan', 'Shu Grain Caravan', 'bb3fdc4473671cde3f7974fb0c0f529a', 'battle_rule_v1:cf6345f2abe140852d655085e4562ae7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ShuGrainCaravan translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('shu soldier-farmers', 'Shu Soldier-Farmers', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ShuSoldierFarmers translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('spiritual guardian', 'Spiritual Guardian', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SpiritualGuardian translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('springmane cervin', 'Springmane Cervin', 'bb3fdc4473671cde3f7974fb0c0f529a', 'battle_rule_v1:cf6345f2abe140852d655085e4562ae7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SpringmaneCervin translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('staunch defenders', 'Staunch Defenders', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class StaunchDefenders translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sylvan brushstrider', 'Sylvan Brushstrider', 'bb3fdc4473671cde3f7974fb0c0f529a', 'battle_rule_v1:cf6345f2abe140852d655085e4562ae7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SylvanBrushstrider translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('temple acolyte', 'Temple Acolyte', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TempleAcolyte translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('teroh''s faithful', 'Teroh''s Faithful', 'ddd5636a82f801cc850af28442261c0a', 'battle_rule_v1:fe62479086cab43003ab8c9d27b1f7a7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":4,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TerohsFaithful translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('tireless missionaries', 'Tireless Missionaries', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TirelessMissionaries translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('turntimber ascetic', 'Turntimber Ascetic', '6a4d99398409198cb3eeb6d3aae0b03c', 'battle_rule_v1:49ba8443dd1ae75b4c67441e1d96cead', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":3,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TurntimberAscetic translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('venerable monk', 'Venerable Monk', 'bb3fdc4473671cde3f7974fb0c0f529a', 'battle_rule_v1:cf6345f2abe140852d655085e4562ae7', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_gain_life_v1","effect":"creature","etb_life_gain_amount":2,"trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class VenerableMonk translated into ManaLoom runtime scope xmage_creature_etb_gain_life_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
matched_cards AS (
  SELECT
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    c.id AS card_id,
    c.name AS db_card_name
  FROM proposed p
  JOIN public.cards c
    ON (
         lower(c.name) = p.normalized_name
         OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
       )
   AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
),
canonical_target_cards AS (
  SELECT
    p.*,
    min(m.card_id::text)::uuid AS card_id,
    min(m.db_card_name) AS db_card_name
  FROM proposed p
  JOIN matched_cards m
    USING (normalized_name, card_name, oracle_hash)
  GROUP BY
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    p.logical_rule_key,
    p.effect_json,
    p.deck_role_json,
    p.source,
    p.confidence,
    p.review_status,
    p.execution_status,
    p.notes,
    p.shadow_handling
),
upserted AS (
  INSERT INTO public.card_battle_rules (
    normalized_name,
    card_id,
    card_name,
    effect_json,
    deck_role_json,
    source,
    confidence,
    review_status,
    rule_version,
    oracle_hash,
    notes,
    reviewed_by,
    reviewed_at,
    created_at,
    updated_at,
    last_seen_at,
    logical_rule_key,
    execution_status
  )
  SELECT
    normalized_name,
    card_id,
    db_card_name,
    effect_json,
    deck_role_json,
    source,
    confidence,
    review_status,
    2,
    oracle_hash,
    notes,
    'codex-xmage-batch',
    now(),
    now(),
    now(),
    now(),
    logical_rule_key,
    execution_status
  FROM canonical_target_cards
  ON CONFLICT (normalized_name, logical_rule_key) DO UPDATE
  SET
    card_id = EXCLUDED.card_id,
    card_name = EXCLUDED.card_name,
    effect_json = EXCLUDED.effect_json,
    deck_role_json = EXCLUDED.deck_role_json,
    source = EXCLUDED.source,
    confidence = EXCLUDED.confidence,
    review_status = EXCLUDED.review_status,
    rule_version = EXCLUDED.rule_version,
    oracle_hash = EXCLUDED.oracle_hash,
    notes = EXCLUDED.notes,
    reviewed_by = EXCLUDED.reviewed_by,
    reviewed_at = EXCLUDED.reviewed_at,
    updated_at = EXCLUDED.updated_at,
    last_seen_at = EXCLUDED.last_seen_at,
    execution_status = EXCLUDED.execution_status
  RETURNING *
)
SELECT count(*) AS upserted_rows FROM upserted;

COMMIT;
