WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('prodigal pyromancer', 'Prodigal Pyromancer', 'c5b1b992d7c7837bf0adfb1c18226e45', 'battle_rule_v1:91b6836aaecc7fc9dc5de29478462357', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"direct_damage","activation_requires_tap":true,"amount":1,"battle_model_scope":"xmage_tap_fixed_damage_target_activated_ability_v1","damage":1,"effect":"direct_damage","target":"any_target","target_constraints":{"scope":"any_target"},"xmage_ability_class":"SimpleActivatedAbility","xmage_activation_cost":"tap","xmage_effect_class":"DamageTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_tap_fixed_damage_target_activated_ability_v1","activated_damage_amount":1,"activated_effect":"direct_damage","activation_requires_tap":true,"battle_model_scope":"xmage_creature_tap_fixed_damage_target_activated_v1","effect":"creature","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"DamageTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ProdigalPyromancer translated into ManaLoom runtime scope xmage_creature_tap_fixed_damage_target_activated_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('prodigal sorcerer', 'Prodigal Sorcerer', 'c5b1b992d7c7837bf0adfb1c18226e45', 'battle_rule_v1:91b6836aaecc7fc9dc5de29478462357', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"direct_damage","activation_requires_tap":true,"amount":1,"battle_model_scope":"xmage_tap_fixed_damage_target_activated_ability_v1","damage":1,"effect":"direct_damage","target":"any_target","target_constraints":{"scope":"any_target"},"xmage_ability_class":"SimpleActivatedAbility","xmage_activation_cost":"tap","xmage_effect_class":"DamageTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_tap_fixed_damage_target_activated_ability_v1","activated_damage_amount":1,"activated_effect":"direct_damage","activation_requires_tap":true,"battle_model_scope":"xmage_creature_tap_fixed_damage_target_activated_v1","effect":"creature","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"DamageTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ProdigalSorcerer translated into ManaLoom runtime scope xmage_creature_tap_fixed_damage_target_activated_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('razorfin hunter', 'Razorfin Hunter', 'c5b1b992d7c7837bf0adfb1c18226e45', 'battle_rule_v1:91b6836aaecc7fc9dc5de29478462357', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"direct_damage","activation_requires_tap":true,"amount":1,"battle_model_scope":"xmage_tap_fixed_damage_target_activated_ability_v1","damage":1,"effect":"direct_damage","target":"any_target","target_constraints":{"scope":"any_target"},"xmage_ability_class":"SimpleActivatedAbility","xmage_activation_cost":"tap","xmage_effect_class":"DamageTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_tap_fixed_damage_target_activated_ability_v1","activated_damage_amount":1,"activated_effect":"direct_damage","activation_requires_tap":true,"battle_model_scope":"xmage_creature_tap_fixed_damage_target_activated_v1","effect":"creature","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"DamageTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class RazorfinHunter translated into ManaLoom runtime scope xmage_creature_tap_fixed_damage_target_activated_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('rootwater hunter', 'Rootwater Hunter', 'c5b1b992d7c7837bf0adfb1c18226e45', 'battle_rule_v1:91b6836aaecc7fc9dc5de29478462357', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"direct_damage","activation_requires_tap":true,"amount":1,"battle_model_scope":"xmage_tap_fixed_damage_target_activated_ability_v1","damage":1,"effect":"direct_damage","target":"any_target","target_constraints":{"scope":"any_target"},"xmage_ability_class":"SimpleActivatedAbility","xmage_activation_cost":"tap","xmage_effect_class":"DamageTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_tap_fixed_damage_target_activated_ability_v1","activated_damage_amount":1,"activated_effect":"direct_damage","activation_requires_tap":true,"battle_model_scope":"xmage_creature_tap_fixed_damage_target_activated_v1","effect":"creature","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"DamageTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class RootwaterHunter translated into ManaLoom runtime scope xmage_creature_tap_fixed_damage_target_activated_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('viashino fangtail', 'Viashino Fangtail', 'c5b1b992d7c7837bf0adfb1c18226e45', 'battle_rule_v1:91b6836aaecc7fc9dc5de29478462357', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"direct_damage","activation_requires_tap":true,"amount":1,"battle_model_scope":"xmage_tap_fixed_damage_target_activated_ability_v1","damage":1,"effect":"direct_damage","target":"any_target","target_constraints":{"scope":"any_target"},"xmage_ability_class":"SimpleActivatedAbility","xmage_activation_cost":"tap","xmage_effect_class":"DamageTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_tap_fixed_damage_target_activated_ability_v1","activated_damage_amount":1,"activated_effect":"direct_damage","activation_requires_tap":true,"battle_model_scope":"xmage_creature_tap_fixed_damage_target_activated_v1","effect":"creature","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"DamageTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ViashinoFangtail translated into ManaLoom runtime scope xmage_creature_tap_fixed_damage_target_activated_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('zuran spellcaster', 'Zuran Spellcaster', 'c5b1b992d7c7837bf0adfb1c18226e45', 'battle_rule_v1:91b6836aaecc7fc9dc5de29478462357', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"direct_damage","activation_requires_tap":true,"amount":1,"battle_model_scope":"xmage_tap_fixed_damage_target_activated_ability_v1","damage":1,"effect":"direct_damage","target":"any_target","target_constraints":{"scope":"any_target"},"xmage_ability_class":"SimpleActivatedAbility","xmage_activation_cost":"tap","xmage_effect_class":"DamageTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_tap_fixed_damage_target_activated_ability_v1","activated_damage_amount":1,"activated_effect":"direct_damage","activation_requires_tap":true,"battle_model_scope":"xmage_creature_tap_fixed_damage_target_activated_v1","effect":"creature","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"DamageTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ZuranSpellcaster translated into ManaLoom runtime scope xmage_creature_tap_fixed_damage_target_activated_v1. This row is package-ready only because the source signature is a narrow instant/sorcery spell with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
rule_rows AS (
  SELECT
    r.normalized_name,
    r.logical_rule_key,
    r.oracle_hash,
    r.review_status,
    r.execution_status
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key = p.logical_rule_key
)
SELECT
  p.card_name,
  p.normalized_name,
  p.logical_rule_key,
  count(r.*) FILTER (WHERE r.logical_rule_key = p.logical_rule_key) AS promoted_rule_rows,
  count(r.*) FILTER (WHERE r.review_status = 'verified' AND r.execution_status = 'auto') AS promoted_verified_auto_rows,
  count(r.*) FILTER (WHERE r.oracle_hash = p.oracle_hash) AS promoted_oracle_hash_rows,
  (SELECT count(*) FROM manaloom_deploy_audit.pg296_xmage_creature_tap_damage_wave_20260701_103016) AS backup_rows
FROM proposed p
LEFT JOIN rule_rows r
  ON r.normalized_name = p.normalized_name
 AND r.logical_rule_key = p.logical_rule_key
 AND r.oracle_hash = p.oracle_hash
GROUP BY p.card_name, p.normalized_name, p.logical_rule_key, p.oracle_hash
ORDER BY p.card_name;
