BEGIN;

DELETE FROM public.card_battle_rules
WHERE normalized_name IN ('angelic wall', 'anvilwrought raptor', 'archers of qarsi', 'ascended lawmage', 'aven fleetwing', 'bassara tower archer', 'benthic giant', 'boros recruit', 'cloud crusader', 'cold-water snapper', 'conifer strider', 'consulate skygate', 'copper host crusher', 'daggerdrome imp', 'darksteel gargoyle', 'darksteel myr', 'dawnstrike paladin', 'deadly insect', 'deadly recluse', 'deathgaze cockatrice', 'deft duelist', 'elvish lookout', 'giant solifuge', 'gladecover scout', 'grendel, spawn of knull', 'griffin sentinel', 'hawkeater moth', 'healer''s hawk', 'humble budoka', 'humongulus', 'kalonian behemoth', 'kederekt creeper', 'kessig recluse', 'knight of meadowgrain', 'kodama of the north tree', 'lightning stormkin', 'midnight assassin', 'mist leopard', 'monster mashup', 'nightveil predator', 'pegasus charger', 'peregrine griffin', 'pincher beetles', 'plated crusher', 'plated slagwurm', 'porcelain legionnaire', 'primal huntbeast', 'razorfoot griffin', 'relic sloth', 'resistance skywarden', 'rubbleback rhino', 'sacred wolf', 'scaled behemoth', 'seraph of the suns', 'serra angel', 'simic sky swallower', 'skyshroud falcon', 'skysnare spider', 'skyspear cavalry', 'slash panther', 'slippery bogle', 'soul of the rapids', 'spined thopter', 'sungrace pegasus', 'swiftblade vindicator', 'tajuru pathwarden', 'taoist hermit', 'the terror of serpent''s pass', 'thornweald archer', 'thundering tanadon', 'tidehollow strix', 'vampire nighthawk', 'vampire of the dire moon', 'vault skirge', 'venomthrope', 'wall of denial', 'wall of razors', 'wall of spears', 'wall of swords', 'wall of vines', 'wardscale crocodile', 'wind spirit', 'wrecking crew', 'zephid', 'zetalpa, primal dawn')
   OR normalized_name LIKE 'angelic wall // %'
   OR normalized_name LIKE 'anvilwrought raptor // %'
   OR normalized_name LIKE 'archers of qarsi // %'
   OR normalized_name LIKE 'ascended lawmage // %'
   OR normalized_name LIKE 'aven fleetwing // %'
   OR normalized_name LIKE 'bassara tower archer // %'
   OR normalized_name LIKE 'benthic giant // %'
   OR normalized_name LIKE 'boros recruit // %'
   OR normalized_name LIKE 'cloud crusader // %'
   OR normalized_name LIKE 'cold-water snapper // %'
   OR normalized_name LIKE 'conifer strider // %'
   OR normalized_name LIKE 'consulate skygate // %'
   OR normalized_name LIKE 'copper host crusher // %'
   OR normalized_name LIKE 'daggerdrome imp // %'
   OR normalized_name LIKE 'darksteel gargoyle // %'
   OR normalized_name LIKE 'darksteel myr // %'
   OR normalized_name LIKE 'dawnstrike paladin // %'
   OR normalized_name LIKE 'deadly insect // %'
   OR normalized_name LIKE 'deadly recluse // %'
   OR normalized_name LIKE 'deathgaze cockatrice // %'
   OR normalized_name LIKE 'deft duelist // %'
   OR normalized_name LIKE 'elvish lookout // %'
   OR normalized_name LIKE 'giant solifuge // %'
   OR normalized_name LIKE 'gladecover scout // %'
   OR normalized_name LIKE 'grendel, spawn of knull // %'
   OR normalized_name LIKE 'griffin sentinel // %'
   OR normalized_name LIKE 'hawkeater moth // %'
   OR normalized_name LIKE 'healer''s hawk // %'
   OR normalized_name LIKE 'humble budoka // %'
   OR normalized_name LIKE 'humongulus // %'
   OR normalized_name LIKE 'kalonian behemoth // %'
   OR normalized_name LIKE 'kederekt creeper // %'
   OR normalized_name LIKE 'kessig recluse // %'
   OR normalized_name LIKE 'knight of meadowgrain // %'
   OR normalized_name LIKE 'kodama of the north tree // %'
   OR normalized_name LIKE 'lightning stormkin // %'
   OR normalized_name LIKE 'midnight assassin // %'
   OR normalized_name LIKE 'mist leopard // %'
   OR normalized_name LIKE 'monster mashup // %'
   OR normalized_name LIKE 'nightveil predator // %'
   OR normalized_name LIKE 'pegasus charger // %'
   OR normalized_name LIKE 'peregrine griffin // %'
   OR normalized_name LIKE 'pincher beetles // %'
   OR normalized_name LIKE 'plated crusher // %'
   OR normalized_name LIKE 'plated slagwurm // %'
   OR normalized_name LIKE 'porcelain legionnaire // %'
   OR normalized_name LIKE 'primal huntbeast // %'
   OR normalized_name LIKE 'razorfoot griffin // %'
   OR normalized_name LIKE 'relic sloth // %'
   OR normalized_name LIKE 'resistance skywarden // %'
   OR normalized_name LIKE 'rubbleback rhino // %'
   OR normalized_name LIKE 'sacred wolf // %'
   OR normalized_name LIKE 'scaled behemoth // %'
   OR normalized_name LIKE 'seraph of the suns // %'
   OR normalized_name LIKE 'serra angel // %'
   OR normalized_name LIKE 'simic sky swallower // %'
   OR normalized_name LIKE 'skyshroud falcon // %'
   OR normalized_name LIKE 'skysnare spider // %'
   OR normalized_name LIKE 'skyspear cavalry // %'
   OR normalized_name LIKE 'slash panther // %'
   OR normalized_name LIKE 'slippery bogle // %'
   OR normalized_name LIKE 'soul of the rapids // %'
   OR normalized_name LIKE 'spined thopter // %'
   OR normalized_name LIKE 'sungrace pegasus // %'
   OR normalized_name LIKE 'swiftblade vindicator // %'
   OR normalized_name LIKE 'tajuru pathwarden // %'
   OR normalized_name LIKE 'taoist hermit // %'
   OR normalized_name LIKE 'the terror of serpent''s pass // %'
   OR normalized_name LIKE 'thornweald archer // %'
   OR normalized_name LIKE 'thundering tanadon // %'
   OR normalized_name LIKE 'tidehollow strix // %'
   OR normalized_name LIKE 'vampire nighthawk // %'
   OR normalized_name LIKE 'vampire of the dire moon // %'
   OR normalized_name LIKE 'vault skirge // %'
   OR normalized_name LIKE 'venomthrope // %'
   OR normalized_name LIKE 'wall of denial // %'
   OR normalized_name LIKE 'wall of razors // %'
   OR normalized_name LIKE 'wall of spears // %'
   OR normalized_name LIKE 'wall of swords // %'
   OR normalized_name LIKE 'wall of vines // %'
   OR normalized_name LIKE 'wardscale crocodile // %'
   OR normalized_name LIKE 'wind spirit // %'
   OR normalized_name LIKE 'wrecking crew // %'
   OR normalized_name LIKE 'zephid // %'
   OR normalized_name LIKE 'zetalpa, primal dawn // %';

INSERT INTO public.card_battle_rules
SELECT *
FROM manaloom_deploy_audit.pg293_xmage_static_self_keyword_creature_v2_wave_2026070;

COMMIT;
