WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('carrion beetles', 'Carrion Beetles', '15400777d70ce0903440c0a4fcbb25cd', 'battle_rule_v1:5bdcda2db6ca4ec908795c86d773fd5b', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"graveyard_exile","activation_cost_colors":["B"],"activation_cost_generic":2,"activation_cost_mana":"{2}{B}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_exile_graveyard_card_v1","count":3,"destination":"exile","effect":"graveyard_exile","graveyard_exile_destination":"exile","graveyard_exile_single_graveyard":true,"graveyard_exile_target":"any_card","graveyard_exile_target_count":3,"graveyard_exile_up_to_count":true,"single_graveyard":true,"target":"any_card","target_constraints":{"card_types":["card"],"controller":"any","zone":"graveyard"},"target_controller":"any","up_to_count":true,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ExileTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_exile_graveyard_card_v1","activated_effect":"graveyard_exile","activation_cost_colors":["B"],"activation_cost_generic":2,"activation_cost_mana":"{2}{B}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_exile_graveyard_card_v1","effect":"creature","graveyard_exile_activation_cost_colors":["B"],"graveyard_exile_activation_cost_generic":2,"graveyard_exile_activation_cost_mana":"{2}{B}","graveyard_exile_activation_requires_sacrifice":false,"graveyard_exile_activation_requires_tap":true,"graveyard_exile_destination":"exile","graveyard_exile_single_graveyard":true,"graveyard_exile_target":"any_card","graveyard_exile_target_count":3,"graveyard_exile_up_to_count":true,"single_graveyard":true,"target":"any_card","target_constraints":{"card_types":["card"],"controller":"any","zone":"graveyard"},"target_controller":"any","up_to_count":true,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ExileTargetEffect"}'::jsonb, '{"category":"removal","effect":"creature","subtype":"graveyard_hate","target":"any_card"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CarrionBeetles translated into ManaLoom runtime scope xmage_permanent_simple_activated_exile_graveyard_card_v1. This row is package-ready only because the source signature is a narrow permanent with a simple activated graveyard-exile ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('crypt creeper', 'Crypt Creeper', '1376d1b8cf7e9008e910141cbd621306', 'battle_rule_v1:858b9ef24c06fd327b23f1ddde7f6f01', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"graveyard_exile","activated_self_sacrifice_graveyard_exile":true,"activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_exile_graveyard_card_v1","count":1,"destination":"exile","effect":"graveyard_exile","graveyard_exile_destination":"exile","graveyard_exile_target":"any_card","graveyard_exile_target_count":1,"target":"any_card","target_constraints":{"card_types":["card"],"controller":"any","zone":"graveyard"},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ExileTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_exile_graveyard_card_v1","activated_effect":"graveyard_exile","activated_self_sacrifice_graveyard_exile":true,"activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_exile_graveyard_card_v1","effect":"creature","graveyard_exile_activation_cost_colors":[],"graveyard_exile_activation_cost_generic":0,"graveyard_exile_activation_cost_mana":"{0}","graveyard_exile_activation_requires_sacrifice":true,"graveyard_exile_activation_requires_tap":false,"graveyard_exile_destination":"exile","graveyard_exile_target":"any_card","graveyard_exile_target_count":1,"target":"any_card","target_constraints":{"card_types":["card"],"controller":"any","zone":"graveyard"},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ExileTargetEffect"}'::jsonb, '{"category":"removal","effect":"creature","subtype":"graveyard_hate","target":"any_card"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CryptCreeper translated into ManaLoom runtime scope xmage_permanent_simple_activated_exile_graveyard_card_v1. This row is package-ready only because the source signature is a narrow permanent with a simple activated graveyard-exile ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('famished ghoul', 'Famished Ghoul', '8cd1048f039c8460fe6280f1a50cf702', 'battle_rule_v1:edd435593205d424a5da255f10ccd42b', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"graveyard_exile","activated_self_sacrifice_graveyard_exile":true,"activation_cost_colors":["B"],"activation_cost_generic":1,"activation_cost_mana":"{1}{B}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_exile_graveyard_card_v1","count":2,"destination":"exile","effect":"graveyard_exile","graveyard_exile_destination":"exile","graveyard_exile_single_graveyard":true,"graveyard_exile_target":"any_card","graveyard_exile_target_count":2,"graveyard_exile_up_to_count":true,"single_graveyard":true,"target":"any_card","target_constraints":{"card_types":["card"],"controller":"any","zone":"graveyard"},"target_controller":"any","up_to_count":true,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ExileTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_exile_graveyard_card_v1","activated_effect":"graveyard_exile","activated_self_sacrifice_graveyard_exile":true,"activation_cost_colors":["B"],"activation_cost_generic":1,"activation_cost_mana":"{1}{B}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_exile_graveyard_card_v1","effect":"creature","graveyard_exile_activation_cost_colors":["B"],"graveyard_exile_activation_cost_generic":1,"graveyard_exile_activation_cost_mana":"{1}{B}","graveyard_exile_activation_requires_sacrifice":true,"graveyard_exile_activation_requires_tap":false,"graveyard_exile_destination":"exile","graveyard_exile_single_graveyard":true,"graveyard_exile_target":"any_card","graveyard_exile_target_count":2,"graveyard_exile_up_to_count":true,"single_graveyard":true,"target":"any_card","target_constraints":{"card_types":["card"],"controller":"any","zone":"graveyard"},"target_controller":"any","up_to_count":true,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ExileTargetEffect"}'::jsonb, '{"category":"removal","effect":"creature","subtype":"graveyard_hate","target":"any_card"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class FamishedGhoul translated into ManaLoom runtime scope xmage_permanent_simple_activated_exile_graveyard_card_v1. This row is package-ready only because the source signature is a narrow permanent with a simple activated graveyard-exile ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('heap doll', 'Heap Doll', '1376d1b8cf7e9008e910141cbd621306', 'battle_rule_v1:858b9ef24c06fd327b23f1ddde7f6f01', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"graveyard_exile","activated_self_sacrifice_graveyard_exile":true,"activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_exile_graveyard_card_v1","count":1,"destination":"exile","effect":"graveyard_exile","graveyard_exile_destination":"exile","graveyard_exile_target":"any_card","graveyard_exile_target_count":1,"target":"any_card","target_constraints":{"card_types":["card"],"controller":"any","zone":"graveyard"},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ExileTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_exile_graveyard_card_v1","activated_effect":"graveyard_exile","activated_self_sacrifice_graveyard_exile":true,"activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_exile_graveyard_card_v1","effect":"creature","graveyard_exile_activation_cost_colors":[],"graveyard_exile_activation_cost_generic":0,"graveyard_exile_activation_cost_mana":"{0}","graveyard_exile_activation_requires_sacrifice":true,"graveyard_exile_activation_requires_tap":false,"graveyard_exile_destination":"exile","graveyard_exile_target":"any_card","graveyard_exile_target_count":1,"target":"any_card","target_constraints":{"card_types":["card"],"controller":"any","zone":"graveyard"},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ExileTargetEffect"}'::jsonb, '{"category":"removal","effect":"creature","subtype":"graveyard_hate","target":"any_card"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HeapDoll translated into ManaLoom runtime scope xmage_permanent_simple_activated_exile_graveyard_card_v1. This row is package-ready only because the source signature is a narrow permanent with a simple activated graveyard-exile ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('rag dealer', 'Rag Dealer', '15400777d70ce0903440c0a4fcbb25cd', 'battle_rule_v1:5bdcda2db6ca4ec908795c86d773fd5b', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"graveyard_exile","activation_cost_colors":["B"],"activation_cost_generic":2,"activation_cost_mana":"{2}{B}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_exile_graveyard_card_v1","count":3,"destination":"exile","effect":"graveyard_exile","graveyard_exile_destination":"exile","graveyard_exile_single_graveyard":true,"graveyard_exile_target":"any_card","graveyard_exile_target_count":3,"graveyard_exile_up_to_count":true,"single_graveyard":true,"target":"any_card","target_constraints":{"card_types":["card"],"controller":"any","zone":"graveyard"},"target_controller":"any","up_to_count":true,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ExileTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_exile_graveyard_card_v1","activated_effect":"graveyard_exile","activation_cost_colors":["B"],"activation_cost_generic":2,"activation_cost_mana":"{2}{B}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_exile_graveyard_card_v1","effect":"creature","graveyard_exile_activation_cost_colors":["B"],"graveyard_exile_activation_cost_generic":2,"graveyard_exile_activation_cost_mana":"{2}{B}","graveyard_exile_activation_requires_sacrifice":false,"graveyard_exile_activation_requires_tap":true,"graveyard_exile_destination":"exile","graveyard_exile_single_graveyard":true,"graveyard_exile_target":"any_card","graveyard_exile_target_count":3,"graveyard_exile_up_to_count":true,"single_graveyard":true,"target":"any_card","target_constraints":{"card_types":["card"],"controller":"any","zone":"graveyard"},"target_controller":"any","up_to_count":true,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ExileTargetEffect"}'::jsonb, '{"category":"removal","effect":"creature","subtype":"graveyard_hate","target":"any_card"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class RagDealer translated into ManaLoom runtime scope xmage_permanent_simple_activated_exile_graveyard_card_v1. This row is package-ready only because the source signature is a narrow permanent with a simple activated graveyard-exile ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('thraben heretic', 'Thraben Heretic', '9018873aaad9f700c6b00b84b91e0438', 'battle_rule_v1:f29d249f79c606b64c874a0e06141168', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"graveyard_exile","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_exile_graveyard_card_v1","count":1,"destination":"exile","effect":"graveyard_exile","graveyard_exile_destination":"exile","graveyard_exile_target":"creature","graveyard_exile_target_count":1,"target":"creature","target_constraints":{"card_types":["creature"],"controller":"any","zone":"graveyard"},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ExileTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_exile_graveyard_card_v1","activated_effect":"graveyard_exile","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_exile_graveyard_card_v1","effect":"creature","graveyard_exile_activation_cost_colors":[],"graveyard_exile_activation_cost_generic":0,"graveyard_exile_activation_cost_mana":"{0}","graveyard_exile_activation_requires_sacrifice":false,"graveyard_exile_activation_requires_tap":true,"graveyard_exile_destination":"exile","graveyard_exile_target":"creature","graveyard_exile_target_count":1,"target":"creature","target_constraints":{"card_types":["creature"],"controller":"any","zone":"graveyard"},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ExileTargetEffect"}'::jsonb, '{"category":"removal","effect":"creature","subtype":"graveyard_hate","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ThrabenHeretic translated into ManaLoom runtime scope xmage_permanent_simple_activated_exile_graveyard_card_v1. This row is package-ready only because the source signature is a narrow permanent with a simple activated graveyard-exile ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('withered wretch', 'Withered Wretch', '0eadc5922b314f16c54e9e873823ae83', 'battle_rule_v1:41f10f2f127d58464803d5f28f5fe8d5', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"graveyard_exile","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_exile_graveyard_card_v1","count":1,"destination":"exile","effect":"graveyard_exile","graveyard_exile_destination":"exile","graveyard_exile_target":"any_card","graveyard_exile_target_count":1,"target":"any_card","target_constraints":{"card_types":["card"],"controller":"any","zone":"graveyard"},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ExileTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_exile_graveyard_card_v1","activated_effect":"graveyard_exile","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_exile_graveyard_card_v1","effect":"creature","graveyard_exile_activation_cost_colors":[],"graveyard_exile_activation_cost_generic":1,"graveyard_exile_activation_cost_mana":"{1}","graveyard_exile_activation_requires_sacrifice":false,"graveyard_exile_activation_requires_tap":false,"graveyard_exile_destination":"exile","graveyard_exile_target":"any_card","graveyard_exile_target_count":1,"target":"any_card","target_constraints":{"card_types":["card"],"controller":"any","zone":"graveyard"},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ExileTargetEffect"}'::jsonb, '{"category":"removal","effect":"creature","subtype":"graveyard_hate","target":"any_card"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class WitheredWretch translated into ManaLoom runtime scope xmage_permanent_simple_activated_exile_graveyard_card_v1. This row is package-ready only because the source signature is a narrow permanent with a simple activated graveyard-exile ability with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
matched_cards AS (
  SELECT
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    c.id AS card_id,
    c.name AS db_card_name
  FROM proposed p
  LEFT JOIN public.cards c
    ON (
         lower(c.name) = p.normalized_name
         OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
       )
   AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
),
target_cards AS (
  SELECT
    normalized_name,
    card_name,
    oracle_hash,
    count(card_id) AS target_card_rows,
    min(card_id::text)::uuid AS canonical_card_id,
    min(db_card_name) AS canonical_card_name
  FROM matched_cards
  GROUP BY normalized_name, card_name, oracle_hash
),
rule_rows AS (
  SELECT p.normalized_name, count(r.*) AS existing_rule_rows
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
  GROUP BY p.normalized_name
),
expected_rows AS (
  SELECT p.normalized_name, count(r.*) AS expected_rule_rows_before
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key = p.logical_rule_key
  GROUP BY p.normalized_name
),
shadow_rows AS (
  SELECT p.normalized_name, count(r.*) AS would_deprecate_shadow_rows
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key <> p.logical_rule_key
   AND r.review_status NOT IN ('deprecated', 'rejected')
   AND r.execution_status <> 'disabled'
  GROUP BY p.normalized_name
)
SELECT
  p.card_name,
  p.normalized_name,
  p.oracle_hash,
  p.logical_rule_key,
  p.shadow_handling,
  tc.target_card_rows,
  tc.canonical_card_id,
  rr.existing_rule_rows,
  er.expected_rule_rows_before,
  sr.would_deprecate_shadow_rows
FROM proposed p
JOIN target_cards tc USING (normalized_name, card_name, oracle_hash)
JOIN rule_rows rr USING (normalized_name)
JOIN expected_rows er USING (normalized_name)
JOIN shadow_rows sr USING (normalized_name)
ORDER BY p.card_name;
