WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('behold the sinister six!', 'Behold the Sinister Six!', '22d23fc917885e5b22cb7b60c483756c', 'battle_rule_v1:990d3d8901fc9239d0089e0ac86bef62', '{"battle_model_scope":"xmage_return_target_graveyard_card_to_battlefield_spell_v1","battlefield_controller":"self","count":6,"destination":"battlefield","effect":"recursion","instant":false,"requires_different_names":true,"sorcery":true,"target":"creature","target_constraints":{"card_types":["creature"],"controller":"self","requires_different_names":true,"zone":"graveyard"},"target_controller":"self","target_graveyard_controller":"self","up_to_count":true,"xmage_effect_class":"ReturnFromGraveyardToBattlefieldTargetEffect"}'::jsonb, '{"category":"engine","effect":"recursion","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BeholdTheSinisterSix translated into ManaLoom runtime scope xmage_return_target_graveyard_card_to_battlefield_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('brought back', 'Brought Back', 'af75ed7190647cd5a685e3dd34dfd3c9', 'battle_rule_v1:e054b75a3b97cc92a917e8bdecbee82c', '{"battle_model_scope":"xmage_return_target_graveyard_card_to_battlefield_spell_v1","battlefield_controller":"self","count":2,"destination":"battlefield","effect":"recursion","enters_tapped":true,"graveyard_from_battlefield_this_turn":true,"instant":true,"sorcery":false,"target":"permanent","target_constraints":{"card_types":["artifact","creature","enchantment","planeswalker","battle","land"],"controller":"self","graveyard_from_battlefield_this_turn":true,"zone":"graveyard"},"target_controller":"self","target_graveyard_controller":"self","up_to_count":true,"xmage_effect_class":"ReturnFromGraveyardToBattlefieldTargetEffect"}'::jsonb, '{"category":"engine","effect":"recursion","target":"permanent","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BroughtBack translated into ManaLoom runtime scope xmage_return_target_graveyard_card_to_battlefield_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('continue?', 'Continue?', '6b2ab191a364b742c0e4c8d4d2957106', 'battle_rule_v1:96c134fe95bf5a8397b9f1bcd8bbc1ef', '{"battle_model_scope":"xmage_return_target_graveyard_card_to_battlefield_spell_v1","battlefield_controller":"self","count":4,"destination":"battlefield","effect":"recursion","graveyard_from_battlefield_this_turn":true,"instant":true,"sorcery":false,"target":"creature","target_constraints":{"card_types":["creature"],"controller":"self","graveyard_from_battlefield_this_turn":true,"zone":"graveyard"},"target_controller":"self","target_graveyard_controller":"self","up_to_count":true,"xmage_effect_class":"ReturnFromGraveyardToBattlefieldTargetEffect"}'::jsonb, '{"category":"engine","effect":"recursion","target":"creature","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Continue translated into ManaLoom runtime scope xmage_return_target_graveyard_card_to_battlefield_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('grim return', 'Grim Return', 'cd84ad9ab549a29a67cbe1b5dae6cf75', 'battle_rule_v1:fb8c63570b73aab5f5069a1232f18e84', '{"battle_model_scope":"xmage_return_target_graveyard_card_to_battlefield_spell_v1","battlefield_controller":"self","count":1,"destination":"battlefield","effect":"recursion","graveyard_from_battlefield_this_turn":true,"instant":true,"sorcery":false,"target":"creature","target_constraints":{"card_types":["creature"],"controller":"any_player","graveyard_from_battlefield_this_turn":true,"zone":"graveyard"},"target_controller":"any_player","target_graveyard_controller":"any_player","xmage_effect_class":"ReturnFromGraveyardToBattlefieldTargetEffect"}'::jsonb, '{"category":"engine","effect":"recursion","target":"creature","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GrimReturn translated into ManaLoom runtime scope xmage_return_target_graveyard_card_to_battlefield_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('march from the tomb', 'March from the Tomb', '23140e7a4f665d8e3e6015e1103ec5b0', 'battle_rule_v1:feb5bdcf4ab012abd1490b3a8611f448', '{"battle_model_scope":"xmage_return_target_graveyard_card_to_battlefield_spell_v1","battlefield_controller":"self","count":99,"destination":"battlefield","effect":"recursion","instant":false,"recursion_total_mana_value_max":8,"sorcery":true,"target":"ally_creature","target_constraints":{"card_types":["creature"],"controller":"self","subtypes":["ally"],"total_mana_value_max":8,"zone":"graveyard"},"target_controller":"self","target_graveyard_controller":"self","up_to_count":true,"xmage_effect_class":"ReturnFromGraveyardToBattlefieldTargetEffect"}'::jsonb, '{"category":"engine","effect":"recursion","target":"ally_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MarchFromTheTomb translated into ManaLoom runtime scope xmage_return_target_graveyard_card_to_battlefield_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('patch up', 'Patch Up', 'c999a9d7c9e85a1656c3fe8f2dc5fc8f', 'battle_rule_v1:77e5f68e27a575e492b33361b92091fa', '{"battle_model_scope":"xmage_return_target_graveyard_card_to_battlefield_spell_v1","battlefield_controller":"self","count":3,"destination":"battlefield","effect":"recursion","instant":false,"recursion_total_mana_value_max":3,"sorcery":true,"target":"creature","target_constraints":{"card_types":["creature"],"controller":"self","total_mana_value_max":3,"zone":"graveyard"},"target_controller":"self","target_graveyard_controller":"self","up_to_count":true,"xmage_effect_class":"ReturnFromGraveyardToBattlefieldTargetEffect"}'::jsonb, '{"category":"engine","effect":"recursion","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PatchUp translated into ManaLoom runtime scope xmage_return_target_graveyard_card_to_battlefield_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
rule_rows AS (
  SELECT
    r.normalized_name,
    r.logical_rule_key,
    r.oracle_hash,
    r.review_status,
    r.execution_status
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key = p.logical_rule_key
)
SELECT
  p.card_name,
  p.normalized_name,
  p.logical_rule_key,
  count(r.*) FILTER (WHERE r.logical_rule_key = p.logical_rule_key) AS promoted_rule_rows,
  count(r.*) FILTER (WHERE r.review_status = 'verified' AND r.execution_status = 'auto') AS promoted_verified_auto_rows,
  count(r.*) FILTER (WHERE r.oracle_hash = p.oracle_hash) AS promoted_oracle_hash_rows,
  (SELECT count(*) FROM manaloom_deploy_audit.pg361_xmage_recursion_battlefield_selection_constraints_) AS backup_rows
FROM proposed p
LEFT JOIN rule_rows r
  ON r.normalized_name = p.normalized_name
 AND r.logical_rule_key = p.logical_rule_key
 AND r.oracle_hash = p.oracle_hash
GROUP BY p.card_name, p.normalized_name, p.logical_rule_key, p.oracle_hash
ORDER BY p.card_name;
