WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('drag under', 'Drag Under', '6dd402431d3b7fb848824229d033614a', 'battle_rule_v1:f862445930f198fc3c6dc8a3d59362bb', '{"_composite_rule_components":[{"battle_model_scope":"xmage_return_target_to_hand_spell_v1","compose_on_resolution":true,"destination":"hand","effect":"remove_creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_effect_class":"ReturnToHandTargetEffect"},{"battle_model_scope":"xmage_fixed_source_controller_draw_spell_v1","compose_on_resolution":true,"count":1,"effect":"draw_cards","xmage_effect_class":"DrawCardSourceControllerEffect"}],"battle_model_scope":"xmage_return_target_to_hand_and_draw_card_spell_v1","count":1,"destination":"hand","draw_count":1,"effect":"composite_resolution","instant":false,"sorcery":true,"target":"creature","target_constraints":{"card_types":["creature"]},"xmage_effect_classes":["ReturnToHandTargetEffect","DrawCardSourceControllerEffect"]}'::jsonb, '{"category":"draw","effect":"composite_resolution","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DragUnder translated into ManaLoom runtime scope xmage_return_target_to_hand_and_draw_card_spell_v1. This row is package-ready only because the source signature is a narrow fixed return-target-to-hand plus draw-card spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('galestrike', 'Galestrike', 'e17ba3ddaf7febad91161213aad18a2a', 'battle_rule_v1:d6525baec4c35d68b522fb1fa2a96b9f', '{"_composite_rule_components":[{"battle_model_scope":"xmage_return_target_to_hand_spell_v1","compose_on_resolution":true,"destination":"hand","effect":"remove_creature","target":"creature","target_constraints":{"card_types":["creature"],"tapped_state":"tapped"},"xmage_effect_class":"ReturnToHandTargetEffect"},{"battle_model_scope":"xmage_fixed_source_controller_draw_spell_v1","compose_on_resolution":true,"count":1,"effect":"draw_cards","xmage_effect_class":"DrawCardSourceControllerEffect"}],"battle_model_scope":"xmage_return_target_to_hand_and_draw_card_spell_v1","count":1,"destination":"hand","draw_count":1,"effect":"composite_resolution","instant":true,"sorcery":false,"target":"creature","target_constraints":{"card_types":["creature"],"tapped_state":"tapped"},"xmage_effect_classes":["ReturnToHandTargetEffect","DrawCardSourceControllerEffect"]}'::jsonb, '{"category":"draw","effect":"composite_resolution","target":"creature","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Galestrike translated into ManaLoom runtime scope xmage_return_target_to_hand_and_draw_card_spell_v1. This row is package-ready only because the source signature is a narrow fixed return-target-to-hand plus draw-card spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('leave in the dust', 'Leave in the Dust', 'e0aea105a62d82d27328b92b26231700', 'battle_rule_v1:1db4bbcee08be05bdcfcdbc8c3503ab1', '{"_composite_rule_components":[{"battle_model_scope":"xmage_return_target_to_hand_spell_v1","compose_on_resolution":true,"destination":"hand","effect":"remove_permanent","target":"nonland_permanent","target_constraints":{"card_types":["nonland_permanent"]},"xmage_effect_class":"ReturnToHandTargetEffect"},{"battle_model_scope":"xmage_fixed_source_controller_draw_spell_v1","compose_on_resolution":true,"count":1,"effect":"draw_cards","xmage_effect_class":"DrawCardSourceControllerEffect"}],"battle_model_scope":"xmage_return_target_to_hand_and_draw_card_spell_v1","count":1,"destination":"hand","draw_count":1,"effect":"composite_resolution","instant":true,"sorcery":false,"target":"nonland_permanent","target_constraints":{"card_types":["nonland_permanent"]},"xmage_effect_classes":["ReturnToHandTargetEffect","DrawCardSourceControllerEffect"]}'::jsonb, '{"category":"draw","effect":"composite_resolution","target":"nonland_permanent","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class LeaveInTheDust translated into ManaLoom runtime scope xmage_return_target_to_hand_and_draw_card_spell_v1. This row is package-ready only because the source signature is a narrow fixed return-target-to-hand plus draw-card spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('repulse', 'Repulse', '6dd402431d3b7fb848824229d033614a', 'battle_rule_v1:c26825e6148a1ceed1bb1f5236af63de', '{"_composite_rule_components":[{"battle_model_scope":"xmage_return_target_to_hand_spell_v1","compose_on_resolution":true,"destination":"hand","effect":"remove_creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_effect_class":"ReturnToHandTargetEffect"},{"battle_model_scope":"xmage_fixed_source_controller_draw_spell_v1","compose_on_resolution":true,"count":1,"effect":"draw_cards","xmage_effect_class":"DrawCardSourceControllerEffect"}],"battle_model_scope":"xmage_return_target_to_hand_and_draw_card_spell_v1","count":1,"destination":"hand","draw_count":1,"effect":"composite_resolution","instant":true,"sorcery":false,"target":"creature","target_constraints":{"card_types":["creature"]},"xmage_effect_classes":["ReturnToHandTargetEffect","DrawCardSourceControllerEffect"]}'::jsonb, '{"category":"draw","effect":"composite_resolution","target":"creature","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Repulse translated into ManaLoom runtime scope xmage_return_target_to_hand_and_draw_card_spell_v1. This row is package-ready only because the source signature is a narrow fixed return-target-to-hand plus draw-card spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('symbol of unsummoning', 'Symbol of Unsummoning', '6dd402431d3b7fb848824229d033614a', 'battle_rule_v1:f862445930f198fc3c6dc8a3d59362bb', '{"_composite_rule_components":[{"battle_model_scope":"xmage_return_target_to_hand_spell_v1","compose_on_resolution":true,"destination":"hand","effect":"remove_creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_effect_class":"ReturnToHandTargetEffect"},{"battle_model_scope":"xmage_fixed_source_controller_draw_spell_v1","compose_on_resolution":true,"count":1,"effect":"draw_cards","xmage_effect_class":"DrawCardSourceControllerEffect"}],"battle_model_scope":"xmage_return_target_to_hand_and_draw_card_spell_v1","count":1,"destination":"hand","draw_count":1,"effect":"composite_resolution","instant":false,"sorcery":true,"target":"creature","target_constraints":{"card_types":["creature"]},"xmage_effect_classes":["ReturnToHandTargetEffect","DrawCardSourceControllerEffect"]}'::jsonb, '{"category":"draw","effect":"composite_resolution","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SymbolOfUnsummoning translated into ManaLoom runtime scope xmage_return_target_to_hand_and_draw_card_spell_v1. This row is package-ready only because the source signature is a narrow fixed return-target-to-hand plus draw-card spell with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
rule_rows AS (
  SELECT
    r.normalized_name,
    r.logical_rule_key,
    r.oracle_hash,
    r.review_status,
    r.execution_status
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key = p.logical_rule_key
)
SELECT
  p.card_name,
  p.normalized_name,
  p.logical_rule_key,
  count(r.*) FILTER (WHERE r.logical_rule_key = p.logical_rule_key) AS promoted_rule_rows,
  count(r.*) FILTER (WHERE r.review_status = 'verified' AND r.execution_status = 'auto') AS promoted_verified_auto_rows,
  count(r.*) FILTER (WHERE r.oracle_hash = p.oracle_hash) AS promoted_oracle_hash_rows,
  (SELECT count(*) FROM manaloom_deploy_audit.pg374_bounce_draw_spell_wave_pg374_bounce_draw_spell_wav) AS backup_rows
FROM proposed p
LEFT JOIN rule_rows r
  ON r.normalized_name = p.normalized_name
 AND r.logical_rule_key = p.logical_rule_key
 AND r.oracle_hash = p.oracle_hash
GROUP BY p.card_name, p.normalized_name, p.logical_rule_key, p.oracle_hash
ORDER BY p.card_name;
