WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('behold the multiverse', 'Behold the Multiverse', 'b5dcf35d4caca8940babf328de8c1f31', 'battle_rule_v1:ece086c9664b69de9394f97db5ea756c', '{"_composite_rule_components":[{"battle_model_scope":"xmage_fixed_scry_spell_v1","compose_on_resolution":true,"count":2,"effect":"scry","scry_count":2,"xmage_effect_class":"ScryEffect"},{"battle_model_scope":"xmage_fixed_source_controller_draw_spell_v1","compose_on_resolution":true,"count":2,"effect":"draw_cards","xmage_effect_class":"DrawCardSourceControllerEffect"}],"battle_model_scope":"xmage_fixed_scry_and_draw_cards_spell_v1","count":2,"draw_count":2,"effect":"composite_resolution","instant":true,"resolution_order":"scry_then_draw","scry_count":2,"sorcery":false,"xmage_effect_classes":["ScryEffect","DrawCardSourceControllerEffect"]}'::jsonb, '{"category":"draw","effect":"composite_resolution","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BeholdTheMultiverse translated into ManaLoom runtime scope xmage_fixed_scry_and_draw_cards_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('deliberate', 'Deliberate', 'f2f55a062b4f6ad52bd1fb7c63529cef', 'battle_rule_v1:e1fba59c194355b5d702d2384ba7255e', '{"_composite_rule_components":[{"battle_model_scope":"xmage_fixed_scry_spell_v1","compose_on_resolution":true,"count":2,"effect":"scry","scry_count":2,"xmage_effect_class":"ScryEffect"},{"battle_model_scope":"xmage_fixed_source_controller_draw_spell_v1","compose_on_resolution":true,"count":1,"effect":"draw_cards","xmage_effect_class":"DrawCardSourceControllerEffect"}],"battle_model_scope":"xmage_fixed_scry_and_draw_cards_spell_v1","count":1,"draw_count":1,"effect":"composite_resolution","instant":true,"resolution_order":"scry_then_draw","scry_count":2,"sorcery":false,"xmage_effect_classes":["ScryEffect","DrawCardSourceControllerEffect"]}'::jsonb, '{"category":"draw","effect":"composite_resolution","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Deliberate translated into ManaLoom runtime scope xmage_fixed_scry_and_draw_cards_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('ember shot', 'Ember Shot', 'ef308033ea4f278064135172d1f23f17', 'battle_rule_v1:6d22d148e6427e4547df23822d8e737c', '{"_composite_rule_components":[{"amount":3,"battle_model_scope":"xmage_fixed_damage_target_spell_v1","compose_on_resolution":true,"damage":3,"effect":"direct_damage","target":"any_target","target_constraints":{"scope":"any_target"},"xmage_effect_class":"DamageTargetEffect"},{"battle_model_scope":"xmage_fixed_source_controller_draw_spell_v1","compose_on_resolution":true,"count":1,"effect":"draw_cards","xmage_effect_class":"DrawCardSourceControllerEffect"}],"amount":3,"battle_model_scope":"xmage_fixed_damage_target_and_draw_card_spell_v1","count":1,"damage":3,"draw_count":1,"effect":"composite_resolution","instant":true,"sorcery":false,"target":"any_target","target_constraints":{"scope":"any_target"},"xmage_effect_classes":["DamageTargetEffect","DrawCardSourceControllerEffect"]}'::jsonb, '{"category":"draw","effect":"composite_resolution","target":"any_target","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class EmberShot translated into ManaLoom runtime scope xmage_fixed_damage_target_and_draw_card_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('foresee', 'Foresee', '1b64fbbd0f8f87760ea58c00aaac5830', 'battle_rule_v1:30f99495b1c991685ef9c793b6d34111', '{"_composite_rule_components":[{"battle_model_scope":"xmage_fixed_scry_spell_v1","compose_on_resolution":true,"count":4,"effect":"scry","scry_count":4,"xmage_effect_class":"ScryEffect"},{"battle_model_scope":"xmage_fixed_source_controller_draw_spell_v1","compose_on_resolution":true,"count":2,"effect":"draw_cards","xmage_effect_class":"DrawCardSourceControllerEffect"}],"battle_model_scope":"xmage_fixed_scry_and_draw_cards_spell_v1","count":2,"draw_count":2,"effect":"composite_resolution","instant":false,"resolution_order":"scry_then_draw","scry_count":4,"sorcery":true,"xmage_effect_classes":["ScryEffect","DrawCardSourceControllerEffect"]}'::jsonb, '{"category":"draw","effect":"composite_resolution"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Foresee translated into ManaLoom runtime scope xmage_fixed_scry_and_draw_cards_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('introduction to prophecy', 'Introduction to Prophecy', 'f2f55a062b4f6ad52bd1fb7c63529cef', 'battle_rule_v1:1397e7484b9f0eb7b8d6c223d0649aa6', '{"_composite_rule_components":[{"battle_model_scope":"xmage_fixed_scry_spell_v1","compose_on_resolution":true,"count":2,"effect":"scry","scry_count":2,"xmage_effect_class":"ScryEffect"},{"battle_model_scope":"xmage_fixed_source_controller_draw_spell_v1","compose_on_resolution":true,"count":1,"effect":"draw_cards","xmage_effect_class":"DrawCardSourceControllerEffect"}],"battle_model_scope":"xmage_fixed_scry_and_draw_cards_spell_v1","count":1,"draw_count":1,"effect":"composite_resolution","instant":false,"resolution_order":"scry_then_draw","scry_count":2,"sorcery":true,"xmage_effect_classes":["ScryEffect","DrawCardSourceControllerEffect"]}'::jsonb, '{"category":"draw","effect":"composite_resolution"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class IntroductionToProphecy translated into ManaLoom runtime scope xmage_fixed_scry_and_draw_cards_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('opt', 'Opt', 'a4b8e16d9deabd12619e9bef807b8c29', 'battle_rule_v1:448911d91036b97ef7d8cd638e13eb53', '{"_composite_rule_components":[{"battle_model_scope":"xmage_fixed_scry_spell_v1","compose_on_resolution":true,"count":1,"effect":"scry","scry_count":1,"xmage_effect_class":"ScryEffect"},{"battle_model_scope":"xmage_fixed_source_controller_draw_spell_v1","compose_on_resolution":true,"count":1,"effect":"draw_cards","xmage_effect_class":"DrawCardSourceControllerEffect"}],"battle_model_scope":"xmage_fixed_scry_and_draw_cards_spell_v1","count":1,"draw_count":1,"effect":"composite_resolution","instant":true,"resolution_order":"scry_then_draw","scry_count":1,"sorcery":false,"xmage_effect_classes":["ScryEffect","DrawCardSourceControllerEffect"]}'::jsonb, '{"category":"draw","effect":"composite_resolution","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Opt translated into ManaLoom runtime scope xmage_fixed_scry_and_draw_cards_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('playful shove', 'Playful Shove', '760e1e2161eec2ad9c8b87bede6caaa3', 'battle_rule_v1:e7a00222152c565ca14b520dbb05825f', '{"_composite_rule_components":[{"amount":1,"battle_model_scope":"xmage_fixed_damage_target_spell_v1","compose_on_resolution":true,"damage":1,"effect":"direct_damage","target":"any_target","target_constraints":{"scope":"any_target"},"xmage_effect_class":"DamageTargetEffect"},{"battle_model_scope":"xmage_fixed_source_controller_draw_spell_v1","compose_on_resolution":true,"count":1,"effect":"draw_cards","xmage_effect_class":"DrawCardSourceControllerEffect"}],"amount":1,"battle_model_scope":"xmage_fixed_damage_target_and_draw_card_spell_v1","count":1,"damage":1,"draw_count":1,"effect":"composite_resolution","instant":false,"sorcery":true,"target":"any_target","target_constraints":{"scope":"any_target"},"xmage_effect_classes":["DamageTargetEffect","DrawCardSourceControllerEffect"]}'::jsonb, '{"category":"draw","effect":"composite_resolution","target":"any_target"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PlayfulShove translated into ManaLoom runtime scope xmage_fixed_damage_target_and_draw_card_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('preordain', 'Preordain', 'fe08a291a061e602c16e75baf7f59d07', 'battle_rule_v1:1397e7484b9f0eb7b8d6c223d0649aa6', '{"_composite_rule_components":[{"battle_model_scope":"xmage_fixed_scry_spell_v1","compose_on_resolution":true,"count":2,"effect":"scry","scry_count":2,"xmage_effect_class":"ScryEffect"},{"battle_model_scope":"xmage_fixed_source_controller_draw_spell_v1","compose_on_resolution":true,"count":1,"effect":"draw_cards","xmage_effect_class":"DrawCardSourceControllerEffect"}],"battle_model_scope":"xmage_fixed_scry_and_draw_cards_spell_v1","count":1,"draw_count":1,"effect":"composite_resolution","instant":false,"resolution_order":"scry_then_draw","scry_count":2,"sorcery":true,"xmage_effect_classes":["ScryEffect","DrawCardSourceControllerEffect"]}'::jsonb, '{"category":"draw","effect":"composite_resolution"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Preordain translated into ManaLoom runtime scope xmage_fixed_scry_and_draw_cards_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('scour all possibilities', 'Scour All Possibilities', 'a4250e42e446bf2476fc20bb27cba9a9', 'battle_rule_v1:1397e7484b9f0eb7b8d6c223d0649aa6', '{"_composite_rule_components":[{"battle_model_scope":"xmage_fixed_scry_spell_v1","compose_on_resolution":true,"count":2,"effect":"scry","scry_count":2,"xmage_effect_class":"ScryEffect"},{"battle_model_scope":"xmage_fixed_source_controller_draw_spell_v1","compose_on_resolution":true,"count":1,"effect":"draw_cards","xmage_effect_class":"DrawCardSourceControllerEffect"}],"battle_model_scope":"xmage_fixed_scry_and_draw_cards_spell_v1","count":1,"draw_count":1,"effect":"composite_resolution","instant":false,"resolution_order":"scry_then_draw","scry_count":2,"sorcery":true,"xmage_effect_classes":["ScryEffect","DrawCardSourceControllerEffect"]}'::jsonb, '{"category":"draw","effect":"composite_resolution"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ScourAllPossibilities translated into ManaLoom runtime scope xmage_fixed_scry_and_draw_cards_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('serum visions', 'Serum Visions', 'b7221a769af9d2b428fb7d01e6a3aa00', 'battle_rule_v1:3672976f55360ae7e7d98412801098e2', '{"_composite_rule_components":[{"battle_model_scope":"xmage_fixed_source_controller_draw_spell_v1","compose_on_resolution":true,"count":1,"effect":"draw_cards","xmage_effect_class":"DrawCardSourceControllerEffect"},{"battle_model_scope":"xmage_fixed_scry_spell_v1","compose_on_resolution":true,"count":2,"effect":"scry","scry_count":2,"xmage_effect_class":"ScryEffect"}],"battle_model_scope":"xmage_fixed_scry_and_draw_cards_spell_v1","count":1,"draw_count":1,"effect":"composite_resolution","instant":false,"resolution_order":"draw_then_scry","scry_count":2,"sorcery":true,"xmage_effect_classes":["ScryEffect","DrawCardSourceControllerEffect"]}'::jsonb, '{"category":"draw","effect":"composite_resolution"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SerumVisions translated into ManaLoom runtime scope xmage_fixed_scry_and_draw_cards_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('tamiyo''s epiphany', 'Tamiyo''s Epiphany', '1b64fbbd0f8f87760ea58c00aaac5830', 'battle_rule_v1:30f99495b1c991685ef9c793b6d34111', '{"_composite_rule_components":[{"battle_model_scope":"xmage_fixed_scry_spell_v1","compose_on_resolution":true,"count":4,"effect":"scry","scry_count":4,"xmage_effect_class":"ScryEffect"},{"battle_model_scope":"xmage_fixed_source_controller_draw_spell_v1","compose_on_resolution":true,"count":2,"effect":"draw_cards","xmage_effect_class":"DrawCardSourceControllerEffect"}],"battle_model_scope":"xmage_fixed_scry_and_draw_cards_spell_v1","count":2,"draw_count":2,"effect":"composite_resolution","instant":false,"resolution_order":"scry_then_draw","scry_count":4,"sorcery":true,"xmage_effect_classes":["ScryEffect","DrawCardSourceControllerEffect"]}'::jsonb, '{"category":"draw","effect":"composite_resolution"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TamiyosEpiphany translated into ManaLoom runtime scope xmage_fixed_scry_and_draw_cards_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('zap', 'Zap', 'f03297ade8a9a5b96d86985f840e7938', 'battle_rule_v1:31ce6de3abbfe9af7568a7ba3e20704a', '{"_composite_rule_components":[{"amount":1,"battle_model_scope":"xmage_fixed_damage_target_spell_v1","compose_on_resolution":true,"damage":1,"effect":"direct_damage","target":"any_target","target_constraints":{"scope":"any_target"},"xmage_effect_class":"DamageTargetEffect"},{"battle_model_scope":"xmage_fixed_source_controller_draw_spell_v1","compose_on_resolution":true,"count":1,"effect":"draw_cards","xmage_effect_class":"DrawCardSourceControllerEffect"}],"amount":1,"battle_model_scope":"xmage_fixed_damage_target_and_draw_card_spell_v1","count":1,"damage":1,"draw_count":1,"effect":"composite_resolution","instant":true,"sorcery":false,"target":"any_target","target_constraints":{"scope":"any_target"},"xmage_effect_classes":["DamageTargetEffect","DrawCardSourceControllerEffect"]}'::jsonb, '{"category":"draw","effect":"composite_resolution","target":"any_target","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Zap translated into ManaLoom runtime scope xmage_fixed_damage_target_and_draw_card_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
rule_rows AS (
  SELECT
    r.normalized_name,
    r.logical_rule_key,
    r.oracle_hash,
    r.review_status,
    r.execution_status
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key = p.logical_rule_key
)
SELECT
  p.card_name,
  p.normalized_name,
  p.logical_rule_key,
  count(r.*) FILTER (WHERE r.logical_rule_key = p.logical_rule_key) AS promoted_rule_rows,
  count(r.*) FILTER (WHERE r.review_status = 'verified' AND r.execution_status = 'auto') AS promoted_verified_auto_rows,
  count(r.*) FILTER (WHERE r.oracle_hash = p.oracle_hash) AS promoted_oracle_hash_rows,
  (SELECT count(*) FROM manaloom_deploy_audit.pg376_scry_damage_draw_20260704_011604) AS backup_rows
FROM proposed p
LEFT JOIN rule_rows r
  ON r.normalized_name = p.normalized_name
 AND r.logical_rule_key = p.logical_rule_key
 AND r.oracle_hash = p.oracle_hash
GROUP BY p.card_name, p.normalized_name, p.logical_rule_key, p.oracle_hash
ORDER BY p.card_name;
