WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('borderland ranger', 'Borderland Ranger', 'f2f4833506e6958d3a8e75af0b350496', 'battle_rule_v1:8b86c15462bd876a6003e8f63063e2ef', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_library_search_to_hand_v1","count":1,"destination":"hand","effect":"creature","etb_tutor_count":1,"etb_tutor_target":"basic_land_to_hand","target":"basic_land_to_hand","trigger":"enters_battlefield","trigger_effect":"library_tutor_to_hand","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"basic_land_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BorderlandRanger translated into ManaLoom runtime scope xmage_creature_etb_library_search_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('call the gatewatch', 'Call the Gatewatch', 'c2f91fea6b8e3049f33ee913296a213c', 'battle_rule_v1:caae61758f5148c88717d895a55aa3e2', '{"battle_model_scope":"xmage_library_search_to_hand_spell_v1","count":1,"destination":"hand","effect":"tutor","instant":false,"max_count":1,"sorcery":true,"target":"planeswalker_to_hand","target_card_types":["planeswalker"],"xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"tutor","effect":"tutor","target":"planeswalker_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CallTheGatewatch translated into ManaLoom runtime scope xmage_library_search_to_hand_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('cateran summons', 'Cateran Summons', '47864ad63a4d50c1691191e60f961bc5', 'battle_rule_v1:2d7e82f759e6d816feb9c1b1054766a8', '{"battle_model_scope":"xmage_library_search_to_hand_spell_v1","count":1,"destination":"hand","effect":"tutor","instant":false,"max_count":1,"sorcery":true,"target":"any_to_hand","target_card_types":["creature"],"target_subtypes":["mercenary"],"xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"tutor","effect":"tutor","target":"any_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CateranSummons translated into ManaLoom runtime scope xmage_library_search_to_hand_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('civic wayfinder', 'Civic Wayfinder', 'f2f4833506e6958d3a8e75af0b350496', 'battle_rule_v1:8b86c15462bd876a6003e8f63063e2ef', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_library_search_to_hand_v1","count":1,"destination":"hand","effect":"creature","etb_tutor_count":1,"etb_tutor_target":"basic_land_to_hand","target":"basic_land_to_hand","trigger":"enters_battlefield","trigger_effect":"library_tutor_to_hand","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"basic_land_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CivicWayfinder translated into ManaLoom runtime scope xmage_creature_etb_library_search_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('daru cavalier', 'Daru Cavalier', '41fe645d9e551925b96b2d07568cecce', 'battle_rule_v1:6775001dd7541098c239a0b938f510d1', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_library_search_to_hand_v1","count":1,"destination":"hand","effect":"creature","etb_tutor_count":1,"etb_tutor_target":"any_to_hand","first_strike":true,"keywords":["first_strike"],"target":"any_to_hand","target_names":["daru cavalier"],"trigger":"enters_battlefield","trigger_effect":"library_tutor_to_hand","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"any_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DaruCavalier translated into ManaLoom runtime scope xmage_creature_etb_library_search_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('deadeye quartermaster', 'Deadeye Quartermaster', '0a951c7941b92c9cd4dd1158cd6db5a4', 'battle_rule_v1:9e97b00ca55bebfd72f637c1b183c116', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_library_search_to_hand_v1","count":1,"destination":"hand","effect":"creature","etb_tutor_count":1,"etb_tutor_target":"any_to_hand","target":"any_to_hand","target_subtypes":["equipment","vehicle"],"trigger":"enters_battlefield","trigger_effect":"library_tutor_to_hand","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"any_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DeadeyeQuartermaster translated into ManaLoom runtime scope xmage_creature_etb_library_search_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('diabolic tutor', 'Diabolic Tutor', '7c881aaacf79f25b41c9788cf307e795', 'battle_rule_v1:3c1042b6ae3a2c610e70ad411460a46e', '{"battle_model_scope":"xmage_library_search_to_hand_spell_v1","count":1,"destination":"hand","effect":"tutor","instant":false,"max_count":1,"sorcery":true,"target":"any_to_hand","xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"tutor","effect":"tutor","target":"any_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DiabolicTutor translated into ManaLoom runtime scope xmage_library_search_to_hand_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('district guide', 'District Guide', 'bd379aab37683cb261cd236e97a6040a', 'battle_rule_v1:cae4abb78b40dd74ed99c9bd02ebc897', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_library_search_to_hand_v1","count":1,"destination":"hand","effect":"creature","etb_tutor_count":1,"etb_tutor_target":"basic_land_or_gate_to_hand","target":"basic_land_or_gate_to_hand","trigger":"enters_battlefield","trigger_effect":"library_tutor_to_hand","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"basic_land_or_gate_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DistrictGuide translated into ManaLoom runtime scope xmage_creature_etb_library_search_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('eerie procession', 'Eerie Procession', '98942b8c0812342e18938bf9c7ebeec4', 'battle_rule_v1:762264b1d43e6e1344585b6762d633f5', '{"battle_model_scope":"xmage_library_search_to_hand_spell_v1","count":1,"destination":"hand","effect":"tutor","instant":false,"max_count":1,"sorcery":true,"target":"any_to_hand","target_subtypes":["arcane"],"xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"tutor","effect":"tutor","target":"any_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class EerieProcession translated into ManaLoom runtime scope xmage_library_search_to_hand_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('environmental scientist', 'Environmental Scientist', 'f2f4833506e6958d3a8e75af0b350496', 'battle_rule_v1:8b86c15462bd876a6003e8f63063e2ef', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_library_search_to_hand_v1","count":1,"destination":"hand","effect":"creature","etb_tutor_count":1,"etb_tutor_target":"basic_land_to_hand","target":"basic_land_to_hand","trigger":"enters_battlefield","trigger_effect":"library_tutor_to_hand","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"basic_land_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class EnvironmentalScientist translated into ManaLoom runtime scope xmage_creature_etb_library_search_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('farfinder', 'Farfinder', '66bb7a6119514caebac90f810be795da', 'battle_rule_v1:508f7fd96ceb577a5f2dab380f6609cb', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_library_search_to_hand_v1","count":1,"destination":"hand","effect":"creature","etb_tutor_count":1,"etb_tutor_target":"basic_land_to_hand","keywords":["vigilance"],"target":"basic_land_to_hand","trigger":"enters_battlefield","trigger_effect":"library_tutor_to_hand","vigilance":true,"xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"basic_land_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Farfinder translated into ManaLoom runtime scope xmage_creature_etb_library_search_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('gatecreeper vine', 'Gatecreeper Vine', '5badaa30071e88ec1abf7a90a4b174c7', 'battle_rule_v1:0dc034646dd47d08c47a9c864a1e9d91', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_library_search_to_hand_v1","count":1,"defender":true,"destination":"hand","effect":"creature","etb_tutor_count":1,"etb_tutor_target":"basic_land_or_gate_to_hand","keywords":["defender"],"target":"basic_land_or_gate_to_hand","trigger":"enters_battlefield","trigger_effect":"library_tutor_to_hand","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"basic_land_or_gate_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GatecreeperVine translated into ManaLoom runtime scope xmage_creature_etb_library_search_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('goblin matron', 'Goblin Matron', '285c67f13cdc988f44ee9e5eb3e0aecc', 'battle_rule_v1:d31ea65123fba8521086549312fda8f2', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_library_search_to_hand_v1","count":1,"destination":"hand","effect":"creature","etb_tutor_count":1,"etb_tutor_target":"any_to_hand","target":"any_to_hand","target_subtypes":["goblin"],"trigger":"enters_battlefield","trigger_effect":"library_tutor_to_hand","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"any_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GoblinMatron translated into ManaLoom runtime scope xmage_creature_etb_library_search_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('heliod''s pilgrim', 'Heliod''s Pilgrim', '6138101a172460fd94a162178ab2f459', 'battle_rule_v1:1a4b45547bbe36030aa08de22d039cf4', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_library_search_to_hand_v1","count":1,"destination":"hand","effect":"creature","etb_tutor_count":1,"etb_tutor_target":"any_to_hand","target":"any_to_hand","target_subtypes":["aura"],"trigger":"enters_battlefield","trigger_effect":"library_tutor_to_hand","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"any_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HeliodsPilgrim translated into ManaLoom runtime scope xmage_creature_etb_library_search_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('howling wolf', 'Howling Wolf', '06c26c7bc5ef8d84596f44569d3cca14', 'battle_rule_v1:2433fd9cab6ea1f19548e0f766b82e4e', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_library_search_to_hand_v1","count":3,"destination":"hand","effect":"creature","etb_tutor_count":3,"etb_tutor_target":"any_to_hand","etb_tutor_up_to_count":true,"target":"any_to_hand","target_names":["howling wolf"],"trigger":"enters_battlefield","trigger_effect":"library_tutor_to_hand","up_to_count":true,"xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"any_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HowlingWolf translated into ManaLoom runtime scope xmage_creature_etb_library_search_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('ignite the beacon', 'Ignite the Beacon', 'e6265bc22dd6b0fe6d4bb70a1ff9f1c7', 'battle_rule_v1:08ac438e086ce79989b6a0e05eed4b74', '{"battle_model_scope":"xmage_library_search_to_hand_spell_v1","count":2,"destination":"hand","effect":"tutor","instant":true,"max_count":2,"sorcery":false,"target":"planeswalker_to_hand","target_card_types":["planeswalker"],"up_to_count":true,"xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"tutor","effect":"tutor","target":"planeswalker_to_hand","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class IgniteTheBeacon translated into ManaLoom runtime scope xmage_library_search_to_hand_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('merchant scroll', 'Merchant Scroll', '9e130df41e16842e764941c6669ea620', 'battle_rule_v1:0d4352abb63d2eac010177d2e1f5f7e6', '{"battle_model_scope":"xmage_library_search_to_hand_spell_v1","count":1,"destination":"hand","effect":"tutor","instant":false,"max_count":1,"sorcery":true,"target":"instant_to_hand","target_card_types":["instant"],"target_colors":["U"],"xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"tutor","effect":"tutor","target":"instant_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MerchantScroll translated into ManaLoom runtime scope xmage_library_search_to_hand_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('nesting wurm', 'Nesting Wurm', '873788b661c8627405133b3a1c381674', 'battle_rule_v1:aacc2a09fb5bbb4643c96c72260e6e26', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_library_search_to_hand_v1","count":3,"destination":"hand","effect":"creature","etb_tutor_count":3,"etb_tutor_target":"any_to_hand","etb_tutor_up_to_count":true,"keywords":["trample"],"target":"any_to_hand","target_names":["nesting wurm"],"trample":true,"trigger":"enters_battlefield","trigger_effect":"library_tutor_to_hand","up_to_count":true,"xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"any_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class NestingWurm translated into ManaLoom runtime scope xmage_creature_etb_library_search_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('open the armory', 'Open the Armory', 'fa220f5773cf5c988e507c714b849503', 'battle_rule_v1:868d143f306cb5e8dfc486f76f8b6369', '{"battle_model_scope":"xmage_library_search_to_hand_spell_v1","count":1,"destination":"hand","effect":"tutor","instant":false,"max_count":1,"sorcery":true,"target":"any_to_hand","target_subtypes":["aura","equipment"],"xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"tutor","effect":"tutor","target":"any_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class OpenTheArmory translated into ManaLoom runtime scope xmage_library_search_to_hand_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('plea for guidance', 'Plea for Guidance', '5c417011e3ed943702026eefc309340f', 'battle_rule_v1:c0342670c739d786cd63c9aa0eb13e83', '{"battle_model_scope":"xmage_library_search_to_hand_spell_v1","count":2,"destination":"hand","effect":"tutor","instant":false,"max_count":2,"sorcery":true,"target":"enchantment_to_hand","target_card_types":["enchantment"],"up_to_count":true,"xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"tutor","effect":"tutor","target":"enchantment_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PleaForGuidance translated into ManaLoom runtime scope xmage_library_search_to_hand_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('ranger of eos', 'Ranger of Eos', 'be899355fd24b180088b1bf967734efb', 'battle_rule_v1:f77411c08095fd4bd3cc42ade3c1254d', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_library_search_to_hand_v1","count":2,"destination":"hand","effect":"creature","etb_tutor_count":2,"etb_tutor_target":"creature_to_hand","etb_tutor_up_to_count":true,"target":"creature_to_hand","target_card_types":["creature"],"target_mana_value_max":1,"trigger":"enters_battlefield","trigger_effect":"library_tutor_to_hand","up_to_count":true,"xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class RangerOfEos translated into ManaLoom runtime scope xmage_creature_etb_library_search_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('rune-scarred demon', 'Rune-Scarred Demon', '6544a9183b59cb44dbad6f4ed0549b56', 'battle_rule_v1:0bae6fefb7dc4689f938c64fa7818332', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_library_search_to_hand_v1","count":1,"destination":"hand","effect":"creature","etb_tutor_count":1,"etb_tutor_target":"any_to_hand","flying":true,"keywords":["flying"],"target":"any_to_hand","trigger":"enters_battlefield","trigger_effect":"library_tutor_to_hand","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"any_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class RuneScarredDemon translated into ManaLoom runtime scope xmage_creature_etb_library_search_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('safewright quest', 'Safewright Quest', '6d6ed58f38f4a9226bf9d849cbed96d1', 'battle_rule_v1:cd7fc0b01dfcf89afa14a9591f7e22bb', '{"battle_model_scope":"xmage_library_search_to_hand_spell_v1","count":1,"destination":"hand","effect":"tutor","instant":false,"max_count":1,"sorcery":true,"target":"land_to_hand","target_card_types":["land"],"target_subtypes":["forest","plains"],"xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"tutor","effect":"tutor","target":"land_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SafewrightQuest translated into ManaLoom runtime scope xmage_library_search_to_hand_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sarkhan''s triumph', 'Sarkhan''s Triumph', 'b31496681c661b16b744df79de670d1b', 'battle_rule_v1:0f1e6a10f42f7c0c834c89ae0c6e72e4', '{"battle_model_scope":"xmage_library_search_to_hand_spell_v1","count":1,"destination":"hand","effect":"tutor","instant":true,"max_count":1,"sorcery":false,"target":"creature_to_hand","target_card_types":["creature"],"target_subtypes":["dragon"],"xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"tutor","effect":"tutor","target":"creature_to_hand","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SarkhansTriumph translated into ManaLoom runtime scope xmage_library_search_to_hand_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('screaming seahawk', 'Screaming Seahawk', '348083d02bf53a9680361f640214da58', 'battle_rule_v1:9083a0a280f37d9cc680368622de965b', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_library_search_to_hand_v1","count":1,"destination":"hand","effect":"creature","etb_tutor_count":1,"etb_tutor_target":"any_to_hand","flying":true,"keywords":["flying"],"target":"any_to_hand","target_names":["screaming seahawk"],"trigger":"enters_battlefield","trigger_effect":"library_tutor_to_hand","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"any_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ScreamingSeahawk translated into ManaLoom runtime scope xmage_creature_etb_library_search_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('seek the horizon', 'Seek the Horizon', 'd74a1f98d1c82a4c62e872c89438fbc9', 'battle_rule_v1:18d04737564bf889d16bdd128abb8848', '{"battle_model_scope":"xmage_library_search_to_hand_spell_v1","count":3,"destination":"hand","effect":"tutor","instant":false,"max_count":3,"sorcery":true,"target":"basic_land_to_hand","up_to_count":true,"xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"tutor","effect":"tutor","target":"basic_land_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SeekTheHorizon translated into ManaLoom runtime scope xmage_library_search_to_hand_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('skyshroud sentinel', 'Skyshroud Sentinel', '1ff341c586feed508faf3c994f24ec6e', 'battle_rule_v1:8b37bfb8924d03b85324e385e2c17666', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_library_search_to_hand_v1","count":3,"destination":"hand","effect":"creature","etb_tutor_count":3,"etb_tutor_target":"any_to_hand","etb_tutor_up_to_count":true,"target":"any_to_hand","target_names":["skyshroud sentinel"],"trigger":"enters_battlefield","trigger_effect":"library_tutor_to_hand","up_to_count":true,"xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"any_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SkyshroudSentinel translated into ManaLoom runtime scope xmage_creature_etb_library_search_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('solve the equation', 'Solve the Equation', '14e38120c0e1603f7bca82f1c2b5e5f1', 'battle_rule_v1:43267ad1d8a2accee0fd7fbf8e17dcb1', '{"battle_model_scope":"xmage_library_search_to_hand_spell_v1","count":1,"destination":"hand","effect":"tutor","instant":false,"max_count":1,"sorcery":true,"target":"instant_or_sorcery_to_hand","xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"tutor","effect":"tutor","target":"instant_or_sorcery_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SolveTheEquation translated into ManaLoom runtime scope xmage_library_search_to_hand_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('squadron hawk', 'Squadron Hawk', '8760c3ad97cb4c0042f87b4d83336e1d', 'battle_rule_v1:877168f396e3b0b4ed186a76f0b99995', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_library_search_to_hand_v1","count":3,"destination":"hand","effect":"creature","etb_tutor_count":3,"etb_tutor_target":"any_to_hand","etb_tutor_up_to_count":true,"flying":true,"keywords":["flying"],"target":"any_to_hand","target_names":["squadron hawk"],"trigger":"enters_battlefield","trigger_effect":"library_tutor_to_hand","up_to_count":true,"xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"any_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SquadronHawk translated into ManaLoom runtime scope xmage_creature_etb_library_search_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sylvan ranger', 'Sylvan Ranger', 'f2f4833506e6958d3a8e75af0b350496', 'battle_rule_v1:8b86c15462bd876a6003e8f63063e2ef', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_library_search_to_hand_v1","count":1,"destination":"hand","effect":"creature","etb_tutor_count":1,"etb_tutor_target":"basic_land_to_hand","target":"basic_land_to_hand","trigger":"enters_battlefield","trigger_effect":"library_tutor_to_hand","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"basic_land_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SylvanRanger translated into ManaLoom runtime scope xmage_creature_etb_library_search_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('time of need', 'Time of Need', '9e4dbb5c6d939e1d3801c29b6173e7b5', 'battle_rule_v1:e5c23aff5977ec12d3a85ee773fe69df', '{"battle_model_scope":"xmage_library_search_to_hand_spell_v1","count":1,"destination":"hand","effect":"tutor","instant":false,"max_count":1,"required_supertypes":["legendary"],"sorcery":true,"target":"creature_to_hand","target_card_types":["creature"],"xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"tutor","effect":"tutor","target":"creature_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TimeOfNeed translated into ManaLoom runtime scope xmage_library_search_to_hand_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('totem-guide hartebeest', 'Totem-Guide Hartebeest', '6138101a172460fd94a162178ab2f459', 'battle_rule_v1:1a4b45547bbe36030aa08de22d039cf4', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_library_search_to_hand_v1","count":1,"destination":"hand","effect":"creature","etb_tutor_count":1,"etb_tutor_target":"any_to_hand","target":"any_to_hand","target_subtypes":["aura"],"trigger":"enters_battlefield","trigger_effect":"library_tutor_to_hand","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"any_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TotemGuideHartebeest translated into ManaLoom runtime scope xmage_creature_etb_library_search_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('transit mage', 'Transit Mage', '9459579bdb675a5e3f72daaeb58b2eee', 'battle_rule_v1:daedbef22c68668817a41354b76423bd', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_library_search_to_hand_v1","count":1,"destination":"hand","effect":"creature","etb_tutor_count":1,"etb_tutor_target":"artifact_to_hand","target":"artifact_to_hand","target_card_types":["artifact"],"target_mana_value_max":5,"target_mana_value_min":4,"trigger":"enters_battlefield","trigger_effect":"library_tutor_to_hand","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"artifact_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TransitMage translated into ManaLoom runtime scope xmage_creature_etb_library_search_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('trapmaker''s snare', 'Trapmaker''s Snare', '17aaa73f597367e9b8c77f1fa28f5301', 'battle_rule_v1:b9456967545569631aad27c2e338e700', '{"battle_model_scope":"xmage_library_search_to_hand_spell_v1","count":1,"destination":"hand","effect":"tutor","instant":true,"max_count":1,"sorcery":false,"target":"any_to_hand","target_subtypes":["trap"],"xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"tutor","effect":"tutor","target":"any_to_hand","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TrapmakersSnare translated into ManaLoom runtime scope xmage_library_search_to_hand_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('tribute mage', 'Tribute Mage', '4105067c06ea609ff5440f507564b08b', 'battle_rule_v1:cf4fcf67e3d80509176a51d7650e4d53', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_library_search_to_hand_v1","count":1,"destination":"hand","effect":"creature","etb_tutor_count":1,"etb_tutor_target":"artifact_to_hand","target":"artifact_to_hand","target_card_types":["artifact"],"target_mana_value_max":2,"target_mana_value_min":2,"trigger":"enters_battlefield","trigger_effect":"library_tutor_to_hand","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"SearchLibraryPutInHandEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"artifact_to_hand"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TributeMage translated into ManaLoom runtime scope xmage_creature_etb_library_search_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
matched_cards AS (
  SELECT
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    c.id AS card_id,
    c.name AS db_card_name
  FROM proposed p
  LEFT JOIN public.cards c
    ON (
         lower(c.name) = p.normalized_name
         OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
       )
   AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
),
target_cards AS (
  SELECT
    normalized_name,
    card_name,
    oracle_hash,
    count(card_id) AS target_card_rows,
    min(card_id::text)::uuid AS canonical_card_id,
    min(db_card_name) AS canonical_card_name
  FROM matched_cards
  GROUP BY normalized_name, card_name, oracle_hash
),
rule_rows AS (
  SELECT p.normalized_name, count(r.*) AS existing_rule_rows
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
  GROUP BY p.normalized_name
),
expected_rows AS (
  SELECT p.normalized_name, count(r.*) AS expected_rule_rows_before
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key = p.logical_rule_key
  GROUP BY p.normalized_name
),
shadow_rows AS (
  SELECT p.normalized_name, count(r.*) AS would_deprecate_shadow_rows
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key <> p.logical_rule_key
   AND r.review_status NOT IN ('deprecated', 'rejected')
   AND r.execution_status <> 'disabled'
  GROUP BY p.normalized_name
)
SELECT
  p.card_name,
  p.normalized_name,
  p.oracle_hash,
  p.logical_rule_key,
  p.shadow_handling,
  tc.target_card_rows,
  tc.canonical_card_id,
  rr.existing_rule_rows,
  er.expected_rule_rows_before,
  sr.would_deprecate_shadow_rows
FROM proposed p
JOIN target_cards tc USING (normalized_name, card_name, oracle_hash)
JOIN rule_rows rr USING (normalized_name)
JOIN expected_rows er USING (normalized_name)
JOIN shadow_rows sr USING (normalized_name)
ORDER BY p.card_name;
