WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('barbarian general', 'Barbarian General', '6f10a2a07dbc67283d061eeaaded1b53', 'battle_rule_v1:7d208ac6a5625631cd5f858097f64cdd', '{"_keywords_are_self":true,"ability_kind":"static","battle_model_scope":"xmage_static_self_horsemanship_creature_v1","effect":"creature","horsemanship":true,"keywords":["horsemanship"],"static_effect":"self_horsemanship","target":"self","target_controller":"self","xmage_ability_class":"HorsemanshipAbility"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BarbarianGeneral translated into ManaLoom runtime scope xmage_static_self_horsemanship_creature_v1. This row is package-ready only because the source signature is a narrow creature static self horsemanship evasion with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('lady zhurong, warrior queen', 'Lady Zhurong, Warrior Queen', '6f10a2a07dbc67283d061eeaaded1b53', 'battle_rule_v1:7d208ac6a5625631cd5f858097f64cdd', '{"_keywords_are_self":true,"ability_kind":"static","battle_model_scope":"xmage_static_self_horsemanship_creature_v1","effect":"creature","horsemanship":true,"keywords":["horsemanship"],"static_effect":"self_horsemanship","target":"self","target_controller":"self","xmage_ability_class":"HorsemanshipAbility"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class LadyZhurongWarriorQueen translated into ManaLoom runtime scope xmage_static_self_horsemanship_creature_v1. This row is package-ready only because the source signature is a narrow creature static self horsemanship evasion with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('lu meng, wu general', 'Lu Meng, Wu General', '6f10a2a07dbc67283d061eeaaded1b53', 'battle_rule_v1:7d208ac6a5625631cd5f858097f64cdd', '{"_keywords_are_self":true,"ability_kind":"static","battle_model_scope":"xmage_static_self_horsemanship_creature_v1","effect":"creature","horsemanship":true,"keywords":["horsemanship"],"static_effect":"self_horsemanship","target":"self","target_controller":"self","xmage_ability_class":"HorsemanshipAbility"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class LuMengWuGeneral translated into ManaLoom runtime scope xmage_static_self_horsemanship_creature_v1. This row is package-ready only because the source signature is a narrow creature static self horsemanship evasion with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('shu cavalry', 'Shu Cavalry', '6f10a2a07dbc67283d061eeaaded1b53', 'battle_rule_v1:7d208ac6a5625631cd5f858097f64cdd', '{"_keywords_are_self":true,"ability_kind":"static","battle_model_scope":"xmage_static_self_horsemanship_creature_v1","effect":"creature","horsemanship":true,"keywords":["horsemanship"],"static_effect":"self_horsemanship","target":"self","target_controller":"self","xmage_ability_class":"HorsemanshipAbility"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ShuCavalry translated into ManaLoom runtime scope xmage_static_self_horsemanship_creature_v1. This row is package-ready only because the source signature is a narrow creature static self horsemanship evasion with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('shu elite companions', 'Shu Elite Companions', '6f10a2a07dbc67283d061eeaaded1b53', 'battle_rule_v1:7d208ac6a5625631cd5f858097f64cdd', '{"_keywords_are_self":true,"ability_kind":"static","battle_model_scope":"xmage_static_self_horsemanship_creature_v1","effect":"creature","horsemanship":true,"keywords":["horsemanship"],"static_effect":"self_horsemanship","target":"self","target_controller":"self","xmage_ability_class":"HorsemanshipAbility"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ShuEliteCompanions translated into ManaLoom runtime scope xmage_static_self_horsemanship_creature_v1. This row is package-ready only because the source signature is a narrow creature static self horsemanship evasion with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('wei elite companions', 'Wei Elite Companions', '6f10a2a07dbc67283d061eeaaded1b53', 'battle_rule_v1:7d208ac6a5625631cd5f858097f64cdd', '{"_keywords_are_self":true,"ability_kind":"static","battle_model_scope":"xmage_static_self_horsemanship_creature_v1","effect":"creature","horsemanship":true,"keywords":["horsemanship"],"static_effect":"self_horsemanship","target":"self","target_controller":"self","xmage_ability_class":"HorsemanshipAbility"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class WeiEliteCompanions translated into ManaLoom runtime scope xmage_static_self_horsemanship_creature_v1. This row is package-ready only because the source signature is a narrow creature static self horsemanship evasion with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('wei scout', 'Wei Scout', '6f10a2a07dbc67283d061eeaaded1b53', 'battle_rule_v1:7d208ac6a5625631cd5f858097f64cdd', '{"_keywords_are_self":true,"ability_kind":"static","battle_model_scope":"xmage_static_self_horsemanship_creature_v1","effect":"creature","horsemanship":true,"keywords":["horsemanship"],"static_effect":"self_horsemanship","target":"self","target_controller":"self","xmage_ability_class":"HorsemanshipAbility"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class WeiScout translated into ManaLoom runtime scope xmage_static_self_horsemanship_creature_v1. This row is package-ready only because the source signature is a narrow creature static self horsemanship evasion with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('wei strike force', 'Wei Strike Force', '6f10a2a07dbc67283d061eeaaded1b53', 'battle_rule_v1:7d208ac6a5625631cd5f858097f64cdd', '{"_keywords_are_self":true,"ability_kind":"static","battle_model_scope":"xmage_static_self_horsemanship_creature_v1","effect":"creature","horsemanship":true,"keywords":["horsemanship"],"static_effect":"self_horsemanship","target":"self","target_controller":"self","xmage_ability_class":"HorsemanshipAbility"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class WeiStrikeForce translated into ManaLoom runtime scope xmage_static_self_horsemanship_creature_v1. This row is package-ready only because the source signature is a narrow creature static self horsemanship evasion with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('wu elite cavalry', 'Wu Elite Cavalry', '6f10a2a07dbc67283d061eeaaded1b53', 'battle_rule_v1:7d208ac6a5625631cd5f858097f64cdd', '{"_keywords_are_self":true,"ability_kind":"static","battle_model_scope":"xmage_static_self_horsemanship_creature_v1","effect":"creature","horsemanship":true,"keywords":["horsemanship"],"static_effect":"self_horsemanship","target":"self","target_controller":"self","xmage_ability_class":"HorsemanshipAbility"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class WuEliteCavalry translated into ManaLoom runtime scope xmage_static_self_horsemanship_creature_v1. This row is package-ready only because the source signature is a narrow creature static self horsemanship evasion with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('wu light cavalry', 'Wu Light Cavalry', '6f10a2a07dbc67283d061eeaaded1b53', 'battle_rule_v1:7d208ac6a5625631cd5f858097f64cdd', '{"_keywords_are_self":true,"ability_kind":"static","battle_model_scope":"xmage_static_self_horsemanship_creature_v1","effect":"creature","horsemanship":true,"keywords":["horsemanship"],"static_effect":"self_horsemanship","target":"self","target_controller":"self","xmage_ability_class":"HorsemanshipAbility"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class WuLightCavalry translated into ManaLoom runtime scope xmage_static_self_horsemanship_creature_v1. This row is package-ready only because the source signature is a narrow creature static self horsemanship evasion with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
rule_rows AS (
  SELECT
    r.normalized_name,
    r.logical_rule_key,
    r.oracle_hash,
    r.review_status,
    r.execution_status
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key = p.logical_rule_key
)
SELECT
  p.card_name,
  p.normalized_name,
  p.logical_rule_key,
  count(r.*) FILTER (WHERE r.logical_rule_key = p.logical_rule_key) AS promoted_rule_rows,
  count(r.*) FILTER (WHERE r.review_status = 'verified' AND r.execution_status = 'auto') AS promoted_verified_auto_rows,
  count(r.*) FILTER (WHERE r.oracle_hash = p.oracle_hash) AS promoted_oracle_hash_rows,
  (SELECT count(*) FROM manaloom_deploy_audit.pg424_xmage_static_horsemanship_new_server_20260704_1920) AS backup_rows
FROM proposed p
LEFT JOIN rule_rows r
  ON r.normalized_name = p.normalized_name
 AND r.logical_rule_key = p.logical_rule_key
 AND r.oracle_hash = p.oracle_hash
GROUP BY p.card_name, p.normalized_name, p.logical_rule_key, p.oracle_hash
ORDER BY p.card_name;
