BEGIN;

DELETE FROM public.card_battle_rules
WHERE normalized_name IN ('anaconda', 'anurid murkdiver', 'benthic behemoth', 'bog raiders', 'bog smugglers', 'bog tatters', 'bog wraith', 'bull hippo', 'canyon wildcat', 'cat warriors', 'cliff threader', 'devouring deep', 'dwarven grunt', 'elite cat warrior', 'emerald oryx', 'farbog explorer', 'glissa''s courier', 'goblin mountaineer', 'goblin spelunkers', 'grayscaled gharial', 'heartwood treefolk', 'hillcomber giant', 'jukai messenger', 'koth''s courier', 'leaf dancer', 'lost soul', 'lynx', 'marsh boa', 'marsh goblins', 'marsh threader', 'moor fiend', 'mountain goat', 'pale bears', 'plague beetle', 'pygmy allosaurus', 'raiding nightstalker', 'righteous avengers', 'river bear', 'rock badger', 'rootwater commando', 'rushwood dryad', 'segovian leviathan', 'shanodin dryads', 'slinking serpent', 'sokenzan bruiser', 'somberwald dryad', 'warthog', 'wild ox', 'willow dryad', 'zendikar farguide', 'zodiac dog', 'zodiac goat', 'zodiac horse', 'zodiac monkey', 'zodiac ox', 'zodiac pig', 'zodiac rabbit', 'zodiac rat', 'zodiac rooster', 'zodiac snake', 'zodiac tiger')
   OR normalized_name LIKE 'anaconda // %'
   OR normalized_name LIKE 'anurid murkdiver // %'
   OR normalized_name LIKE 'benthic behemoth // %'
   OR normalized_name LIKE 'bog raiders // %'
   OR normalized_name LIKE 'bog smugglers // %'
   OR normalized_name LIKE 'bog tatters // %'
   OR normalized_name LIKE 'bog wraith // %'
   OR normalized_name LIKE 'bull hippo // %'
   OR normalized_name LIKE 'canyon wildcat // %'
   OR normalized_name LIKE 'cat warriors // %'
   OR normalized_name LIKE 'cliff threader // %'
   OR normalized_name LIKE 'devouring deep // %'
   OR normalized_name LIKE 'dwarven grunt // %'
   OR normalized_name LIKE 'elite cat warrior // %'
   OR normalized_name LIKE 'emerald oryx // %'
   OR normalized_name LIKE 'farbog explorer // %'
   OR normalized_name LIKE 'glissa''s courier // %'
   OR normalized_name LIKE 'goblin mountaineer // %'
   OR normalized_name LIKE 'goblin spelunkers // %'
   OR normalized_name LIKE 'grayscaled gharial // %'
   OR normalized_name LIKE 'heartwood treefolk // %'
   OR normalized_name LIKE 'hillcomber giant // %'
   OR normalized_name LIKE 'jukai messenger // %'
   OR normalized_name LIKE 'koth''s courier // %'
   OR normalized_name LIKE 'leaf dancer // %'
   OR normalized_name LIKE 'lost soul // %'
   OR normalized_name LIKE 'lynx // %'
   OR normalized_name LIKE 'marsh boa // %'
   OR normalized_name LIKE 'marsh goblins // %'
   OR normalized_name LIKE 'marsh threader // %'
   OR normalized_name LIKE 'moor fiend // %'
   OR normalized_name LIKE 'mountain goat // %'
   OR normalized_name LIKE 'pale bears // %'
   OR normalized_name LIKE 'plague beetle // %'
   OR normalized_name LIKE 'pygmy allosaurus // %'
   OR normalized_name LIKE 'raiding nightstalker // %'
   OR normalized_name LIKE 'righteous avengers // %'
   OR normalized_name LIKE 'river bear // %'
   OR normalized_name LIKE 'rock badger // %'
   OR normalized_name LIKE 'rootwater commando // %'
   OR normalized_name LIKE 'rushwood dryad // %'
   OR normalized_name LIKE 'segovian leviathan // %'
   OR normalized_name LIKE 'shanodin dryads // %'
   OR normalized_name LIKE 'slinking serpent // %'
   OR normalized_name LIKE 'sokenzan bruiser // %'
   OR normalized_name LIKE 'somberwald dryad // %'
   OR normalized_name LIKE 'warthog // %'
   OR normalized_name LIKE 'wild ox // %'
   OR normalized_name LIKE 'willow dryad // %'
   OR normalized_name LIKE 'zendikar farguide // %'
   OR normalized_name LIKE 'zodiac dog // %'
   OR normalized_name LIKE 'zodiac goat // %'
   OR normalized_name LIKE 'zodiac horse // %'
   OR normalized_name LIKE 'zodiac monkey // %'
   OR normalized_name LIKE 'zodiac ox // %'
   OR normalized_name LIKE 'zodiac pig // %'
   OR normalized_name LIKE 'zodiac rabbit // %'
   OR normalized_name LIKE 'zodiac rat // %'
   OR normalized_name LIKE 'zodiac rooster // %'
   OR normalized_name LIKE 'zodiac snake // %'
   OR normalized_name LIKE 'zodiac tiger // %';

INSERT INTO public.card_battle_rules
SELECT *
FROM manaloom_deploy_audit.pg420_xmage_static_basic_landwalk_new_server_20260704_18;

COMMIT;
