WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('ambush viper', 'Ambush Viper', 'c8f16b33c4b28977abb1746f0387728e', 'battle_rule_v1:0d334008fea61bb626110dc1db32b6d0', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","deathtouch":true,"effect":"creature","flash":true,"keywords":["flash","deathtouch"],"xmage_ability_classes":["DeathtouchAbility","FlashAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AmbushViper translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('ashcoat bear', 'Ashcoat Bear', '4a2c565e9fda686748cd261b1298b784', 'battle_rule_v1:c8861f554480ae68baa034a71de2fcae', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"keywords":["flash"],"xmage_ability_classes":["FlashAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AshcoatBear translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('aven reedstalker', 'Aven Reedstalker', '3baebb06100722ec034bcfe15b534fb7', 'battle_rule_v1:41fb4ab488cdbfa783ec06bca9c79259', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"flying":true,"keywords":["flash","flying"],"xmage_ability_classes":["FlashAbility","FlyingAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AvenReedstalker translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('benalish knight', 'Benalish Knight', 'fcb744ee0a138e1bb29c33212f14398c', 'battle_rule_v1:e69be624f5717c9c450521ca938fde94', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","first_strike":true,"flash":true,"keywords":["flash","first_strike"],"xmage_ability_classes":["FirstStrikeAbility","FlashAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BenalishKnight translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('bounding wolf', 'Bounding Wolf', 'c6a597480f571cbfab0ea87ebc019b85', 'battle_rule_v1:015f4c1e88bfb228ee80d796a1aef0d1', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"keywords":["flash","reach"],"reach":true,"xmage_ability_classes":["FlashAbility","ReachAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BoundingWolf translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('cloaked siren', 'Cloaked Siren', 'da6fdbbff5d93feaa47849886ae61ab3', 'battle_rule_v1:41fb4ab488cdbfa783ec06bca9c79259', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"flying":true,"keywords":["flash","flying"],"xmage_ability_classes":["FlashAbility","FlyingAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CloakedSiren translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('crystacean', 'Crystacean', '4a2c565e9fda686748cd261b1298b784', 'battle_rule_v1:c8861f554480ae68baa034a71de2fcae', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"keywords":["flash"],"xmage_ability_classes":["FlashAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Crystacean translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('darksteel sentinel', 'Darksteel Sentinel', '8ced2ff7a7a3af95d0f8198bd4dc3d2b', 'battle_rule_v1:69cf1a8a74e0b40c022ba0cefbac4f29', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"indestructible":true,"keywords":["flash","vigilance","indestructible"],"vigilance":true,"xmage_ability_classes":["FlashAbility","IndestructibleAbility","VigilanceAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DarksteelSentinel translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('dawn''s light archer', 'Dawn''s Light Archer', 'c6a597480f571cbfab0ea87ebc019b85', 'battle_rule_v1:015f4c1e88bfb228ee80d796a1aef0d1', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"keywords":["flash","reach"],"reach":true,"xmage_ability_classes":["FlashAbility","ReachAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DawnsLightArcher translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('faerie invaders', 'Faerie Invaders', 'da6fdbbff5d93feaa47849886ae61ab3', 'battle_rule_v1:41fb4ab488cdbfa783ec06bca9c79259', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"flying":true,"keywords":["flash","flying"],"xmage_ability_classes":["FlashAbility","FlyingAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class FaerieInvaders translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('fire nation ambushers', 'Fire Nation Ambushers', '4a2c565e9fda686748cd261b1298b784', 'battle_rule_v1:c8861f554480ae68baa034a71de2fcae', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"keywords":["flash"],"xmage_ability_classes":["FlashAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class FireNationAmbushers translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('galewind moose', 'Galewind Moose', '46fdf1268a89e54af4894249c88fad6c', 'battle_rule_v1:3b9008f96c5d746ad6e1f5e17dd87e20', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"keywords":["flash","reach","trample","vigilance"],"reach":true,"trample":true,"vigilance":true,"xmage_ability_classes":["FlashAbility","ReachAbility","TrampleAbility","VigilanceAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GalewindMoose translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('havenwood wurm', 'Havenwood Wurm', '0401904a9ced72875eddd7de1e5a55f4', 'battle_rule_v1:ef412605d53621e6df6854b57f9b352c', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"keywords":["flash","trample"],"trample":true,"xmage_ability_classes":["FlashAbility","TrampleAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HavenwoodWurm translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('hired blade', 'Hired Blade', '4a2c565e9fda686748cd261b1298b784', 'battle_rule_v1:c8861f554480ae68baa034a71de2fcae', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"keywords":["flash"],"xmage_ability_classes":["FlashAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HiredBlade translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('hussar patrol', 'Hussar Patrol', 'f9e4e3bae652f9e091908dc888e27dbe', 'battle_rule_v1:0e7ff9ef8e5837f51587ddb7ba59851c', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"keywords":["flash","vigilance"],"vigilance":true,"xmage_ability_classes":["FlashAbility","VigilanceAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HussarPatrol translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('king cheetah', 'King Cheetah', 'bf2c44e6fc09515648b91b1bb4ec3f5f', 'battle_rule_v1:c8861f554480ae68baa034a71de2fcae', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"keywords":["flash"],"xmage_ability_classes":["FlashAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class KingCheetah translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('living tempest', 'Living Tempest', '3baebb06100722ec034bcfe15b534fb7', 'battle_rule_v1:41fb4ab488cdbfa783ec06bca9c79259', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"flying":true,"keywords":["flash","flying"],"xmage_ability_classes":["FlashAbility","FlyingAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class LivingTempest translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('merfolk of the depths', 'Merfolk of the Depths', '4a2c565e9fda686748cd261b1298b784', 'battle_rule_v1:c8861f554480ae68baa034a71de2fcae', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"keywords":["flash"],"xmage_ability_classes":["FlashAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MerfolkOfTheDepths translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('nephalia seakite', 'Nephalia Seakite', 'da6fdbbff5d93feaa47849886ae61ab3', 'battle_rule_v1:41fb4ab488cdbfa783ec06bca9c79259', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"flying":true,"keywords":["flash","flying"],"xmage_ability_classes":["FlashAbility","FlyingAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class NephaliaSeakite translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('plumeveil', 'Plumeveil', '1635dbfc5c0c438f8c4162633c303ed3', 'battle_rule_v1:0d9e9efd643d383269e6284f7db3a9af', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","defender":true,"effect":"creature","flash":true,"flying":true,"keywords":["flash","flying","defender"],"xmage_ability_classes":["DefenderAbility","FlashAbility","FlyingAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Plumeveil translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('pouncing cheetah', 'Pouncing Cheetah', 'bf2c44e6fc09515648b91b1bb4ec3f5f', 'battle_rule_v1:c8861f554480ae68baa034a71de2fcae', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"keywords":["flash"],"xmage_ability_classes":["FlashAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PouncingCheetah translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('raging kavu', 'Raging Kavu', 'ef26d540d93145fee85f76dbeb57fff9', 'battle_rule_v1:1d62ae53017137f3b6a850b6cd6a2606', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"haste":true,"keywords":["flash","haste"],"xmage_ability_classes":["FlashAbility","HasteAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class RagingKavu translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('riptide turtle', 'Riptide Turtle', '08e19ac1e964423ace0df0845826d3a2', 'battle_rule_v1:8a884a5f51973344420a302d0455f390', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","defender":true,"effect":"creature","flash":true,"keywords":["flash","defender"],"xmage_ability_classes":["DefenderAbility","FlashAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class RiptideTurtle translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sentinels of glen elendra', 'Sentinels of Glen Elendra', '3baebb06100722ec034bcfe15b534fb7', 'battle_rule_v1:41fb4ab488cdbfa783ec06bca9c79259', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"flying":true,"keywords":["flash","flying"],"xmage_ability_classes":["FlashAbility","FlyingAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SentinelsOfGlenElendra translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('skyline predator', 'Skyline Predator', 'da6fdbbff5d93feaa47849886ae61ab3', 'battle_rule_v1:41fb4ab488cdbfa783ec06bca9c79259', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"flying":true,"keywords":["flash","flying"],"xmage_ability_classes":["FlashAbility","FlyingAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SkylinePredator translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('spire monitor', 'Spire Monitor', 'da6fdbbff5d93feaa47849886ae61ab3', 'battle_rule_v1:41fb4ab488cdbfa783ec06bca9c79259', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"flying":true,"keywords":["flash","flying"],"xmage_ability_classes":["FlashAbility","FlyingAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SpireMonitor translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('stormrider spirit', 'Stormrider Spirit', '3baebb06100722ec034bcfe15b534fb7', 'battle_rule_v1:41fb4ab488cdbfa783ec06bca9c79259', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"flying":true,"keywords":["flash","flying"],"xmage_ability_classes":["FlashAbility","FlyingAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class StormriderSpirit translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('swift spinner', 'Swift Spinner', '5b68bdd096c620fd99f2fa2d5b655469', 'battle_rule_v1:015f4c1e88bfb228ee80d796a1aef0d1', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"keywords":["flash","reach"],"reach":true,"xmage_ability_classes":["FlashAbility","ReachAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SwiftSpinner translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('tangle spider', 'Tangle Spider', '5b68bdd096c620fd99f2fa2d5b655469', 'battle_rule_v1:015f4c1e88bfb228ee80d796a1aef0d1', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"keywords":["flash","reach"],"reach":true,"xmage_ability_classes":["FlashAbility","ReachAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TangleSpider translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('vexing gull', 'Vexing Gull', '3baebb06100722ec034bcfe15b534fb7', 'battle_rule_v1:41fb4ab488cdbfa783ec06bca9c79259', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"flying":true,"keywords":["flash","flying"],"xmage_ability_classes":["FlashAbility","FlyingAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class VexingGull translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('wind strider', 'Wind Strider', 'da6fdbbff5d93feaa47849886ae61ab3', 'battle_rule_v1:41fb4ab488cdbfa783ec06bca9c79259', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"flying":true,"keywords":["flash","flying"],"xmage_ability_classes":["FlashAbility","FlyingAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class WindStrider translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('winged coatl', 'Winged Coatl', 'c76841e62af8f16f47552bcce367e463', 'battle_rule_v1:c269497a1b68cc205b2db22742d203ba', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","deathtouch":true,"effect":"creature","flash":true,"flying":true,"keywords":["flash","flying","deathtouch"],"xmage_ability_classes":["DeathtouchAbility","FlashAbility","FlyingAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class WingedCoatl translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('zealous guardian', 'Zealous Guardian', 'bf2c44e6fc09515648b91b1bb4ec3f5f', 'battle_rule_v1:c8861f554480ae68baa034a71de2fcae', '{"_keywords_are_self":true,"battle_model_scope":"xmage_static_self_combat_keyword_creature_v1","effect":"creature","flash":true,"keywords":["flash"],"xmage_ability_classes":["FlashAbility"]}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ZealousGuardian translated into ManaLoom runtime scope xmage_static_self_combat_keyword_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
matched_cards AS (
  SELECT
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    c.id AS card_id,
    c.name AS db_card_name
  FROM proposed p
  LEFT JOIN public.cards c
    ON (
         lower(c.name) = p.normalized_name
         OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
       )
   AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
),
target_cards AS (
  SELECT
    normalized_name,
    card_name,
    oracle_hash,
    count(card_id) AS target_card_rows,
    min(card_id::text)::uuid AS canonical_card_id,
    min(db_card_name) AS canonical_card_name
  FROM matched_cards
  GROUP BY normalized_name, card_name, oracle_hash
),
rule_rows AS (
  SELECT p.normalized_name, count(r.*) AS existing_rule_rows
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
  GROUP BY p.normalized_name
),
expected_rows AS (
  SELECT p.normalized_name, count(r.*) AS expected_rule_rows_before
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key = p.logical_rule_key
  GROUP BY p.normalized_name
),
shadow_rows AS (
  SELECT p.normalized_name, count(r.*) AS would_deprecate_shadow_rows
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key <> p.logical_rule_key
   AND r.review_status NOT IN ('deprecated', 'rejected')
   AND r.execution_status <> 'disabled'
  GROUP BY p.normalized_name
)
SELECT
  p.card_name,
  p.normalized_name,
  p.oracle_hash,
  p.logical_rule_key,
  p.shadow_handling,
  tc.target_card_rows,
  tc.canonical_card_id,
  rr.existing_rule_rows,
  er.expected_rule_rows_before,
  sr.would_deprecate_shadow_rows
FROM proposed p
JOIN target_cards tc USING (normalized_name, card_name, oracle_hash)
JOIN rule_rows rr USING (normalized_name)
JOIN expected_rows er USING (normalized_name)
JOIN shadow_rows sr USING (normalized_name)
ORDER BY p.card_name;
