WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('beskir shieldmate', 'Beskir Shieldmate', '89fb793e3d183e1a3d352d759288d9d5', 'battle_rule_v1:7a5c752ef27017f2e75ce0f55ed0f24a', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_token_colors":["W"],"dies_token_count":1,"dies_token_name":"Human Warrior Token","dies_token_power":1,"dies_token_subtype":"Human Warrior","dies_token_toughness":1,"dies_trigger_effect":"token_maker","effect":"creature","token_description":"1/1 white Human Warrior creature token","trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"HumanWarriorToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BeskirShieldmate translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('brindle shoat', 'Brindle Shoat', '62901a84db69b8edda50cd7f1a733533', 'battle_rule_v1:04e8494c0691cf7dd230789adf7bc286', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_token_colors":["G"],"dies_token_count":1,"dies_token_name":"Boar Token","dies_token_power":3,"dies_token_subtype":"Boar","dies_token_toughness":3,"dies_trigger_effect":"token_maker","effect":"creature","token_description":"3/3 green Boar creature token","trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"BoarToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BrindleShoat translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('brood weaver', 'Brood Weaver', '51e227a65f407ba62455d94b3a0695cc', 'battle_rule_v1:2dcd84e152f45572a05f9f8d43a2aae0', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_token_colors":["G"],"dies_token_count":1,"dies_token_keywords":["reach"],"dies_token_name":"Spider Token","dies_token_power":1,"dies_token_subtype":"Spider","dies_token_toughness":2,"dies_trigger_effect":"token_maker","effect":"creature","keywords":["reach"],"reach":true,"token_description":"1/2 green Spider creature token with reach","trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"SpiderToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BroodWeaver translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('conscripted infantry', 'Conscripted Infantry', '25e183b1dacc1be7f9da2f31818aa028', 'battle_rule_v1:2cce2e20c521add80e6cad078072c035', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_artifact_tokens":true,"dies_token_count":1,"dies_token_name":"Soldier Token","dies_token_power":1,"dies_token_subtype":"Soldier","dies_token_toughness":1,"dies_trigger_effect":"token_maker","effect":"creature","token_description":"1/1 colorless Soldier artifact creature token","trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"SoldierArtifactToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ConscriptedInfantry translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('deathbloom thallid', 'Deathbloom Thallid', '6e0b562f99e80aa42fc539f44f400447', 'battle_rule_v1:508465079bb84a8a1e6be6b72cabd67b', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_token_colors":["G"],"dies_token_count":1,"dies_token_name":"Saproling Token","dies_token_power":1,"dies_token_subtype":"Saproling","dies_token_toughness":1,"dies_trigger_effect":"token_maker","effect":"creature","token_description":"1/1 green Saproling creature token","trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"SaprolingToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DeathbloomThallid translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('discordant piper', 'Discordant Piper', 'dd733152b1ce5fa027f45c97120115b1', 'battle_rule_v1:ad0e12aa20654aba517d10e9f36ba5b6', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_token_colors":["W"],"dies_token_count":1,"dies_token_name":"Goat Token","dies_token_power":0,"dies_token_subtype":"Goat","dies_token_toughness":1,"dies_trigger_effect":"token_maker","effect":"creature","token_description":"0/1 white Goat creature token","trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"GoatToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DiscordantPiper translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('doomed dissenter', 'Doomed Dissenter', '2ab448518057ad9b18d4e2a6a0341143', 'battle_rule_v1:edebf7fc3cc9646f30387c314dcde94e', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_token_colors":["B"],"dies_token_count":1,"dies_token_name":"Zombie Token","dies_token_power":2,"dies_token_subtype":"Zombie","dies_token_toughness":2,"dies_trigger_effect":"token_maker","effect":"creature","token_description":"2/2 black Zombie creature token","trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"ZombieToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DoomedDissenter translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('doomed traveler', 'Doomed Traveler', 'de756341b6369b2f370f2cede1c9b5ed', 'battle_rule_v1:ac86a2a29ae7c0cfdcf73ec9a713d3cb', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_token_colors":["W"],"dies_token_count":1,"dies_token_flying":true,"dies_token_keywords":["flying"],"dies_token_name":"Spirit Token","dies_token_power":1,"dies_token_subtype":"Spirit","dies_token_toughness":1,"dies_trigger_effect":"token_maker","effect":"creature","token_description":"1/1 white Spirit creature token with flying","trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"SpiritWhiteToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DoomedTraveler translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('dwarven castle guard', 'Dwarven Castle Guard', '1d7cc43aa46a86937f63de92f8833319', 'battle_rule_v1:08b5f23d0ba3ececd41afd1c0b27e545', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_token_count":1,"dies_token_name":"Hero Token","dies_token_power":1,"dies_token_subtype":"Hero","dies_token_toughness":1,"dies_trigger_effect":"token_maker","effect":"creature","token_description":"1/1 colorless Hero creature token","trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"HeroToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DwarvenCastleGuard translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('elgaud inquisitor', 'Elgaud Inquisitor', '354b612167a8079d089953876e641763', 'battle_rule_v1:b27ac08efcdb59f9e5f79a2018068ab4', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_token_colors":["W"],"dies_token_count":1,"dies_token_flying":true,"dies_token_keywords":["flying"],"dies_token_name":"Spirit Token","dies_token_power":1,"dies_token_subtype":"Spirit","dies_token_toughness":1,"dies_trigger_effect":"token_maker","effect":"creature","keywords":["lifelink"],"lifelink":true,"token_description":"1/1 white Spirit creature token with flying","trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"SpiritWhiteToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ElgaudInquisitor translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('filigree crawler', 'Filigree Crawler', 'd59c39b39c79d4b53dabc2ab154fa89f', 'battle_rule_v1:a096cd3aed03009497106c2db9f209bc', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_artifact_tokens":true,"dies_token_count":1,"dies_token_flying":true,"dies_token_keywords":["flying"],"dies_token_name":"Thopter Token","dies_token_power":1,"dies_token_subtype":"Thopter","dies_token_toughness":1,"dies_trigger_effect":"token_maker","effect":"creature","token_description":"1/1 colorless Thopter artifact creature token with flying","trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"ThopterColorlessToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class FiligreeCrawler translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('garrison cat', 'Garrison Cat', '29f1b4320917ca21c9997126f08eade8', 'battle_rule_v1:4eb7dcd745a142cb45c4077db59687d3', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_token_colors":["W"],"dies_token_count":1,"dies_token_name":"Human Soldier Token","dies_token_power":1,"dies_token_subtype":"Human Soldier","dies_token_toughness":1,"dies_trigger_effect":"token_maker","effect":"creature","token_description":"1/1 white Human Soldier creature token","trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"HumanSoldierToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GarrisonCat translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('hunted witness', 'Hunted Witness', 'e255a06c0665c973118fe5b75e6d7502', 'battle_rule_v1:c01cfdd1141dc6552ff0253d15340f04', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_token_colors":["W"],"dies_token_count":1,"dies_token_keywords":["lifelink"],"dies_token_name":"Soldier Token","dies_token_power":1,"dies_token_subtype":"Soldier","dies_token_toughness":1,"dies_trigger_effect":"token_maker","effect":"creature","token_description":"1/1 white Soldier creature token with lifelink","trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"SoldierLifelinkToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HuntedWitness translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('infestation sage', 'Infestation Sage', '76d8a8b36d4d294e0bcf4fbf766cefb3', 'battle_rule_v1:063aea50108acb3ff8ff2d1642fa9de8', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_token_colors":["B","G"],"dies_token_count":1,"dies_token_flying":true,"dies_token_keywords":["flying"],"dies_token_name":"Insect Token","dies_token_power":1,"dies_token_subtype":"Insect","dies_token_toughness":1,"dies_trigger_effect":"token_maker","effect":"creature","token_description":"1/1 black and green Insect creature token with flying","trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"InsectBlackGreenFlyingToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class InfestationSage translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('maalfeld twins', 'Maalfeld Twins', 'b93594a92bd90f13d7b557059a8d83b7', 'battle_rule_v1:d3fde7fc16ae1aecd6c8b1c81a1c72d8', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_token_colors":["B"],"dies_token_count":2,"dies_token_name":"Zombie Token","dies_token_power":2,"dies_token_subtype":"Zombie","dies_token_toughness":2,"dies_trigger_effect":"token_maker","effect":"creature","token_description":"2/2 black Zombie creature token","trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"ZombieToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MaalfeldTwins translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('martyr of dusk', 'Martyr of Dusk', '22d93e92247d062d2373f43624d519f2', 'battle_rule_v1:81a506711ed7bd57ddb4ab35d7f4a66c', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_token_colors":["W"],"dies_token_count":1,"dies_token_keywords":["lifelink"],"dies_token_name":"Vampire Token","dies_token_power":1,"dies_token_subtype":"Vampire","dies_token_toughness":1,"dies_trigger_effect":"token_maker","effect":"creature","token_description":"1/1 white Vampire creature token with lifelink","trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"IxalanVampireToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MartyrOfDusk translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('myr sire', 'Myr Sire', 'b642f47076f215b5303fe8c37969d9c7', 'battle_rule_v1:25584d7c86ac16ca719c188f2d571b31', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_artifact_tokens":true,"dies_token_count":1,"dies_token_name":"Phyrexian Myr Token","dies_token_power":1,"dies_token_subtype":"Phyrexian Myr","dies_token_toughness":1,"dies_trigger_effect":"token_maker","effect":"creature","token_description":"1/1 colorless Phyrexian Myr artifact creature token","trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"PhyrexianMyrToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MyrSire translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('penumbra bobcat', 'Penumbra Bobcat', 'bad2cbbacc9a7b4b1d2f00fef9d6e08e', 'battle_rule_v1:c8773318eae9506eddbd72a0e453d6e4', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_token_colors":["B"],"dies_token_count":1,"dies_token_name":"Cat Token","dies_token_power":2,"dies_token_subtype":"Cat","dies_token_toughness":1,"dies_trigger_effect":"token_maker","effect":"creature","token_description":"2/1 black Cat creature token","trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"PenumbraBobcatToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PenumbraBobcat translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('penumbra kavu', 'Penumbra Kavu', '914070971bf87a5967ce2081f0e373df', 'battle_rule_v1:7f00bc2b1fc8cd4077131be5988136ed', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_token_colors":["B"],"dies_token_count":1,"dies_token_name":"Kavu Token","dies_token_power":3,"dies_token_subtype":"Kavu","dies_token_toughness":3,"dies_trigger_effect":"token_maker","effect":"creature","token_description":"3/3 black Kavu creature token","trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"PenumbraKavuToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PenumbraKavu translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('penumbra spider', 'Penumbra Spider', 'aafdabd85a3aa45ea3fdce5bae24b377', 'battle_rule_v1:047d03e7a2c6714e3247741e81a41ff1', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_token_colors":["B"],"dies_token_count":1,"dies_token_keywords":["reach"],"dies_token_name":"Spider Token","dies_token_power":2,"dies_token_subtype":"Spider","dies_token_toughness":4,"dies_trigger_effect":"token_maker","effect":"creature","keywords":["reach"],"reach":true,"token_description":"2/4 black Spider creature token with reach","trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"PenumbraSpiderToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PenumbraSpider translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('penumbra wurm', 'Penumbra Wurm', '7393d00a98736c334e374426d1f3a5d3', 'battle_rule_v1:c94157fd5bd2044ab43ba5e594a03bd5', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_token_colors":["B"],"dies_token_count":1,"dies_token_keywords":["trample"],"dies_token_name":"Wurm Token","dies_token_power":6,"dies_token_subtype":"Wurm","dies_token_toughness":6,"dies_trigger_effect":"token_maker","effect":"creature","keywords":["trample"],"token_description":"6/6 black Wurm creature token with trample","trample":true,"trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"PenumbraWurmToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PenumbraWurm translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('pretending poxbearers', 'Pretending Poxbearers', '83f29f4346f7420740944ed35b1e463c', 'battle_rule_v1:dc87a61782aeec3e2b8dd1c0cf62ef59', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_token_colors":["W"],"dies_token_count":1,"dies_token_name":"Ally Token","dies_token_power":1,"dies_token_subtype":"Ally","dies_token_toughness":1,"dies_trigger_effect":"token_maker","effect":"creature","token_description":"1/1 white Ally creature token","trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"AllyToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PretendingPoxbearers translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('tukatongue thallid', 'Tukatongue Thallid', '6e0b562f99e80aa42fc539f44f400447', 'battle_rule_v1:508465079bb84a8a1e6be6b72cabd67b', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_token_colors":["G"],"dies_token_count":1,"dies_token_name":"Saproling Token","dies_token_power":1,"dies_token_subtype":"Saproling","dies_token_toughness":1,"dies_trigger_effect":"token_maker","effect":"creature","token_description":"1/1 green Saproling creature token","trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"SaprolingToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TukatongueThallid translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('wriggling grub', 'Wriggling Grub', '13d8c9254983dfaf4e6eb2e00dfec731', 'battle_rule_v1:a989e9845f2222d86457d14990e48107', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_create_tokens_v1","dies_token_colors":["B","G"],"dies_token_count":2,"dies_token_name":"Worm Token","dies_token_power":1,"dies_token_subtype":"Worm","dies_token_toughness":1,"dies_trigger_effect":"token_maker","effect":"creature","token_description":"1/1 black and green Worm creature token","trigger":"dies","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"BlackGreenWormToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class WrigglingGrub translated into ManaLoom runtime scope xmage_creature_dies_create_tokens_v1. This row is package-ready only because the source signature is a narrow creature dies triggered fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
matched_cards AS (
  SELECT
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    c.id AS card_id,
    c.name AS db_card_name
  FROM proposed p
  LEFT JOIN public.cards c
    ON (
         lower(c.name) = p.normalized_name
         OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
       )
   AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
),
target_cards AS (
  SELECT
    normalized_name,
    card_name,
    oracle_hash,
    count(card_id) AS target_card_rows,
    min(card_id::text)::uuid AS canonical_card_id,
    min(db_card_name) AS canonical_card_name
  FROM matched_cards
  GROUP BY normalized_name, card_name, oracle_hash
),
rule_rows AS (
  SELECT p.normalized_name, count(r.*) AS existing_rule_rows
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
  GROUP BY p.normalized_name
),
expected_rows AS (
  SELECT p.normalized_name, count(r.*) AS expected_rule_rows_before
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key = p.logical_rule_key
  GROUP BY p.normalized_name
),
shadow_rows AS (
  SELECT p.normalized_name, count(r.*) AS would_deprecate_shadow_rows
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key <> p.logical_rule_key
   AND r.review_status NOT IN ('deprecated', 'rejected')
   AND r.execution_status <> 'disabled'
  GROUP BY p.normalized_name
)
SELECT
  p.card_name,
  p.normalized_name,
  p.oracle_hash,
  p.logical_rule_key,
  p.shadow_handling,
  tc.target_card_rows,
  tc.canonical_card_id,
  rr.existing_rule_rows,
  er.expected_rule_rows_before,
  sr.would_deprecate_shadow_rows
FROM proposed p
JOIN target_cards tc USING (normalized_name, card_name, oracle_hash)
JOIN rule_rows rr USING (normalized_name)
JOIN expected_rows er USING (normalized_name)
JOIN shadow_rows sr USING (normalized_name)
ORDER BY p.card_name;
