WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('defile', 'Defile', 'ca60f5e3d71a02fd888b0f2ebdce61d9', 'battle_rule_v1:1100b16aa567a4166c89925fa02116ed', '{"battle_model_scope":"xmage_dynamic_count_boost_target_creature_until_eot_spell_v1","battlefield_count_card_types":["land"],"battlefield_count_scope":"controller_battlefield","battlefield_count_subtypes":["swamp"],"duration":"until_end_of_turn","effect":"stat_modifier_until_eot","instant":true,"power_base_delta":0,"power_delta_per_graveyard_count":-1,"sorcery":false,"stat_modifier_amount_source":"battlefield_permanent_count","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_base_delta":0,"toughness_delta_per_graveyard_count":-1,"xmage_effect_class":"BoostTargetEffect"}'::jsonb, '{"category":"support","effect":"stat_modifier_until_eot","subtype":"temporary_pump","target":"creature","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Defile translated into ManaLoom runtime scope xmage_dynamic_count_boost_target_creature_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('desert''s due', 'Desert''s Due', '49adb7c8e3d3bb853d9326f0af9aaeb9', 'battle_rule_v1:c47f8cfa7cc6a286de6d8e56a0b350eb', '{"battle_model_scope":"xmage_dynamic_count_boost_target_creature_until_eot_spell_v1","battlefield_count_card_types":["land"],"battlefield_count_scope":"controller_battlefield","battlefield_count_subtypes":["desert"],"duration":"until_end_of_turn","effect":"stat_modifier_until_eot","instant":true,"power_base_delta":-2,"power_delta_per_graveyard_count":-1,"sorcery":false,"stat_modifier_amount_source":"battlefield_permanent_count","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_base_delta":-2,"toughness_delta_per_graveyard_count":-1,"xmage_effect_class":"BoostTargetEffect"}'::jsonb, '{"category":"support","effect":"stat_modifier_until_eot","subtype":"temporary_pump","target":"creature","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DesertsDue translated into ManaLoom runtime scope xmage_dynamic_count_boost_target_creature_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('drag down', 'Drag Down', 'a3975b258df864690a219dcc1f4f95a7', 'battle_rule_v1:210c9f43c60a296a79af941511abf2ea', '{"battle_model_scope":"xmage_dynamic_count_boost_target_creature_until_eot_spell_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","instant":true,"power_base_delta":0,"power_delta_per_graveyard_count":-1,"sorcery":false,"stat_modifier_amount_source":"domain_basic_land_types","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_base_delta":0,"toughness_delta_per_graveyard_count":-1,"xmage_effect_class":"BoostTargetEffect"}'::jsonb, '{"category":"support","effect":"stat_modifier_until_eot","subtype":"temporary_pump","target":"creature","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DragDown translated into ManaLoom runtime scope xmage_dynamic_count_boost_target_creature_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('feeding frenzy', 'Feeding Frenzy', 'ea2ff3ba1587cba08d9262aaa88fcd32', 'battle_rule_v1:00c7f63a7cceb61b5f8561db237f81ec', '{"battle_model_scope":"xmage_dynamic_count_boost_target_creature_until_eot_spell_v1","battlefield_count_scope":"all_battlefields","battlefield_count_subtypes":["zombie"],"duration":"until_end_of_turn","effect":"stat_modifier_until_eot","instant":true,"power_base_delta":0,"power_delta_per_graveyard_count":-1,"sorcery":false,"stat_modifier_amount_source":"battlefield_permanent_count","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_base_delta":0,"toughness_delta_per_graveyard_count":-1,"xmage_effect_class":"BoostTargetEffect"}'::jsonb, '{"category":"support","effect":"stat_modifier_until_eot","subtype":"temporary_pump","target":"creature","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class FeedingFrenzy translated into ManaLoom runtime scope xmage_dynamic_count_boost_target_creature_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('gaea''s might', 'Gaea''s Might', 'be2ac80e1e9a2af2e3d54ad8ceb686c1', 'battle_rule_v1:f6a6dd8a95547608ac7f79c6465088c0', '{"battle_model_scope":"xmage_dynamic_count_boost_target_creature_until_eot_spell_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","instant":true,"power_base_delta":0,"power_delta_per_graveyard_count":1,"sorcery":false,"stat_modifier_amount_source":"domain_basic_land_types","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_base_delta":0,"toughness_delta_per_graveyard_count":1,"xmage_effect_class":"BoostTargetEffect"}'::jsonb, '{"category":"support","effect":"stat_modifier_until_eot","subtype":"temporary_pump","target":"creature","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GaeasMight translated into ManaLoom runtime scope xmage_dynamic_count_boost_target_creature_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('hunger of the nim', 'Hunger of the Nim', '008a2e6c710c73f5a0972b451b66f7a7', 'battle_rule_v1:9044a82a7faa7ba39758bbd225595fcd', '{"battle_model_scope":"xmage_dynamic_count_boost_target_creature_until_eot_spell_v1","battlefield_count_card_types":["artifact"],"battlefield_count_scope":"controller_battlefield","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","instant":false,"power_base_delta":0,"power_delta_per_graveyard_count":1,"sorcery":true,"stat_modifier_amount_source":"battlefield_permanent_count","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_base_delta":0,"toughness_delta_per_graveyard_count":0,"xmage_effect_class":"BoostTargetEffect"}'::jsonb, '{"category":"support","effect":"stat_modifier_until_eot","subtype":"temporary_pump","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HungerOfTheNim translated into ManaLoom runtime scope xmage_dynamic_count_boost_target_creature_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('inner calm, outer strength', 'Inner Calm, Outer Strength', '18d68ccf2f96f30acec5bb7f5093aaf3', 'battle_rule_v1:9f6efe319b4033f156aad274dd198d88', '{"battle_model_scope":"xmage_dynamic_count_boost_target_creature_until_eot_spell_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","instant":true,"power_base_delta":0,"power_delta_per_graveyard_count":1,"sorcery":false,"stat_modifier_amount_source":"controller_hand_count","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_base_delta":0,"toughness_delta_per_graveyard_count":1,"xmage_effect_class":"BoostTargetEffect"}'::jsonb, '{"category":"support","effect":"stat_modifier_until_eot","subtype":"temporary_pump","target":"creature","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class InnerCalmOuterStrength translated into ManaLoom runtime scope xmage_dynamic_count_boost_target_creature_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('irradiate', 'Irradiate', '3d4ec2868f66f9af1e0d63902702f7f2', 'battle_rule_v1:b73631198cb3e8cbfdce3b5800531f1a', '{"battle_model_scope":"xmage_dynamic_count_boost_target_creature_until_eot_spell_v1","battlefield_count_card_types":["artifact"],"battlefield_count_scope":"controller_battlefield","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","instant":true,"power_base_delta":0,"power_delta_per_graveyard_count":-1,"sorcery":false,"stat_modifier_amount_source":"battlefield_permanent_count","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_base_delta":0,"toughness_delta_per_graveyard_count":-1,"xmage_effect_class":"BoostTargetEffect"}'::jsonb, '{"category":"support","effect":"stat_modifier_until_eot","subtype":"temporary_pump","target":"creature","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Irradiate translated into ManaLoom runtime scope xmage_dynamic_count_boost_target_creature_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('might of alara', 'Might of Alara', 'be2ac80e1e9a2af2e3d54ad8ceb686c1', 'battle_rule_v1:f6a6dd8a95547608ac7f79c6465088c0', '{"battle_model_scope":"xmage_dynamic_count_boost_target_creature_until_eot_spell_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","instant":true,"power_base_delta":0,"power_delta_per_graveyard_count":1,"sorcery":false,"stat_modifier_amount_source":"domain_basic_land_types","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_base_delta":0,"toughness_delta_per_graveyard_count":1,"xmage_effect_class":"BoostTargetEffect"}'::jsonb, '{"category":"support","effect":"stat_modifier_until_eot","subtype":"temporary_pump","target":"creature","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MightOfAlara translated into ManaLoom runtime scope xmage_dynamic_count_boost_target_creature_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('might of the masses', 'Might of the Masses', '265c407a7e7418e03ac6df0c6f7673dc', 'battle_rule_v1:6bd781adebd1fd040b548b5ca68d66a3', '{"battle_model_scope":"xmage_dynamic_count_boost_target_creature_until_eot_spell_v1","battlefield_count_card_types":["creature"],"battlefield_count_scope":"controller_battlefield","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","instant":true,"power_base_delta":0,"power_delta_per_graveyard_count":1,"sorcery":false,"stat_modifier_amount_source":"battlefield_permanent_count","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_base_delta":0,"toughness_delta_per_graveyard_count":1,"xmage_effect_class":"BoostTargetEffect"}'::jsonb, '{"category":"support","effect":"stat_modifier_until_eot","subtype":"temporary_pump","target":"creature","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MightOfTheMasses translated into ManaLoom runtime scope xmage_dynamic_count_boost_target_creature_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('nightmarish end', 'Nightmarish End', '436d4fb570ffb05e0cdfbee2118b0981', 'battle_rule_v1:68c94b97da910dce93cc269180b7f0fd', '{"battle_model_scope":"xmage_dynamic_count_boost_target_creature_until_eot_spell_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","instant":true,"power_base_delta":0,"power_delta_per_graveyard_count":-1,"sorcery":false,"stat_modifier_amount_source":"controller_hand_count","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_base_delta":0,"toughness_delta_per_graveyard_count":-1,"xmage_effect_class":"BoostTargetEffect"}'::jsonb, '{"category":"support","effect":"stat_modifier_until_eot","subtype":"temporary_pump","target":"creature","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class NightmarishEnd translated into ManaLoom runtime scope xmage_dynamic_count_boost_target_creature_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('strength of cedars', 'Strength of Cedars', '6b950817f1f7afbec1f02f7e369ed926', 'battle_rule_v1:3ca636350943972a180f4f2535a9c384', '{"battle_model_scope":"xmage_dynamic_count_boost_target_creature_until_eot_spell_v1","battlefield_count_card_types":["land"],"battlefield_count_scope":"controller_battlefield","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","instant":true,"power_base_delta":0,"power_delta_per_graveyard_count":1,"sorcery":false,"stat_modifier_amount_source":"battlefield_permanent_count","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_base_delta":0,"toughness_delta_per_graveyard_count":1,"xmage_effect_class":"BoostTargetEffect"}'::jsonb, '{"category":"support","effect":"stat_modifier_until_eot","subtype":"temporary_pump","target":"creature","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class StrengthOfCedars translated into ManaLoom runtime scope xmage_dynamic_count_boost_target_creature_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('warped physique', 'Warped Physique', 'e59c03451b6154627e2115c632e45d87', 'battle_rule_v1:d1e30e5fc99f7122f4debeb26047597a', '{"battle_model_scope":"xmage_dynamic_count_boost_target_creature_until_eot_spell_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","instant":true,"power_base_delta":0,"power_delta_per_graveyard_count":1,"sorcery":false,"stat_modifier_amount_source":"controller_hand_count","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_base_delta":0,"toughness_delta_per_graveyard_count":-1,"xmage_effect_class":"BoostTargetEffect"}'::jsonb, '{"category":"support","effect":"stat_modifier_until_eot","subtype":"temporary_pump","target":"creature","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class WarpedPhysique translated into ManaLoom runtime scope xmage_dynamic_count_boost_target_creature_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('wirewood pride', 'Wirewood Pride', '725d775135c01097c9ed49d586ec9ad0', 'battle_rule_v1:c2abb3e20f0ac836039dbdb9cd080e2c', '{"battle_model_scope":"xmage_dynamic_count_boost_target_creature_until_eot_spell_v1","battlefield_count_scope":"all_battlefields","battlefield_count_subtypes":["elf"],"duration":"until_end_of_turn","effect":"stat_modifier_until_eot","instant":true,"power_base_delta":0,"power_delta_per_graveyard_count":1,"sorcery":false,"stat_modifier_amount_source":"battlefield_permanent_count","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_base_delta":0,"toughness_delta_per_graveyard_count":1,"xmage_effect_class":"BoostTargetEffect"}'::jsonb, '{"category":"support","effect":"stat_modifier_until_eot","subtype":"temporary_pump","target":"creature","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class WirewoodPride translated into ManaLoom runtime scope xmage_dynamic_count_boost_target_creature_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
rule_rows AS (
  SELECT
    r.normalized_name,
    r.logical_rule_key,
    r.oracle_hash,
    r.review_status,
    r.execution_status
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key = p.logical_rule_key
)
SELECT
  p.card_name,
  p.normalized_name,
  p.logical_rule_key,
  count(r.*) FILTER (WHERE r.logical_rule_key = p.logical_rule_key) AS promoted_rule_rows,
  count(r.*) FILTER (WHERE r.review_status = 'verified' AND r.execution_status = 'auto') AS promoted_verified_auto_rows,
  count(r.*) FILTER (WHERE r.oracle_hash = p.oracle_hash) AS promoted_oracle_hash_rows,
  (SELECT count(*) FROM manaloom_deploy_audit.pg445_xmage_dynamic_count_boost_new_server_20260704_2254) AS backup_rows
FROM proposed p
LEFT JOIN rule_rows r
  ON r.normalized_name = p.normalized_name
 AND r.logical_rule_key = p.logical_rule_key
 AND r.oracle_hash = p.oracle_hash
GROUP BY p.card_name, p.normalized_name, p.logical_rule_key, p.oracle_hash
ORDER BY p.card_name;
