BEGIN;

CREATE SCHEMA IF NOT EXISTS manaloom_deploy_audit;

CREATE TABLE IF NOT EXISTS manaloom_deploy_audit.pg527_boost_all_filtered_new_server_20260705_200027 AS
SELECT *
FROM public.card_battle_rules
WHERE normalized_name IN ('army of allah', 'eyeblight massacre', 'festergloom', 'hazardous conditions', 'hold the line', 'holy light', 'morale', 'nocturnal raid', 'rally', 'stench of decay', 'trumpet blast', 'valorous charge')
   OR normalized_name LIKE 'army of allah // %'
   OR normalized_name LIKE 'eyeblight massacre // %'
   OR normalized_name LIKE 'festergloom // %'
   OR normalized_name LIKE 'hazardous conditions // %'
   OR normalized_name LIKE 'hold the line // %'
   OR normalized_name LIKE 'holy light // %'
   OR normalized_name LIKE 'morale // %'
   OR normalized_name LIKE 'nocturnal raid // %'
   OR normalized_name LIKE 'rally // %'
   OR normalized_name LIKE 'stench of decay // %'
   OR normalized_name LIKE 'trumpet blast // %'
   OR normalized_name LIKE 'valorous charge // %';

DO $$
DECLARE
  v_missing jsonb;
BEGIN
  WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('army of allah', 'Army of Allah', '1ef4be52d08f0475feaa7d6d6fe78134', 'battle_rule_v1:38a0877b47351dea781b3e292168ba3f', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"combat_state":"attacking"},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":2,"sorcery":false,"target":"attacking_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"combat_state":"attacking"}},"target_controller":"all","toughness_delta":0,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"attacking_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ArmyOfAllah translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('eyeblight massacre', 'Eyeblight Massacre', 'cbff45a47c8a16ac2aa10e8c93c3195d', 'battle_rule_v1:b230476e11f26739ccb0bc67a312affe', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"exclude_subtypes":["Elf"]},"effect":"global_stat_modifier_until_eot","instant":false,"power_delta":-2,"sorcery":true,"target":"non_elf_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"exclude_subtypes":["Elf"]}},"target_controller":"all","toughness_delta":-2,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"non_elf_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class EyeblightMassacre translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('festergloom', 'Festergloom', '960ea67732e18980852f95373228552e', 'battle_rule_v1:352f141f48f3fcd4ceb24a2b92338d4f', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"exclude_colors":["B"]},"effect":"global_stat_modifier_until_eot","instant":false,"power_delta":-1,"sorcery":true,"target":"non_b_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"exclude_colors":["B"]}},"target_controller":"all","toughness_delta":-1,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"non_b_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Festergloom translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('hazardous conditions', 'Hazardous Conditions', 'eed2ece1875a19627ed69dfd5181fce2', 'battle_rule_v1:0d1b0e2f966c8962b875ddef80c5a71d', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"no_counters":true},"effect":"global_stat_modifier_until_eot","instant":false,"power_delta":-2,"sorcery":true,"target":"creatures_with_no_counters","target_constraints":{"card_types":["creature"],"creature_filter":{"no_counters":true}},"target_controller":"all","toughness_delta":-2,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"creatures_with_no_counters"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HazardousConditions translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('hold the line', 'Hold the Line', '770d2d7e18416184090fb01d854f62ec', 'battle_rule_v1:65f9a4c354c56642a5c813fab2ecbd7b', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"combat_state":"blocking"},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":7,"sorcery":false,"target":"blocking_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"combat_state":"blocking"}},"target_controller":"all","toughness_delta":7,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"blocking_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HoldTheLine translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('holy light', 'Holy Light', 'eb426784c3f6417501c84e5b540533f5', 'battle_rule_v1:0310fa36bc90e4f8d3a50f3dd18733dc', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"exclude_colors":["W"]},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":-1,"sorcery":false,"target":"non_w_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"exclude_colors":["W"]}},"target_controller":"all","toughness_delta":-1,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"non_w_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HolyLight translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('morale', 'Morale', '1830ec642002de376ed69e4f6766b937', 'battle_rule_v1:b47fdc764d84003fc74f6177d0f0df1e', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"combat_state":"attacking"},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":1,"sorcery":false,"target":"attacking_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"combat_state":"attacking"}},"target_controller":"all","toughness_delta":1,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"attacking_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Morale translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('nocturnal raid', 'Nocturnal Raid', '4136576b251ae9ea8a1a3c90a0c164c4', 'battle_rule_v1:6e22f29986bf8915b94b6e3abe825b71', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"colors":["B"]},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":2,"sorcery":false,"target":"b_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"colors":["B"]}},"target_controller":"all","toughness_delta":0,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"b_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class NocturnalRaid translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('rally', 'Rally', 'f83272e913174713d72858ca9f6917ad', 'battle_rule_v1:b86e3f6a50e8449a806e54ba6a3e7207', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"combat_state":"blocking"},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":1,"sorcery":false,"target":"blocking_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"combat_state":"blocking"}},"target_controller":"all","toughness_delta":1,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"blocking_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Rally translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('stench of decay', 'Stench of Decay', 'a5e5e5bbe487403fa3c1d872563bd777', 'battle_rule_v1:383e3cc52fdccddc76a04ea09a0cc79b', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"exclude_card_types":["artifact"]},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":-1,"sorcery":false,"target":"non_artifact_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"exclude_card_types":["artifact"]}},"target_controller":"all","toughness_delta":-1,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"non_artifact_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class StenchOfDecay translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('trumpet blast', 'Trumpet Blast', '1ef4be52d08f0475feaa7d6d6fe78134', 'battle_rule_v1:38a0877b47351dea781b3e292168ba3f', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"combat_state":"attacking"},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":2,"sorcery":false,"target":"attacking_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"combat_state":"attacking"}},"target_controller":"all","toughness_delta":0,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"attacking_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TrumpetBlast translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('valorous charge', 'Valorous Charge', 'f3a96246a7f3f9092d30f081d7f0fa90', 'battle_rule_v1:6f9f3e1fd5c01d164db507c86d9011fc', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"colors":["W"]},"effect":"global_stat_modifier_until_eot","instant":false,"power_delta":2,"sorcery":true,"target":"w_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"colors":["W"]}},"target_controller":"all","toughness_delta":0,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"w_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ValorousCharge translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
  counts AS (
    SELECT
      p.card_name,
      p.normalized_name,
      p.oracle_hash,
      count(c.id) AS target_card_rows,
      min(c.id::text)::uuid AS canonical_card_id
    FROM proposed p
    LEFT JOIN public.cards c
      ON (
           lower(c.name) = p.normalized_name
           OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
         )
     AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
    GROUP BY p.card_name, p.normalized_name, p.oracle_hash
  )
  SELECT jsonb_agg(counts ORDER BY card_name)
    INTO v_missing
  FROM counts
  WHERE target_card_rows < 1;

  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION 'XMage batch package abort: expected at least one Oracle-hash-matched card row for every proposed card: %', v_missing;
  END IF;
END $$;

WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('army of allah', 'Army of Allah', '1ef4be52d08f0475feaa7d6d6fe78134', 'battle_rule_v1:38a0877b47351dea781b3e292168ba3f', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"combat_state":"attacking"},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":2,"sorcery":false,"target":"attacking_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"combat_state":"attacking"}},"target_controller":"all","toughness_delta":0,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"attacking_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ArmyOfAllah translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('eyeblight massacre', 'Eyeblight Massacre', 'cbff45a47c8a16ac2aa10e8c93c3195d', 'battle_rule_v1:b230476e11f26739ccb0bc67a312affe', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"exclude_subtypes":["Elf"]},"effect":"global_stat_modifier_until_eot","instant":false,"power_delta":-2,"sorcery":true,"target":"non_elf_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"exclude_subtypes":["Elf"]}},"target_controller":"all","toughness_delta":-2,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"non_elf_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class EyeblightMassacre translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('festergloom', 'Festergloom', '960ea67732e18980852f95373228552e', 'battle_rule_v1:352f141f48f3fcd4ceb24a2b92338d4f', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"exclude_colors":["B"]},"effect":"global_stat_modifier_until_eot","instant":false,"power_delta":-1,"sorcery":true,"target":"non_b_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"exclude_colors":["B"]}},"target_controller":"all","toughness_delta":-1,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"non_b_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Festergloom translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('hazardous conditions', 'Hazardous Conditions', 'eed2ece1875a19627ed69dfd5181fce2', 'battle_rule_v1:0d1b0e2f966c8962b875ddef80c5a71d', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"no_counters":true},"effect":"global_stat_modifier_until_eot","instant":false,"power_delta":-2,"sorcery":true,"target":"creatures_with_no_counters","target_constraints":{"card_types":["creature"],"creature_filter":{"no_counters":true}},"target_controller":"all","toughness_delta":-2,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"creatures_with_no_counters"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HazardousConditions translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('hold the line', 'Hold the Line', '770d2d7e18416184090fb01d854f62ec', 'battle_rule_v1:65f9a4c354c56642a5c813fab2ecbd7b', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"combat_state":"blocking"},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":7,"sorcery":false,"target":"blocking_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"combat_state":"blocking"}},"target_controller":"all","toughness_delta":7,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"blocking_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HoldTheLine translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('holy light', 'Holy Light', 'eb426784c3f6417501c84e5b540533f5', 'battle_rule_v1:0310fa36bc90e4f8d3a50f3dd18733dc', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"exclude_colors":["W"]},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":-1,"sorcery":false,"target":"non_w_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"exclude_colors":["W"]}},"target_controller":"all","toughness_delta":-1,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"non_w_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HolyLight translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('morale', 'Morale', '1830ec642002de376ed69e4f6766b937', 'battle_rule_v1:b47fdc764d84003fc74f6177d0f0df1e', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"combat_state":"attacking"},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":1,"sorcery":false,"target":"attacking_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"combat_state":"attacking"}},"target_controller":"all","toughness_delta":1,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"attacking_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Morale translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('nocturnal raid', 'Nocturnal Raid', '4136576b251ae9ea8a1a3c90a0c164c4', 'battle_rule_v1:6e22f29986bf8915b94b6e3abe825b71', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"colors":["B"]},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":2,"sorcery":false,"target":"b_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"colors":["B"]}},"target_controller":"all","toughness_delta":0,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"b_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class NocturnalRaid translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('rally', 'Rally', 'f83272e913174713d72858ca9f6917ad', 'battle_rule_v1:b86e3f6a50e8449a806e54ba6a3e7207', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"combat_state":"blocking"},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":1,"sorcery":false,"target":"blocking_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"combat_state":"blocking"}},"target_controller":"all","toughness_delta":1,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"blocking_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Rally translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('stench of decay', 'Stench of Decay', 'a5e5e5bbe487403fa3c1d872563bd777', 'battle_rule_v1:383e3cc52fdccddc76a04ea09a0cc79b', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"exclude_card_types":["artifact"]},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":-1,"sorcery":false,"target":"non_artifact_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"exclude_card_types":["artifact"]}},"target_controller":"all","toughness_delta":-1,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"non_artifact_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class StenchOfDecay translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('trumpet blast', 'Trumpet Blast', '1ef4be52d08f0475feaa7d6d6fe78134', 'battle_rule_v1:38a0877b47351dea781b3e292168ba3f', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"combat_state":"attacking"},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":2,"sorcery":false,"target":"attacking_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"combat_state":"attacking"}},"target_controller":"all","toughness_delta":0,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"attacking_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TrumpetBlast translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('valorous charge', 'Valorous Charge', 'f3a96246a7f3f9092d30f081d7f0fa90', 'battle_rule_v1:6f9f3e1fd5c01d164db507c86d9011fc', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"colors":["W"]},"effect":"global_stat_modifier_until_eot","instant":false,"power_delta":2,"sorcery":true,"target":"w_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"colors":["W"]}},"target_controller":"all","toughness_delta":0,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"w_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ValorousCharge translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
deprecated AS (
  UPDATE public.card_battle_rules r
  SET
    review_status = 'deprecated',
    execution_status = 'disabled',
    updated_at = now(),
    notes = concat_ws(E'\n', nullif(r.notes, ''), 'XMage batch package: deprecated stale shadow before curated batch rule upsert.')
  FROM proposed p
  WHERE (
        r.normalized_name = p.normalized_name
        OR r.normalized_name LIKE p.normalized_name || ' // %'
      )
    AND p.shadow_handling <> 'preserve_existing_rows'
    AND r.logical_rule_key <> p.logical_rule_key
  RETURNING r.*
)
SELECT count(*) AS deprecated_shadow_rows FROM deprecated;

WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('army of allah', 'Army of Allah', '1ef4be52d08f0475feaa7d6d6fe78134', 'battle_rule_v1:38a0877b47351dea781b3e292168ba3f', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"combat_state":"attacking"},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":2,"sorcery":false,"target":"attacking_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"combat_state":"attacking"}},"target_controller":"all","toughness_delta":0,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"attacking_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ArmyOfAllah translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('eyeblight massacre', 'Eyeblight Massacre', 'cbff45a47c8a16ac2aa10e8c93c3195d', 'battle_rule_v1:b230476e11f26739ccb0bc67a312affe', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"exclude_subtypes":["Elf"]},"effect":"global_stat_modifier_until_eot","instant":false,"power_delta":-2,"sorcery":true,"target":"non_elf_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"exclude_subtypes":["Elf"]}},"target_controller":"all","toughness_delta":-2,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"non_elf_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class EyeblightMassacre translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('festergloom', 'Festergloom', '960ea67732e18980852f95373228552e', 'battle_rule_v1:352f141f48f3fcd4ceb24a2b92338d4f', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"exclude_colors":["B"]},"effect":"global_stat_modifier_until_eot","instant":false,"power_delta":-1,"sorcery":true,"target":"non_b_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"exclude_colors":["B"]}},"target_controller":"all","toughness_delta":-1,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"non_b_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Festergloom translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('hazardous conditions', 'Hazardous Conditions', 'eed2ece1875a19627ed69dfd5181fce2', 'battle_rule_v1:0d1b0e2f966c8962b875ddef80c5a71d', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"no_counters":true},"effect":"global_stat_modifier_until_eot","instant":false,"power_delta":-2,"sorcery":true,"target":"creatures_with_no_counters","target_constraints":{"card_types":["creature"],"creature_filter":{"no_counters":true}},"target_controller":"all","toughness_delta":-2,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"creatures_with_no_counters"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HazardousConditions translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('hold the line', 'Hold the Line', '770d2d7e18416184090fb01d854f62ec', 'battle_rule_v1:65f9a4c354c56642a5c813fab2ecbd7b', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"combat_state":"blocking"},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":7,"sorcery":false,"target":"blocking_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"combat_state":"blocking"}},"target_controller":"all","toughness_delta":7,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"blocking_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HoldTheLine translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('holy light', 'Holy Light', 'eb426784c3f6417501c84e5b540533f5', 'battle_rule_v1:0310fa36bc90e4f8d3a50f3dd18733dc', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"exclude_colors":["W"]},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":-1,"sorcery":false,"target":"non_w_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"exclude_colors":["W"]}},"target_controller":"all","toughness_delta":-1,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"non_w_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HolyLight translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('morale', 'Morale', '1830ec642002de376ed69e4f6766b937', 'battle_rule_v1:b47fdc764d84003fc74f6177d0f0df1e', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"combat_state":"attacking"},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":1,"sorcery":false,"target":"attacking_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"combat_state":"attacking"}},"target_controller":"all","toughness_delta":1,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"attacking_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Morale translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('nocturnal raid', 'Nocturnal Raid', '4136576b251ae9ea8a1a3c90a0c164c4', 'battle_rule_v1:6e22f29986bf8915b94b6e3abe825b71', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"colors":["B"]},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":2,"sorcery":false,"target":"b_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"colors":["B"]}},"target_controller":"all","toughness_delta":0,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"b_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class NocturnalRaid translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('rally', 'Rally', 'f83272e913174713d72858ca9f6917ad', 'battle_rule_v1:b86e3f6a50e8449a806e54ba6a3e7207', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"combat_state":"blocking"},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":1,"sorcery":false,"target":"blocking_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"combat_state":"blocking"}},"target_controller":"all","toughness_delta":1,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"blocking_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Rally translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('stench of decay', 'Stench of Decay', 'a5e5e5bbe487403fa3c1d872563bd777', 'battle_rule_v1:383e3cc52fdccddc76a04ea09a0cc79b', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"exclude_card_types":["artifact"]},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":-1,"sorcery":false,"target":"non_artifact_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"exclude_card_types":["artifact"]}},"target_controller":"all","toughness_delta":-1,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"non_artifact_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class StenchOfDecay translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('trumpet blast', 'Trumpet Blast', '1ef4be52d08f0475feaa7d6d6fe78134', 'battle_rule_v1:38a0877b47351dea781b3e292168ba3f', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"combat_state":"attacking"},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":2,"sorcery":false,"target":"attacking_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"combat_state":"attacking"}},"target_controller":"all","toughness_delta":0,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"attacking_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TrumpetBlast translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('valorous charge', 'Valorous Charge', 'f3a96246a7f3f9092d30f081d7f0fa90', 'battle_rule_v1:6f9f3e1fd5c01d164db507c86d9011fc', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"colors":["W"]},"effect":"global_stat_modifier_until_eot","instant":false,"power_delta":2,"sorcery":true,"target":"w_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"colors":["W"]}},"target_controller":"all","toughness_delta":0,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"w_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ValorousCharge translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
matched_cards AS (
  SELECT
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    c.id AS card_id,
    c.name AS db_card_name
  FROM proposed p
  JOIN public.cards c
    ON (
         lower(c.name) = p.normalized_name
         OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
       )
   AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
),
canonical_target_cards AS (
  SELECT
    p.*,
    min(m.card_id::text)::uuid AS card_id,
    min(m.db_card_name) AS db_card_name
  FROM proposed p
  JOIN matched_cards m
    USING (normalized_name, card_name, oracle_hash)
  GROUP BY
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    p.logical_rule_key,
    p.effect_json,
    p.deck_role_json,
    p.source,
    p.confidence,
    p.review_status,
    p.execution_status,
    p.notes,
    p.shadow_handling
),
upserted AS (
  INSERT INTO public.card_battle_rules (
    normalized_name,
    card_id,
    card_name,
    effect_json,
    deck_role_json,
    source,
    confidence,
    review_status,
    rule_version,
    oracle_hash,
    notes,
    reviewed_by,
    reviewed_at,
    created_at,
    updated_at,
    last_seen_at,
    logical_rule_key,
    execution_status
  )
  SELECT
    normalized_name,
    card_id,
    db_card_name,
    effect_json,
    deck_role_json,
    source,
    confidence,
    review_status,
    2,
    oracle_hash,
    notes,
    'codex-xmage-batch',
    now(),
    now(),
    now(),
    now(),
    logical_rule_key,
    execution_status
  FROM canonical_target_cards
  ON CONFLICT (normalized_name, logical_rule_key) DO UPDATE
  SET
    card_id = EXCLUDED.card_id,
    card_name = EXCLUDED.card_name,
    effect_json = EXCLUDED.effect_json,
    deck_role_json = EXCLUDED.deck_role_json,
    source = EXCLUDED.source,
    confidence = EXCLUDED.confidence,
    review_status = EXCLUDED.review_status,
    rule_version = EXCLUDED.rule_version,
    oracle_hash = EXCLUDED.oracle_hash,
    notes = EXCLUDED.notes,
    reviewed_by = EXCLUDED.reviewed_by,
    reviewed_at = EXCLUDED.reviewed_at,
    updated_at = EXCLUDED.updated_at,
    last_seen_at = EXCLUDED.last_seen_at,
    execution_status = EXCLUDED.execution_status
  RETURNING *
)
SELECT count(*) AS upserted_rows FROM upserted;

COMMIT;
