WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('army of allah', 'Army of Allah', '1ef4be52d08f0475feaa7d6d6fe78134', 'battle_rule_v1:38a0877b47351dea781b3e292168ba3f', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"combat_state":"attacking"},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":2,"sorcery":false,"target":"attacking_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"combat_state":"attacking"}},"target_controller":"all","toughness_delta":0,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"attacking_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ArmyOfAllah translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('eyeblight massacre', 'Eyeblight Massacre', 'cbff45a47c8a16ac2aa10e8c93c3195d', 'battle_rule_v1:b230476e11f26739ccb0bc67a312affe', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"exclude_subtypes":["Elf"]},"effect":"global_stat_modifier_until_eot","instant":false,"power_delta":-2,"sorcery":true,"target":"non_elf_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"exclude_subtypes":["Elf"]}},"target_controller":"all","toughness_delta":-2,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"non_elf_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class EyeblightMassacre translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('festergloom', 'Festergloom', '960ea67732e18980852f95373228552e', 'battle_rule_v1:352f141f48f3fcd4ceb24a2b92338d4f', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"exclude_colors":["B"]},"effect":"global_stat_modifier_until_eot","instant":false,"power_delta":-1,"sorcery":true,"target":"non_b_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"exclude_colors":["B"]}},"target_controller":"all","toughness_delta":-1,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"non_b_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Festergloom translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('hazardous conditions', 'Hazardous Conditions', 'eed2ece1875a19627ed69dfd5181fce2', 'battle_rule_v1:0d1b0e2f966c8962b875ddef80c5a71d', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"no_counters":true},"effect":"global_stat_modifier_until_eot","instant":false,"power_delta":-2,"sorcery":true,"target":"creatures_with_no_counters","target_constraints":{"card_types":["creature"],"creature_filter":{"no_counters":true}},"target_controller":"all","toughness_delta":-2,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"creatures_with_no_counters"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HazardousConditions translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('hold the line', 'Hold the Line', '770d2d7e18416184090fb01d854f62ec', 'battle_rule_v1:65f9a4c354c56642a5c813fab2ecbd7b', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"combat_state":"blocking"},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":7,"sorcery":false,"target":"blocking_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"combat_state":"blocking"}},"target_controller":"all","toughness_delta":7,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"blocking_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HoldTheLine translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('holy light', 'Holy Light', 'eb426784c3f6417501c84e5b540533f5', 'battle_rule_v1:0310fa36bc90e4f8d3a50f3dd18733dc', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"exclude_colors":["W"]},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":-1,"sorcery":false,"target":"non_w_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"exclude_colors":["W"]}},"target_controller":"all","toughness_delta":-1,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"non_w_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HolyLight translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('morale', 'Morale', '1830ec642002de376ed69e4f6766b937', 'battle_rule_v1:b47fdc764d84003fc74f6177d0f0df1e', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"combat_state":"attacking"},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":1,"sorcery":false,"target":"attacking_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"combat_state":"attacking"}},"target_controller":"all","toughness_delta":1,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"attacking_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Morale translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('nocturnal raid', 'Nocturnal Raid', '4136576b251ae9ea8a1a3c90a0c164c4', 'battle_rule_v1:6e22f29986bf8915b94b6e3abe825b71', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"colors":["B"]},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":2,"sorcery":false,"target":"b_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"colors":["B"]}},"target_controller":"all","toughness_delta":0,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"b_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class NocturnalRaid translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('rally', 'Rally', 'f83272e913174713d72858ca9f6917ad', 'battle_rule_v1:b86e3f6a50e8449a806e54ba6a3e7207', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"combat_state":"blocking"},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":1,"sorcery":false,"target":"blocking_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"combat_state":"blocking"}},"target_controller":"all","toughness_delta":1,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"blocking_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Rally translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('stench of decay', 'Stench of Decay', 'a5e5e5bbe487403fa3c1d872563bd777', 'battle_rule_v1:383e3cc52fdccddc76a04ea09a0cc79b', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"exclude_card_types":["artifact"]},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":-1,"sorcery":false,"target":"non_artifact_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"exclude_card_types":["artifact"]}},"target_controller":"all","toughness_delta":-1,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"non_artifact_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class StenchOfDecay translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('trumpet blast', 'Trumpet Blast', '1ef4be52d08f0475feaa7d6d6fe78134', 'battle_rule_v1:38a0877b47351dea781b3e292168ba3f', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"combat_state":"attacking"},"effect":"global_stat_modifier_until_eot","instant":true,"power_delta":2,"sorcery":false,"target":"attacking_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"combat_state":"attacking"}},"target_controller":"all","toughness_delta":0,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"attacking_creatures","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TrumpetBlast translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('valorous charge', 'Valorous Charge', 'f3a96246a7f3f9092d30f081d7f0fa90', 'battle_rule_v1:6f9f3e1fd5c01d164db507c86d9011fc', '{"battle_model_scope":"xmage_fixed_boost_filtered_creatures_until_eot_spell_v1","creature_filter":{"colors":["W"]},"effect":"global_stat_modifier_until_eot","instant":false,"power_delta":2,"sorcery":true,"target":"w_creatures","target_constraints":{"card_types":["creature"],"creature_filter":{"colors":["W"]}},"target_controller":"all","toughness_delta":0,"xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"unknown","effect":"global_stat_modifier_until_eot","target":"w_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ValorousCharge translated into ManaLoom runtime scope xmage_fixed_boost_filtered_creatures_until_eot_spell_v1. This row is package-ready only because the source signature is a narrow fixed filtered-creature boost until end of turn spell with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
rule_rows AS (
  SELECT
    r.normalized_name,
    r.logical_rule_key,
    r.oracle_hash,
    r.review_status,
    r.execution_status
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key = p.logical_rule_key
)
SELECT
  p.card_name,
  p.normalized_name,
  p.logical_rule_key,
  count(r.*) FILTER (WHERE r.logical_rule_key = p.logical_rule_key) AS promoted_rule_rows,
  count(r.*) FILTER (WHERE r.review_status = 'verified' AND r.execution_status = 'auto') AS promoted_verified_auto_rows,
  count(r.*) FILTER (WHERE r.oracle_hash = p.oracle_hash) AS promoted_oracle_hash_rows,
  (SELECT count(*) FROM manaloom_deploy_audit.pg527_boost_all_filtered_new_server_20260705_200027) AS backup_rows
FROM proposed p
LEFT JOIN rule_rows r
  ON r.normalized_name = p.normalized_name
 AND r.logical_rule_key = p.logical_rule_key
 AND r.oracle_hash = p.oracle_hash
GROUP BY p.card_name, p.normalized_name, p.logical_rule_key, p.oracle_hash
ORDER BY p.card_name;
