WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('anaba spirit crafter', 'Anaba Spirit Crafter', '42963ba84364b2375ec41f6e61bb6088', 'battle_rule_v1:993bd69c423eb7117a71de8b29625279', '{"ability_kind":"static","battle_model_scope":"xmage_static_global_power_toughness_boost_v1","creature_filter":{"subtypes":["minotaur"]},"effect":"static_global_power_toughness_boost","permanent_type":"creature","static_applies_to":"minotaur_creatures","static_controller_scope":"all","static_effect":"global_power_toughness_boost","static_exclude_source":false,"static_power_bonus":1,"static_toughness_bonus":0,"target":"minotaur_creatures","target_constraints":{"card_types":["creature"],"controller":"all","creature_filter":{"subtypes":["minotaur"]},"subtypes":["minotaur"]},"target_controller":"all","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"support","effect":"static_global_power_toughness_boost","subtype":"static_global_pump","target":"minotaur_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AnabaSpiritCrafter translated into ManaLoom runtime scope xmage_static_global_power_toughness_boost_v1. This row is package-ready only because the source signature is a narrow permanent static global/opponent/filtered creature power/toughness boost with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('bad moon', 'Bad Moon', '2c8bafd49261c43124aadd0c2469c4d7', 'battle_rule_v1:c6b4760d4f7a6338ea095a9648319173', '{"ability_kind":"static","battle_model_scope":"xmage_static_global_power_toughness_boost_v1","creature_filter":{"colors":["B"]},"effect":"static_global_power_toughness_boost","permanent_type":"enchantment","static_applies_to":"b_creatures","static_controller_scope":"all","static_effect":"global_power_toughness_boost","static_exclude_source":false,"static_power_bonus":1,"static_toughness_bonus":1,"target":"b_creatures","target_constraints":{"card_types":["creature"],"colors":["B"],"controller":"all","creature_filter":{"colors":["B"]}},"target_controller":"all","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"support","effect":"static_global_power_toughness_boost","subtype":"static_global_pump","target":"b_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BadMoon translated into ManaLoom runtime scope xmage_static_global_power_toughness_boost_v1. This row is package-ready only because the source signature is a narrow permanent static global/opponent/filtered creature power/toughness boost with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('blade sliver', 'Blade Sliver', '80e88a5ec27e492a51739af0b7f3fcf3', 'battle_rule_v1:3f031b3f549fbee3ac7045d570c39af8', '{"ability_kind":"static","battle_model_scope":"xmage_static_global_power_toughness_boost_v1","creature_filter":{"subtypes":["sliver"]},"effect":"static_global_power_toughness_boost","permanent_type":"creature","static_applies_to":"sliver_creatures","static_controller_scope":"all","static_effect":"global_power_toughness_boost","static_exclude_source":false,"static_power_bonus":1,"static_toughness_bonus":0,"target":"sliver_creatures","target_constraints":{"card_types":["creature"],"controller":"all","creature_filter":{"subtypes":["sliver"]},"subtypes":["sliver"]},"target_controller":"all","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"support","effect":"static_global_power_toughness_boost","subtype":"static_global_pump","target":"sliver_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BladeSliver translated into ManaLoom runtime scope xmage_static_global_power_toughness_boost_v1. This row is package-ready only because the source signature is a narrow permanent static global/opponent/filtered creature power/toughness boost with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('bonesplitter sliver', 'Bonesplitter Sliver', '913032340a01d231b5896a4635236481', 'battle_rule_v1:69253c698baf2e13254e0f1399a8b786', '{"ability_kind":"static","battle_model_scope":"xmage_static_global_power_toughness_boost_v1","creature_filter":{"subtypes":["sliver"]},"effect":"static_global_power_toughness_boost","permanent_type":"creature","static_applies_to":"sliver_creatures","static_controller_scope":"all","static_effect":"global_power_toughness_boost","static_exclude_source":false,"static_power_bonus":2,"static_toughness_bonus":0,"target":"sliver_creatures","target_constraints":{"card_types":["creature"],"controller":"all","creature_filter":{"subtypes":["sliver"]},"subtypes":["sliver"]},"target_controller":"all","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"support","effect":"static_global_power_toughness_boost","subtype":"static_global_pump","target":"sliver_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BonesplitterSliver translated into ManaLoom runtime scope xmage_static_global_power_toughness_boost_v1. This row is package-ready only because the source signature is a narrow permanent static global/opponent/filtered creature power/toughness boost with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('dampening pulse', 'Dampening Pulse', '4fee96f2119dff687363c35257328850', 'battle_rule_v1:a912ad5ca2d6d6548fedb920192295ca', '{"ability_kind":"static","battle_model_scope":"xmage_static_global_power_toughness_boost_v1","creature_filter":null,"effect":"static_global_power_toughness_boost","permanent_type":"enchantment","static_applies_to":"opponents_creatures","static_controller_scope":"opponents","static_effect":"global_power_toughness_boost","static_exclude_source":false,"static_power_bonus":-1,"static_toughness_bonus":0,"target":"opponents_creatures","target_constraints":{"card_types":["creature"],"controller":"opponents"},"target_controller":"opponents","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"removal","effect":"static_global_power_toughness_boost","subtype":"static_global_debuff","target":"opponents_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DampeningPulse translated into ManaLoom runtime scope xmage_static_global_power_toughness_boost_v1. This row is package-ready only because the source signature is a narrow permanent static global/opponent/filtered creature power/toughness boost with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('dread of night', 'Dread of Night', 'e97cd78b994234a08daf9ac5c4f1e3bd', 'battle_rule_v1:319eb706453b6e2f59c9d7217969f4da', '{"ability_kind":"static","battle_model_scope":"xmage_static_global_power_toughness_boost_v1","creature_filter":{"colors":["W"]},"effect":"static_global_power_toughness_boost","permanent_type":"enchantment","static_applies_to":"w_creatures","static_controller_scope":"all","static_effect":"global_power_toughness_boost","static_exclude_source":false,"static_power_bonus":-1,"static_toughness_bonus":-1,"target":"w_creatures","target_constraints":{"card_types":["creature"],"colors":["W"],"controller":"all","creature_filter":{"colors":["W"]}},"target_controller":"all","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"removal","effect":"static_global_power_toughness_boost","subtype":"static_global_debuff","target":"w_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DreadOfNight translated into ManaLoom runtime scope xmage_static_global_power_toughness_boost_v1. This row is package-ready only because the source signature is a narrow permanent static global/opponent/filtered creature power/toughness boost with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('earth surge', 'Earth Surge', '1cb610c33c257e506ec4a1efb0c88597', 'battle_rule_v1:9c9ff8e663d045ed8853be2811170614', '{"ability_kind":"static","battle_model_scope":"xmage_static_global_power_toughness_boost_v1","creature_filter":{"card_types":["land"]},"effect":"static_global_power_toughness_boost","permanent_type":"enchantment","static_applies_to":"land_creatures","static_controller_scope":"all","static_effect":"global_power_toughness_boost","static_exclude_source":true,"static_power_bonus":2,"static_toughness_bonus":2,"target":"land_creatures","target_constraints":{"card_types":["creature","land"],"controller":"all","creature_filter":{"card_types":["land"]}},"target_controller":"all","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"support","effect":"static_global_power_toughness_boost","subtype":"static_global_pump","target":"land_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class EarthSurge translated into ManaLoom runtime scope xmage_static_global_power_toughness_boost_v1. This row is package-ready only because the source signature is a narrow permanent static global/opponent/filtered creature power/toughness boost with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('illness in the ranks', 'Illness in the Ranks', 'b855e07b97a68b105b8aa237bd9e6247', 'battle_rule_v1:dd09864cb0de3a910c7cafb5824b47a3', '{"ability_kind":"static","battle_model_scope":"xmage_static_global_power_toughness_boost_v1","creature_filter":{"token":true},"effect":"static_global_power_toughness_boost","permanent_type":"enchantment","static_applies_to":"creature_tokens","static_controller_scope":"all","static_effect":"global_power_toughness_boost","static_exclude_source":false,"static_power_bonus":-1,"static_toughness_bonus":-1,"target":"creature_tokens","target_constraints":{"card_types":["creature"],"controller":"all","creature_filter":{"token":true},"token":true},"target_controller":"all","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"removal","effect":"static_global_power_toughness_boost","subtype":"static_global_debuff","target":"creature_tokens"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class IllnessInTheRanks translated into ManaLoom runtime scope xmage_static_global_power_toughness_boost_v1. This row is package-ready only because the source signature is a narrow permanent static global/opponent/filtered creature power/toughness boost with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('kaervek, the spiteful', 'Kaervek, the Spiteful', 'f04be6e1013032bdd7af116ac75164ef', 'battle_rule_v1:6d9b4aa450c873897fa5bf7882eaa859', '{"ability_kind":"static","battle_model_scope":"xmage_static_global_power_toughness_boost_v1","creature_filter":null,"effect":"static_global_power_toughness_boost","permanent_type":"creature","static_applies_to":"creatures","static_controller_scope":"all","static_effect":"global_power_toughness_boost","static_exclude_source":true,"static_power_bonus":-1,"static_toughness_bonus":-1,"target":"creatures","target_constraints":{"card_types":["creature"],"controller":"all"},"target_controller":"all","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"removal","effect":"static_global_power_toughness_boost","subtype":"static_global_debuff","target":"creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class KaervekTheSpiteful translated into ManaLoom runtime scope xmage_static_global_power_toughness_boost_v1. This row is package-ready only because the source signature is a narrow permanent static global/opponent/filtered creature power/toughness boost with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('might sliver', 'Might Sliver', '954c87be57f0e77e26116a11df044341', 'battle_rule_v1:32acbc5add4bf3d787a32ef8620d1574', '{"ability_kind":"static","battle_model_scope":"xmage_static_global_power_toughness_boost_v1","creature_filter":{"subtypes":["sliver"]},"effect":"static_global_power_toughness_boost","permanent_type":"creature","static_applies_to":"sliver_creatures","static_controller_scope":"all","static_effect":"global_power_toughness_boost","static_exclude_source":false,"static_power_bonus":2,"static_toughness_bonus":2,"target":"sliver_creatures","target_constraints":{"card_types":["creature"],"controller":"all","creature_filter":{"subtypes":["sliver"]},"subtypes":["sliver"]},"target_controller":"all","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"support","effect":"static_global_power_toughness_boost","subtype":"static_global_pump","target":"sliver_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MightSliver translated into ManaLoom runtime scope xmage_static_global_power_toughness_boost_v1. This row is package-ready only because the source signature is a narrow permanent static global/opponent/filtered creature power/toughness boost with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('muscle sliver', 'Muscle Sliver', 'e788f814cbdefe441e912f10ad8e8355', 'battle_rule_v1:2aabeb4becbc045ca2858aa02cab518a', '{"ability_kind":"static","battle_model_scope":"xmage_static_global_power_toughness_boost_v1","creature_filter":{"subtypes":["sliver"]},"effect":"static_global_power_toughness_boost","permanent_type":"creature","static_applies_to":"sliver_creatures","static_controller_scope":"all","static_effect":"global_power_toughness_boost","static_exclude_source":false,"static_power_bonus":1,"static_toughness_bonus":1,"target":"sliver_creatures","target_constraints":{"card_types":["creature"],"controller":"all","creature_filter":{"subtypes":["sliver"]},"subtypes":["sliver"]},"target_controller":"all","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"support","effect":"static_global_power_toughness_boost","subtype":"static_global_pump","target":"sliver_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MuscleSliver translated into ManaLoom runtime scope xmage_static_global_power_toughness_boost_v1. This row is package-ready only because the source signature is a narrow permanent static global/opponent/filtered creature power/toughness boost with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('night of souls'' betrayal', 'Night of Souls'' Betrayal', 'e4b8258fec54842c689078784020d6f0', 'battle_rule_v1:1e8343029d31d5f4baa1c6ac401dff79', '{"ability_kind":"static","battle_model_scope":"xmage_static_global_power_toughness_boost_v1","creature_filter":null,"effect":"static_global_power_toughness_boost","permanent_type":"enchantment","static_applies_to":"creatures","static_controller_scope":"all","static_effect":"global_power_toughness_boost","static_exclude_source":false,"static_power_bonus":-1,"static_toughness_bonus":-1,"target":"creatures","target_constraints":{"card_types":["creature"],"controller":"all"},"target_controller":"all","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"removal","effect":"static_global_power_toughness_boost","subtype":"static_global_debuff","target":"creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class NightOfSoulsBetrayal translated into ManaLoom runtime scope xmage_static_global_power_toughness_boost_v1. This row is package-ready only because the source signature is a narrow permanent static global/opponent/filtered creature power/toughness boost with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('plated sliver', 'Plated Sliver', '096b6ff27180cf3106b940d6a441e1f7', 'battle_rule_v1:441c1e5fc66cf0abdc6b1b3c7fd02ec5', '{"ability_kind":"static","battle_model_scope":"xmage_static_global_power_toughness_boost_v1","creature_filter":{"subtypes":["sliver"]},"effect":"static_global_power_toughness_boost","permanent_type":"creature","static_applies_to":"sliver_creatures","static_controller_scope":"all","static_effect":"global_power_toughness_boost","static_exclude_source":false,"static_power_bonus":0,"static_toughness_bonus":1,"target":"sliver_creatures","target_constraints":{"card_types":["creature"],"controller":"all","creature_filter":{"subtypes":["sliver"]},"subtypes":["sliver"]},"target_controller":"all","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"support","effect":"static_global_power_toughness_boost","subtype":"static_global_pump","target":"sliver_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PlatedSliver translated into ManaLoom runtime scope xmage_static_global_power_toughness_boost_v1. This row is package-ready only because the source signature is a narrow permanent static global/opponent/filtered creature power/toughness boost with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sinew sliver', 'Sinew Sliver', 'e788f814cbdefe441e912f10ad8e8355', 'battle_rule_v1:2aabeb4becbc045ca2858aa02cab518a', '{"ability_kind":"static","battle_model_scope":"xmage_static_global_power_toughness_boost_v1","creature_filter":{"subtypes":["sliver"]},"effect":"static_global_power_toughness_boost","permanent_type":"creature","static_applies_to":"sliver_creatures","static_controller_scope":"all","static_effect":"global_power_toughness_boost","static_exclude_source":false,"static_power_bonus":1,"static_toughness_bonus":1,"target":"sliver_creatures","target_constraints":{"card_types":["creature"],"controller":"all","creature_filter":{"subtypes":["sliver"]},"subtypes":["sliver"]},"target_controller":"all","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"support","effect":"static_global_power_toughness_boost","subtype":"static_global_pump","target":"sliver_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SinewSliver translated into ManaLoom runtime scope xmage_static_global_power_toughness_boost_v1. This row is package-ready only because the source signature is a narrow permanent static global/opponent/filtered creature power/toughness boost with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('stronghold taskmaster', 'Stronghold Taskmaster', 'dfacc9d2b7281a7722ebf6dc53f944a4', 'battle_rule_v1:7f806849dd176e9405ba4776a11a5c5f', '{"ability_kind":"static","battle_model_scope":"xmage_static_global_power_toughness_boost_v1","creature_filter":{"colors":["B"]},"effect":"static_global_power_toughness_boost","permanent_type":"creature","static_applies_to":"b_creatures","static_controller_scope":"all","static_effect":"global_power_toughness_boost","static_exclude_source":true,"static_power_bonus":-1,"static_toughness_bonus":-1,"target":"b_creatures","target_constraints":{"card_types":["creature"],"colors":["B"],"controller":"all","creature_filter":{"colors":["B"]}},"target_controller":"all","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"removal","effect":"static_global_power_toughness_boost","subtype":"static_global_debuff","target":"b_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class StrongholdTaskmaster translated into ManaLoom runtime scope xmage_static_global_power_toughness_boost_v1. This row is package-ready only because the source signature is a narrow permanent static global/opponent/filtered creature power/toughness boost with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('urborg shambler', 'Urborg Shambler', 'dfacc9d2b7281a7722ebf6dc53f944a4', 'battle_rule_v1:7f806849dd176e9405ba4776a11a5c5f', '{"ability_kind":"static","battle_model_scope":"xmage_static_global_power_toughness_boost_v1","creature_filter":{"colors":["B"]},"effect":"static_global_power_toughness_boost","permanent_type":"creature","static_applies_to":"b_creatures","static_controller_scope":"all","static_effect":"global_power_toughness_boost","static_exclude_source":true,"static_power_bonus":-1,"static_toughness_bonus":-1,"target":"b_creatures","target_constraints":{"card_types":["creature"],"colors":["B"],"controller":"all","creature_filter":{"colors":["B"]}},"target_controller":"all","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"removal","effect":"static_global_power_toughness_boost","subtype":"static_global_debuff","target":"b_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class UrborgShambler translated into ManaLoom runtime scope xmage_static_global_power_toughness_boost_v1. This row is package-ready only because the source signature is a narrow permanent static global/opponent/filtered creature power/toughness boost with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('virulent plague', 'Virulent Plague', 'bb77f6ada984cb747a92f8ed1accce19', 'battle_rule_v1:95a51e7b60e6c4367aa474de86230207', '{"ability_kind":"static","battle_model_scope":"xmage_static_global_power_toughness_boost_v1","creature_filter":{"token":true},"effect":"static_global_power_toughness_boost","permanent_type":"enchantment","static_applies_to":"creature_tokens","static_controller_scope":"all","static_effect":"global_power_toughness_boost","static_exclude_source":false,"static_power_bonus":-2,"static_toughness_bonus":-2,"target":"creature_tokens","target_constraints":{"card_types":["creature"],"controller":"all","creature_filter":{"token":true},"token":true},"target_controller":"all","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"removal","effect":"static_global_power_toughness_boost","subtype":"static_global_debuff","target":"creature_tokens"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class VirulentPlague translated into ManaLoom runtime scope xmage_static_global_power_toughness_boost_v1. This row is package-ready only because the source signature is a narrow permanent static global/opponent/filtered creature power/toughness boost with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('watcher sliver', 'Watcher Sliver', '68d97ef13847948e533d4749033947a9', 'battle_rule_v1:182a62239d1bd120d9a26e6d94eebc9f', '{"ability_kind":"static","battle_model_scope":"xmage_static_global_power_toughness_boost_v1","creature_filter":{"subtypes":["sliver"]},"effect":"static_global_power_toughness_boost","permanent_type":"creature","static_applies_to":"sliver_creatures","static_controller_scope":"all","static_effect":"global_power_toughness_boost","static_exclude_source":false,"static_power_bonus":0,"static_toughness_bonus":2,"target":"sliver_creatures","target_constraints":{"card_types":["creature"],"controller":"all","creature_filter":{"subtypes":["sliver"]},"subtypes":["sliver"]},"target_controller":"all","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostAllEffect"}'::jsonb, '{"category":"support","effect":"static_global_power_toughness_boost","subtype":"static_global_pump","target":"sliver_creatures"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class WatcherSliver translated into ManaLoom runtime scope xmage_static_global_power_toughness_boost_v1. This row is package-ready only because the source signature is a narrow permanent static global/opponent/filtered creature power/toughness boost with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
matched_cards AS (
  SELECT
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    c.id AS card_id,
    c.name AS db_card_name
  FROM proposed p
  LEFT JOIN public.cards c
    ON (
         lower(c.name) = p.normalized_name
         OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
       )
   AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
),
target_cards AS (
  SELECT
    normalized_name,
    card_name,
    oracle_hash,
    count(card_id) AS target_card_rows,
    min(card_id::text)::uuid AS canonical_card_id,
    min(db_card_name) AS canonical_card_name
  FROM matched_cards
  GROUP BY normalized_name, card_name, oracle_hash
),
rule_rows AS (
  SELECT p.normalized_name, count(r.*) AS existing_rule_rows
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
  GROUP BY p.normalized_name
),
expected_rows AS (
  SELECT p.normalized_name, count(r.*) AS expected_rule_rows_before
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key = p.logical_rule_key
  GROUP BY p.normalized_name
),
shadow_rows AS (
  SELECT p.normalized_name, count(r.*) AS would_deprecate_shadow_rows
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key <> p.logical_rule_key
   AND r.review_status NOT IN ('deprecated', 'rejected')
   AND r.execution_status <> 'disabled'
  GROUP BY p.normalized_name
)
SELECT
  p.card_name,
  p.normalized_name,
  p.oracle_hash,
  p.logical_rule_key,
  p.shadow_handling,
  tc.target_card_rows,
  tc.canonical_card_id,
  rr.existing_rule_rows,
  er.expected_rule_rows_before,
  sr.would_deprecate_shadow_rows
FROM proposed p
JOIN target_cards tc USING (normalized_name, card_name, oracle_hash)
JOIN rule_rows rr USING (normalized_name)
JOIN expected_rows er USING (normalized_name)
JOIN shadow_rows sr USING (normalized_name)
ORDER BY p.card_name;
