WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('blessed reversal', 'Blessed Reversal', '823a9c3aa2094d20b96fd4ccb747bbb5', 'battle_rule_v1:a30d89079274b0aeb350157489c02bee', '{"battle_model_scope":"xmage_dynamic_controller_gain_life_spell_v1","battlefield_count_card_types":["creature"],"battlefield_count_combat_state":"attacking","battlefield_count_scope":"opponents_battlefield","effect":"life_total_change","instant":true,"life_gain_amount_source":"battlefield_permanent_count","life_gain_base_amount":0,"life_gain_per_count":3,"sorcery":false,"target":"self","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"life_total_change","target":"self","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BlessedReversal translated into ManaLoom runtime scope xmage_dynamic_controller_gain_life_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('bountiful harvest', 'Bountiful Harvest', '80024b4cf516a43e6d18839cf03860e6', 'battle_rule_v1:f609e13e36e1e99fd47c17fe7ea088d2', '{"battle_model_scope":"xmage_dynamic_controller_gain_life_spell_v1","battlefield_count_card_types":["land"],"battlefield_count_scope":"controller_battlefield","effect":"life_total_change","instant":false,"life_gain_amount_source":"battlefield_permanent_count","life_gain_base_amount":0,"life_gain_per_count":1,"sorcery":true,"target":"self","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"life_total_change","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BountifulHarvest translated into ManaLoom runtime scope xmage_dynamic_controller_gain_life_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('festival of trokin', 'Festival of Trokin', 'c854e6479f1427e2b5d0c823a7244f19', 'battle_rule_v1:898aa76651becdc5799867dd5c4a71b7', '{"battle_model_scope":"xmage_dynamic_controller_gain_life_spell_v1","battlefield_count_card_types":["creature"],"battlefield_count_scope":"controller_battlefield","effect":"life_total_change","instant":false,"life_gain_amount_source":"battlefield_permanent_count","life_gain_base_amount":0,"life_gain_per_count":2,"sorcery":true,"target":"self","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"life_total_change","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class FestivalOfTrokin translated into ManaLoom runtime scope xmage_dynamic_controller_gain_life_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('fruition', 'Fruition', '1d7d5ee9cf5d1d8f0868d99d5f795919', 'battle_rule_v1:4be0feca617880d6fd5d2b94dd07eee4', '{"battle_model_scope":"xmage_dynamic_controller_gain_life_spell_v1","battlefield_count_card_types":["land"],"battlefield_count_scope":"all_battlefields","battlefield_count_subtypes":["forest"],"effect":"life_total_change","instant":false,"life_gain_amount_source":"battlefield_permanent_count","life_gain_base_amount":0,"life_gain_per_count":1,"sorcery":true,"target":"self","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"life_total_change","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Fruition translated into ManaLoom runtime scope xmage_dynamic_controller_gain_life_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('gerrard''s wisdom', 'Gerrard''s Wisdom', '2f3b5a81795c702888749982471cc0b0', 'battle_rule_v1:0dc75e25a69cb2c92abdc1358e2ce3b5', '{"battle_model_scope":"xmage_dynamic_controller_gain_life_spell_v1","effect":"life_total_change","instant":false,"life_gain_amount_source":"controller_hand_count","life_gain_base_amount":0,"life_gain_per_count":2,"sorcery":true,"target":"self","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"life_total_change","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GerrardsWisdom translated into ManaLoom runtime scope xmage_dynamic_controller_gain_life_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('invigorating falls', 'Invigorating Falls', 'ade29be2af80d9a21039a33b8d862a31', 'battle_rule_v1:8cc8c8b01bba9fe02e7c3a27f2b387ee', '{"battle_model_scope":"xmage_dynamic_controller_gain_life_spell_v1","effect":"life_total_change","graveyard_count_card_types":["creature"],"graveyard_count_scope":"all_graveyards","instant":false,"life_gain_amount_source":"graveyard_card_count","life_gain_base_amount":0,"life_gain_per_count":1,"sorcery":true,"target":"self","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"life_total_change","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class InvigoratingFalls translated into ManaLoom runtime scope xmage_dynamic_controller_gain_life_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('joyous respite', 'Joyous Respite', '80024b4cf516a43e6d18839cf03860e6', 'battle_rule_v1:f609e13e36e1e99fd47c17fe7ea088d2', '{"battle_model_scope":"xmage_dynamic_controller_gain_life_spell_v1","battlefield_count_card_types":["land"],"battlefield_count_scope":"controller_battlefield","effect":"life_total_change","instant":false,"life_gain_amount_source":"battlefield_permanent_count","life_gain_base_amount":0,"life_gain_per_count":1,"sorcery":true,"target":"self","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"life_total_change","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class JoyousRespite translated into ManaLoom runtime scope xmage_dynamic_controller_gain_life_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('landbind ritual', 'Landbind Ritual', 'd84556b6708d3cf7331b93ece9875ae6', 'battle_rule_v1:9e929643503771dc1bec7ee764f4e2c3', '{"battle_model_scope":"xmage_dynamic_controller_gain_life_spell_v1","battlefield_count_card_types":["land"],"battlefield_count_scope":"controller_battlefield","battlefield_count_subtypes":["plains"],"effect":"life_total_change","instant":false,"life_gain_amount_source":"battlefield_permanent_count","life_gain_base_amount":0,"life_gain_per_count":2,"sorcery":true,"target":"self","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"life_total_change","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class LandbindRitual translated into ManaLoom runtime scope xmage_dynamic_controller_gain_life_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('peach garden oath', 'Peach Garden Oath', 'c854e6479f1427e2b5d0c823a7244f19', 'battle_rule_v1:898aa76651becdc5799867dd5c4a71b7', '{"battle_model_scope":"xmage_dynamic_controller_gain_life_spell_v1","battlefield_count_card_types":["creature"],"battlefield_count_scope":"controller_battlefield","effect":"life_total_change","instant":false,"life_gain_amount_source":"battlefield_permanent_count","life_gain_base_amount":0,"life_gain_per_count":2,"sorcery":true,"target":"self","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"life_total_change","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PeachGardenOath translated into ManaLoom runtime scope xmage_dynamic_controller_gain_life_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('presence of the wise', 'Presence of the Wise', '2f3b5a81795c702888749982471cc0b0', 'battle_rule_v1:0dc75e25a69cb2c92abdc1358e2ce3b5', '{"battle_model_scope":"xmage_dynamic_controller_gain_life_spell_v1","effect":"life_total_change","instant":false,"life_gain_amount_source":"controller_hand_count","life_gain_base_amount":0,"life_gain_per_count":2,"sorcery":true,"target":"self","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"life_total_change","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PresenceOfTheWise translated into ManaLoom runtime scope xmage_dynamic_controller_gain_life_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('toil to renown', 'Toil to Renown', '4521866f2c0302b96432f72194b560b8', 'battle_rule_v1:7cde60c98e70c669b462ea5874e17232', '{"battle_model_scope":"xmage_dynamic_controller_gain_life_spell_v1","battlefield_count_card_types":["artifact","creature","land"],"battlefield_count_scope":"controller_battlefield","battlefield_count_tapped_state":"tapped","effect":"life_total_change","instant":false,"life_gain_amount_source":"battlefield_permanent_count","life_gain_base_amount":0,"life_gain_per_count":1,"sorcery":true,"target":"self","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"life_total_change","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ToilToRenown translated into ManaLoom runtime scope xmage_dynamic_controller_gain_life_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('wandering stream', 'Wandering Stream', 'fb473dc7cf9f74523c04b406b6d36a8e', 'battle_rule_v1:2672dfc54371d68650a2f9ea851b5990', '{"battle_model_scope":"xmage_dynamic_controller_gain_life_spell_v1","effect":"life_total_change","instant":false,"life_gain_amount_source":"domain_basic_land_types","life_gain_base_amount":0,"life_gain_per_count":2,"sorcery":true,"target":"self","xmage_effect_class":"GainLifeEffect"}'::jsonb, '{"category":"unknown","effect":"life_total_change","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class WanderingStream translated into ManaLoom runtime scope xmage_dynamic_controller_gain_life_spell_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
rule_rows AS (
  SELECT
    r.normalized_name,
    r.logical_rule_key,
    r.oracle_hash,
    r.review_status,
    r.execution_status
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key = p.logical_rule_key
)
SELECT
  p.card_name,
  p.normalized_name,
  p.logical_rule_key,
  count(r.*) FILTER (WHERE r.logical_rule_key = p.logical_rule_key) AS promoted_rule_rows,
  count(r.*) FILTER (WHERE r.review_status = 'verified' AND r.execution_status = 'auto') AS promoted_verified_auto_rows,
  count(r.*) FILTER (WHERE r.oracle_hash = p.oracle_hash) AS promoted_oracle_hash_rows,
  (SELECT count(*) FROM manaloom_deploy_audit.pg556_dynamic_life_gain_new_server_dynam_20260706_065301) AS backup_rows
FROM proposed p
LEFT JOIN rule_rows r
  ON r.normalized_name = p.normalized_name
 AND r.logical_rule_key = p.logical_rule_key
 AND r.oracle_hash = p.oracle_hash
GROUP BY p.card_name, p.normalized_name, p.logical_rule_key, p.oracle_hash
ORDER BY p.card_name;
