WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('carnassid', 'Carnassid', '699fe7157aa3378c74a3c59eed9aab8e', 'battle_rule_v1:179814045bae871df353ee6d31391b37', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["G"],"activation_cost_generic":1,"activation_cost_mana":"{1}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["trample"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["G"],"activation_cost_generic":1,"activation_cost_mana":"{1}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","keywords":["trample"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","trample":true,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Carnassid translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('carrion wall', 'Carrion Wall', 'd69db5583813c1d819d05a2861b60c2e', 'battle_rule_v1:079adbefa754b2d64ae32275f927c83b', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["B"],"activation_cost_generic":1,"activation_cost_mana":"{1}{B}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["defender"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["B"],"activation_cost_generic":1,"activation_cost_mana":"{1}{B}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","defender":true,"duration":"until_end_of_turn","effect":"creature","keywords":["defender"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CarrionWall translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('charging troll', 'Charging Troll', '6dd43af5ee2687a33872ef3736467564', 'battle_rule_v1:65a4ed46a3b7e84ecbeaba69512298e5', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["G"],"activation_cost_generic":0,"activation_cost_mana":"{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["vigilance"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["G"],"activation_cost_generic":0,"activation_cost_mana":"{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","keywords":["vigilance"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","vigilance":true,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ChargingTroll translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('drudge reavers', 'Drudge Reavers', '9ec2f4e58bea3aaa9aea2bb345554640', 'battle_rule_v1:f07c9e5d5f469436999be45910f0c9c1', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["B"],"activation_cost_generic":0,"activation_cost_mana":"{B}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["flash"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["B"],"activation_cost_generic":0,"activation_cost_mana":"{B}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","flash":true,"keywords":["flash"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DrudgeReavers translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('fog of gnats', 'Fog of Gnats', '4dfddb21c900f052c40fccd1def8f559', 'battle_rule_v1:8dc91ea54b85b5b9be1c2af98f7a6266', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["B"],"activation_cost_generic":0,"activation_cost_mana":"{B}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["B"],"activation_cost_generic":0,"activation_cost_mana":"{B}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","flying":true,"keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class FogOfGnats translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('ghost ship', 'Ghost Ship', '1b47777d7febc1c85022b520adad3f2f', 'battle_rule_v1:27394cfee376cfd5deca3a0bfd27eaf0', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["U","U","U"],"activation_cost_generic":0,"activation_cost_mana":"{U}{U}{U}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["U","U","U"],"activation_cost_generic":0,"activation_cost_mana":"{U}{U}{U}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","flying":true,"keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GhostShip translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('lim-dûl''s high guard', 'Lim-Dûl''s High Guard', '0d859ac9292f64eb82869fb0e82a8383', 'battle_rule_v1:3d397a64ca07ff1e6eabd92d75df5cac', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["B"],"activation_cost_generic":1,"activation_cost_mana":"{1}{B}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["first_strike"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["B"],"activation_cost_generic":1,"activation_cost_mana":"{1}{B}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","first_strike":true,"keywords":["first_strike"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class LimDulsHighGuard translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('living airship', 'Living Airship', '39f2da1ca099d9202896a8ad9c7911f0', 'battle_rule_v1:702fe68fdd2d07dec233b6c79af2f3f9', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["G"],"activation_cost_generic":2,"activation_cost_mana":"{2}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["G"],"activation_cost_generic":2,"activation_cost_mana":"{2}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","flying":true,"keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class LivingAirship translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('living wall', 'Living Wall', '37ef5a7619401101813035c1199bc7fc', 'battle_rule_v1:14e8b02aaea3d5d7ad420aea917273d0', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["defender"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","defender":true,"duration":"until_end_of_turn","effect":"creature","keywords":["defender"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class LivingWall translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('malach of the dawn', 'Malach of the Dawn', '94b67a0b6820d2dfffb9e0f3b0584346', 'battle_rule_v1:5ed1a93b51ef173656111ba11b52d727', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["W","W","W"],"activation_cost_generic":0,"activation_cost_mana":"{W}{W}{W}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["W","W","W"],"activation_cost_generic":0,"activation_cost_mana":"{W}{W}{W}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","flying":true,"keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MalachOfTheDawn translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('manor skeleton', 'Manor Skeleton', 'f517fee9cf87ff964f796d01457c47ed', 'battle_rule_v1:205ff47143ba1ff90fd6a00863e34afd', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["B"],"activation_cost_generic":1,"activation_cost_mana":"{1}{B}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["haste"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["B"],"activation_cost_generic":1,"activation_cost_mana":"{1}{B}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","haste":true,"keywords":["haste"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ManorSkeleton translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('ranger en-vec', 'Ranger en-Vec', '928a7e5f05e741065ecd0147ca25515e', 'battle_rule_v1:5b2f1067d56d006fe814266adf19f63a', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["G"],"activation_cost_generic":0,"activation_cost_mana":"{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["first_strike"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["G"],"activation_cost_generic":0,"activation_cost_mana":"{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","first_strike":true,"keywords":["first_strike"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class RangerEnVec translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sanguine guard', 'Sanguine Guard', '0d859ac9292f64eb82869fb0e82a8383', 'battle_rule_v1:3d397a64ca07ff1e6eabd92d75df5cac', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["B"],"activation_cost_generic":1,"activation_cost_mana":"{1}{B}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["first_strike"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["B"],"activation_cost_generic":1,"activation_cost_mana":"{1}{B}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","first_strike":true,"keywords":["first_strike"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SanguineGuard translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('screeching harpy', 'Screeching Harpy', '615928f0965cc8a6326898a7d4dac35c', 'battle_rule_v1:fe19464168ddf9e77f4f2b85d626f5a4', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["B"],"activation_cost_generic":1,"activation_cost_mana":"{1}{B}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["B"],"activation_cost_generic":1,"activation_cost_mana":"{1}{B}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","flying":true,"keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ScreechingHarpy translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('tattered drake', 'Tattered Drake', '4dfddb21c900f052c40fccd1def8f559', 'battle_rule_v1:8dc91ea54b85b5b9be1c2af98f7a6266', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["B"],"activation_cost_generic":0,"activation_cost_mana":"{B}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["B"],"activation_cost_generic":0,"activation_cost_mana":"{B}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","flying":true,"keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TatteredDrake translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('trestle troll', 'Trestle Troll', '843aa7803a65f0f7f81b3c4b9032fddd', 'battle_rule_v1:1bc5b1ca6f9d03605c99f97bb76c46ce', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["B","G"],"activation_cost_generic":1,"activation_cost_mana":"{1}{B}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["reach","defender"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["B","G"],"activation_cost_generic":1,"activation_cost_mana":"{1}{B}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","defender":true,"duration":"until_end_of_turn","effect":"creature","keywords":["reach","defender"],"reach":true,"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TrestleTroll translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('wall of bone', 'Wall of Bone', '47ee68bc401b967512203d6a4a105dc2', 'battle_rule_v1:521607387ff17208c5a484c80e307caf', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["B"],"activation_cost_generic":0,"activation_cost_mana":"{B}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["defender"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["B"],"activation_cost_generic":0,"activation_cost_mana":"{B}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","defender":true,"duration":"until_end_of_turn","effect":"creature","keywords":["defender"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class WallOfBone translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('wall of brambles', 'Wall of Brambles', '784672448126c82a2d52260e1386b6b4', 'battle_rule_v1:35d9630c249fd1e8444bb8174b24dcec', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["G"],"activation_cost_generic":0,"activation_cost_mana":"{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["defender"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["G"],"activation_cost_generic":0,"activation_cost_mana":"{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","defender":true,"duration":"until_end_of_turn","effect":"creature","keywords":["defender"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class WallOfBrambles translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('wall of pine needles', 'Wall of Pine Needles', '784672448126c82a2d52260e1386b6b4', 'battle_rule_v1:35d9630c249fd1e8444bb8174b24dcec', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["G"],"activation_cost_generic":0,"activation_cost_mana":"{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["defender"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["G"],"activation_cost_generic":0,"activation_cost_mana":"{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","defender":true,"duration":"until_end_of_turn","effect":"creature","keywords":["defender"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class WallOfPineNeedles translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('will-o''-the-wisp', 'Will-o''-the-Wisp', '89d0206ac678583af3e690c430e22294', 'battle_rule_v1:8dc91ea54b85b5b9be1c2af98f7a6266', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["B"],"activation_cost_generic":0,"activation_cost_mana":"{B}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["B"],"activation_cost_generic":0,"activation_cost_mana":"{B}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","flying":true,"keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class WillOTheWisp translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('wolfir avenger', 'Wolfir Avenger', 'f6e3de5f4474d0535b67ab585b771f82', 'battle_rule_v1:d37f1c009e454a5c98089a7696fb068c', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["G"],"activation_cost_generic":1,"activation_cost_mana":"{1}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["flash"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["G"],"activation_cost_generic":1,"activation_cost_mana":"{1}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","flash":true,"keywords":["flash"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class WolfirAvenger translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('yavimaya gnats', 'Yavimaya Gnats', 'dd39d782432897a05c0204d495fe794a', 'battle_rule_v1:8bec7fa676cc9796220159d3c17d81d4', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["G"],"activation_cost_generic":0,"activation_cost_mana":"{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["G"],"activation_cost_generic":0,"activation_cost_mana":"{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","flying":true,"keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class YavimayaGnats translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
matched_cards AS (
  SELECT
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    c.id AS card_id,
    c.name AS db_card_name
  FROM proposed p
  LEFT JOIN public.cards c
    ON (
         lower(c.name) = p.normalized_name
         OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
       )
   AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
),
target_cards AS (
  SELECT
    normalized_name,
    card_name,
    oracle_hash,
    count(card_id) AS target_card_rows,
    min(card_id::text)::uuid AS canonical_card_id,
    min(db_card_name) AS canonical_card_name
  FROM matched_cards
  GROUP BY normalized_name, card_name, oracle_hash
),
rule_rows AS (
  SELECT p.normalized_name, count(r.*) AS existing_rule_rows
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
  GROUP BY p.normalized_name
),
expected_rows AS (
  SELECT p.normalized_name, count(r.*) AS expected_rule_rows_before
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key = p.logical_rule_key
  GROUP BY p.normalized_name
),
shadow_rows AS (
  SELECT p.normalized_name, count(r.*) AS would_deprecate_shadow_rows
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key <> p.logical_rule_key
   AND r.review_status NOT IN ('deprecated', 'rejected')
   AND r.execution_status <> 'disabled'
  GROUP BY p.normalized_name
)
SELECT
  p.card_name,
  p.normalized_name,
  p.oracle_hash,
  p.logical_rule_key,
  p.shadow_handling,
  tc.target_card_rows,
  tc.canonical_card_id,
  rr.existing_rule_rows,
  er.expected_rule_rows_before,
  sr.would_deprecate_shadow_rows
FROM proposed p
JOIN target_cards tc USING (normalized_name, card_name, oracle_hash)
JOIN rule_rows rr USING (normalized_name)
JOIN expected_rows er USING (normalized_name)
JOIN shadow_rows sr USING (normalized_name)
ORDER BY p.card_name;
