BEGIN;

CREATE SCHEMA IF NOT EXISTS manaloom_deploy_audit;

CREATE TABLE IF NOT EXISTS manaloom_deploy_audit.pg618_activated_target_keyword_sacrifice_20260707_134204 AS
SELECT *
FROM public.card_battle_rules
WHERE normalized_name IN ('need for speed', 'selfless savior', 'slobad, goblin tinkerer', 'torch courier', 'vial of poison')
   OR normalized_name LIKE 'need for speed // %'
   OR normalized_name LIKE 'selfless savior // %'
   OR normalized_name LIKE 'slobad, goblin tinkerer // %'
   OR normalized_name LIKE 'torch courier // %'
   OR normalized_name LIKE 'vial of poison // %';

DO $$
DECLARE
  v_missing jsonb;
BEGIN
  WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('need for speed', 'Need for Speed', '21118790c7f783fc315a70093f1f9211', 'battle_rule_v1:8d3778bc24beaf21b2df8efdd6a7ae12', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_sacrifice_target":true,"activation_requires_tap":false,"activation_sacrifice_target":"land","battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","granted_keywords_until_eot":["haste"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"HasteAbility"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_sacrifice_target":true,"activation_requires_tap":false,"activation_sacrifice_target":"land","battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"enchantment","granted_keywords_until_eot":["haste"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"HasteAbility"}'::jsonb, '{"category":"unknown","effect":"enchantment","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class NeedForSpeed translated into ManaLoom runtime scope xmage_permanent_simple_activated_target_keyword_until_eot_v1. This row is package-ready only because the source signature is a narrow permanent simple activated target-creature keyword until end of turn with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('selfless savior', 'Selfless Savior', '791dcd14252bbbcc229c9b551c2ffc55', 'battle_rule_v1:0ba5a40f8461aca65c44184ea3c6e6b9', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","granted_keywords_until_eot":["indestructible"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"],"exclude_source":true},"target_controller":"self","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"IndestructibleAbility"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"creature","granted_keywords_until_eot":["indestructible"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"],"exclude_source":true},"target_controller":"self","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"IndestructibleAbility"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SelflessSavior translated into ManaLoom runtime scope xmage_permanent_simple_activated_target_keyword_until_eot_v1. This row is package-ready only because the source signature is a narrow permanent simple activated target-creature keyword until end of turn with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('slobad, goblin tinkerer', 'Slobad, Goblin Tinkerer', 'a4aaf5f6c815fac2ba5a20bca4f9f859', 'battle_rule_v1:972bbc1b17f2eeb41d47b665441c2d34', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_sacrifice_target":true,"activation_requires_tap":false,"activation_sacrifice_target":"artifact","battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","granted_keywords_until_eot":["indestructible"],"power_delta":0,"target":"artifact","target_constraints":{"card_types":["artifact"]},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"IndestructibleAbility"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_sacrifice_target":true,"activation_requires_tap":false,"activation_sacrifice_target":"artifact","battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"creature","granted_keywords_until_eot":["indestructible"],"power_delta":0,"target":"artifact","target_constraints":{"card_types":["artifact"]},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"IndestructibleAbility"}'::jsonb, '{"category":"unknown","effect":"creature","target":"artifact"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SlobadGoblinTinkerer translated into ManaLoom runtime scope xmage_permanent_simple_activated_target_keyword_until_eot_v1. This row is package-ready only because the source signature is a narrow permanent simple activated target-creature keyword until end of turn with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('torch courier', 'Torch Courier', 'c55fbd0145c74143cacc79f7d230ae86', 'battle_rule_v1:e0e5aba2caf68cd499de1a6984bb9c0e', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","granted_keywords_until_eot":["haste"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"],"exclude_source":true},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"HasteAbility"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"creature","granted_keywords_until_eot":["haste"],"haste":true,"keywords":["haste"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"],"exclude_source":true},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"HasteAbility"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TorchCourier translated into ManaLoom runtime scope xmage_permanent_simple_activated_target_keyword_until_eot_v1. This row is package-ready only because the source signature is a narrow permanent simple activated target-creature keyword until end of turn with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('vial of poison', 'Vial of Poison', 'b54a117f2490816b8e3756470053af11', 'battle_rule_v1:ed2515b77291a88a4aa6e423cdc63305', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","granted_keywords_until_eot":["deathtouch"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"DeathtouchAbility"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"artifact","granted_keywords_until_eot":["deathtouch"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"DeathtouchAbility"}'::jsonb, '{"category":"unknown","effect":"artifact","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class VialOfPoison translated into ManaLoom runtime scope xmage_permanent_simple_activated_target_keyword_until_eot_v1. This row is package-ready only because the source signature is a narrow permanent simple activated target-creature keyword until end of turn with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
  counts AS (
    SELECT
      p.card_name,
      p.normalized_name,
      p.oracle_hash,
      count(c.id) AS target_card_rows,
      min(c.id::text)::uuid AS canonical_card_id
    FROM proposed p
    LEFT JOIN public.cards c
      ON (
           lower(c.name) = p.normalized_name
           OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
         )
     AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
    GROUP BY p.card_name, p.normalized_name, p.oracle_hash
  )
  SELECT jsonb_agg(counts ORDER BY card_name)
    INTO v_missing
  FROM counts
  WHERE target_card_rows < 1;

  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION 'XMage batch package abort: expected at least one Oracle-hash-matched card row for every proposed card: %', v_missing;
  END IF;
END $$;

WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('need for speed', 'Need for Speed', '21118790c7f783fc315a70093f1f9211', 'battle_rule_v1:8d3778bc24beaf21b2df8efdd6a7ae12', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_sacrifice_target":true,"activation_requires_tap":false,"activation_sacrifice_target":"land","battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","granted_keywords_until_eot":["haste"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"HasteAbility"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_sacrifice_target":true,"activation_requires_tap":false,"activation_sacrifice_target":"land","battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"enchantment","granted_keywords_until_eot":["haste"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"HasteAbility"}'::jsonb, '{"category":"unknown","effect":"enchantment","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class NeedForSpeed translated into ManaLoom runtime scope xmage_permanent_simple_activated_target_keyword_until_eot_v1. This row is package-ready only because the source signature is a narrow permanent simple activated target-creature keyword until end of turn with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('selfless savior', 'Selfless Savior', '791dcd14252bbbcc229c9b551c2ffc55', 'battle_rule_v1:0ba5a40f8461aca65c44184ea3c6e6b9', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","granted_keywords_until_eot":["indestructible"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"],"exclude_source":true},"target_controller":"self","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"IndestructibleAbility"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"creature","granted_keywords_until_eot":["indestructible"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"],"exclude_source":true},"target_controller":"self","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"IndestructibleAbility"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SelflessSavior translated into ManaLoom runtime scope xmage_permanent_simple_activated_target_keyword_until_eot_v1. This row is package-ready only because the source signature is a narrow permanent simple activated target-creature keyword until end of turn with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('slobad, goblin tinkerer', 'Slobad, Goblin Tinkerer', 'a4aaf5f6c815fac2ba5a20bca4f9f859', 'battle_rule_v1:972bbc1b17f2eeb41d47b665441c2d34', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_sacrifice_target":true,"activation_requires_tap":false,"activation_sacrifice_target":"artifact","battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","granted_keywords_until_eot":["indestructible"],"power_delta":0,"target":"artifact","target_constraints":{"card_types":["artifact"]},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"IndestructibleAbility"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_sacrifice_target":true,"activation_requires_tap":false,"activation_sacrifice_target":"artifact","battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"creature","granted_keywords_until_eot":["indestructible"],"power_delta":0,"target":"artifact","target_constraints":{"card_types":["artifact"]},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"IndestructibleAbility"}'::jsonb, '{"category":"unknown","effect":"creature","target":"artifact"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SlobadGoblinTinkerer translated into ManaLoom runtime scope xmage_permanent_simple_activated_target_keyword_until_eot_v1. This row is package-ready only because the source signature is a narrow permanent simple activated target-creature keyword until end of turn with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('torch courier', 'Torch Courier', 'c55fbd0145c74143cacc79f7d230ae86', 'battle_rule_v1:e0e5aba2caf68cd499de1a6984bb9c0e', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","granted_keywords_until_eot":["haste"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"],"exclude_source":true},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"HasteAbility"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"creature","granted_keywords_until_eot":["haste"],"haste":true,"keywords":["haste"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"],"exclude_source":true},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"HasteAbility"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TorchCourier translated into ManaLoom runtime scope xmage_permanent_simple_activated_target_keyword_until_eot_v1. This row is package-ready only because the source signature is a narrow permanent simple activated target-creature keyword until end of turn with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('vial of poison', 'Vial of Poison', 'b54a117f2490816b8e3756470053af11', 'battle_rule_v1:ed2515b77291a88a4aa6e423cdc63305', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","granted_keywords_until_eot":["deathtouch"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"DeathtouchAbility"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"artifact","granted_keywords_until_eot":["deathtouch"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"DeathtouchAbility"}'::jsonb, '{"category":"unknown","effect":"artifact","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class VialOfPoison translated into ManaLoom runtime scope xmage_permanent_simple_activated_target_keyword_until_eot_v1. This row is package-ready only because the source signature is a narrow permanent simple activated target-creature keyword until end of turn with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
deprecated AS (
  UPDATE public.card_battle_rules r
  SET
    review_status = 'deprecated',
    execution_status = 'disabled',
    updated_at = now(),
    notes = concat_ws(E'\n', nullif(r.notes, ''), 'XMage batch package: deprecated stale shadow before curated batch rule upsert.')
  FROM proposed p
  WHERE (
        r.normalized_name = p.normalized_name
        OR r.normalized_name LIKE p.normalized_name || ' // %'
      )
    AND p.shadow_handling <> 'preserve_existing_rows'
    AND r.logical_rule_key <> p.logical_rule_key
  RETURNING r.*
)
SELECT count(*) AS deprecated_shadow_rows FROM deprecated;

WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('need for speed', 'Need for Speed', '21118790c7f783fc315a70093f1f9211', 'battle_rule_v1:8d3778bc24beaf21b2df8efdd6a7ae12', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_sacrifice_target":true,"activation_requires_tap":false,"activation_sacrifice_target":"land","battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","granted_keywords_until_eot":["haste"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"HasteAbility"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_sacrifice_target":true,"activation_requires_tap":false,"activation_sacrifice_target":"land","battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"enchantment","granted_keywords_until_eot":["haste"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"HasteAbility"}'::jsonb, '{"category":"unknown","effect":"enchantment","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class NeedForSpeed translated into ManaLoom runtime scope xmage_permanent_simple_activated_target_keyword_until_eot_v1. This row is package-ready only because the source signature is a narrow permanent simple activated target-creature keyword until end of turn with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('selfless savior', 'Selfless Savior', '791dcd14252bbbcc229c9b551c2ffc55', 'battle_rule_v1:0ba5a40f8461aca65c44184ea3c6e6b9', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","granted_keywords_until_eot":["indestructible"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"],"exclude_source":true},"target_controller":"self","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"IndestructibleAbility"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"creature","granted_keywords_until_eot":["indestructible"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"],"exclude_source":true},"target_controller":"self","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"IndestructibleAbility"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SelflessSavior translated into ManaLoom runtime scope xmage_permanent_simple_activated_target_keyword_until_eot_v1. This row is package-ready only because the source signature is a narrow permanent simple activated target-creature keyword until end of turn with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('slobad, goblin tinkerer', 'Slobad, Goblin Tinkerer', 'a4aaf5f6c815fac2ba5a20bca4f9f859', 'battle_rule_v1:972bbc1b17f2eeb41d47b665441c2d34', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_sacrifice_target":true,"activation_requires_tap":false,"activation_sacrifice_target":"artifact","battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","granted_keywords_until_eot":["indestructible"],"power_delta":0,"target":"artifact","target_constraints":{"card_types":["artifact"]},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"IndestructibleAbility"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_sacrifice_target":true,"activation_requires_tap":false,"activation_sacrifice_target":"artifact","battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"creature","granted_keywords_until_eot":["indestructible"],"power_delta":0,"target":"artifact","target_constraints":{"card_types":["artifact"]},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"IndestructibleAbility"}'::jsonb, '{"category":"unknown","effect":"creature","target":"artifact"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SlobadGoblinTinkerer translated into ManaLoom runtime scope xmage_permanent_simple_activated_target_keyword_until_eot_v1. This row is package-ready only because the source signature is a narrow permanent simple activated target-creature keyword until end of turn with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('torch courier', 'Torch Courier', 'c55fbd0145c74143cacc79f7d230ae86', 'battle_rule_v1:e0e5aba2caf68cd499de1a6984bb9c0e', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","granted_keywords_until_eot":["haste"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"],"exclude_source":true},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"HasteAbility"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"creature","granted_keywords_until_eot":["haste"],"haste":true,"keywords":["haste"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"],"exclude_source":true},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"HasteAbility"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TorchCourier translated into ManaLoom runtime scope xmage_permanent_simple_activated_target_keyword_until_eot_v1. This row is package-ready only because the source signature is a narrow permanent simple activated target-creature keyword until end of turn with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('vial of poison', 'Vial of Poison', 'b54a117f2490816b8e3756470053af11', 'battle_rule_v1:ed2515b77291a88a4aa6e423cdc63305', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","granted_keywords_until_eot":["deathtouch"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"DeathtouchAbility"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"artifact","granted_keywords_until_eot":["deathtouch"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"DeathtouchAbility"}'::jsonb, '{"category":"unknown","effect":"artifact","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class VialOfPoison translated into ManaLoom runtime scope xmage_permanent_simple_activated_target_keyword_until_eot_v1. This row is package-ready only because the source signature is a narrow permanent simple activated target-creature keyword until end of turn with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
matched_cards AS (
  SELECT
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    c.id AS card_id,
    c.name AS db_card_name
  FROM proposed p
  JOIN public.cards c
    ON (
         lower(c.name) = p.normalized_name
         OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
       )
   AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
),
canonical_target_cards AS (
  SELECT
    p.*,
    min(m.card_id::text)::uuid AS card_id,
    min(m.db_card_name) AS db_card_name
  FROM proposed p
  JOIN matched_cards m
    USING (normalized_name, card_name, oracle_hash)
  GROUP BY
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    p.logical_rule_key,
    p.effect_json,
    p.deck_role_json,
    p.source,
    p.confidence,
    p.review_status,
    p.execution_status,
    p.notes,
    p.shadow_handling
),
upserted AS (
  INSERT INTO public.card_battle_rules (
    normalized_name,
    card_id,
    card_name,
    effect_json,
    deck_role_json,
    source,
    confidence,
    review_status,
    rule_version,
    oracle_hash,
    notes,
    reviewed_by,
    reviewed_at,
    created_at,
    updated_at,
    last_seen_at,
    logical_rule_key,
    execution_status
  )
  SELECT
    normalized_name,
    card_id,
    db_card_name,
    effect_json,
    deck_role_json,
    source,
    confidence,
    review_status,
    2,
    oracle_hash,
    notes,
    'codex-xmage-batch',
    now(),
    now(),
    now(),
    now(),
    logical_rule_key,
    execution_status
  FROM canonical_target_cards
  ON CONFLICT (normalized_name, logical_rule_key) DO UPDATE
  SET
    card_id = EXCLUDED.card_id,
    card_name = EXCLUDED.card_name,
    effect_json = EXCLUDED.effect_json,
    deck_role_json = EXCLUDED.deck_role_json,
    source = EXCLUDED.source,
    confidence = EXCLUDED.confidence,
    review_status = EXCLUDED.review_status,
    rule_version = EXCLUDED.rule_version,
    oracle_hash = EXCLUDED.oracle_hash,
    notes = EXCLUDED.notes,
    reviewed_by = EXCLUDED.reviewed_by,
    reviewed_at = EXCLUDED.reviewed_at,
    updated_at = EXCLUDED.updated_at,
    last_seen_at = EXCLUDED.last_seen_at,
    execution_status = EXCLUDED.execution_status
  RETURNING *
)
SELECT count(*) AS upserted_rows FROM upserted;

COMMIT;
