WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('bile-vial boggart', 'Bile-Vial Boggart', '765f9a0c55872371d4e69b2dea91632d', 'battle_rule_v1:d99ef6cb26e7f6879ee8558b6b1f24c6', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_add_counters_target_creature_v1","count":1,"counter_count":1,"counter_type":"-1/-1","dies_add_counters":true,"dies_add_counters_count":1,"dies_add_counters_counter_type":"-1/-1","dies_add_counters_target":"creature","effect":"creature","instant":false,"sorcery":false,"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","target_count_max":1,"target_count_min":0,"trigger":"dies","trigger_effect":"add_counters","up_to_count":true,"xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"AddCountersTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BileVialBoggart translated into ManaLoom runtime scope xmage_creature_dies_add_counters_target_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('festering mummy', 'Festering Mummy', '9e47de100c190411c8e30156312a120c', 'battle_rule_v1:500f0abd244b5b94191c9b4ff1243b01', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_add_counters_target_creature_v1","count":1,"counter_count":1,"counter_type":"-1/-1","dies_add_counters":true,"dies_add_counters_count":1,"dies_add_counters_counter_type":"-1/-1","dies_add_counters_optional":true,"dies_add_counters_target":"creature","effect":"creature","instant":false,"optional":true,"sorcery":false,"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","trigger":"dies","trigger_effect":"add_counters","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"AddCountersTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class FesteringMummy translated into ManaLoom runtime scope xmage_creature_dies_add_counters_target_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('goblin assault team', 'Goblin Assault Team', '599e24538eeab1caa1dea482843a1802', 'battle_rule_v1:fdc0ed4e42df19e95b8f2b81f30c3963', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_add_counters_target_creature_v1","count":1,"counter_count":1,"counter_type":"+1/+1","dies_add_counters":true,"dies_add_counters_count":1,"dies_add_counters_counter_type":"+1/+1","dies_add_counters_target":"creature","effect":"creature","instant":false,"keywords":["haste"],"sorcery":false,"target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"self"},"target_controller":"self","trigger":"dies","trigger_effect":"add_counters","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"AddCountersTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GoblinAssaultTeam translated into ManaLoom runtime scope xmage_creature_dies_add_counters_target_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('guul draz mucklord', 'Guul Draz Mucklord', 'b2cf73bf78e0e5a7cd750ad498f2773e', 'battle_rule_v1:dc6d9eeb7537ceb1ad4b8351b1af12d8', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_add_counters_target_creature_v1","count":1,"counter_count":1,"counter_type":"+1/+1","dies_add_counters":true,"dies_add_counters_count":1,"dies_add_counters_counter_type":"+1/+1","dies_add_counters_target":"creature","effect":"creature","instant":false,"sorcery":false,"target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"self"},"target_controller":"self","trigger":"dies","trigger_effect":"add_counters","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"AddCountersTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GuulDrazMucklord translated into ManaLoom runtime scope xmage_creature_dies_add_counters_target_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('lawless broker', 'Lawless Broker', 'b2cf73bf78e0e5a7cd750ad498f2773e', 'battle_rule_v1:dc6d9eeb7537ceb1ad4b8351b1af12d8', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_add_counters_target_creature_v1","count":1,"counter_count":1,"counter_type":"+1/+1","dies_add_counters":true,"dies_add_counters_count":1,"dies_add_counters_counter_type":"+1/+1","dies_add_counters_target":"creature","effect":"creature","instant":false,"sorcery":false,"target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"self"},"target_controller":"self","trigger":"dies","trigger_effect":"add_counters","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"AddCountersTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class LawlessBroker translated into ManaLoom runtime scope xmage_creature_dies_add_counters_target_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sparring construct', 'Sparring Construct', 'b2cf73bf78e0e5a7cd750ad498f2773e', 'battle_rule_v1:dc6d9eeb7537ceb1ad4b8351b1af12d8', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_add_counters_target_creature_v1","count":1,"counter_count":1,"counter_type":"+1/+1","dies_add_counters":true,"dies_add_counters_count":1,"dies_add_counters_counter_type":"+1/+1","dies_add_counters_target":"creature","effect":"creature","instant":false,"sorcery":false,"target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"self"},"target_controller":"self","trigger":"dies","trigger_effect":"add_counters","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"AddCountersTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SparringConstruct translated into ManaLoom runtime scope xmage_creature_dies_add_counters_target_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('spinal centipede', 'Spinal Centipede', 'b2cf73bf78e0e5a7cd750ad498f2773e', 'battle_rule_v1:dc6d9eeb7537ceb1ad4b8351b1af12d8', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_add_counters_target_creature_v1","count":1,"counter_count":1,"counter_type":"+1/+1","dies_add_counters":true,"dies_add_counters_count":1,"dies_add_counters_counter_type":"+1/+1","dies_add_counters_target":"creature","effect":"creature","instant":false,"sorcery":false,"target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"self"},"target_controller":"self","trigger":"dies","trigger_effect":"add_counters","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"AddCountersTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SpinalCentipede translated into ManaLoom runtime scope xmage_creature_dies_add_counters_target_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('steadfast sentry', 'Steadfast Sentry', '5bd444489d885eeb73b0aec7c7f0609f', 'battle_rule_v1:741a080f18b880224c645da9fc305da1', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_add_counters_target_creature_v1","count":1,"counter_count":1,"counter_type":"+1/+1","dies_add_counters":true,"dies_add_counters_count":1,"dies_add_counters_counter_type":"+1/+1","dies_add_counters_target":"creature","effect":"creature","instant":false,"keywords":["vigilance"],"sorcery":false,"target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"self"},"target_controller":"self","trigger":"dies","trigger_effect":"add_counters","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"AddCountersTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SteadfastSentry translated into ManaLoom runtime scope xmage_creature_dies_add_counters_target_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('venerable knight', 'Venerable Knight', '27c7ab08136b9ceb9eca7963462af6c6', 'battle_rule_v1:44c3f8f7e38bf65029e832f0b8195111', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_dies_add_counters_target_creature_v1","count":1,"counter_count":1,"counter_type":"+1/+1","dies_add_counters":true,"dies_add_counters_count":1,"dies_add_counters_counter_type":"+1/+1","dies_add_counters_target":"creature","effect":"creature","instant":false,"sorcery":false,"target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"self","required_subtypes":["knight"]},"target_controller":"self","trigger":"dies","trigger_effect":"add_counters","xmage_ability_class":"DiesSourceTriggeredAbility","xmage_effect_class":"AddCountersTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class VenerableKnight translated into ManaLoom runtime scope xmage_creature_dies_add_counters_target_creature_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
rule_rows AS (
  SELECT
    r.normalized_name,
    r.logical_rule_key,
    r.oracle_hash,
    r.review_status,
    r.execution_status
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key = p.logical_rule_key
)
SELECT
  p.card_name,
  p.normalized_name,
  p.logical_rule_key,
  count(r.*) FILTER (WHERE r.logical_rule_key = p.logical_rule_key) AS promoted_rule_rows,
  count(r.*) FILTER (WHERE r.review_status = 'verified' AND r.execution_status = 'auto') AS promoted_verified_auto_rows,
  count(r.*) FILTER (WHERE r.oracle_hash = p.oracle_hash) AS promoted_oracle_hash_rows,
  (SELECT count(*) FROM manaloom_deploy_audit.pg711_dies_add_counters_new_server_20260710_172518) AS backup_rows
FROM proposed p
LEFT JOIN rule_rows r
  ON r.normalized_name = p.normalized_name
 AND r.logical_rule_key = p.logical_rule_key
 AND r.oracle_hash = p.oracle_hash
GROUP BY p.card_name, p.normalized_name, p.logical_rule_key, p.oracle_hash
ORDER BY p.card_name;
