BEGIN;

CREATE SCHEMA IF NOT EXISTS manaloom_deploy_audit;

CREATE TABLE IF NOT EXISTS manaloom_deploy_audit.pg722_regenerate_costs_new_server_regene_20260710_212650 AS
SELECT *
FROM public.card_battle_rules
WHERE normalized_name IN ('centaur veteran', 'deepwood ghoul', 'marrow bats', 'mischievous poltergeist', 'sentry of the underworld', 'tunneler wurm')
   OR normalized_name LIKE 'centaur veteran // %'
   OR normalized_name LIKE 'deepwood ghoul // %'
   OR normalized_name LIKE 'marrow bats // %'
   OR normalized_name LIKE 'mischievous poltergeist // %'
   OR normalized_name LIKE 'sentry of the underworld // %'
   OR normalized_name LIKE 'tunneler wurm // %';

DO $$
DECLARE
  v_missing jsonb;
BEGIN
  WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('centaur veteran', 'Centaur Veteran', 'a7c2878030bdc99b3d0aa9d6194122da', 'battle_rule_v1:e35f3ce9a67c2de7b719f5ea094632a7', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["G"],"activation_cost_generic":0,"activation_cost_mana":"{G}","activation_discard_count":1,"activation_discard_target":"any_card","activation_requires_discard_card":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["trample"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["G"],"activation_cost_generic":0,"activation_cost_mana":"{G}","activation_discard_count":1,"activation_discard_target":"any_card","activation_requires_discard_card":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","keywords":["trample"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","trample":true,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CentaurVeteran translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('deepwood ghoul', 'Deepwood Ghoul', 'b0b618643b86c0988608c4bd63abb49e', 'battle_rule_v1:29b27ad949f2a0feccff92ec8a36370f', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_life_cost":2,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_life_cost":2,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DeepwoodGhoul translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('marrow bats', 'Marrow Bats', '13915d0190c111ada0a320e33aa8255d', 'battle_rule_v1:627a532a5466d2e059212b0f09f07d2e', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_life_cost":4,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_life_cost":4,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","flying":true,"keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MarrowBats translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('mischievous poltergeist', 'Mischievous Poltergeist', '1d4c28511b92b358353a30f5ed2ea864', 'battle_rule_v1:16334bd23c8bf65025cc0e18abb544f8', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_life_cost":1,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_life_cost":1,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","flying":true,"keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MischievousPoltergeist translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sentry of the underworld', 'Sentry of the Underworld', '73a705cab53339dede31c0ca712cfeb2', 'battle_rule_v1:9de50b65fd645a62bc46d4c369b84c4d', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["W","B"],"activation_cost_generic":0,"activation_cost_mana":"{W}{B}","activation_life_cost":3,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["flying","vigilance"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["W","B"],"activation_cost_generic":0,"activation_cost_mana":"{W}{B}","activation_life_cost":3,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","flying":true,"keywords":["flying","vigilance"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","vigilance":true,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SentryOfTheUnderworld translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('tunneler wurm', 'Tunneler Wurm', 'bf60dc8ee6f3fc31a5d4a40b014a65fa', 'battle_rule_v1:6eff9f19b181732abd0a6c4d6d1d0069', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_discard_count":1,"activation_discard_target":"any_card","activation_requires_discard_card":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_discard_count":1,"activation_discard_target":"any_card","activation_requires_discard_card":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TunnelerWurm translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
  counts AS (
    SELECT
      p.card_name,
      p.normalized_name,
      p.oracle_hash,
      count(c.id) AS target_card_rows,
      min(c.id::text)::uuid AS canonical_card_id
    FROM proposed p
    LEFT JOIN public.cards c
      ON (
           lower(c.name) = p.normalized_name
           OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
         )
     AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
    GROUP BY p.card_name, p.normalized_name, p.oracle_hash
  )
  SELECT jsonb_agg(counts ORDER BY card_name)
    INTO v_missing
  FROM counts
  WHERE target_card_rows < 1;

  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION 'XMage batch package abort: expected at least one Oracle-hash-matched card row for every proposed card: %', v_missing;
  END IF;
END $$;

WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('centaur veteran', 'Centaur Veteran', 'a7c2878030bdc99b3d0aa9d6194122da', 'battle_rule_v1:e35f3ce9a67c2de7b719f5ea094632a7', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["G"],"activation_cost_generic":0,"activation_cost_mana":"{G}","activation_discard_count":1,"activation_discard_target":"any_card","activation_requires_discard_card":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["trample"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["G"],"activation_cost_generic":0,"activation_cost_mana":"{G}","activation_discard_count":1,"activation_discard_target":"any_card","activation_requires_discard_card":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","keywords":["trample"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","trample":true,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CentaurVeteran translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('deepwood ghoul', 'Deepwood Ghoul', 'b0b618643b86c0988608c4bd63abb49e', 'battle_rule_v1:29b27ad949f2a0feccff92ec8a36370f', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_life_cost":2,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_life_cost":2,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DeepwoodGhoul translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('marrow bats', 'Marrow Bats', '13915d0190c111ada0a320e33aa8255d', 'battle_rule_v1:627a532a5466d2e059212b0f09f07d2e', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_life_cost":4,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_life_cost":4,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","flying":true,"keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MarrowBats translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('mischievous poltergeist', 'Mischievous Poltergeist', '1d4c28511b92b358353a30f5ed2ea864', 'battle_rule_v1:16334bd23c8bf65025cc0e18abb544f8', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_life_cost":1,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_life_cost":1,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","flying":true,"keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MischievousPoltergeist translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sentry of the underworld', 'Sentry of the Underworld', '73a705cab53339dede31c0ca712cfeb2', 'battle_rule_v1:9de50b65fd645a62bc46d4c369b84c4d', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["W","B"],"activation_cost_generic":0,"activation_cost_mana":"{W}{B}","activation_life_cost":3,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["flying","vigilance"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["W","B"],"activation_cost_generic":0,"activation_cost_mana":"{W}{B}","activation_life_cost":3,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","flying":true,"keywords":["flying","vigilance"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","vigilance":true,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SentryOfTheUnderworld translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('tunneler wurm', 'Tunneler Wurm', 'bf60dc8ee6f3fc31a5d4a40b014a65fa', 'battle_rule_v1:6eff9f19b181732abd0a6c4d6d1d0069', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_discard_count":1,"activation_discard_target":"any_card","activation_requires_discard_card":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_discard_count":1,"activation_discard_target":"any_card","activation_requires_discard_card":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TunnelerWurm translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
deprecated AS (
  UPDATE public.card_battle_rules r
  SET
    review_status = 'deprecated',
    execution_status = 'disabled',
    updated_at = now(),
    notes = concat_ws(E'\n', nullif(r.notes, ''), 'XMage batch package: deprecated stale shadow before curated batch rule upsert.')
  FROM proposed p
  WHERE (
        r.normalized_name = p.normalized_name
        OR r.normalized_name LIKE p.normalized_name || ' // %'
      )
    AND p.shadow_handling <> 'preserve_existing_rows'
    AND r.logical_rule_key <> p.logical_rule_key
  RETURNING r.*
)
SELECT count(*) AS deprecated_shadow_rows FROM deprecated;

WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('centaur veteran', 'Centaur Veteran', 'a7c2878030bdc99b3d0aa9d6194122da', 'battle_rule_v1:e35f3ce9a67c2de7b719f5ea094632a7', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["G"],"activation_cost_generic":0,"activation_cost_mana":"{G}","activation_discard_count":1,"activation_discard_target":"any_card","activation_requires_discard_card":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["trample"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["G"],"activation_cost_generic":0,"activation_cost_mana":"{G}","activation_discard_count":1,"activation_discard_target":"any_card","activation_requires_discard_card":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","keywords":["trample"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","trample":true,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CentaurVeteran translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('deepwood ghoul', 'Deepwood Ghoul', 'b0b618643b86c0988608c4bd63abb49e', 'battle_rule_v1:29b27ad949f2a0feccff92ec8a36370f', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_life_cost":2,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_life_cost":2,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DeepwoodGhoul translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('marrow bats', 'Marrow Bats', '13915d0190c111ada0a320e33aa8255d', 'battle_rule_v1:627a532a5466d2e059212b0f09f07d2e', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_life_cost":4,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_life_cost":4,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","flying":true,"keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MarrowBats translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('mischievous poltergeist', 'Mischievous Poltergeist', '1d4c28511b92b358353a30f5ed2ea864', 'battle_rule_v1:16334bd23c8bf65025cc0e18abb544f8', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_life_cost":1,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_life_cost":1,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","flying":true,"keywords":["flying"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MischievousPoltergeist translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sentry of the underworld', 'Sentry of the Underworld', '73a705cab53339dede31c0ca712cfeb2', 'battle_rule_v1:9de50b65fd645a62bc46d4c369b84c4d', '{"_activated_rule_effects":[{"_keywords_are_self":true,"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":["W","B"],"activation_cost_generic":0,"activation_cost_mana":"{W}{B}","activation_life_cost":3,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","keywords":["flying","vigilance"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":["W","B"],"activation_cost_generic":0,"activation_cost_mana":"{W}{B}","activation_life_cost":3,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","flying":true,"keywords":["flying","vigilance"],"regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","vigilance":true,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SentryOfTheUnderworld translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('tunneler wurm', 'Tunneler Wurm', 'bf60dc8ee6f3fc31a5d4a40b014a65fa', 'battle_rule_v1:6eff9f19b181732abd0a6c4d6d1d0069', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_discard_count":1,"activation_discard_target":"any_card","activation_requires_discard_card":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_discard_count":1,"activation_discard_target":"any_card","activation_requires_discard_card":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TunnelerWurm translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
matched_cards AS (
  SELECT
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    c.id AS card_id,
    c.name AS db_card_name
  FROM proposed p
  JOIN public.cards c
    ON (
         lower(c.name) = p.normalized_name
         OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
       )
   AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
),
canonical_target_cards AS (
  SELECT
    p.*,
    min(m.card_id::text)::uuid AS card_id,
    min(m.db_card_name) AS db_card_name
  FROM proposed p
  JOIN matched_cards m
    USING (normalized_name, card_name, oracle_hash)
  GROUP BY
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    p.logical_rule_key,
    p.effect_json,
    p.deck_role_json,
    p.source,
    p.confidence,
    p.review_status,
    p.execution_status,
    p.notes,
    p.shadow_handling
),
upserted AS (
  INSERT INTO public.card_battle_rules (
    normalized_name,
    card_id,
    card_name,
    effect_json,
    deck_role_json,
    source,
    confidence,
    review_status,
    rule_version,
    oracle_hash,
    notes,
    reviewed_by,
    reviewed_at,
    created_at,
    updated_at,
    last_seen_at,
    logical_rule_key,
    execution_status
  )
  SELECT
    normalized_name,
    card_id,
    db_card_name,
    effect_json,
    deck_role_json,
    source,
    confidence,
    review_status,
    2,
    oracle_hash,
    notes,
    'codex-xmage-batch',
    now(),
    now(),
    now(),
    now(),
    logical_rule_key,
    execution_status
  FROM canonical_target_cards
  ON CONFLICT (normalized_name, logical_rule_key) DO UPDATE
  SET
    card_id = EXCLUDED.card_id,
    card_name = EXCLUDED.card_name,
    effect_json = EXCLUDED.effect_json,
    deck_role_json = EXCLUDED.deck_role_json,
    source = EXCLUDED.source,
    confidence = EXCLUDED.confidence,
    review_status = EXCLUDED.review_status,
    rule_version = EXCLUDED.rule_version,
    oracle_hash = EXCLUDED.oracle_hash,
    notes = EXCLUDED.notes,
    reviewed_by = EXCLUDED.reviewed_by,
    reviewed_at = EXCLUDED.reviewed_at,
    updated_at = EXCLUDED.updated_at,
    last_seen_at = EXCLUDED.last_seen_at,
    execution_status = EXCLUDED.execution_status
  RETURNING *
)
SELECT count(*) AS upserted_rows FROM upserted;

COMMIT;
