WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('boreal centaur', 'Boreal Centaur', '0d85161f5d85617376172e7b9388f9d8', 'battle_rule_v1:02a48f6b6210f2f163ea06b2211c492b', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"self_stat_modifier_until_eot","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{S}","activation_limit_per_turn":1,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","power_boost":1,"power_delta":1,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","toughness_boost":1,"toughness_delta":1,"xmage_ability_class":"LimitedTimesPerTurnActivatedAbility","xmage_effect_class":"BoostSourceEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","activated_effect":"self_stat_modifier_until_eot","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{S}","activation_limit_per_turn":1,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","duration":"until_end_of_turn","effect":"creature","power_boost":1,"power_delta":1,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","toughness_boost":1,"toughness_delta":1,"xmage_ability_class":"LimitedTimesPerTurnActivatedAbility","xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BorealCentaur translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_boost_until_eot_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('chilling shade', 'Chilling Shade', 'cf55d26890ad6eae036169cabfecdb73', 'battle_rule_v1:e1ecd4c903fe9b698d82dd63178ce2f6', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"self_stat_modifier_until_eot","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{S}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","power_boost":1,"power_delta":1,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","toughness_boost":1,"toughness_delta":1,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"BoostSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","activated_effect":"self_stat_modifier_until_eot","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{S}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","duration":"until_end_of_turn","effect":"creature","flying":true,"keywords":["flying"],"power_boost":1,"power_delta":1,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","toughness_boost":1,"toughness_delta":1,"xmage_ability_class":"SimpleActivatedAbility","xmage_auxiliary_static_keywords":["flying"],"xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ChillingShade translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_boost_until_eot_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('frostwalla', 'Frostwalla', '8d357dd6b36767622bc4f7066d2520e5', 'battle_rule_v1:c8c6061b2f682b3b82a0c3438c1e42dd', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"self_stat_modifier_until_eot","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{S}","activation_limit_per_turn":1,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","power_boost":2,"power_delta":2,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","toughness_boost":2,"toughness_delta":2,"xmage_ability_class":"LimitedTimesPerTurnActivatedAbility","xmage_effect_class":"BoostSourceEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","activated_effect":"self_stat_modifier_until_eot","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{S}","activation_limit_per_turn":1,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","duration":"until_end_of_turn","effect":"creature","power_boost":2,"power_delta":2,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","toughness_boost":2,"toughness_delta":2,"xmage_ability_class":"LimitedTimesPerTurnActivatedAbility","xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Frostwalla translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_boost_until_eot_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('hailstorm valkyrie', 'Hailstorm Valkyrie', 'e3311bed8aaf234a8a1134c1ba137180', 'battle_rule_v1:6dcf5eec7c2c0b9d2d939822373d31d2', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"self_stat_modifier_until_eot","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{S}{S}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","power_boost":2,"power_delta":2,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","toughness_boost":2,"toughness_delta":2,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"BoostSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","activated_effect":"self_stat_modifier_until_eot","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{S}{S}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","duration":"until_end_of_turn","effect":"creature","flying":true,"keywords":["flying","trample"],"power_boost":2,"power_delta":2,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","toughness_boost":2,"toughness_delta":2,"trample":true,"xmage_ability_class":"SimpleActivatedAbility","xmage_auxiliary_static_keywords":["flying","trample"],"xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HailstormValkyrie translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_boost_until_eot_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('icebind pillar', 'Icebind Pillar', 'dead9de1f7d08e0a6faeed89ef07fa21', 'battle_rule_v1:67e86633d7e4744a4bbd1ffad3ad6c64', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"artifact_or_creature","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{S}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"artifact_or_creature","target_constraints":{"card_types":["artifact","creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"artifact_or_creature","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{S}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"artifact","target":"artifact_or_creature","target_constraints":{"card_types":["artifact","creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"artifact","target":"artifact_or_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class IcebindPillar translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('immolating souleater', 'Immolating Souleater', '381c3c47e8eec9a931c2b896ae268518', 'battle_rule_v1:60e469d68d57d8baf9668def2cd7fe53', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"self_stat_modifier_until_eot","activation_cost_colors":["R/P"],"activation_cost_generic":0,"activation_cost_mana":"{R/P}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","power_boost":1,"power_delta":1,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","toughness_boost":0,"toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"BoostSourceEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","activated_effect":"self_stat_modifier_until_eot","activation_cost_colors":["R/P"],"activation_cost_generic":0,"activation_cost_mana":"{R/P}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","duration":"until_end_of_turn","effect":"creature","power_boost":1,"power_delta":1,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","toughness_boost":0,"toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ImmolatingSouleater translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_boost_until_eot_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('ohran yeti', 'Ohran Yeti', 'aa8d44e2d406084258033b50c28705a4', 'battle_rule_v1:a6b16a7a680bb1ea43bd8397321573c6', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":3,"activation_cost_mana":"{2}{S}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","granted_keywords_until_eot":["first_strike"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"],"required_supertypes":["snow"]},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"FirstStrikeAbility"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","activated_effect":"target_keyword_until_eot","activation_cost_colors":[],"activation_cost_generic":3,"activation_cost_mana":"{2}{S}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_target_keyword_until_eot_v1","duration":"until_end_of_turn","effect":"creature","granted_keywords_until_eot":["first_strike"],"power_delta":0,"target":"creature","target_constraints":{"card_types":["creature"],"required_supertypes":["snow"]},"target_controller":"any","toughness_delta":0,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"GainAbilityTargetEffect","xmage_keyword_ability_class":"FirstStrikeAbility"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class OhranYeti translated into ManaLoom runtime scope xmage_permanent_simple_activated_target_keyword_until_eot_v1. This row is package-ready only because the source signature is a narrow permanent simple activated target-creature keyword until end of turn with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('phyrexian battleflies', 'Phyrexian Battleflies', 'a3d395a2a38828e25352ab9d188364a8', 'battle_rule_v1:0e03f3ba110aa9a4e68b1c4bdbb8554a', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"self_stat_modifier_until_eot","activation_cost_colors":["B"],"activation_cost_generic":0,"activation_cost_mana":"{B}","activation_limit_per_turn":2,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","power_boost":1,"power_delta":1,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","toughness_boost":0,"toughness_delta":0,"xmage_ability_class":"LimitedTimesPerTurnActivatedAbility","xmage_effect_class":"BoostSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","activated_effect":"self_stat_modifier_until_eot","activation_cost_colors":["B"],"activation_cost_generic":0,"activation_cost_mana":"{B}","activation_limit_per_turn":2,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","duration":"until_end_of_turn","effect":"creature","flying":true,"keywords":["flying"],"power_boost":1,"power_delta":1,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","toughness_boost":0,"toughness_delta":0,"xmage_ability_class":"LimitedTimesPerTurnActivatedAbility","xmage_auxiliary_static_keywords":["flying"],"xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PhyrexianBattleflies translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_boost_until_eot_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('pit imp', 'Pit Imp', 'a3d395a2a38828e25352ab9d188364a8', 'battle_rule_v1:0e03f3ba110aa9a4e68b1c4bdbb8554a', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"self_stat_modifier_until_eot","activation_cost_colors":["B"],"activation_cost_generic":0,"activation_cost_mana":"{B}","activation_limit_per_turn":2,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","power_boost":1,"power_delta":1,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","toughness_boost":0,"toughness_delta":0,"xmage_ability_class":"LimitedTimesPerTurnActivatedAbility","xmage_effect_class":"BoostSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","activated_effect":"self_stat_modifier_until_eot","activation_cost_colors":["B"],"activation_cost_generic":0,"activation_cost_mana":"{B}","activation_limit_per_turn":2,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","duration":"until_end_of_turn","effect":"creature","flying":true,"keywords":["flying"],"power_boost":1,"power_delta":1,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","toughness_boost":0,"toughness_delta":0,"xmage_ability_class":"LimitedTimesPerTurnActivatedAbility","xmage_auxiliary_static_keywords":["flying"],"xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PitImp translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_boost_until_eot_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('rimebound dead', 'Rimebound Dead', '19f88ee784d0fd8a2ee95128de842b76', 'battle_rule_v1:46ba569bacf613313d0ec8b7e0b1d660', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{S}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"regenerate_source","regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","activated_effect":"regenerate_source","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{S}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_regenerate_source_v1","duration":"until_end_of_turn","effect":"creature","regenerate_source":true,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"RegenerateSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class RimeboundDead translated into ManaLoom runtime scope xmage_permanent_simple_activated_regenerate_source_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('roterothopter', 'Roterothopter', 'b76ac9408e7f850c6396bf5449dfb4bd', 'battle_rule_v1:8381b909377c93b675c5b94984dca5cd', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"self_stat_modifier_until_eot","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{2}","activation_limit_per_turn":2,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","power_boost":1,"power_delta":1,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","toughness_boost":0,"toughness_delta":0,"xmage_ability_class":"LimitedTimesPerTurnActivatedAbility","xmage_effect_class":"BoostSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","activated_effect":"self_stat_modifier_until_eot","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{2}","activation_limit_per_turn":2,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","duration":"until_end_of_turn","effect":"creature","flying":true,"keywords":["flying"],"power_boost":1,"power_delta":1,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","toughness_boost":0,"toughness_delta":0,"xmage_ability_class":"LimitedTimesPerTurnActivatedAbility","xmage_auxiliary_static_keywords":["flying"],"xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Roterothopter translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_boost_until_eot_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sewer rats', 'Sewer Rats', 'ee129c1388c08f19b565aee934e71489', 'battle_rule_v1:f0727a60960f6f9ce184d0571e293db5', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"self_stat_modifier_until_eot","activation_cost_colors":["B"],"activation_cost_generic":0,"activation_cost_mana":"{B}","activation_life_cost":1,"activation_limit_per_turn":3,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","power_boost":1,"power_delta":1,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","toughness_boost":0,"toughness_delta":0,"xmage_ability_class":"LimitedTimesPerTurnActivatedAbility","xmage_effect_class":"BoostSourceEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","activated_effect":"self_stat_modifier_until_eot","activation_cost_colors":["B"],"activation_cost_generic":0,"activation_cost_mana":"{B}","activation_life_cost":1,"activation_limit_per_turn":3,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","duration":"until_end_of_turn","effect":"creature","power_boost":1,"power_delta":1,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","toughness_boost":0,"toughness_delta":0,"xmage_ability_class":"LimitedTimesPerTurnActivatedAbility","xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SewerRats translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_boost_until_eot_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('vampire bats', 'Vampire Bats', '8d5e2432d37a22761a24c93231487767', 'battle_rule_v1:0e03f3ba110aa9a4e68b1c4bdbb8554a', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"self_stat_modifier_until_eot","activation_cost_colors":["B"],"activation_cost_generic":0,"activation_cost_mana":"{B}","activation_limit_per_turn":2,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","duration":"until_end_of_turn","effect":"stat_modifier_until_eot","power_boost":1,"power_delta":1,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","toughness_boost":0,"toughness_delta":0,"xmage_ability_class":"LimitedTimesPerTurnActivatedAbility","xmage_effect_class":"BoostSourceEffect"}],"_keywords_are_self":true,"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","activated_effect":"self_stat_modifier_until_eot","activation_cost_colors":["B"],"activation_cost_generic":0,"activation_cost_mana":"{B}","activation_limit_per_turn":2,"activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_boost_until_eot_v1","duration":"until_end_of_turn","effect":"creature","flying":true,"keywords":["flying"],"power_boost":1,"power_delta":1,"target":"self","target_constraints":{"card_types":["creature"],"source":"self"},"target_controller":"self","toughness_boost":0,"toughness_delta":0,"xmage_ability_class":"LimitedTimesPerTurnActivatedAbility","xmage_auxiliary_static_keywords":["flying"],"xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class VampireBats translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_boost_until_eot_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
matched_cards AS (
  SELECT
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    c.id AS card_id,
    c.name AS db_card_name
  FROM proposed p
  LEFT JOIN public.cards c
    ON (
         lower(c.name) = p.normalized_name
         OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
       )
   AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
),
target_cards AS (
  SELECT
    normalized_name,
    card_name,
    oracle_hash,
    count(card_id) AS target_card_rows,
    min(card_id::text)::uuid AS canonical_card_id,
    min(db_card_name) AS canonical_card_name
  FROM matched_cards
  GROUP BY normalized_name, card_name, oracle_hash
),
rule_rows AS (
  SELECT p.normalized_name, count(r.*) AS existing_rule_rows
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
  GROUP BY p.normalized_name
),
expected_rows AS (
  SELECT p.normalized_name, count(r.*) AS expected_rule_rows_before
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key = p.logical_rule_key
  GROUP BY p.normalized_name
),
shadow_rows AS (
  SELECT p.normalized_name, count(r.*) AS would_deprecate_shadow_rows
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key <> p.logical_rule_key
   AND r.review_status NOT IN ('deprecated', 'rejected')
   AND r.execution_status <> 'disabled'
  GROUP BY p.normalized_name
)
SELECT
  p.card_name,
  p.normalized_name,
  p.oracle_hash,
  p.logical_rule_key,
  p.shadow_handling,
  tc.target_card_rows,
  tc.canonical_card_id,
  rr.existing_rule_rows,
  er.expected_rule_rows_before,
  sr.would_deprecate_shadow_rows
FROM proposed p
JOIN target_cards tc USING (normalized_name, card_name, oracle_hash)
JOIN rule_rows rr USING (normalized_name)
JOIN expected_rows er USING (normalized_name)
JOIN shadow_rows sr USING (normalized_name)
ORDER BY p.card_name;
