BEGIN;

CREATE SCHEMA IF NOT EXISTS manaloom_deploy_audit;

CREATE TABLE IF NOT EXISTS manaloom_deploy_audit.pg752_activated_bounce_new_server_20260711_094637 AS
SELECT *
FROM public.card_battle_rules
WHERE normalized_name IN ('aegis automaton', 'escape routes', 'galecaster colossus', 'kami of twisted reflection', 'neurok replica', 'obelisk of undoing', 'seal of removal', 'temporal adept', 'vedalken mastermind')
   OR normalized_name LIKE 'aegis automaton // %'
   OR normalized_name LIKE 'escape routes // %'
   OR normalized_name LIKE 'galecaster colossus // %'
   OR normalized_name LIKE 'kami of twisted reflection // %'
   OR normalized_name LIKE 'neurok replica // %'
   OR normalized_name LIKE 'obelisk of undoing // %'
   OR normalized_name LIKE 'seal of removal // %'
   OR normalized_name LIKE 'temporal adept // %'
   OR normalized_name LIKE 'vedalken mastermind // %';

DO $$
DECLARE
  v_missing jsonb;
BEGIN
  WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('aegis automaton', 'Aegis Automaton', 'c39d788123c3b8682a05f81a5eee36a6', 'battle_rule_v1:27a158cdf2166c1f380b13b1b7f90f53', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":4,"activation_cost_mana":"{4}{W}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_creature","target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"self","exclude_source":true},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":4,"activation_cost_mana":"{4}{W}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"self","exclude_source":true},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AegisAutomaton translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('escape routes', 'Escape Routes', '99f2d140a2736cf11e8949a6fe64db50', 'battle_rule_v1:ad0899579c9e83930dc3417432e9d3f4', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"white_or_black_creature","activation_cost_colors":["U"],"activation_cost_generic":2,"activation_cost_mana":"{2}{U}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_creature","target":"white_or_black_creature","target_constraints":{"card_types":["creature"],"controller_scope":"self","target_colors":["W","B"]},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"white_or_black_creature","activation_cost_colors":["U"],"activation_cost_generic":2,"activation_cost_mana":"{2}{U}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"enchantment","target":"white_or_black_creature","target_constraints":{"card_types":["creature"],"controller_scope":"self","target_colors":["W","B"]},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"enchantment","target":"white_or_black_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class EscapeRoutes translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('galecaster colossus', 'Galecaster Colossus', 'bac18d1190e6f03fb0d7ee9488add1a8', 'battle_rule_v1:13292b94e7562c44cad86841daf8557b', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"nonland_permanent","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":false,"activation_requires_tap_target":true,"activation_tap_cost":{"constraints":{"card_types":["creature"],"required_subtypes":["wizard"],"tapped_state":"untapped"},"count":1,"target_controller":"self"},"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_permanent","target":"nonland_permanent","target_constraints":{"card_types":["permanent"],"controller_scope":"opponent","exclude_card_types":["land"]},"target_controller":"opponent","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"nonland_permanent","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":false,"activation_requires_tap_target":true,"activation_tap_cost":{"constraints":{"card_types":["creature"],"required_subtypes":["wizard"],"tapped_state":"untapped"},"count":1,"target_controller":"self"},"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"creature","target":"nonland_permanent","target_constraints":{"card_types":["permanent"],"controller_scope":"opponent","exclude_card_types":["land"]},"target_controller":"opponent","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"nonland_permanent"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GalecasterColossus translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('kami of twisted reflection', 'Kami of Twisted Reflection', 'b6b7ea9a7c6a39f17f561d6975e3d620', 'battle_rule_v1:152b6c139fecd552a37446d2f3a3ff34', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activated_self_sacrifice_bounce":true,"activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_creature","target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activated_self_sacrifice_bounce":true,"activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class KamiOfTwistedReflection translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('neurok replica', 'Neurok Replica', '06c3ad8808eec196a82cb12fc37463bb', 'battle_rule_v1:71fea3d6e68db7404fd2f47a9f3a4af1', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activated_self_sacrifice_bounce":true,"activation_cost_colors":["U"],"activation_cost_generic":1,"activation_cost_mana":"{1}{U}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_creature","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activated_self_sacrifice_bounce":true,"activation_cost_colors":["U"],"activation_cost_generic":1,"activation_cost_mana":"{1}{U}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class NeurokReplica translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('obelisk of undoing', 'Obelisk of Undoing', '86dbc6f0c0ca38d42603b5020ce23ba5', 'battle_rule_v1:1f37448633316f79146c2fdecab338fb', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"permanent","activation_cost_colors":[],"activation_cost_generic":6,"activation_cost_mana":"{6}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_permanent","target":"permanent","target_constraints":{"card_types":["permanent"],"controller_scope":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"permanent","activation_cost_colors":[],"activation_cost_generic":6,"activation_cost_mana":"{6}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"artifact","target":"permanent","target_constraints":{"card_types":["permanent"],"controller_scope":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"artifact","target":"permanent"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ObeliskOfUndoing translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('seal of removal', 'Seal of Removal', 'df5cd2a545162b89a589a2e636b075f4', 'battle_rule_v1:5725a84a10c88e4717cae1384f8e6a63', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activated_self_sacrifice_bounce":true,"activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_creature","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activated_self_sacrifice_bounce":true,"activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"enchantment","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"enchantment","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SealOfRemoval translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('temporal adept', 'Temporal Adept', '60978fd8ccc32a16114af30485cc82c8', 'battle_rule_v1:7a4f8cf1c37a7dabce5ec99b494b15e1', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"permanent","activation_cost_colors":["U","U","U"],"activation_cost_generic":0,"activation_cost_mana":"{U}{U}{U}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_permanent","target":"permanent","target_constraints":{"card_types":["permanent"]},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"permanent","activation_cost_colors":["U","U","U"],"activation_cost_generic":0,"activation_cost_mana":"{U}{U}{U}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"creature","target":"permanent","target_constraints":{"card_types":["permanent"]},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"permanent"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TemporalAdept translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('vedalken mastermind', 'Vedalken Mastermind', 'ab3ea69bea787dc1d44b94c9d1febaf1', 'battle_rule_v1:c73f97178d2d03ae48964ac2b6e124df', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"permanent","activation_cost_colors":["U"],"activation_cost_generic":0,"activation_cost_mana":"{U}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_permanent","target":"permanent","target_constraints":{"card_types":["permanent"],"controller_scope":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"permanent","activation_cost_colors":["U"],"activation_cost_generic":0,"activation_cost_mana":"{U}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"creature","target":"permanent","target_constraints":{"card_types":["permanent"],"controller_scope":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"permanent"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class VedalkenMastermind translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
  counts AS (
    SELECT
      p.card_name,
      p.normalized_name,
      p.oracle_hash,
      count(c.id) AS target_card_rows,
      min(c.id::text)::uuid AS canonical_card_id
    FROM proposed p
    LEFT JOIN public.cards c
      ON (
           lower(c.name) = p.normalized_name
           OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
         )
     AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
    GROUP BY p.card_name, p.normalized_name, p.oracle_hash
  )
  SELECT jsonb_agg(counts ORDER BY card_name)
    INTO v_missing
  FROM counts
  WHERE target_card_rows < 1;

  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION 'XMage batch package abort: expected at least one Oracle-hash-matched card row for every proposed card: %', v_missing;
  END IF;
END $$;

WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('aegis automaton', 'Aegis Automaton', 'c39d788123c3b8682a05f81a5eee36a6', 'battle_rule_v1:27a158cdf2166c1f380b13b1b7f90f53', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":4,"activation_cost_mana":"{4}{W}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_creature","target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"self","exclude_source":true},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":4,"activation_cost_mana":"{4}{W}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"self","exclude_source":true},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AegisAutomaton translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('escape routes', 'Escape Routes', '99f2d140a2736cf11e8949a6fe64db50', 'battle_rule_v1:ad0899579c9e83930dc3417432e9d3f4', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"white_or_black_creature","activation_cost_colors":["U"],"activation_cost_generic":2,"activation_cost_mana":"{2}{U}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_creature","target":"white_or_black_creature","target_constraints":{"card_types":["creature"],"controller_scope":"self","target_colors":["W","B"]},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"white_or_black_creature","activation_cost_colors":["U"],"activation_cost_generic":2,"activation_cost_mana":"{2}{U}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"enchantment","target":"white_or_black_creature","target_constraints":{"card_types":["creature"],"controller_scope":"self","target_colors":["W","B"]},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"enchantment","target":"white_or_black_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class EscapeRoutes translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('galecaster colossus', 'Galecaster Colossus', 'bac18d1190e6f03fb0d7ee9488add1a8', 'battle_rule_v1:13292b94e7562c44cad86841daf8557b', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"nonland_permanent","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":false,"activation_requires_tap_target":true,"activation_tap_cost":{"constraints":{"card_types":["creature"],"required_subtypes":["wizard"],"tapped_state":"untapped"},"count":1,"target_controller":"self"},"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_permanent","target":"nonland_permanent","target_constraints":{"card_types":["permanent"],"controller_scope":"opponent","exclude_card_types":["land"]},"target_controller":"opponent","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"nonland_permanent","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":false,"activation_requires_tap_target":true,"activation_tap_cost":{"constraints":{"card_types":["creature"],"required_subtypes":["wizard"],"tapped_state":"untapped"},"count":1,"target_controller":"self"},"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"creature","target":"nonland_permanent","target_constraints":{"card_types":["permanent"],"controller_scope":"opponent","exclude_card_types":["land"]},"target_controller":"opponent","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"nonland_permanent"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GalecasterColossus translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('kami of twisted reflection', 'Kami of Twisted Reflection', 'b6b7ea9a7c6a39f17f561d6975e3d620', 'battle_rule_v1:152b6c139fecd552a37446d2f3a3ff34', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activated_self_sacrifice_bounce":true,"activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_creature","target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activated_self_sacrifice_bounce":true,"activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class KamiOfTwistedReflection translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('neurok replica', 'Neurok Replica', '06c3ad8808eec196a82cb12fc37463bb', 'battle_rule_v1:71fea3d6e68db7404fd2f47a9f3a4af1', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activated_self_sacrifice_bounce":true,"activation_cost_colors":["U"],"activation_cost_generic":1,"activation_cost_mana":"{1}{U}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_creature","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activated_self_sacrifice_bounce":true,"activation_cost_colors":["U"],"activation_cost_generic":1,"activation_cost_mana":"{1}{U}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class NeurokReplica translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('obelisk of undoing', 'Obelisk of Undoing', '86dbc6f0c0ca38d42603b5020ce23ba5', 'battle_rule_v1:1f37448633316f79146c2fdecab338fb', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"permanent","activation_cost_colors":[],"activation_cost_generic":6,"activation_cost_mana":"{6}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_permanent","target":"permanent","target_constraints":{"card_types":["permanent"],"controller_scope":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"permanent","activation_cost_colors":[],"activation_cost_generic":6,"activation_cost_mana":"{6}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"artifact","target":"permanent","target_constraints":{"card_types":["permanent"],"controller_scope":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"artifact","target":"permanent"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ObeliskOfUndoing translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('seal of removal', 'Seal of Removal', 'df5cd2a545162b89a589a2e636b075f4', 'battle_rule_v1:5725a84a10c88e4717cae1384f8e6a63', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activated_self_sacrifice_bounce":true,"activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_creature","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activated_self_sacrifice_bounce":true,"activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"enchantment","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"enchantment","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SealOfRemoval translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('temporal adept', 'Temporal Adept', '60978fd8ccc32a16114af30485cc82c8', 'battle_rule_v1:7a4f8cf1c37a7dabce5ec99b494b15e1', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"permanent","activation_cost_colors":["U","U","U"],"activation_cost_generic":0,"activation_cost_mana":"{U}{U}{U}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_permanent","target":"permanent","target_constraints":{"card_types":["permanent"]},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"permanent","activation_cost_colors":["U","U","U"],"activation_cost_generic":0,"activation_cost_mana":"{U}{U}{U}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"creature","target":"permanent","target_constraints":{"card_types":["permanent"]},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"permanent"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TemporalAdept translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('vedalken mastermind', 'Vedalken Mastermind', 'ab3ea69bea787dc1d44b94c9d1febaf1', 'battle_rule_v1:c73f97178d2d03ae48964ac2b6e124df', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"permanent","activation_cost_colors":["U"],"activation_cost_generic":0,"activation_cost_mana":"{U}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_permanent","target":"permanent","target_constraints":{"card_types":["permanent"],"controller_scope":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"permanent","activation_cost_colors":["U"],"activation_cost_generic":0,"activation_cost_mana":"{U}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"creature","target":"permanent","target_constraints":{"card_types":["permanent"],"controller_scope":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"permanent"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class VedalkenMastermind translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
deprecated AS (
  UPDATE public.card_battle_rules r
  SET
    review_status = 'deprecated',
    execution_status = 'disabled',
    updated_at = now(),
    notes = concat_ws(E'\n', nullif(r.notes, ''), 'XMage batch package: deprecated stale shadow before curated batch rule upsert.')
  FROM proposed p
  WHERE (
        r.normalized_name = p.normalized_name
        OR r.normalized_name LIKE p.normalized_name || ' // %'
      )
    AND p.shadow_handling <> 'preserve_existing_rows'
    AND r.logical_rule_key <> p.logical_rule_key
  RETURNING r.*
)
SELECT count(*) AS deprecated_shadow_rows FROM deprecated;

WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('aegis automaton', 'Aegis Automaton', 'c39d788123c3b8682a05f81a5eee36a6', 'battle_rule_v1:27a158cdf2166c1f380b13b1b7f90f53', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":4,"activation_cost_mana":"{4}{W}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_creature","target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"self","exclude_source":true},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":4,"activation_cost_mana":"{4}{W}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"self","exclude_source":true},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AegisAutomaton translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('escape routes', 'Escape Routes', '99f2d140a2736cf11e8949a6fe64db50', 'battle_rule_v1:ad0899579c9e83930dc3417432e9d3f4', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"white_or_black_creature","activation_cost_colors":["U"],"activation_cost_generic":2,"activation_cost_mana":"{2}{U}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_creature","target":"white_or_black_creature","target_constraints":{"card_types":["creature"],"controller_scope":"self","target_colors":["W","B"]},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"white_or_black_creature","activation_cost_colors":["U"],"activation_cost_generic":2,"activation_cost_mana":"{2}{U}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"enchantment","target":"white_or_black_creature","target_constraints":{"card_types":["creature"],"controller_scope":"self","target_colors":["W","B"]},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"enchantment","target":"white_or_black_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class EscapeRoutes translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('galecaster colossus', 'Galecaster Colossus', 'bac18d1190e6f03fb0d7ee9488add1a8', 'battle_rule_v1:13292b94e7562c44cad86841daf8557b', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"nonland_permanent","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":false,"activation_requires_tap_target":true,"activation_tap_cost":{"constraints":{"card_types":["creature"],"required_subtypes":["wizard"],"tapped_state":"untapped"},"count":1,"target_controller":"self"},"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_permanent","target":"nonland_permanent","target_constraints":{"card_types":["permanent"],"controller_scope":"opponent","exclude_card_types":["land"]},"target_controller":"opponent","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"nonland_permanent","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":false,"activation_requires_tap_target":true,"activation_tap_cost":{"constraints":{"card_types":["creature"],"required_subtypes":["wizard"],"tapped_state":"untapped"},"count":1,"target_controller":"self"},"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"creature","target":"nonland_permanent","target_constraints":{"card_types":["permanent"],"controller_scope":"opponent","exclude_card_types":["land"]},"target_controller":"opponent","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"nonland_permanent"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GalecasterColossus translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('kami of twisted reflection', 'Kami of Twisted Reflection', 'b6b7ea9a7c6a39f17f561d6975e3d620', 'battle_rule_v1:152b6c139fecd552a37446d2f3a3ff34', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activated_self_sacrifice_bounce":true,"activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_creature","target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activated_self_sacrifice_bounce":true,"activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class KamiOfTwistedReflection translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('neurok replica', 'Neurok Replica', '06c3ad8808eec196a82cb12fc37463bb', 'battle_rule_v1:71fea3d6e68db7404fd2f47a9f3a4af1', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activated_self_sacrifice_bounce":true,"activation_cost_colors":["U"],"activation_cost_generic":1,"activation_cost_mana":"{1}{U}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_creature","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activated_self_sacrifice_bounce":true,"activation_cost_colors":["U"],"activation_cost_generic":1,"activation_cost_mana":"{1}{U}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class NeurokReplica translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('obelisk of undoing', 'Obelisk of Undoing', '86dbc6f0c0ca38d42603b5020ce23ba5', 'battle_rule_v1:1f37448633316f79146c2fdecab338fb', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"permanent","activation_cost_colors":[],"activation_cost_generic":6,"activation_cost_mana":"{6}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_permanent","target":"permanent","target_constraints":{"card_types":["permanent"],"controller_scope":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"permanent","activation_cost_colors":[],"activation_cost_generic":6,"activation_cost_mana":"{6}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"artifact","target":"permanent","target_constraints":{"card_types":["permanent"],"controller_scope":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"artifact","target":"permanent"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ObeliskOfUndoing translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('seal of removal', 'Seal of Removal', 'df5cd2a545162b89a589a2e636b075f4', 'battle_rule_v1:5725a84a10c88e4717cae1384f8e6a63', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activated_self_sacrifice_bounce":true,"activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_creature","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_creature","activated_remove_target":"creature","activated_self_sacrifice_bounce":true,"activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"enchantment","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"enchantment","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SealOfRemoval translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('temporal adept', 'Temporal Adept', '60978fd8ccc32a16114af30485cc82c8', 'battle_rule_v1:7a4f8cf1c37a7dabce5ec99b494b15e1', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"permanent","activation_cost_colors":["U","U","U"],"activation_cost_generic":0,"activation_cost_mana":"{U}{U}{U}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_permanent","target":"permanent","target_constraints":{"card_types":["permanent"]},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"permanent","activation_cost_colors":["U","U","U"],"activation_cost_generic":0,"activation_cost_mana":"{U}{U}{U}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"creature","target":"permanent","target_constraints":{"card_types":["permanent"]},"target_controller":"any","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"permanent"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TemporalAdept translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('vedalken mastermind', 'Vedalken Mastermind', 'ab3ea69bea787dc1d44b94c9d1febaf1', 'battle_rule_v1:c73f97178d2d03ae48964ac2b6e124df', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"permanent","activation_cost_colors":["U"],"activation_cost_generic":0,"activation_cost_mana":"{U}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"remove_permanent","target":"permanent","target_constraints":{"card_types":["permanent"],"controller_scope":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","activated_effect":"return_to_hand","activated_remove_effect":"remove_permanent","activated_remove_target":"permanent","activation_cost_colors":["U"],"activation_cost_generic":0,"activation_cost_mana":"{U}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_return_to_hand_v1","destination":"hand","effect":"creature","target":"permanent","target_constraints":{"card_types":["permanent"],"controller_scope":"self"},"target_controller":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"permanent"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class VedalkenMastermind translated into ManaLoom runtime scope xmage_permanent_simple_activated_return_to_hand_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
matched_cards AS (
  SELECT
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    c.id AS card_id,
    c.name AS db_card_name
  FROM proposed p
  JOIN public.cards c
    ON (
         lower(c.name) = p.normalized_name
         OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
       )
   AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
),
canonical_target_cards AS (
  SELECT
    p.*,
    min(m.card_id::text)::uuid AS card_id,
    min(m.db_card_name) AS db_card_name
  FROM proposed p
  JOIN matched_cards m
    USING (normalized_name, card_name, oracle_hash)
  GROUP BY
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    p.logical_rule_key,
    p.effect_json,
    p.deck_role_json,
    p.source,
    p.confidence,
    p.review_status,
    p.execution_status,
    p.notes,
    p.shadow_handling
),
upserted AS (
  INSERT INTO public.card_battle_rules (
    normalized_name,
    card_id,
    card_name,
    effect_json,
    deck_role_json,
    source,
    confidence,
    review_status,
    rule_version,
    oracle_hash,
    notes,
    reviewed_by,
    reviewed_at,
    created_at,
    updated_at,
    last_seen_at,
    logical_rule_key,
    execution_status
  )
  SELECT
    normalized_name,
    card_id,
    db_card_name,
    effect_json,
    deck_role_json,
    source,
    confidence,
    review_status,
    2,
    oracle_hash,
    notes,
    'codex-xmage-batch',
    now(),
    now(),
    now(),
    now(),
    logical_rule_key,
    execution_status
  FROM canonical_target_cards
  ON CONFLICT (normalized_name, logical_rule_key) DO UPDATE
  SET
    card_id = EXCLUDED.card_id,
    card_name = EXCLUDED.card_name,
    effect_json = EXCLUDED.effect_json,
    deck_role_json = EXCLUDED.deck_role_json,
    source = EXCLUDED.source,
    confidence = EXCLUDED.confidence,
    review_status = EXCLUDED.review_status,
    rule_version = EXCLUDED.rule_version,
    oracle_hash = EXCLUDED.oracle_hash,
    notes = EXCLUDED.notes,
    reviewed_by = EXCLUDED.reviewed_by,
    reviewed_at = EXCLUDED.reviewed_at,
    updated_at = EXCLUDED.updated_at,
    last_seen_at = EXCLUDED.last_seen_at,
    execution_status = EXCLUDED.execution_status
  RETURNING *
)
SELECT count(*) AS upserted_rows FROM upserted;

COMMIT;
