WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('copper gnomes', 'Copper Gnomes', '86f601cac2a1ddec4101401e195c5f44', 'battle_rule_v1:c0e315987ec8cfb5ec955d5e6190b8bb', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":[],"activation_cost_generic":4,"activation_cost_mana":"{4}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"put_from_hand_onto_battlefield","optional":true,"put_from_hand_target":"artifact_card","target":"artifact_card","target_constraints":{"card_types":["artifact"],"controller":"self","zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":[],"activation_cost_generic":4,"activation_cost_mana":"{4}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"creature","instant":false,"optional":true,"put_from_hand_target":"artifact_card","sorcery":false,"target":"artifact_card","target_constraints":{"card_types":["artifact"],"controller":"self","zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"artifact_card"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CopperGnomes translated into ManaLoom runtime scope xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('didgeridoo', 'Didgeridoo', '036322561d5362f05f2f2ae56b7451fd', 'battle_rule_v1:6cb65891ac0552dbd283c92c0ef0cade', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":[],"activation_cost_generic":3,"activation_cost_mana":"{3}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"put_from_hand_onto_battlefield","optional":true,"put_from_hand_target":"minotaur_permanent_card","target":"minotaur_permanent_card","target_constraints":{"card_types":["permanent"],"controller":"self","subtypes":["minotaur"],"zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":[],"activation_cost_generic":3,"activation_cost_mana":"{3}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"artifact","instant":false,"optional":true,"put_from_hand_target":"minotaur_permanent_card","sorcery":false,"target":"minotaur_permanent_card","target_constraints":{"card_types":["permanent"],"controller":"self","subtypes":["minotaur"],"zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}'::jsonb, '{"category":"unknown","effect":"artifact","target":"minotaur_permanent_card"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Didgeridoo translated into ManaLoom runtime scope xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('dragon arch', 'Dragon Arch', '47a41258d4c7434988148fc5f4142f15', 'battle_rule_v1:47e25735ad79962b7c529936cbace0fd', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{2}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"put_from_hand_onto_battlefield","optional":true,"put_from_hand_target":"multicolored_creature_card","target":"multicolored_creature_card","target_constraints":{"card_types":["creature"],"color_count_min":2,"controller":"self","zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{2}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"artifact","instant":false,"optional":true,"put_from_hand_target":"multicolored_creature_card","sorcery":false,"target":"multicolored_creature_card","target_constraints":{"card_types":["creature"],"color_count_min":2,"controller":"self","zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}'::jsonb, '{"category":"unknown","effect":"artifact","target":"multicolored_creature_card"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DragonArch translated into ManaLoom runtime scope xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('elvish piper', 'Elvish Piper', '09e28c5068d5b5b4904975841c003436', 'battle_rule_v1:f971b322a2ca8f29b674bddafef7eae8', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":["G"],"activation_cost_generic":0,"activation_cost_mana":"{G}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"put_from_hand_onto_battlefield","optional":true,"put_from_hand_target":"creature_card","target":"creature_card","target_constraints":{"card_types":["creature"],"controller":"self","zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":["G"],"activation_cost_generic":0,"activation_cost_mana":"{G}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"creature","instant":false,"optional":true,"put_from_hand_target":"creature_card","sorcery":false,"target":"creature_card","target_constraints":{"card_types":["creature"],"controller":"self","zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature_card"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ElvishPiper translated into ManaLoom runtime scope xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('firebrand ranger', 'Firebrand Ranger', '245417b431c03ddcd23c62c85cdf9ba1', 'battle_rule_v1:066d000a8fca2582a554b3ba7688f2ad', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":["G"],"activation_cost_generic":0,"activation_cost_mana":"{G}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"put_from_hand_onto_battlefield","optional":true,"put_from_hand_target":"basic_land_card","target":"basic_land_card","target_constraints":{"card_types":["land"],"controller":"self","required_supertypes":["basic"],"zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":["G"],"activation_cost_generic":0,"activation_cost_mana":"{G}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"creature","instant":false,"optional":true,"put_from_hand_target":"basic_land_card","sorcery":false,"target":"basic_land_card","target_constraints":{"card_types":["land"],"controller":"self","required_supertypes":["basic"],"zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"basic_land_card"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class FirebrandRanger translated into ManaLoom runtime scope xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('krosan wayfarer', 'Krosan Wayfarer', '66fc711ff4867977695b51ad6cdbe51f', 'battle_rule_v1:2b2f816d7c025090aacf671fac6ea9f1', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"put_from_hand_onto_battlefield","optional":true,"put_from_hand_target":"land_card","target":"land_card","target_constraints":{"card_types":["land"],"controller":"self","zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":true,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"creature","instant":false,"optional":true,"put_from_hand_target":"land_card","sorcery":false,"target":"land_card","target_constraints":{"card_types":["land"],"controller":"self","zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"land_card"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class KrosanWayfarer translated into ManaLoom runtime scope xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('llanowar scout', 'Llanowar Scout', '549cfec8af2ff3af4cde7f0c79f4ba8f', 'battle_rule_v1:36df08521da3182549a69ad11f754f87', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"put_from_hand_onto_battlefield","optional":true,"put_from_hand_target":"land_card","target":"land_card","target_constraints":{"card_types":["land"],"controller":"self","zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"creature","instant":false,"optional":true,"put_from_hand_target":"land_card","sorcery":false,"target":"land_card","target_constraints":{"card_types":["land"],"controller":"self","zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"land_card"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class LlanowarScout translated into ManaLoom runtime scope xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('quicksilver amulet', 'Quicksilver Amulet', '5a6fa5d251e34f51abc60120806df86b', 'battle_rule_v1:6e8c5bcbdac1cebafde4d999f7c9cb29', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":[],"activation_cost_generic":4,"activation_cost_mana":"{4}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"put_from_hand_onto_battlefield","optional":true,"put_from_hand_target":"creature_card","target":"creature_card","target_constraints":{"card_types":["creature"],"controller":"self","zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":[],"activation_cost_generic":4,"activation_cost_mana":"{4}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"artifact","instant":false,"optional":true,"put_from_hand_target":"creature_card","sorcery":false,"target":"creature_card","target_constraints":{"card_types":["creature"],"controller":"self","zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}'::jsonb, '{"category":"unknown","effect":"artifact","target":"creature_card"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class QuicksilverAmulet translated into ManaLoom runtime scope xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sakura-tribe scout', 'Sakura-Tribe Scout', '549cfec8af2ff3af4cde7f0c79f4ba8f', 'battle_rule_v1:36df08521da3182549a69ad11f754f87', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"put_from_hand_onto_battlefield","optional":true,"put_from_hand_target":"land_card","target":"land_card","target_constraints":{"card_types":["land"],"controller":"self","zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"creature","instant":false,"optional":true,"put_from_hand_target":"land_card","sorcery":false,"target":"land_card","target_constraints":{"card_types":["land"],"controller":"self","zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"land_card"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SakuraTribeScout translated into ManaLoom runtime scope xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('scaled herbalist', 'Scaled Herbalist', '549cfec8af2ff3af4cde7f0c79f4ba8f', 'battle_rule_v1:36df08521da3182549a69ad11f754f87', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"put_from_hand_onto_battlefield","optional":true,"put_from_hand_target":"land_card","target":"land_card","target_constraints":{"card_types":["land"],"controller":"self","zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"creature","instant":false,"optional":true,"put_from_hand_target":"land_card","sorcery":false,"target":"land_card","target_constraints":{"card_types":["land"],"controller":"self","zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"land_card"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ScaledHerbalist translated into ManaLoom runtime scope xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('thran temporal gateway', 'Thran Temporal Gateway', '623bfcfd6f4e222da110b6a95e623537', 'battle_rule_v1:254cdc5f5a635adf001dc6bece9b04ca', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":[],"activation_cost_generic":4,"activation_cost_mana":"{4}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"put_from_hand_onto_battlefield","optional":true,"put_from_hand_target":"historic_permanent_card","target":"historic_permanent_card","target_constraints":{"card_types":["permanent"],"controller":"self","historic":true,"zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":[],"activation_cost_generic":4,"activation_cost_mana":"{4}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"artifact","instant":false,"optional":true,"put_from_hand_target":"historic_permanent_card","sorcery":false,"target":"historic_permanent_card","target_constraints":{"card_types":["permanent"],"controller":"self","historic":true,"zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}'::jsonb, '{"category":"unknown","effect":"artifact","target":"historic_permanent_card"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ThranTemporalGateway translated into ManaLoom runtime scope xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('walking atlas', 'Walking Atlas', '549cfec8af2ff3af4cde7f0c79f4ba8f', 'battle_rule_v1:36df08521da3182549a69ad11f754f87', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"put_from_hand_onto_battlefield","optional":true,"put_from_hand_target":"land_card","target":"land_card","target_constraints":{"card_types":["land"],"controller":"self","zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","activated_effect":"put_from_hand_onto_battlefield","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1","count":1,"destination":"battlefield","effect":"creature","instant":false,"optional":true,"put_from_hand_target":"land_card","sorcery":false,"target":"land_card","target_constraints":{"card_types":["land"],"controller":"self","zone":"hand"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"PutCardFromHandOntoBattlefieldEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"land_card"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class WalkingAtlas translated into ManaLoom runtime scope xmage_permanent_simple_activated_put_hand_card_onto_battlefield_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
matched_cards AS (
  SELECT
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    c.id AS card_id,
    c.name AS db_card_name
  FROM proposed p
  LEFT JOIN public.cards c
    ON (
         lower(c.name) = p.normalized_name
         OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
       )
   AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
),
target_cards AS (
  SELECT
    normalized_name,
    card_name,
    oracle_hash,
    count(card_id) AS target_card_rows,
    min(card_id::text)::uuid AS canonical_card_id,
    min(db_card_name) AS canonical_card_name
  FROM matched_cards
  GROUP BY normalized_name, card_name, oracle_hash
),
rule_rows AS (
  SELECT p.normalized_name, count(r.*) AS existing_rule_rows
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
  GROUP BY p.normalized_name
),
expected_rows AS (
  SELECT p.normalized_name, count(r.*) AS expected_rule_rows_before
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key = p.logical_rule_key
  GROUP BY p.normalized_name
),
shadow_rows AS (
  SELECT p.normalized_name, count(r.*) AS would_deprecate_shadow_rows
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key <> p.logical_rule_key
   AND r.review_status NOT IN ('deprecated', 'rejected')
   AND r.execution_status <> 'disabled'
  GROUP BY p.normalized_name
)
SELECT
  p.card_name,
  p.normalized_name,
  p.oracle_hash,
  p.logical_rule_key,
  p.shadow_handling,
  tc.target_card_rows,
  tc.canonical_card_id,
  rr.existing_rule_rows,
  er.expected_rule_rows_before,
  sr.would_deprecate_shadow_rows
FROM proposed p
JOIN target_cards tc USING (normalized_name, card_name, oracle_hash)
JOIN rule_rows rr USING (normalized_name)
JOIN expected_rows er USING (normalized_name)
JOIN shadow_rows sr USING (normalized_name)
ORDER BY p.card_name;
