WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('moment of craving', 'Moment of Craving', 'dc486e3f0b4387b644d636f58918b41f', 'battle_rule_v1:b63f76d6ec9977d6406965136735a100', '{"_composite_rule_components":[{"battle_model_scope":"xmage_fixed_boost_target_creature_until_eot_spell_v1","compose_on_resolution":true,"duration":"until_end_of_turn","effect":"stat_modifier_until_eot","power_boost":-2,"power_delta":-2,"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_boost":-2,"toughness_delta":-2,"xmage_effect_class":"BoostTargetEffect"},{"battle_model_scope":"xmage_fixed_controller_gain_life_spell_v1","compose_on_resolution":true,"effect":"life_total_change","life_gain_amount":2,"target":"self","xmage_effect_class":"GainLifeEffect"}],"battle_model_scope":"xmage_fixed_boost_target_creature_until_eot_gain_life_spell_v1","effect":"composite_resolution","instant":true,"life_gain_amount":2,"power_boost":-2,"power_delta":-2,"resolution_order":"boost_then_gain","sorcery":false,"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_boost":-2,"toughness_delta":-2,"xmage_effect_classes":["BoostTargetEffect","GainLifeEffect"]}'::jsonb, '{"category":"draw","effect":"composite_resolution","target":"creature","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MomentOfCraving translated into ManaLoom runtime scope xmage_fixed_boost_target_creature_until_eot_gain_life_spell_v1. This row is package-ready only because the source signature is a narrow fixed target-creature boost plus controller life-gain spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('moment of triumph', 'Moment of Triumph', '5953b146ebacdef49f8cf977f511f0f6', 'battle_rule_v1:133a9d7b7187d216ca297d65b8d3028b', '{"_composite_rule_components":[{"battle_model_scope":"xmage_fixed_boost_target_creature_until_eot_spell_v1","compose_on_resolution":true,"duration":"until_end_of_turn","effect":"stat_modifier_until_eot","power_boost":2,"power_delta":2,"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_boost":2,"toughness_delta":2,"xmage_effect_class":"BoostTargetEffect"},{"battle_model_scope":"xmage_fixed_controller_gain_life_spell_v1","compose_on_resolution":true,"effect":"life_total_change","life_gain_amount":2,"target":"self","xmage_effect_class":"GainLifeEffect"}],"battle_model_scope":"xmage_fixed_boost_target_creature_until_eot_gain_life_spell_v1","effect":"composite_resolution","instant":true,"life_gain_amount":2,"power_boost":2,"power_delta":2,"resolution_order":"boost_then_gain","sorcery":false,"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_boost":2,"toughness_delta":2,"xmage_effect_classes":["BoostTargetEffect","GainLifeEffect"]}'::jsonb, '{"category":"draw","effect":"composite_resolution","target":"creature","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MomentOfTriumph translated into ManaLoom runtime scope xmage_fixed_boost_target_creature_until_eot_gain_life_spell_v1. This row is package-ready only because the source signature is a narrow fixed target-creature boost plus controller life-gain spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('syphon fuel', 'Syphon Fuel', '424c2ba6a7cd5c1a82e1bfd31594a768', 'battle_rule_v1:5a6480818679773b600d24b5f84861f6', '{"_composite_rule_components":[{"battle_model_scope":"xmage_fixed_boost_target_creature_until_eot_spell_v1","compose_on_resolution":true,"duration":"until_end_of_turn","effect":"stat_modifier_until_eot","power_boost":-6,"power_delta":-6,"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_boost":-6,"toughness_delta":-6,"xmage_effect_class":"BoostTargetEffect"},{"battle_model_scope":"xmage_fixed_controller_gain_life_spell_v1","compose_on_resolution":true,"effect":"life_total_change","life_gain_amount":2,"target":"self","xmage_effect_class":"GainLifeEffect"}],"battle_model_scope":"xmage_fixed_boost_target_creature_until_eot_gain_life_spell_v1","effect":"composite_resolution","instant":true,"life_gain_amount":2,"power_boost":-6,"power_delta":-6,"resolution_order":"boost_then_gain","sorcery":false,"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","toughness_boost":-6,"toughness_delta":-6,"xmage_effect_classes":["BoostTargetEffect","GainLifeEffect"]}'::jsonb, '{"category":"draw","effect":"composite_resolution","target":"creature","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SyphonFuel translated into ManaLoom runtime scope xmage_fixed_boost_target_creature_until_eot_gain_life_spell_v1. This row is package-ready only because the source signature is a narrow fixed target-creature boost plus controller life-gain spell with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('tandem tactics', 'Tandem Tactics', '84c5a871f4a5b344ae46515e616900d6', 'battle_rule_v1:6535eb0fb5f92bbde58e0340d48c6672', '{"_composite_rule_components":[{"battle_model_scope":"xmage_fixed_boost_target_creature_until_eot_spell_v1","compose_on_resolution":true,"duration":"until_end_of_turn","effect":"stat_modifier_until_eot","power_boost":1,"power_delta":1,"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","target_count":2,"target_count_max":2,"target_count_min":0,"toughness_boost":2,"toughness_delta":2,"up_to_count":true,"xmage_effect_class":"BoostTargetEffect"},{"battle_model_scope":"xmage_fixed_controller_gain_life_spell_v1","compose_on_resolution":true,"effect":"life_total_change","life_gain_amount":2,"target":"self","xmage_effect_class":"GainLifeEffect"}],"battle_model_scope":"xmage_fixed_boost_target_creature_until_eot_gain_life_spell_v1","effect":"composite_resolution","instant":true,"life_gain_amount":2,"power_boost":1,"power_delta":1,"resolution_order":"boost_then_gain","sorcery":false,"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","target_count":2,"target_count_max":2,"target_count_min":0,"toughness_boost":2,"toughness_delta":2,"up_to_count":true,"xmage_effect_classes":["BoostTargetEffect","GainLifeEffect"]}'::jsonb, '{"category":"draw","effect":"composite_resolution","target":"creature","timing":"instant"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class TandemTactics translated into ManaLoom runtime scope xmage_fixed_boost_target_creature_until_eot_gain_life_spell_v1. This row is package-ready only because the source signature is a narrow fixed target-creature boost plus controller life-gain spell with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
rule_rows AS (
  SELECT
    r.normalized_name,
    r.logical_rule_key,
    r.oracle_hash,
    r.review_status,
    r.execution_status
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key = p.logical_rule_key
)
SELECT
  p.card_name,
  p.normalized_name,
  p.logical_rule_key,
  count(r.*) FILTER (WHERE r.logical_rule_key = p.logical_rule_key) AS promoted_rule_rows,
  count(r.*) FILTER (WHERE r.review_status = 'verified' AND r.execution_status = 'auto') AS promoted_verified_auto_rows,
  count(r.*) FILTER (WHERE r.oracle_hash = p.oracle_hash) AS promoted_oracle_hash_rows,
  (SELECT count(*) FROM manaloom_deploy_audit.pg795_boost_life_gain_new_server_20260712_002511) AS backup_rows
FROM proposed p
LEFT JOIN rule_rows r
  ON r.normalized_name = p.normalized_name
 AND r.logical_rule_key = p.logical_rule_key
 AND r.oracle_hash = p.oracle_hash
GROUP BY p.card_name, p.normalized_name, p.logical_rule_key, p.oracle_hash
ORDER BY p.card_name;
