WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('aesthir glider', 'Aesthir Glider', '4893eefbd4bc76a7b9d1e891a37d70be', 'battle_rule_v1:8b80cbc5dee879a560224daf9172f1d0', '{"_keywords_are_self":true,"ability_kind":"static","battle_model_scope":"xmage_static_self_cant_block_creature_v1","cannot_block":true,"cant_block":true,"effect":"creature","flying":true,"keywords":["flying"],"static_cant_block":true,"static_effect":"self_cant_block","target":"self","target_controller":"self","xmage_ability_class":"CantBlockAbility","xmage_ability_classes":["CantBlockAbility","FlyingAbility"]}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AesthirGlider translated into ManaLoom runtime scope xmage_static_self_cant_block_creature_v1. This row is package-ready only because the source signature is a narrow creature static self can''t-block restriction with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('daggerclaw imp', 'Daggerclaw Imp', '4893eefbd4bc76a7b9d1e891a37d70be', 'battle_rule_v1:8b80cbc5dee879a560224daf9172f1d0', '{"_keywords_are_self":true,"ability_kind":"static","battle_model_scope":"xmage_static_self_cant_block_creature_v1","cannot_block":true,"cant_block":true,"effect":"creature","flying":true,"keywords":["flying"],"static_cant_block":true,"static_effect":"self_cant_block","target":"self","target_controller":"self","xmage_ability_class":"CantBlockAbility","xmage_ability_classes":["CantBlockAbility","FlyingAbility"]}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DaggerclawImp translated into ManaLoom runtime scope xmage_static_self_cant_block_creature_v1. This row is package-ready only because the source signature is a narrow creature static self can''t-block restriction with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('goblin glider', 'Goblin Glider', '4893eefbd4bc76a7b9d1e891a37d70be', 'battle_rule_v1:8b80cbc5dee879a560224daf9172f1d0', '{"_keywords_are_self":true,"ability_kind":"static","battle_model_scope":"xmage_static_self_cant_block_creature_v1","cannot_block":true,"cant_block":true,"effect":"creature","flying":true,"keywords":["flying"],"static_cant_block":true,"static_effect":"self_cant_block","target":"self","target_controller":"self","xmage_ability_class":"CantBlockAbility","xmage_ability_classes":["CantBlockAbility","FlyingAbility"]}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GoblinGlider translated into ManaLoom runtime scope xmage_static_self_cant_block_creature_v1. This row is package-ready only because the source signature is a narrow creature static self can''t-block restriction with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('iron-barb hellion', 'Iron-Barb Hellion', '2befb1427bdc8b017a18f5f51eeaaa71', 'battle_rule_v1:e38b28bd3c0984bc6c252aa8b1594fa7', '{"_keywords_are_self":true,"ability_kind":"static","battle_model_scope":"xmage_static_self_cant_block_creature_v1","cannot_block":true,"cant_block":true,"effect":"creature","haste":true,"keywords":["haste"],"static_cant_block":true,"static_effect":"self_cant_block","target":"self","target_controller":"self","xmage_ability_class":"CantBlockAbility","xmage_ability_classes":["CantBlockAbility","HasteAbility"]}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class IronBarbHellion translated into ManaLoom runtime scope xmage_static_self_cant_block_creature_v1. This row is package-ready only because the source signature is a narrow creature static self can''t-block restriction with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('kyren glider', 'Kyren Glider', '4893eefbd4bc76a7b9d1e891a37d70be', 'battle_rule_v1:8b80cbc5dee879a560224daf9172f1d0', '{"_keywords_are_self":true,"ability_kind":"static","battle_model_scope":"xmage_static_self_cant_block_creature_v1","cannot_block":true,"cant_block":true,"effect":"creature","flying":true,"keywords":["flying"],"static_cant_block":true,"static_effect":"self_cant_block","target":"self","target_controller":"self","xmage_ability_class":"CantBlockAbility","xmage_ability_classes":["CantBlockAbility","FlyingAbility"]}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class KyrenGlider translated into ManaLoom runtime scope xmage_static_self_cant_block_creature_v1. This row is package-ready only because the source signature is a narrow creature static self can''t-block restriction with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('nezumi cutthroat', 'Nezumi Cutthroat', '50f19cc3f7bb41d61e0eb0b7c2838df9', 'battle_rule_v1:c7b91b48e780f212a286c4011ac31b5b', '{"_keywords_are_self":true,"ability_kind":"static","battle_model_scope":"xmage_static_self_cant_block_creature_v1","cannot_block":true,"cant_block":true,"effect":"creature","fear":true,"keywords":["fear"],"static_cant_block":true,"static_effect":"self_cant_block","target":"self","target_controller":"self","xmage_ability_class":"CantBlockAbility","xmage_ability_classes":["CantBlockAbility","FearAbility"]}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class NezumiCutthroat translated into ManaLoom runtime scope xmage_static_self_cant_block_creature_v1. This row is package-ready only because the source signature is a narrow creature static self can''t-block restriction with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('nightshade stinger', 'Nightshade Stinger', '4893eefbd4bc76a7b9d1e891a37d70be', 'battle_rule_v1:8b80cbc5dee879a560224daf9172f1d0', '{"_keywords_are_self":true,"ability_kind":"static","battle_model_scope":"xmage_static_self_cant_block_creature_v1","cannot_block":true,"cant_block":true,"effect":"creature","flying":true,"keywords":["flying"],"static_cant_block":true,"static_effect":"self_cant_block","target":"self","target_controller":"self","xmage_ability_class":"CantBlockAbility","xmage_ability_classes":["CantBlockAbility","FlyingAbility"]}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class NightshadeStinger translated into ManaLoom runtime scope xmage_static_self_cant_block_creature_v1. This row is package-ready only because the source signature is a narrow creature static self can''t-block restriction with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('vampire interloper', 'Vampire Interloper', '4893eefbd4bc76a7b9d1e891a37d70be', 'battle_rule_v1:8b80cbc5dee879a560224daf9172f1d0', '{"_keywords_are_self":true,"ability_kind":"static","battle_model_scope":"xmage_static_self_cant_block_creature_v1","cannot_block":true,"cant_block":true,"effect":"creature","flying":true,"keywords":["flying"],"static_cant_block":true,"static_effect":"self_cant_block","target":"self","target_controller":"self","xmage_ability_class":"CantBlockAbility","xmage_ability_classes":["CantBlockAbility","FlyingAbility"]}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class VampireInterloper translated into ManaLoom runtime scope xmage_static_self_cant_block_creature_v1. This row is package-ready only because the source signature is a narrow creature static self can''t-block restriction with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
rule_rows AS (
  SELECT
    r.normalized_name,
    r.logical_rule_key,
    r.oracle_hash,
    r.review_status,
    r.execution_status
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key = p.logical_rule_key
)
SELECT
  p.card_name,
  p.normalized_name,
  p.logical_rule_key,
  count(r.*) FILTER (WHERE r.logical_rule_key = p.logical_rule_key) AS promoted_rule_rows,
  count(r.*) FILTER (WHERE r.review_status = 'verified' AND r.execution_status = 'auto') AS promoted_verified_auto_rows,
  count(r.*) FILTER (WHERE r.oracle_hash = p.oracle_hash) AS promoted_oracle_hash_rows,
  (SELECT count(*) FROM manaloom_deploy_audit.pg805_static_cant_block_with_keywords_ne_20260712_040435) AS backup_rows
FROM proposed p
LEFT JOIN rule_rows r
  ON r.normalized_name = p.normalized_name
 AND r.logical_rule_key = p.logical_rule_key
 AND r.oracle_hash = p.oracle_hash
GROUP BY p.card_name, p.normalized_name, p.logical_rule_key, p.oracle_hash
ORDER BY p.card_name;
