WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('benalish honor guard', 'Benalish Honor Guard', 'e04714c0f63ef12c75fbc3e449a90e47', 'battle_rule_v1:d47448fbda29d9e307ab3875459ea680', '{"ability_kind":"static","battle_model_scope":"xmage_static_source_dynamic_count_boost_v1","battlefield_count_card_types":["creature"],"battlefield_count_required_supertypes":["legendary"],"battlefield_count_scope":"controller_battlefield","effect":"creature","power_base_delta":0,"power_delta_per_graveyard_count":1,"stat_modifier_amount_source":"battlefield_permanent_count","static_effect":"source_power_toughness_boost_equal_dynamic_count","target":"self","target_controller":"self","toughness_base_delta":0,"toughness_delta_per_graveyard_count":0,"xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BenalishHonorGuard translated into ManaLoom runtime scope xmage_static_source_dynamic_count_boost_v1. This row is package-ready only because the source signature is a narrow creature static source power/toughness boost equal to dynamic count with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('champion of the flame', 'Champion of the Flame', '53d8236351e7e791097bcf121ee3ac2e', 'battle_rule_v1:5938fd013e96f613e355fef3cf755b4c', '{"_keywords_are_self":true,"ability_kind":"static","attached_count_subtypes":["aura","equipment"],"battle_model_scope":"xmage_static_source_dynamic_count_boost_v1","effect":"creature","keywords":["trample"],"power_base_delta":0,"power_delta_per_graveyard_count":2,"stat_modifier_amount_source":"attached_permanent_count","static_effect":"source_power_toughness_boost_equal_dynamic_count","target":"self","target_controller":"self","toughness_base_delta":0,"toughness_delta_per_graveyard_count":2,"trample":true,"xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ChampionOfTheFlame translated into ManaLoom runtime scope xmage_static_source_dynamic_count_boost_v1. This row is package-ready only because the source signature is a narrow creature static source power/toughness boost equal to dynamic count with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('copperhoof vorrac', 'Copperhoof Vorrac', 'e0e1b88a68b29e82d21a6249ca6f66a3', 'battle_rule_v1:1fd61bb5b8feca01256030c1e1da17b6', '{"ability_kind":"static","battle_model_scope":"xmage_static_source_dynamic_count_boost_v1","battlefield_count_card_types":["permanent"],"battlefield_count_scope":"opponents_battlefield","battlefield_count_tapped_state":"untapped","effect":"creature","power_base_delta":0,"power_delta_per_graveyard_count":1,"stat_modifier_amount_source":"battlefield_permanent_count","static_effect":"source_power_toughness_boost_equal_dynamic_count","target":"self","target_controller":"self","toughness_base_delta":0,"toughness_delta_per_graveyard_count":1,"xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CopperhoofVorrac translated into ManaLoom runtime scope xmage_static_source_dynamic_count_boost_v1. This row is package-ready only because the source signature is a narrow creature static source power/toughness boost equal to dynamic count with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('earth servant', 'Earth Servant', '368b24654a552f97468022ed55db63d2', 'battle_rule_v1:d87b26107bff1e0ba537bc943098f76b', '{"ability_kind":"static","battle_model_scope":"xmage_static_source_dynamic_count_boost_v1","battlefield_count_card_types":["land"],"battlefield_count_scope":"controller_battlefield","battlefield_count_subtypes":["mountain"],"effect":"creature","power_base_delta":0,"power_delta_per_graveyard_count":0,"stat_modifier_amount_source":"battlefield_permanent_count","static_effect":"source_power_toughness_boost_equal_dynamic_count","target":"self","target_controller":"self","toughness_base_delta":0,"toughness_delta_per_graveyard_count":1,"xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class EarthServant translated into ManaLoom runtime scope xmage_static_source_dynamic_count_boost_v1. This row is package-ready only because the source signature is a narrow creature static source power/toughness boost equal to dynamic count with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('goblin gaveleer', 'Goblin Gaveleer', '63acb3177d4ba6fe2922a13162cebeca', 'battle_rule_v1:22163bde0beed1365367e7d4af59de1f', '{"_keywords_are_self":true,"ability_kind":"static","attached_count_subtypes":["equipment"],"battle_model_scope":"xmage_static_source_dynamic_count_boost_v1","effect":"creature","keywords":["trample"],"power_base_delta":0,"power_delta_per_graveyard_count":2,"stat_modifier_amount_source":"attached_permanent_count","static_effect":"source_power_toughness_boost_equal_dynamic_count","target":"self","target_controller":"self","toughness_base_delta":0,"toughness_delta_per_graveyard_count":0,"trample":true,"xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GoblinGaveleer translated into ManaLoom runtime scope xmage_static_source_dynamic_count_boost_v1. This row is package-ready only because the source signature is a narrow creature static source power/toughness boost equal to dynamic count with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('graceblade artisan', 'Graceblade Artisan', '8b3b3c76563a0a54a320a2f621287276', 'battle_rule_v1:2ee4138952dd4b5479c6e068397aec75', '{"ability_kind":"static","attached_count_subtypes":["aura"],"battle_model_scope":"xmage_static_source_dynamic_count_boost_v1","effect":"creature","power_base_delta":0,"power_delta_per_graveyard_count":2,"stat_modifier_amount_source":"attached_permanent_count","static_effect":"source_power_toughness_boost_equal_dynamic_count","target":"self","target_controller":"self","toughness_base_delta":0,"toughness_delta_per_graveyard_count":2,"xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GracebladeArtisan translated into ManaLoom runtime scope xmage_static_source_dynamic_count_boost_v1. This row is package-ready only because the source signature is a narrow creature static source power/toughness boost equal to dynamic count with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('grim strider', 'Grim Strider', 'edd54628b83006eac968948d29b31cb5', 'battle_rule_v1:642a8f99ca15e69db9dfbef9332d4729', '{"ability_kind":"static","battle_model_scope":"xmage_static_source_dynamic_count_boost_v1","effect":"creature","power_base_delta":0,"power_delta_per_graveyard_count":-1,"stat_modifier_amount_source":"controller_hand_count","static_effect":"source_power_toughness_boost_equal_dynamic_count","target":"self","target_controller":"self","toughness_base_delta":0,"toughness_delta_per_graveyard_count":-1,"xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GrimStrider translated into ManaLoom runtime scope xmage_static_source_dynamic_count_boost_v1. This row is package-ready only because the source signature is a narrow creature static source power/toughness boost equal to dynamic count with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('kavu scout', 'Kavu Scout', '22ef004f8d158e4703cb6669da4630c4', 'battle_rule_v1:febb779f9f6d863a2b0d58f634437ddc', '{"ability_kind":"static","battle_model_scope":"xmage_static_source_dynamic_count_boost_v1","effect":"creature","power_base_delta":0,"power_delta_per_graveyard_count":1,"stat_modifier_amount_source":"domain_basic_land_types","static_effect":"source_power_toughness_boost_equal_dynamic_count","target":"self","target_controller":"self","toughness_base_delta":0,"toughness_delta_per_graveyard_count":0,"xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class KavuScout translated into ManaLoom runtime scope xmage_static_source_dynamic_count_boost_v1. This row is package-ready only because the source signature is a narrow creature static source power/toughness boost equal to dynamic count with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('loxodon punisher', 'Loxodon Punisher', 'd8d85dfa9728b37c6039c84c7ee4ba72', 'battle_rule_v1:c562cac3eb63df28af264ee48f9ca29e', '{"ability_kind":"static","attached_count_subtypes":["equipment"],"battle_model_scope":"xmage_static_source_dynamic_count_boost_v1","effect":"creature","power_base_delta":0,"power_delta_per_graveyard_count":2,"stat_modifier_amount_source":"attached_permanent_count","static_effect":"source_power_toughness_boost_equal_dynamic_count","target":"self","target_controller":"self","toughness_base_delta":0,"toughness_delta_per_graveyard_count":2,"xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class LoxodonPunisher translated into ManaLoom runtime scope xmage_static_source_dynamic_count_boost_v1. This row is package-ready only because the source signature is a narrow creature static source power/toughness boost equal to dynamic count with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('mogg squad', 'Mogg Squad', '39dcbc130869743d19efc2f05e70a471', 'battle_rule_v1:6de2bf99942a883898f37f58586ed6ba', '{"ability_kind":"static","battle_model_scope":"xmage_static_source_dynamic_count_boost_v1","battlefield_count_card_types":["creature"],"battlefield_count_exclude_source":true,"battlefield_count_scope":"all_battlefields","effect":"creature","power_base_delta":0,"power_delta_per_graveyard_count":-1,"stat_modifier_amount_source":"battlefield_permanent_count","static_effect":"source_power_toughness_boost_equal_dynamic_count","target":"self","target_controller":"self","toughness_base_delta":0,"toughness_delta_per_graveyard_count":-1,"xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MoggSquad translated into ManaLoom runtime scope xmage_static_source_dynamic_count_boost_v1. This row is package-ready only because the source signature is a narrow creature static source power/toughness boost equal to dynamic count with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('nim lasher', 'Nim Lasher', '87d37033566ccd20fda7d6d4281b428d', 'battle_rule_v1:207340c7fc271472aeccae579bf5dda3', '{"ability_kind":"static","battle_model_scope":"xmage_static_source_dynamic_count_boost_v1","battlefield_count_card_types":["artifact"],"battlefield_count_scope":"controller_battlefield","effect":"creature","power_base_delta":0,"power_delta_per_graveyard_count":1,"stat_modifier_amount_source":"battlefield_permanent_count","static_effect":"source_power_toughness_boost_equal_dynamic_count","target":"self","target_controller":"self","toughness_base_delta":0,"toughness_delta_per_graveyard_count":0,"xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class NimLasher translated into ManaLoom runtime scope xmage_static_source_dynamic_count_boost_v1. This row is package-ready only because the source signature is a narrow creature static source power/toughness boost equal to dynamic count with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('nim shrieker', 'Nim Shrieker', 'ed9cf1defeaa0b4d0662372dcf453648', 'battle_rule_v1:4c1f8e842d5616c5b2274049082691e0', '{"_keywords_are_self":true,"ability_kind":"static","battle_model_scope":"xmage_static_source_dynamic_count_boost_v1","battlefield_count_card_types":["artifact"],"battlefield_count_scope":"controller_battlefield","effect":"creature","flying":true,"keywords":["flying"],"power_base_delta":0,"power_delta_per_graveyard_count":1,"stat_modifier_amount_source":"battlefield_permanent_count","static_effect":"source_power_toughness_boost_equal_dynamic_count","target":"self","target_controller":"self","toughness_base_delta":0,"toughness_delta_per_graveyard_count":0,"xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class NimShrieker translated into ManaLoom runtime scope xmage_static_source_dynamic_count_boost_v1. This row is package-ready only because the source signature is a narrow creature static source power/toughness boost equal to dynamic count with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('rabid wombat', 'Rabid Wombat', '7f50432c0e2410fc6da86a996593dd11', 'battle_rule_v1:fc141de0e3ea087821af50d4818d0adf', '{"_keywords_are_self":true,"ability_kind":"static","attached_count_subtypes":["aura"],"battle_model_scope":"xmage_static_source_dynamic_count_boost_v1","effect":"creature","keywords":["vigilance"],"power_base_delta":0,"power_delta_per_graveyard_count":2,"stat_modifier_amount_source":"attached_permanent_count","static_effect":"source_power_toughness_boost_equal_dynamic_count","target":"self","target_controller":"self","toughness_base_delta":0,"toughness_delta_per_graveyard_count":2,"vigilance":true,"xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class RabidWombat translated into ManaLoom runtime scope xmage_static_source_dynamic_count_boost_v1. This row is package-ready only because the source signature is a narrow creature static source power/toughness boost equal to dynamic count with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('radiant, archangel', 'Radiant, Archangel', '3891ace14402b0a6a3c4cdf8eafb826b', 'battle_rule_v1:81d20423177fdcc5fa4f5e2f527627d4', '{"_keywords_are_self":true,"ability_kind":"static","battle_model_scope":"xmage_static_source_dynamic_count_boost_v1","battlefield_count_card_types":["creature"],"battlefield_count_exclude_source":true,"battlefield_count_keywords":["flying"],"battlefield_count_scope":"all_battlefields","effect":"creature","flying":true,"keywords":["flying","vigilance"],"power_base_delta":0,"power_delta_per_graveyard_count":1,"stat_modifier_amount_source":"battlefield_permanent_count","static_effect":"source_power_toughness_boost_equal_dynamic_count","target":"self","target_controller":"self","toughness_base_delta":0,"toughness_delta_per_graveyard_count":1,"vigilance":true,"xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class RadiantArchangel translated into ManaLoom runtime scope xmage_static_source_dynamic_count_boost_v1. This row is package-ready only because the source signature is a narrow creature static source power/toughness boost equal to dynamic count with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('scourge of geier reach', 'Scourge of Geier Reach', 'ca2645396d7f7f808a5ab44ea9946ded', 'battle_rule_v1:e445e82e5dbf1f938e47e04336503083', '{"ability_kind":"static","battle_model_scope":"xmage_static_source_dynamic_count_boost_v1","battlefield_count_card_types":["creature"],"battlefield_count_scope":"opponents_battlefield","effect":"creature","power_base_delta":0,"power_delta_per_graveyard_count":1,"stat_modifier_amount_source":"battlefield_permanent_count","static_effect":"source_power_toughness_boost_equal_dynamic_count","target":"self","target_controller":"self","toughness_base_delta":0,"toughness_delta_per_graveyard_count":1,"xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ScourgeOfGeierReach translated into ManaLoom runtime scope xmage_static_source_dynamic_count_boost_v1. This row is package-ready only because the source signature is a narrow creature static source power/toughness boost equal to dynamic count with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('uril, the miststalker', 'Uril, the Miststalker', 'c109d186a59792f32e83fecbd8fec7d8', 'battle_rule_v1:cdb97242fd0ba447c2591fe77a79cc52', '{"_keywords_are_self":true,"ability_kind":"static","attached_count_subtypes":["aura"],"battle_model_scope":"xmage_static_source_dynamic_count_boost_v1","effect":"creature","hexproof":true,"keywords":["hexproof"],"power_base_delta":0,"power_delta_per_graveyard_count":2,"stat_modifier_amount_source":"attached_permanent_count","static_effect":"source_power_toughness_boost_equal_dynamic_count","target":"self","target_controller":"self","toughness_base_delta":0,"toughness_delta_per_graveyard_count":2,"xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class UrilTheMiststalker translated into ManaLoom runtime scope xmage_static_source_dynamic_count_boost_v1. This row is package-ready only because the source signature is a narrow creature static source power/toughness boost equal to dynamic count with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('wayfaring giant', 'Wayfaring Giant', '909e5269ad99f22ff8e2a78f8b980a17', 'battle_rule_v1:dd73943dd52b5ce2ca430d651ee572e2', '{"ability_kind":"static","battle_model_scope":"xmage_static_source_dynamic_count_boost_v1","effect":"creature","power_base_delta":0,"power_delta_per_graveyard_count":1,"stat_modifier_amount_source":"domain_basic_land_types","static_effect":"source_power_toughness_boost_equal_dynamic_count","target":"self","target_controller":"self","toughness_base_delta":0,"toughness_delta_per_graveyard_count":1,"xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class WayfaringGiant translated into ManaLoom runtime scope xmage_static_source_dynamic_count_boost_v1. This row is package-ready only because the source signature is a narrow creature static source power/toughness boost equal to dynamic count with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('yavimaya enchantress', 'Yavimaya Enchantress', '228ea59ba2fca7e600a97619a8a0dc21', 'battle_rule_v1:538f4df31a04499c3f413157c67962d1', '{"ability_kind":"static","battle_model_scope":"xmage_static_source_dynamic_count_boost_v1","battlefield_count_card_types":["enchantment"],"battlefield_count_scope":"all_battlefields","effect":"creature","power_base_delta":0,"power_delta_per_graveyard_count":1,"stat_modifier_amount_source":"battlefield_permanent_count","static_effect":"source_power_toughness_boost_equal_dynamic_count","target":"self","target_controller":"self","toughness_base_delta":0,"toughness_delta_per_graveyard_count":1,"xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"BoostSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class YavimayaEnchantress translated into ManaLoom runtime scope xmage_static_source_dynamic_count_boost_v1. This row is package-ready only because the source signature is a narrow creature static source power/toughness boost equal to dynamic count with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
rule_rows AS (
  SELECT
    r.normalized_name,
    r.logical_rule_key,
    r.oracle_hash,
    r.review_status,
    r.execution_status
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key = p.logical_rule_key
)
SELECT
  p.card_name,
  p.normalized_name,
  p.logical_rule_key,
  count(r.*) FILTER (WHERE r.logical_rule_key = p.logical_rule_key) AS promoted_rule_rows,
  count(r.*) FILTER (WHERE r.review_status = 'verified' AND r.execution_status = 'auto') AS promoted_verified_auto_rows,
  count(r.*) FILTER (WHERE r.oracle_hash = p.oracle_hash) AS promoted_oracle_hash_rows,
  (SELECT count(*) FROM manaloom_deploy_audit.pg830_static_dynamic_count_source_boost_20260712_122413) AS backup_rows
FROM proposed p
LEFT JOIN rule_rows r
  ON r.normalized_name = p.normalized_name
 AND r.logical_rule_key = p.logical_rule_key
 AND r.oracle_hash = p.oracle_hash
GROUP BY p.card_name, p.normalized_name, p.logical_rule_key, p.oracle_hash
ORDER BY p.card_name;
