WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('dauntless cathar', 'Dauntless Cathar', '503274f25a5b923875fa25d58f8572d8', 'battle_rule_v1:d91365b63aa1b7f20e2a2f375b597485', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"token_maker","activation_cost_colors":["W"],"activation_cost_generic":1,"activation_cost_mana":"{1}{W}","activation_requires_exile_source_from_graveyard":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"activation_timing":"sorcery","activation_zone":"graveyard","battle_model_scope":"xmage_graveyard_self_exile_activated_create_token_v1","effect":"token_maker","token_colors":["W"],"token_count":1,"token_description":"1/1 white Spirit creature token with flying","token_flying":true,"token_keywords":["flying"],"token_name":"Spirit Token","token_power":1,"token_subtype":"Spirit","token_toughness":1,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"SpiritWhiteToken"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_graveyard_self_exile_activated_create_token_v1","activated_create_token":true,"activated_effect":"token_maker","activation_cost_colors":["W"],"activation_cost_generic":1,"activation_cost_mana":"{1}{W}","activation_requires_exile_source_from_graveyard":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"activation_timing":"sorcery","activation_zone":"graveyard","battle_model_scope":"xmage_graveyard_self_exile_activated_create_token_v1","effect":"creature","token_colors":["W"],"token_count":1,"token_description":"1/1 white Spirit creature token with flying","token_flying":true,"token_keywords":["flying"],"token_name":"Spirit Token","token_power":1,"token_subtype":"Spirit","token_toughness":1,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"SpiritWhiteToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DauntlessCathar translated into ManaLoom runtime scope xmage_graveyard_self_exile_activated_create_token_v1. This row is package-ready only because the source signature is a narrow card with a graveyard self-exile activated fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('fairgrounds patrol', 'Fairgrounds Patrol', '9c759004856fe87d54eb35068d8d9c9a', 'battle_rule_v1:85383cdbcc783b09a1e9b5658d797d1c', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"token_maker","activation_cost_colors":["W"],"activation_cost_generic":1,"activation_cost_mana":"{1}{W}","activation_requires_exile_source_from_graveyard":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"activation_timing":"sorcery","activation_zone":"graveyard","artifact_tokens":true,"battle_model_scope":"xmage_graveyard_self_exile_activated_create_token_v1","effect":"token_maker","token_count":1,"token_description":"1/1 colorless Thopter artifact creature token with flying","token_flying":true,"token_keywords":["flying"],"token_name":"Thopter Token","token_power":1,"token_subtype":"Thopter","token_toughness":1,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"ThopterColorlessToken"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_graveyard_self_exile_activated_create_token_v1","activated_create_token":true,"activated_effect":"token_maker","activation_cost_colors":["W"],"activation_cost_generic":1,"activation_cost_mana":"{1}{W}","activation_requires_exile_source_from_graveyard":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"activation_timing":"sorcery","activation_zone":"graveyard","artifact_tokens":true,"battle_model_scope":"xmage_graveyard_self_exile_activated_create_token_v1","effect":"creature","token_count":1,"token_description":"1/1 colorless Thopter artifact creature token with flying","token_flying":true,"token_keywords":["flying"],"token_name":"Thopter Token","token_power":1,"token_subtype":"Thopter","token_toughness":1,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"ThopterColorlessToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class FairgroundsPatrol translated into ManaLoom runtime scope xmage_graveyard_self_exile_activated_create_token_v1. This row is package-ready only because the source signature is a narrow card with a graveyard self-exile activated fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('ghoulcaller''s accomplice', 'Ghoulcaller''s Accomplice', '0423112d96989eb8cce9052971418fa6', 'battle_rule_v1:908e0de3f16268f1c05c02ae56679eeb', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"token_maker","activation_cost_colors":["B"],"activation_cost_generic":3,"activation_cost_mana":"{3}{B}","activation_requires_exile_source_from_graveyard":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"activation_timing":"sorcery","activation_zone":"graveyard","battle_model_scope":"xmage_graveyard_self_exile_activated_create_token_v1","effect":"token_maker","token_colors":["B"],"token_count":1,"token_description":"2/2 black Zombie creature token","token_name":"Zombie Token","token_power":2,"token_subtype":"Zombie","token_toughness":2,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"ZombieToken"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_graveyard_self_exile_activated_create_token_v1","activated_create_token":true,"activated_effect":"token_maker","activation_cost_colors":["B"],"activation_cost_generic":3,"activation_cost_mana":"{3}{B}","activation_requires_exile_source_from_graveyard":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"activation_timing":"sorcery","activation_zone":"graveyard","battle_model_scope":"xmage_graveyard_self_exile_activated_create_token_v1","effect":"creature","token_colors":["B"],"token_count":1,"token_description":"2/2 black Zombie creature token","token_name":"Zombie Token","token_power":2,"token_subtype":"Zombie","token_toughness":2,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"ZombieToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GhoulcallersAccomplice translated into ManaLoom runtime scope xmage_graveyard_self_exile_activated_create_token_v1. This row is package-ready only because the source signature is a narrow card with a graveyard self-exile activated fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('goldmeadow nomad', 'Goldmeadow Nomad', '62df52a6790b43c793abdbc64e318af0', 'battle_rule_v1:74502a3a5890461af09a16321cbc0377', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"token_maker","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_exile_source_from_graveyard":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"activation_timing":"sorcery","activation_zone":"graveyard","battle_model_scope":"xmage_graveyard_self_exile_activated_create_token_v1","effect":"token_maker","token_colors":["W","G"],"token_count":1,"token_description":"1/1 green and white Kithkin creature token","token_name":"Kithkin Token","token_power":1,"token_subtype":"Kithkin","token_toughness":1,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"KithkinGreenWhiteToken"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_graveyard_self_exile_activated_create_token_v1","activated_create_token":true,"activated_effect":"token_maker","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_exile_source_from_graveyard":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"activation_timing":"sorcery","activation_zone":"graveyard","battle_model_scope":"xmage_graveyard_self_exile_activated_create_token_v1","effect":"creature","token_colors":["W","G"],"token_count":1,"token_description":"1/1 green and white Kithkin creature token","token_name":"Kithkin Token","token_power":1,"token_subtype":"Kithkin","token_toughness":1,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"KithkinGreenWhiteToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GoldmeadowNomad translated into ManaLoom runtime scope xmage_graveyard_self_exile_activated_create_token_v1. This row is package-ready only because the source signature is a narrow card with a graveyard self-exile activated fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('mother bear', 'Mother Bear', '369884547649bfb110918e925e8b7630', 'battle_rule_v1:6e475c3e7d19e8e38b1eb3482c624625', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"token_maker","activation_cost_colors":["G","G"],"activation_cost_generic":3,"activation_cost_mana":"{3}{G}{G}","activation_requires_exile_source_from_graveyard":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"activation_timing":"sorcery","activation_zone":"graveyard","battle_model_scope":"xmage_graveyard_self_exile_activated_create_token_v1","effect":"token_maker","token_colors":["G"],"token_count":2,"token_description":"2/2 green Bear creature token","token_name":"Bear Token","token_power":2,"token_subtype":"Bear","token_toughness":2,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"BearToken"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_graveyard_self_exile_activated_create_token_v1","activated_create_token":true,"activated_effect":"token_maker","activation_cost_colors":["G","G"],"activation_cost_generic":3,"activation_cost_mana":"{3}{G}{G}","activation_requires_exile_source_from_graveyard":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"activation_timing":"sorcery","activation_zone":"graveyard","battle_model_scope":"xmage_graveyard_self_exile_activated_create_token_v1","effect":"creature","token_colors":["G"],"token_count":2,"token_description":"2/2 green Bear creature token","token_name":"Bear Token","token_power":2,"token_subtype":"Bear","token_toughness":2,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"BearToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MotherBear translated into ManaLoom runtime scope xmage_graveyard_self_exile_activated_create_token_v1. This row is package-ready only because the source signature is a narrow card with a graveyard self-exile activated fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('stoic grove-guide', 'Stoic Grove-Guide', 'd7f9e7847e9b1b97a09a0b6aaabcc67d', 'battle_rule_v1:3742d752972faa58cb3e08d8910f3754', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"token_maker","activation_cost_colors":["B/G"],"activation_cost_generic":1,"activation_cost_mana":"{1}{B/G}","activation_requires_exile_source_from_graveyard":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"activation_timing":"sorcery","activation_zone":"graveyard","battle_model_scope":"xmage_graveyard_self_exile_activated_create_token_v1","effect":"token_maker","token_colors":["B","G"],"token_count":1,"token_description":"2/2 black and green Elf creature token","token_name":"Elf Token","token_power":2,"token_subtype":"Elf","token_toughness":2,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"BlackGreenElfToken"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_graveyard_self_exile_activated_create_token_v1","activated_create_token":true,"activated_effect":"token_maker","activation_cost_colors":["B/G"],"activation_cost_generic":1,"activation_cost_mana":"{1}{B/G}","activation_requires_exile_source_from_graveyard":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"activation_timing":"sorcery","activation_zone":"graveyard","battle_model_scope":"xmage_graveyard_self_exile_activated_create_token_v1","effect":"creature","token_colors":["B","G"],"token_count":1,"token_description":"2/2 black and green Elf creature token","token_name":"Elf Token","token_power":2,"token_subtype":"Elf","token_toughness":2,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"BlackGreenElfToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class StoicGroveGuide translated into ManaLoom runtime scope xmage_graveyard_self_exile_activated_create_token_v1. This row is package-ready only because the source signature is a narrow card with a graveyard self-exile activated fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('suspicious shambler', 'Suspicious Shambler', 'a13b163c0b4079f3298879b840969cc8', 'battle_rule_v1:16e44600ebc45e610d7b633213672a78', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"token_maker","activation_cost_colors":["B","B"],"activation_cost_generic":4,"activation_cost_mana":"{4}{B}{B}","activation_requires_exile_source_from_graveyard":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"activation_timing":"sorcery","activation_zone":"graveyard","battle_model_scope":"xmage_graveyard_self_exile_activated_create_token_v1","effect":"token_maker","token_colors":["B"],"token_count":2,"token_description":"2/2 black Zombie creature token","token_name":"Zombie Token","token_power":2,"token_subtype":"Zombie","token_toughness":2,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"ZombieToken"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_graveyard_self_exile_activated_create_token_v1","activated_create_token":true,"activated_effect":"token_maker","activation_cost_colors":["B","B"],"activation_cost_generic":4,"activation_cost_mana":"{4}{B}{B}","activation_requires_exile_source_from_graveyard":true,"activation_requires_sacrifice":false,"activation_requires_tap":false,"activation_timing":"sorcery","activation_zone":"graveyard","battle_model_scope":"xmage_graveyard_self_exile_activated_create_token_v1","effect":"creature","token_colors":["B"],"token_count":2,"token_description":"2/2 black Zombie creature token","token_name":"Zombie Token","token_power":2,"token_subtype":"Zombie","token_toughness":2,"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"CreateTokenEffect","xmage_token_class":"ZombieToken"}'::jsonb, '{"category":"unknown","effect":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SuspiciousShambler translated into ManaLoom runtime scope xmage_graveyard_self_exile_activated_create_token_v1. This row is package-ready only because the source signature is a narrow card with a graveyard self-exile activated fixed creature-token ability with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
matched_cards AS (
  SELECT
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    c.id AS card_id,
    c.name AS db_card_name
  FROM proposed p
  LEFT JOIN public.cards c
    ON (
         lower(c.name) = p.normalized_name
         OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
       )
   AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
),
target_cards AS (
  SELECT
    normalized_name,
    card_name,
    oracle_hash,
    count(card_id) AS target_card_rows,
    min(card_id::text)::uuid AS canonical_card_id,
    min(db_card_name) AS canonical_card_name
  FROM matched_cards
  GROUP BY normalized_name, card_name, oracle_hash
),
rule_rows AS (
  SELECT p.normalized_name, count(r.*) AS existing_rule_rows
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
  GROUP BY p.normalized_name
),
expected_rows AS (
  SELECT p.normalized_name, count(r.*) AS expected_rule_rows_before
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key = p.logical_rule_key
  GROUP BY p.normalized_name
),
shadow_rows AS (
  SELECT p.normalized_name, count(r.*) AS would_deprecate_shadow_rows
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key <> p.logical_rule_key
   AND r.review_status NOT IN ('deprecated', 'rejected')
   AND r.execution_status <> 'disabled'
  GROUP BY p.normalized_name
)
SELECT
  p.card_name,
  p.normalized_name,
  p.oracle_hash,
  p.logical_rule_key,
  p.shadow_handling,
  tc.target_card_rows,
  tc.canonical_card_id,
  rr.existing_rule_rows,
  er.expected_rule_rows_before,
  sr.would_deprecate_shadow_rows
FROM proposed p
JOIN target_cards tc USING (normalized_name, card_name, oracle_hash)
JOIN rule_rows rr USING (normalized_name)
JOIN expected_rows er USING (normalized_name)
JOIN shadow_rows sr USING (normalized_name)
ORDER BY p.card_name;
