WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('ballyrush banneret', 'Ballyrush Banneret', '589c49cee1133cebf35e67323cdeb6ad', 'battle_rule_v1:d9038ce0eaf069a46c6adec11dfe830a', '{"ability_kind":"static","applies_to_subtypes":["kithkin","soldier"],"battle_model_scope":"xmage_static_generic_cost_reduction_for_matching_spells_v1","cost_reduction_amount_source":"fixed","cost_reduction_applies_to":"spells_you_cast","cost_reduction_generic":1,"effect":"static_cost_reduction","permanent_type":"creature","static_effect":"generic_cost_reduction_for_matching_spells","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"SpellsCostReductionControllerEffect"}'::jsonb, '{"category":"support","effect":"static_cost_reduction"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BallyrushBanneret translated into ManaLoom runtime scope xmage_static_generic_cost_reduction_for_matching_spells_v1. This row is package-ready only because the source signature is a narrow permanent static generic cost reduction for matching spells you cast with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('bosk banneret', 'Bosk Banneret', 'd3324f2d1b46468d7f05127501069a3d', 'battle_rule_v1:1082b4a59a4e4ab45b36cec3ceb31fd8', '{"ability_kind":"static","applies_to_subtypes":["shaman","treefolk"],"battle_model_scope":"xmage_static_generic_cost_reduction_for_matching_spells_v1","cost_reduction_amount_source":"fixed","cost_reduction_applies_to":"spells_you_cast","cost_reduction_generic":1,"effect":"static_cost_reduction","permanent_type":"creature","static_effect":"generic_cost_reduction_for_matching_spells","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"SpellsCostReductionControllerEffect"}'::jsonb, '{"category":"support","effect":"static_cost_reduction"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BoskBanneret translated into ManaLoom runtime scope xmage_static_generic_cost_reduction_for_matching_spells_v1. This row is package-ready only because the source signature is a narrow permanent static generic cost reduction for matching spells you cast with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('dragonlord''s servant', 'Dragonlord''s Servant', '993790878a196bc1041b1293108367cb', 'battle_rule_v1:ec77f894d6594b7dd449e88da78f7a8e', '{"ability_kind":"static","applies_to_subtypes":["dragon"],"battle_model_scope":"xmage_static_generic_cost_reduction_for_matching_spells_v1","cost_reduction_amount_source":"fixed","cost_reduction_applies_to":"spells_you_cast","cost_reduction_generic":1,"effect":"static_cost_reduction","permanent_type":"creature","static_effect":"generic_cost_reduction_for_matching_spells","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"SpellsCostReductionControllerEffect"}'::jsonb, '{"category":"support","effect":"static_cost_reduction"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DragonlordsServant translated into ManaLoom runtime scope xmage_static_generic_cost_reduction_for_matching_spells_v1. This row is package-ready only because the source signature is a narrow permanent static generic cost reduction for matching spells you cast with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('dragonspeaker shaman', 'Dragonspeaker Shaman', 'd684de81aea07cbc6905869004f5aeb4', 'battle_rule_v1:3a0439051970f6c4ec1bf8ffc0efe3e3', '{"ability_kind":"static","applies_to_subtypes":["dragon"],"battle_model_scope":"xmage_static_generic_cost_reduction_for_matching_spells_v1","cost_reduction_amount_source":"fixed","cost_reduction_applies_to":"spells_you_cast","cost_reduction_generic":2,"effect":"static_cost_reduction","permanent_type":"creature","static_effect":"generic_cost_reduction_for_matching_spells","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"SpellsCostReductionControllerEffect"}'::jsonb, '{"category":"support","effect":"static_cost_reduction"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DragonspeakerShaman translated into ManaLoom runtime scope xmage_static_generic_cost_reduction_for_matching_spells_v1. This row is package-ready only because the source signature is a narrow permanent static generic cost reduction for matching spells you cast with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('emerald medallion', 'Emerald Medallion', '64d37738e6d200489451c7be9b5da3c9', 'battle_rule_v1:d1575b7e349debdcc00cb11a81a98d63', '{"ability_kind":"static","applies_to_spell_colors":["G"],"battle_model_scope":"xmage_static_generic_cost_reduction_for_matching_spells_v1","cost_reduction_amount_source":"fixed","cost_reduction_applies_to":"spells_you_cast","cost_reduction_generic":1,"effect":"static_cost_reduction","permanent_type":"artifact","static_effect":"generic_cost_reduction_for_matching_spells","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"SpellsCostReductionControllerEffect"}'::jsonb, '{"category":"support","effect":"static_cost_reduction"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class EmeraldMedallion translated into ManaLoom runtime scope xmage_static_generic_cost_reduction_for_matching_spells_v1. This row is package-ready only because the source signature is a narrow permanent static generic cost reduction for matching spells you cast with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('etherium sculptor', 'Etherium Sculptor', 'ea60d391afb6f2d73cdd177b45a726b7', 'battle_rule_v1:8dc1c1998408b6b4f9e1541bfc587170', '{"ability_kind":"static","applies_to_card_types":["artifact"],"battle_model_scope":"xmage_static_generic_cost_reduction_for_matching_spells_v1","cost_reduction_amount_source":"fixed","cost_reduction_applies_to":"spells_you_cast","cost_reduction_generic":1,"effect":"static_cost_reduction","permanent_type":"creature","static_effect":"generic_cost_reduction_for_matching_spells","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"SpellsCostReductionControllerEffect"}'::jsonb, '{"category":"support","effect":"static_cost_reduction"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class EtheriumSculptor translated into ManaLoom runtime scope xmage_static_generic_cost_reduction_for_matching_spells_v1. This row is package-ready only because the source signature is a narrow permanent static generic cost reduction for matching spells you cast with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('foundry inspector', 'Foundry Inspector', 'ea60d391afb6f2d73cdd177b45a726b7', 'battle_rule_v1:8dc1c1998408b6b4f9e1541bfc587170', '{"ability_kind":"static","applies_to_card_types":["artifact"],"battle_model_scope":"xmage_static_generic_cost_reduction_for_matching_spells_v1","cost_reduction_amount_source":"fixed","cost_reduction_applies_to":"spells_you_cast","cost_reduction_generic":1,"effect":"static_cost_reduction","permanent_type":"creature","static_effect":"generic_cost_reduction_for_matching_spells","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"SpellsCostReductionControllerEffect"}'::jsonb, '{"category":"support","effect":"static_cost_reduction"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class FoundryInspector translated into ManaLoom runtime scope xmage_static_generic_cost_reduction_for_matching_spells_v1. This row is package-ready only because the source signature is a narrow permanent static generic cost reduction for matching spells you cast with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('goblin anarchomancer', 'Goblin Anarchomancer', '7791d9cf6f6733acb73703aaf966ec7a', 'battle_rule_v1:69dcc05d941ebeb0ff30d84d2f79a2a4', '{"ability_kind":"static","applies_to_spell_colors":["R","G"],"battle_model_scope":"xmage_static_generic_cost_reduction_for_matching_spells_v1","cost_reduction_amount_source":"fixed","cost_reduction_applies_to":"spells_you_cast","cost_reduction_generic":1,"effect":"static_cost_reduction","permanent_type":"creature","static_effect":"generic_cost_reduction_for_matching_spells","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"SpellsCostReductionControllerEffect"}'::jsonb, '{"category":"support","effect":"static_cost_reduction"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GoblinAnarchomancer translated into ManaLoom runtime scope xmage_static_generic_cost_reduction_for_matching_spells_v1. This row is package-ready only because the source signature is a narrow permanent static generic cost reduction for matching spells you cast with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('goblin electromancer', 'Goblin Electromancer', '08a5f3901b3bc8297adecdc0e40b934d', 'battle_rule_v1:97742df754bd4727c76acdff9b052bcd', '{"ability_kind":"static","applies_to_card_types":["instant","sorcery"],"battle_model_scope":"xmage_static_generic_cost_reduction_for_matching_spells_v1","cost_reduction_amount_source":"fixed","cost_reduction_applies_to":"spells_you_cast","cost_reduction_generic":1,"effect":"static_cost_reduction","permanent_type":"creature","static_effect":"generic_cost_reduction_for_matching_spells","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"SpellsCostReductionControllerEffect"}'::jsonb, '{"category":"support","effect":"static_cost_reduction"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GoblinElectromancer translated into ManaLoom runtime scope xmage_static_generic_cost_reduction_for_matching_spells_v1. This row is package-ready only because the source signature is a narrow permanent static generic cost reduction for matching spells you cast with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('jet medallion', 'Jet Medallion', '235bf306c30e7aa38b4ff6eb6f9c9b60', 'battle_rule_v1:60eb5ad36259e78de7afd7602355822d', '{"ability_kind":"static","applies_to_spell_colors":["B"],"battle_model_scope":"xmage_static_generic_cost_reduction_for_matching_spells_v1","cost_reduction_amount_source":"fixed","cost_reduction_applies_to":"spells_you_cast","cost_reduction_generic":1,"effect":"static_cost_reduction","permanent_type":"artifact","static_effect":"generic_cost_reduction_for_matching_spells","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"SpellsCostReductionControllerEffect"}'::jsonb, '{"category":"support","effect":"static_cost_reduction"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class JetMedallion translated into ManaLoom runtime scope xmage_static_generic_cost_reduction_for_matching_spells_v1. This row is package-ready only because the source signature is a narrow permanent static generic cost reduction for matching spells you cast with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('kinjalli''s caller', 'Kinjalli''s Caller', 'ebac3e19b660e42254f82764f5f431c5', 'battle_rule_v1:24778ef9c8f9902d9cc486d10184fcf8', '{"ability_kind":"static","applies_to_subtypes":["dinosaur"],"battle_model_scope":"xmage_static_generic_cost_reduction_for_matching_spells_v1","cost_reduction_amount_source":"fixed","cost_reduction_applies_to":"spells_you_cast","cost_reduction_generic":1,"effect":"static_cost_reduction","permanent_type":"creature","static_effect":"generic_cost_reduction_for_matching_spells","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"SpellsCostReductionControllerEffect"}'::jsonb, '{"category":"support","effect":"static_cost_reduction"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class KinjallisCaller translated into ManaLoom runtime scope xmage_static_generic_cost_reduction_for_matching_spells_v1. This row is package-ready only because the source signature is a narrow permanent static generic cost reduction for matching spells you cast with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('knight of the stampede', 'Knight of the Stampede', '4aff3918f7e6039d76a78942acd0e9c3', 'battle_rule_v1:e5391f735165a635c5529d0516f52b32', '{"ability_kind":"static","applies_to_subtypes":["dinosaur"],"battle_model_scope":"xmage_static_generic_cost_reduction_for_matching_spells_v1","cost_reduction_amount_source":"fixed","cost_reduction_applies_to":"spells_you_cast","cost_reduction_generic":2,"effect":"static_cost_reduction","permanent_type":"creature","static_effect":"generic_cost_reduction_for_matching_spells","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"SpellsCostReductionControllerEffect"}'::jsonb, '{"category":"support","effect":"static_cost_reduction"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class KnightOfTheStampede translated into ManaLoom runtime scope xmage_static_generic_cost_reduction_for_matching_spells_v1. This row is package-ready only because the source signature is a narrow permanent static generic cost reduction for matching spells you cast with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('krosan drover', 'Krosan Drover', 'c892e97e4e4ac391aca9f3ea98214475', 'battle_rule_v1:f65dffd9475e2bf6158dc2953ed0c0c0', '{"ability_kind":"static","applies_to_card_types":["creature"],"battle_model_scope":"xmage_static_generic_cost_reduction_for_matching_spells_v1","cost_reduction_amount_source":"fixed","cost_reduction_applies_to":"spells_you_cast","cost_reduction_generic":2,"effect":"static_cost_reduction","mana_value_min":6,"permanent_type":"creature","static_effect":"generic_cost_reduction_for_matching_spells","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"SpellsCostReductionControllerEffect"}'::jsonb, '{"category":"support","effect":"static_cost_reduction"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class KrosanDrover translated into ManaLoom runtime scope xmage_static_generic_cost_reduction_for_matching_spells_v1. This row is package-ready only because the source signature is a narrow permanent static generic cost reduction for matching spells you cast with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('mana matrix', 'Mana Matrix', '6971bbb583a7cb8107874e1134765dc0', 'battle_rule_v1:65c4b5011824391362541154c43048dd', '{"ability_kind":"static","applies_to_card_types":["enchantment","instant"],"battle_model_scope":"xmage_static_generic_cost_reduction_for_matching_spells_v1","cost_reduction_amount_source":"fixed","cost_reduction_applies_to":"spells_you_cast","cost_reduction_generic":2,"effect":"static_cost_reduction","permanent_type":"artifact","static_effect":"generic_cost_reduction_for_matching_spells","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"SpellsCostReductionControllerEffect"}'::jsonb, '{"category":"support","effect":"static_cost_reduction"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ManaMatrix translated into ManaLoom runtime scope xmage_static_generic_cost_reduction_for_matching_spells_v1. This row is package-ready only because the source signature is a narrow permanent static generic cost reduction for matching spells you cast with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('planar gate', 'Planar Gate', '82947868876564380f84066647d242fa', 'battle_rule_v1:b544492e418127e41bca5abc1a8b4f89', '{"ability_kind":"static","applies_to_card_types":["creature"],"battle_model_scope":"xmage_static_generic_cost_reduction_for_matching_spells_v1","cost_reduction_amount_source":"fixed","cost_reduction_applies_to":"spells_you_cast","cost_reduction_generic":2,"effect":"static_cost_reduction","permanent_type":"artifact","static_effect":"generic_cost_reduction_for_matching_spells","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"SpellsCostReductionControllerEffect"}'::jsonb, '{"category":"support","effect":"static_cost_reduction"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PlanarGate translated into ManaLoom runtime scope xmage_static_generic_cost_reduction_for_matching_spells_v1. This row is package-ready only because the source signature is a narrow permanent static generic cost reduction for matching spells you cast with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sapphire medallion', 'Sapphire Medallion', 'ce0b6343ccf5f7701f575fb94834a23c', 'battle_rule_v1:f00d642df9881613f42056f752390e6f', '{"ability_kind":"static","applies_to_spell_colors":["U"],"battle_model_scope":"xmage_static_generic_cost_reduction_for_matching_spells_v1","cost_reduction_amount_source":"fixed","cost_reduction_applies_to":"spells_you_cast","cost_reduction_generic":1,"effect":"static_cost_reduction","permanent_type":"artifact","static_effect":"generic_cost_reduction_for_matching_spells","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"SpellsCostReductionControllerEffect"}'::jsonb, '{"category":"support","effect":"static_cost_reduction"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SapphireMedallion translated into ManaLoom runtime scope xmage_static_generic_cost_reduction_for_matching_spells_v1. This row is package-ready only because the source signature is a narrow permanent static generic cost reduction for matching spells you cast with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('starnheim aspirant', 'Starnheim Aspirant', 'b1dfb8cd144123ab09f7bde37fed9cf4', 'battle_rule_v1:c8dd17b96b2f406548230a80e7cb721c', '{"ability_kind":"static","applies_to_subtypes":["angel"],"battle_model_scope":"xmage_static_generic_cost_reduction_for_matching_spells_v1","cost_reduction_amount_source":"fixed","cost_reduction_applies_to":"spells_you_cast","cost_reduction_generic":2,"effect":"static_cost_reduction","permanent_type":"creature","static_effect":"generic_cost_reduction_for_matching_spells","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"SpellsCostReductionControllerEffect"}'::jsonb, '{"category":"support","effect":"static_cost_reduction"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class StarnheimAspirant translated into ManaLoom runtime scope xmage_static_generic_cost_reduction_for_matching_spells_v1. This row is package-ready only because the source signature is a narrow permanent static generic cost reduction for matching spells you cast with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('stinkdrinker daredevil', 'Stinkdrinker Daredevil', 'e6eeeb0647bed579b15b973498287c81', 'battle_rule_v1:40afd6630f0f910d931a3c03a6ccef2a', '{"ability_kind":"static","applies_to_subtypes":["giant"],"battle_model_scope":"xmage_static_generic_cost_reduction_for_matching_spells_v1","cost_reduction_amount_source":"fixed","cost_reduction_applies_to":"spells_you_cast","cost_reduction_generic":2,"effect":"static_cost_reduction","permanent_type":"creature","static_effect":"generic_cost_reduction_for_matching_spells","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"SpellsCostReductionControllerEffect"}'::jsonb, '{"category":"support","effect":"static_cost_reduction"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class StinkdrinkerDaredevil translated into ManaLoom runtime scope xmage_static_generic_cost_reduction_for_matching_spells_v1. This row is package-ready only because the source signature is a narrow permanent static generic cost reduction for matching spells you cast with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('stone calendar', 'Stone Calendar', 'a44e1e3215d3972e3634f7d0eeef2791', 'battle_rule_v1:6abb2de88eac5fd4d683b0b51d82401a', '{"ability_kind":"static","battle_model_scope":"xmage_static_generic_cost_reduction_for_matching_spells_v1","cost_reduction_amount_source":"fixed","cost_reduction_applies_to":"spells_you_cast","cost_reduction_generic":1,"effect":"static_cost_reduction","permanent_type":"artifact","static_effect":"generic_cost_reduction_for_matching_spells","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"SpellsCostReductionControllerEffect"}'::jsonb, '{"category":"support","effect":"static_cost_reduction"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class StoneCalendar translated into ManaLoom runtime scope xmage_static_generic_cost_reduction_for_matching_spells_v1. This row is package-ready only because the source signature is a narrow permanent static generic cost reduction for matching spells you cast with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('thornscape familiar', 'Thornscape Familiar', 'e77945e49db81da34c5c87bba147020a', 'battle_rule_v1:04cc4c542745fa6b0f95ee27afa30335', '{"ability_kind":"static","applies_to_spell_colors":["W","R"],"battle_model_scope":"xmage_static_generic_cost_reduction_for_matching_spells_v1","cost_reduction_amount_source":"fixed","cost_reduction_applies_to":"spells_you_cast","cost_reduction_generic":1,"effect":"static_cost_reduction","permanent_type":"creature","static_effect":"generic_cost_reduction_for_matching_spells","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"SpellsCostReductionControllerEffect"}'::jsonb, '{"category":"support","effect":"static_cost_reduction"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ThornscapeFamiliar translated into ManaLoom runtime scope xmage_static_generic_cost_reduction_for_matching_spells_v1. This row is package-ready only because the source signature is a narrow permanent static generic cost reduction for matching spells you cast with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('voyager quickwelder', 'Voyager Quickwelder', 'ea60d391afb6f2d73cdd177b45a726b7', 'battle_rule_v1:8dc1c1998408b6b4f9e1541bfc587170', '{"ability_kind":"static","applies_to_card_types":["artifact"],"battle_model_scope":"xmage_static_generic_cost_reduction_for_matching_spells_v1","cost_reduction_amount_source":"fixed","cost_reduction_applies_to":"spells_you_cast","cost_reduction_generic":1,"effect":"static_cost_reduction","permanent_type":"creature","static_effect":"generic_cost_reduction_for_matching_spells","xmage_ability_class":"SimpleStaticAbility","xmage_effect_class":"SpellsCostReductionControllerEffect"}'::jsonb, '{"category":"support","effect":"static_cost_reduction"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class VoyagerQuickwelder translated into ManaLoom runtime scope xmage_static_generic_cost_reduction_for_matching_spells_v1. This row is package-ready only because the source signature is a narrow permanent static generic cost reduction for matching spells you cast with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
matched_cards AS (
  SELECT
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    c.id AS card_id,
    c.name AS db_card_name
  FROM proposed p
  LEFT JOIN public.cards c
    ON (
         lower(c.name) = p.normalized_name
         OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
       )
   AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
),
target_cards AS (
  SELECT
    normalized_name,
    card_name,
    oracle_hash,
    count(card_id) AS target_card_rows,
    min(card_id::text)::uuid AS canonical_card_id,
    min(db_card_name) AS canonical_card_name
  FROM matched_cards
  GROUP BY normalized_name, card_name, oracle_hash
),
rule_rows AS (
  SELECT p.normalized_name, count(r.*) AS existing_rule_rows
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
  GROUP BY p.normalized_name
),
expected_rows AS (
  SELECT p.normalized_name, count(r.*) AS expected_rule_rows_before
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key = p.logical_rule_key
  GROUP BY p.normalized_name
),
shadow_rows AS (
  SELECT p.normalized_name, count(r.*) AS would_deprecate_shadow_rows
  FROM proposed p
  LEFT JOIN public.card_battle_rules r
    ON (
         r.normalized_name = p.normalized_name
         OR r.normalized_name LIKE p.normalized_name || ' // %'
       )
   AND r.logical_rule_key <> p.logical_rule_key
   AND r.review_status NOT IN ('deprecated', 'rejected')
   AND r.execution_status <> 'disabled'
  GROUP BY p.normalized_name
)
SELECT
  p.card_name,
  p.normalized_name,
  p.oracle_hash,
  p.logical_rule_key,
  p.shadow_handling,
  tc.target_card_rows,
  tc.canonical_card_id,
  rr.existing_rule_rows,
  er.expected_rule_rows_before,
  sr.would_deprecate_shadow_rows
FROM proposed p
JOIN target_cards tc USING (normalized_name, card_name, oracle_hash)
JOIN rule_rows rr USING (normalized_name)
JOIN expected_rows er USING (normalized_name)
JOIN shadow_rows sr USING (normalized_name)
ORDER BY p.card_name;
