BEGIN;

CREATE SCHEMA IF NOT EXISTS manaloom_deploy_audit;

CREATE TABLE IF NOT EXISTS manaloom_deploy_audit.pg612_restricted_tap_target_new_server_20260707_114017 AS
SELECT *
FROM public.card_battle_rules
WHERE normalized_name IN ('ali baba', 'coeurl', 'kitsune diviner', 'law-rune enforcer', 'sigardian priest', 'sterling keykeeper', 'storm front')
   OR normalized_name LIKE 'ali baba // %'
   OR normalized_name LIKE 'coeurl // %'
   OR normalized_name LIKE 'kitsune diviner // %'
   OR normalized_name LIKE 'law-rune enforcer // %'
   OR normalized_name LIKE 'sigardian priest // %'
   OR normalized_name LIKE 'sterling keykeeper // %'
   OR normalized_name LIKE 'storm front // %';

DO $$
DECLARE
  v_missing jsonb;
BEGIN
  WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('ali baba', 'Ali Baba', '9d2a321e3c668d8a701485c346c42c1a', 'battle_rule_v1:f3d57d6ac678195ce05ee4e8e781b39c', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"wall_creature","activation_cost_colors":["R"],"activation_cost_generic":0,"activation_cost_mana":"{R}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"wall_creature","target_constraints":{"card_types":["creature"],"required_subtypes":["wall"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"wall_creature","activation_cost_colors":["R"],"activation_cost_generic":0,"activation_cost_mana":"{R}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"wall_creature","target_constraints":{"card_types":["creature"],"required_subtypes":["wall"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"wall_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AliBaba translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('coeurl', 'Coeurl', 'dc320bded3c84b47cf4dda77e8a61525', 'battle_rule_v1:b416e913affdf6c3acced3e0aa5cad3b', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"nonenchantment_creature","activation_cost_colors":["W"],"activation_cost_generic":1,"activation_cost_mana":"{1}{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"nonenchantment_creature","target_constraints":{"card_types":["creature"],"exclude_card_types":["enchantment"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"nonenchantment_creature","activation_cost_colors":["W"],"activation_cost_generic":1,"activation_cost_mana":"{1}{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"nonenchantment_creature","target_constraints":{"card_types":["creature"],"exclude_card_types":["enchantment"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"nonenchantment_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Coeurl translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('kitsune diviner', 'Kitsune Diviner', '917ed923cf08e4a8073b524b16174e7a', 'battle_rule_v1:292dafa735745dd648240e2e7adf5f80', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"spirit_creature","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"spirit_creature","target_constraints":{"card_types":["creature"],"required_subtypes":["spirit"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"spirit_creature","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"spirit_creature","target_constraints":{"card_types":["creature"],"required_subtypes":["spirit"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"spirit_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class KitsuneDiviner translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('law-rune enforcer', 'Law-Rune Enforcer', '8844325fa17c7065e2a8d621dde94fa2', 'battle_rule_v1:4f355610aaa475281bb90e85180ca261', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature_mana_value_2_or_greater","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature_mana_value_2_or_greater","target_constraints":{"card_types":["creature"],"mana_value_min":2},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature_mana_value_2_or_greater","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature_mana_value_2_or_greater","target_constraints":{"card_types":["creature"],"mana_value_min":2},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature_mana_value_2_or_greater"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class LawRuneEnforcer translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sigardian priest', 'Sigardian Priest', 'df262801a1beb003dc72e34e4cdcf5d5', 'battle_rule_v1:9cae008fc7e7c5dd76fc3d5bbec0b55c', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"non_human_creature","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"non_human_creature","target_constraints":{"card_types":["creature"],"exclude_subtypes":["human"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"non_human_creature","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"non_human_creature","target_constraints":{"card_types":["creature"],"exclude_subtypes":["human"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"non_human_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SigardianPriest translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sterling keykeeper', 'Sterling Keykeeper', '69ca93bc4e3d96263ce9c8727524865f', 'battle_rule_v1:79c8df6d7b60de0c04ce52c71d7cf16c', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"non_mount_creature","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{2}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"non_mount_creature","target_constraints":{"card_types":["creature"],"exclude_subtypes":["mount"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"non_mount_creature","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{2}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"non_mount_creature","target_constraints":{"card_types":["creature"],"exclude_subtypes":["mount"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"non_mount_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SterlingKeykeeper translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('storm front', 'Storm Front', '2345441c7f4fa2a3adce46ca934931de', 'battle_rule_v1:369f1e4c26619dbdfb3a20640fe95cbf', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"flying_creature","activation_cost_colors":["G","G"],"activation_cost_generic":0,"activation_cost_mana":"{G}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"flying_creature","target_constraints":{"card_types":["creature"],"required_keywords":["flying"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"flying_creature","activation_cost_colors":["G","G"],"activation_cost_generic":0,"activation_cost_mana":"{G}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"enchantment","target":"flying_creature","target_constraints":{"card_types":["creature"],"required_keywords":["flying"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"enchantment","target":"flying_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class StormFront translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
  counts AS (
    SELECT
      p.card_name,
      p.normalized_name,
      p.oracle_hash,
      count(c.id) AS target_card_rows,
      min(c.id::text)::uuid AS canonical_card_id
    FROM proposed p
    LEFT JOIN public.cards c
      ON (
           lower(c.name) = p.normalized_name
           OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
         )
     AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
    GROUP BY p.card_name, p.normalized_name, p.oracle_hash
  )
  SELECT jsonb_agg(counts ORDER BY card_name)
    INTO v_missing
  FROM counts
  WHERE target_card_rows < 1;

  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION 'XMage batch package abort: expected at least one Oracle-hash-matched card row for every proposed card: %', v_missing;
  END IF;
END $$;

WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('ali baba', 'Ali Baba', '9d2a321e3c668d8a701485c346c42c1a', 'battle_rule_v1:f3d57d6ac678195ce05ee4e8e781b39c', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"wall_creature","activation_cost_colors":["R"],"activation_cost_generic":0,"activation_cost_mana":"{R}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"wall_creature","target_constraints":{"card_types":["creature"],"required_subtypes":["wall"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"wall_creature","activation_cost_colors":["R"],"activation_cost_generic":0,"activation_cost_mana":"{R}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"wall_creature","target_constraints":{"card_types":["creature"],"required_subtypes":["wall"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"wall_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AliBaba translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('coeurl', 'Coeurl', 'dc320bded3c84b47cf4dda77e8a61525', 'battle_rule_v1:b416e913affdf6c3acced3e0aa5cad3b', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"nonenchantment_creature","activation_cost_colors":["W"],"activation_cost_generic":1,"activation_cost_mana":"{1}{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"nonenchantment_creature","target_constraints":{"card_types":["creature"],"exclude_card_types":["enchantment"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"nonenchantment_creature","activation_cost_colors":["W"],"activation_cost_generic":1,"activation_cost_mana":"{1}{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"nonenchantment_creature","target_constraints":{"card_types":["creature"],"exclude_card_types":["enchantment"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"nonenchantment_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Coeurl translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('kitsune diviner', 'Kitsune Diviner', '917ed923cf08e4a8073b524b16174e7a', 'battle_rule_v1:292dafa735745dd648240e2e7adf5f80', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"spirit_creature","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"spirit_creature","target_constraints":{"card_types":["creature"],"required_subtypes":["spirit"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"spirit_creature","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"spirit_creature","target_constraints":{"card_types":["creature"],"required_subtypes":["spirit"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"spirit_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class KitsuneDiviner translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('law-rune enforcer', 'Law-Rune Enforcer', '8844325fa17c7065e2a8d621dde94fa2', 'battle_rule_v1:4f355610aaa475281bb90e85180ca261', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature_mana_value_2_or_greater","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature_mana_value_2_or_greater","target_constraints":{"card_types":["creature"],"mana_value_min":2},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature_mana_value_2_or_greater","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature_mana_value_2_or_greater","target_constraints":{"card_types":["creature"],"mana_value_min":2},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature_mana_value_2_or_greater"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class LawRuneEnforcer translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sigardian priest', 'Sigardian Priest', 'df262801a1beb003dc72e34e4cdcf5d5', 'battle_rule_v1:9cae008fc7e7c5dd76fc3d5bbec0b55c', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"non_human_creature","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"non_human_creature","target_constraints":{"card_types":["creature"],"exclude_subtypes":["human"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"non_human_creature","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"non_human_creature","target_constraints":{"card_types":["creature"],"exclude_subtypes":["human"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"non_human_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SigardianPriest translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sterling keykeeper', 'Sterling Keykeeper', '69ca93bc4e3d96263ce9c8727524865f', 'battle_rule_v1:79c8df6d7b60de0c04ce52c71d7cf16c', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"non_mount_creature","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{2}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"non_mount_creature","target_constraints":{"card_types":["creature"],"exclude_subtypes":["mount"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"non_mount_creature","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{2}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"non_mount_creature","target_constraints":{"card_types":["creature"],"exclude_subtypes":["mount"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"non_mount_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SterlingKeykeeper translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('storm front', 'Storm Front', '2345441c7f4fa2a3adce46ca934931de', 'battle_rule_v1:369f1e4c26619dbdfb3a20640fe95cbf', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"flying_creature","activation_cost_colors":["G","G"],"activation_cost_generic":0,"activation_cost_mana":"{G}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"flying_creature","target_constraints":{"card_types":["creature"],"required_keywords":["flying"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"flying_creature","activation_cost_colors":["G","G"],"activation_cost_generic":0,"activation_cost_mana":"{G}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"enchantment","target":"flying_creature","target_constraints":{"card_types":["creature"],"required_keywords":["flying"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"enchantment","target":"flying_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class StormFront translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
deprecated AS (
  UPDATE public.card_battle_rules r
  SET
    review_status = 'deprecated',
    execution_status = 'disabled',
    updated_at = now(),
    notes = concat_ws(E'\n', nullif(r.notes, ''), 'XMage batch package: deprecated stale shadow before curated batch rule upsert.')
  FROM proposed p
  WHERE (
        r.normalized_name = p.normalized_name
        OR r.normalized_name LIKE p.normalized_name || ' // %'
      )
    AND p.shadow_handling <> 'preserve_existing_rows'
    AND r.logical_rule_key <> p.logical_rule_key
  RETURNING r.*
)
SELECT count(*) AS deprecated_shadow_rows FROM deprecated;

WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('ali baba', 'Ali Baba', '9d2a321e3c668d8a701485c346c42c1a', 'battle_rule_v1:f3d57d6ac678195ce05ee4e8e781b39c', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"wall_creature","activation_cost_colors":["R"],"activation_cost_generic":0,"activation_cost_mana":"{R}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"wall_creature","target_constraints":{"card_types":["creature"],"required_subtypes":["wall"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"wall_creature","activation_cost_colors":["R"],"activation_cost_generic":0,"activation_cost_mana":"{R}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"wall_creature","target_constraints":{"card_types":["creature"],"required_subtypes":["wall"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"wall_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AliBaba translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('coeurl', 'Coeurl', 'dc320bded3c84b47cf4dda77e8a61525', 'battle_rule_v1:b416e913affdf6c3acced3e0aa5cad3b', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"nonenchantment_creature","activation_cost_colors":["W"],"activation_cost_generic":1,"activation_cost_mana":"{1}{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"nonenchantment_creature","target_constraints":{"card_types":["creature"],"exclude_card_types":["enchantment"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"nonenchantment_creature","activation_cost_colors":["W"],"activation_cost_generic":1,"activation_cost_mana":"{1}{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"nonenchantment_creature","target_constraints":{"card_types":["creature"],"exclude_card_types":["enchantment"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"nonenchantment_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Coeurl translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('kitsune diviner', 'Kitsune Diviner', '917ed923cf08e4a8073b524b16174e7a', 'battle_rule_v1:292dafa735745dd648240e2e7adf5f80', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"spirit_creature","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"spirit_creature","target_constraints":{"card_types":["creature"],"required_subtypes":["spirit"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"spirit_creature","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"spirit_creature","target_constraints":{"card_types":["creature"],"required_subtypes":["spirit"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"spirit_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class KitsuneDiviner translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('law-rune enforcer', 'Law-Rune Enforcer', '8844325fa17c7065e2a8d621dde94fa2', 'battle_rule_v1:4f355610aaa475281bb90e85180ca261', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature_mana_value_2_or_greater","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature_mana_value_2_or_greater","target_constraints":{"card_types":["creature"],"mana_value_min":2},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature_mana_value_2_or_greater","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature_mana_value_2_or_greater","target_constraints":{"card_types":["creature"],"mana_value_min":2},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature_mana_value_2_or_greater"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class LawRuneEnforcer translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sigardian priest', 'Sigardian Priest', 'df262801a1beb003dc72e34e4cdcf5d5', 'battle_rule_v1:9cae008fc7e7c5dd76fc3d5bbec0b55c', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"non_human_creature","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"non_human_creature","target_constraints":{"card_types":["creature"],"exclude_subtypes":["human"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"non_human_creature","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"non_human_creature","target_constraints":{"card_types":["creature"],"exclude_subtypes":["human"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"non_human_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SigardianPriest translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sterling keykeeper', 'Sterling Keykeeper', '69ca93bc4e3d96263ce9c8727524865f', 'battle_rule_v1:79c8df6d7b60de0c04ce52c71d7cf16c', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"non_mount_creature","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{2}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"non_mount_creature","target_constraints":{"card_types":["creature"],"exclude_subtypes":["mount"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"non_mount_creature","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{2}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"non_mount_creature","target_constraints":{"card_types":["creature"],"exclude_subtypes":["mount"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"non_mount_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SterlingKeykeeper translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('storm front', 'Storm Front', '2345441c7f4fa2a3adce46ca934931de', 'battle_rule_v1:369f1e4c26619dbdfb3a20640fe95cbf', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"flying_creature","activation_cost_colors":["G","G"],"activation_cost_generic":0,"activation_cost_mana":"{G}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"flying_creature","target_constraints":{"card_types":["creature"],"required_keywords":["flying"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"flying_creature","activation_cost_colors":["G","G"],"activation_cost_generic":0,"activation_cost_mana":"{G}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"enchantment","target":"flying_creature","target_constraints":{"card_types":["creature"],"required_keywords":["flying"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"enchantment","target":"flying_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class StormFront translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
matched_cards AS (
  SELECT
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    c.id AS card_id,
    c.name AS db_card_name
  FROM proposed p
  JOIN public.cards c
    ON (
         lower(c.name) = p.normalized_name
         OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
       )
   AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
),
canonical_target_cards AS (
  SELECT
    p.*,
    min(m.card_id::text)::uuid AS card_id,
    min(m.db_card_name) AS db_card_name
  FROM proposed p
  JOIN matched_cards m
    USING (normalized_name, card_name, oracle_hash)
  GROUP BY
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    p.logical_rule_key,
    p.effect_json,
    p.deck_role_json,
    p.source,
    p.confidence,
    p.review_status,
    p.execution_status,
    p.notes,
    p.shadow_handling
),
upserted AS (
  INSERT INTO public.card_battle_rules (
    normalized_name,
    card_id,
    card_name,
    effect_json,
    deck_role_json,
    source,
    confidence,
    review_status,
    rule_version,
    oracle_hash,
    notes,
    reviewed_by,
    reviewed_at,
    created_at,
    updated_at,
    last_seen_at,
    logical_rule_key,
    execution_status
  )
  SELECT
    normalized_name,
    card_id,
    db_card_name,
    effect_json,
    deck_role_json,
    source,
    confidence,
    review_status,
    2,
    oracle_hash,
    notes,
    'codex-xmage-batch',
    now(),
    now(),
    now(),
    now(),
    logical_rule_key,
    execution_status
  FROM canonical_target_cards
  ON CONFLICT (normalized_name, logical_rule_key) DO UPDATE
  SET
    card_id = EXCLUDED.card_id,
    card_name = EXCLUDED.card_name,
    effect_json = EXCLUDED.effect_json,
    deck_role_json = EXCLUDED.deck_role_json,
    source = EXCLUDED.source,
    confidence = EXCLUDED.confidence,
    review_status = EXCLUDED.review_status,
    rule_version = EXCLUDED.rule_version,
    oracle_hash = EXCLUDED.oracle_hash,
    notes = EXCLUDED.notes,
    reviewed_by = EXCLUDED.reviewed_by,
    reviewed_at = EXCLUDED.reviewed_at,
    updated_at = EXCLUDED.updated_at,
    last_seen_at = EXCLUDED.last_seen_at,
    execution_status = EXCLUDED.execution_status
  RETURNING *
)
SELECT count(*) AS upserted_rows FROM upserted;

COMMIT;
