BEGIN;

CREATE SCHEMA IF NOT EXISTS manaloom_deploy_audit;

CREATE TABLE IF NOT EXISTS manaloom_deploy_audit.pg490_creature_etb_bounce_new_server_20260705_073732 AS
SELECT *
FROM public.card_battle_rules
WHERE normalized_name IN ('aether adept', 'angler drake', 'aven fogbringer', 'bigfin bouncer', 'dispersal technician', 'exclusion mage', 'glowing anemone', 'iceridge serpent', 'man-o''-war', 'mist raven', 'peerless ropemaster', 'riddlemaster sphinx', 'separatist voidmage', 'spider-byte, web warden', 'stern proctor', 'surrakar banisher', 'voidwielder')
   OR normalized_name LIKE 'aether adept // %'
   OR normalized_name LIKE 'angler drake // %'
   OR normalized_name LIKE 'aven fogbringer // %'
   OR normalized_name LIKE 'bigfin bouncer // %'
   OR normalized_name LIKE 'dispersal technician // %'
   OR normalized_name LIKE 'exclusion mage // %'
   OR normalized_name LIKE 'glowing anemone // %'
   OR normalized_name LIKE 'iceridge serpent // %'
   OR normalized_name LIKE 'man-o''-war // %'
   OR normalized_name LIKE 'mist raven // %'
   OR normalized_name LIKE 'peerless ropemaster // %'
   OR normalized_name LIKE 'riddlemaster sphinx // %'
   OR normalized_name LIKE 'separatist voidmage // %'
   OR normalized_name LIKE 'spider-byte, web warden // %'
   OR normalized_name LIKE 'stern proctor // %'
   OR normalized_name LIKE 'surrakar banisher // %'
   OR normalized_name LIKE 'voidwielder // %';

DO $$
DECLARE
  v_missing jsonb;
BEGIN
  WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('aether adept', 'Aether Adept', '80dffbcb668db400babd48af1e4e9667', 'battle_rule_v1:d8d9647e557e324a29e260afaf2e51fe', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AetherAdept translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('angler drake', 'Angler Drake', 'b1bb06eaf6d1a0a9c943d686a1d50a01', 'battle_rule_v1:24fd20f36e87387e5e087563f3be1e90', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_optional":true,"etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","flying":true,"keywords":["flying"],"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AnglerDrake translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('aven fogbringer', 'Aven Fogbringer', '407bd126b7ba242429ecbc6416b939db', 'battle_rule_v1:10d8fac1e5b63846033d7839bab6e48e', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"land","etb_remove_effect":"remove_permanent","etb_remove_target":"land","flying":true,"keywords":["flying"],"target":"land","target_constraints":{"card_types":["land"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"land"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AvenFogbringer translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('bigfin bouncer', 'Bigfin Bouncer', 'dfcf28d5e43894395491c58dcbe280c2', 'battle_rule_v1:1a9f0a479dede202f08453d8e9294789', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"opponent"},"target_controller":"opponent","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BigfinBouncer translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('dispersal technician', 'Dispersal Technician', '71a9f2b3e26dac021c5392799a75ed84', 'battle_rule_v1:eb5271e3e1214d5399abd013e7879111', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_optional":true,"etb_bounce_target":"artifact","etb_remove_effect":"remove_permanent","etb_remove_target":"artifact","target":"artifact","target_constraints":{"card_types":["artifact"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"artifact"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DispersalTechnician translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('exclusion mage', 'Exclusion Mage', 'dfcf28d5e43894395491c58dcbe280c2', 'battle_rule_v1:1a9f0a479dede202f08453d8e9294789', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"opponent"},"target_controller":"opponent","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ExclusionMage translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('glowing anemone', 'Glowing Anemone', '3b901f8a7d868cc2c471766c3fc0a077', 'battle_rule_v1:46f72af38480db246db05647ca909365', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_optional":true,"etb_bounce_target":"land","etb_remove_effect":"remove_permanent","etb_remove_target":"land","target":"land","target_constraints":{"card_types":["land"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"land"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GlowingAnemone translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('iceridge serpent', 'Iceridge Serpent', 'dfcf28d5e43894395491c58dcbe280c2', 'battle_rule_v1:1a9f0a479dede202f08453d8e9294789', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"opponent"},"target_controller":"opponent","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class IceridgeSerpent translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('man-o''-war', 'Man-o''-War', '80dffbcb668db400babd48af1e4e9667', 'battle_rule_v1:d8d9647e557e324a29e260afaf2e51fe', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ManOWar translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('mist raven', 'Mist Raven', '9d19914ae2c408659fabca985c80f7ee', 'battle_rule_v1:f38ecdc92c12a16c51a4bcb6c709ecd3', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","flying":true,"keywords":["flying"],"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MistRaven translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('peerless ropemaster', 'Peerless Ropemaster', '28e22b0ca1e5320c2bd775ae39efa76b', 'battle_rule_v1:b7bcb54f51fa900014a1503e9a901c69', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"tapped_creature","etb_remove_effect":"remove_creature","etb_remove_target":"tapped_creature","target":"tapped_creature","target_constraints":{"card_types":["creature"],"tapped_state":"tapped"},"target_controller":"any","target_count":1,"trigger":"enters_battlefield","up_to_count":true,"xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"tapped_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PeerlessRopemaster translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('riddlemaster sphinx', 'Riddlemaster Sphinx', '5486c89cfd56ff67762468ac78e76c07', 'battle_rule_v1:4b8d5305977a9d45866ef2aa13fbedc0', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_optional":true,"etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","flying":true,"keywords":["flying"],"target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"opponent"},"target_controller":"opponent","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class RiddlemasterSphinx translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('separatist voidmage', 'Separatist Voidmage', '08a159153816185848d470ebe16c22d9', 'battle_rule_v1:295f6d55ea5bc08f0e80a60ecf4e1ea3', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_optional":true,"etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SeparatistVoidmage translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('spider-byte, web warden', 'Spider-Byte, Web Warden', '196787a37dabfb3760dd252f2ab94c10', 'battle_rule_v1:6e46258de4dabcd3395dbf2dee1e2368', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"nonland_permanent","etb_remove_effect":"remove_permanent","etb_remove_target":"nonland_permanent","target":"nonland_permanent","target_constraints":{"card_types":["nonland_permanent"]},"target_controller":"any","target_count":1,"trigger":"enters_battlefield","up_to_count":true,"xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"nonland_permanent"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SpiderByteWebWarden translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('stern proctor', 'Stern Proctor', '415f5023face93de34ffc21dd349f183', 'battle_rule_v1:c172fa7ff58746e04d6b4f8971377d4a', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"artifact_or_enchantment","etb_remove_effect":"remove_permanent","etb_remove_target":"artifact_or_enchantment","target":"artifact_or_enchantment","target_constraints":{"card_types":["artifact","enchantment"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"artifact_or_enchantment"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SternProctor translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('surrakar banisher', 'Surrakar Banisher', 'a6fa2bc7f23f9732e426b634020f05df', 'battle_rule_v1:5a0ca4eb4bfd1921c6e830c26749eaff', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_optional":true,"etb_bounce_target":"tapped_creature","etb_remove_effect":"remove_creature","etb_remove_target":"tapped_creature","target":"tapped_creature","target_constraints":{"card_types":["creature"],"tapped_state":"tapped"},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"tapped_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SurrakarBanisher translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('voidwielder', 'Voidwielder', '08a159153816185848d470ebe16c22d9', 'battle_rule_v1:295f6d55ea5bc08f0e80a60ecf4e1ea3', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_optional":true,"etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Voidwielder translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
  counts AS (
    SELECT
      p.card_name,
      p.normalized_name,
      p.oracle_hash,
      count(c.id) AS target_card_rows,
      min(c.id::text)::uuid AS canonical_card_id
    FROM proposed p
    LEFT JOIN public.cards c
      ON (
           lower(c.name) = p.normalized_name
           OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
         )
     AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
    GROUP BY p.card_name, p.normalized_name, p.oracle_hash
  )
  SELECT jsonb_agg(counts ORDER BY card_name)
    INTO v_missing
  FROM counts
  WHERE target_card_rows < 1;

  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION 'XMage batch package abort: expected at least one Oracle-hash-matched card row for every proposed card: %', v_missing;
  END IF;
END $$;

WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('aether adept', 'Aether Adept', '80dffbcb668db400babd48af1e4e9667', 'battle_rule_v1:d8d9647e557e324a29e260afaf2e51fe', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AetherAdept translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('angler drake', 'Angler Drake', 'b1bb06eaf6d1a0a9c943d686a1d50a01', 'battle_rule_v1:24fd20f36e87387e5e087563f3be1e90', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_optional":true,"etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","flying":true,"keywords":["flying"],"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AnglerDrake translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('aven fogbringer', 'Aven Fogbringer', '407bd126b7ba242429ecbc6416b939db', 'battle_rule_v1:10d8fac1e5b63846033d7839bab6e48e', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"land","etb_remove_effect":"remove_permanent","etb_remove_target":"land","flying":true,"keywords":["flying"],"target":"land","target_constraints":{"card_types":["land"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"land"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AvenFogbringer translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('bigfin bouncer', 'Bigfin Bouncer', 'dfcf28d5e43894395491c58dcbe280c2', 'battle_rule_v1:1a9f0a479dede202f08453d8e9294789', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"opponent"},"target_controller":"opponent","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BigfinBouncer translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('dispersal technician', 'Dispersal Technician', '71a9f2b3e26dac021c5392799a75ed84', 'battle_rule_v1:eb5271e3e1214d5399abd013e7879111', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_optional":true,"etb_bounce_target":"artifact","etb_remove_effect":"remove_permanent","etb_remove_target":"artifact","target":"artifact","target_constraints":{"card_types":["artifact"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"artifact"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DispersalTechnician translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('exclusion mage', 'Exclusion Mage', 'dfcf28d5e43894395491c58dcbe280c2', 'battle_rule_v1:1a9f0a479dede202f08453d8e9294789', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"opponent"},"target_controller":"opponent","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ExclusionMage translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('glowing anemone', 'Glowing Anemone', '3b901f8a7d868cc2c471766c3fc0a077', 'battle_rule_v1:46f72af38480db246db05647ca909365', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_optional":true,"etb_bounce_target":"land","etb_remove_effect":"remove_permanent","etb_remove_target":"land","target":"land","target_constraints":{"card_types":["land"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"land"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GlowingAnemone translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('iceridge serpent', 'Iceridge Serpent', 'dfcf28d5e43894395491c58dcbe280c2', 'battle_rule_v1:1a9f0a479dede202f08453d8e9294789', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"opponent"},"target_controller":"opponent","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class IceridgeSerpent translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('man-o''-war', 'Man-o''-War', '80dffbcb668db400babd48af1e4e9667', 'battle_rule_v1:d8d9647e557e324a29e260afaf2e51fe', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ManOWar translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('mist raven', 'Mist Raven', '9d19914ae2c408659fabca985c80f7ee', 'battle_rule_v1:f38ecdc92c12a16c51a4bcb6c709ecd3', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","flying":true,"keywords":["flying"],"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MistRaven translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('peerless ropemaster', 'Peerless Ropemaster', '28e22b0ca1e5320c2bd775ae39efa76b', 'battle_rule_v1:b7bcb54f51fa900014a1503e9a901c69', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"tapped_creature","etb_remove_effect":"remove_creature","etb_remove_target":"tapped_creature","target":"tapped_creature","target_constraints":{"card_types":["creature"],"tapped_state":"tapped"},"target_controller":"any","target_count":1,"trigger":"enters_battlefield","up_to_count":true,"xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"tapped_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PeerlessRopemaster translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('riddlemaster sphinx', 'Riddlemaster Sphinx', '5486c89cfd56ff67762468ac78e76c07', 'battle_rule_v1:4b8d5305977a9d45866ef2aa13fbedc0', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_optional":true,"etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","flying":true,"keywords":["flying"],"target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"opponent"},"target_controller":"opponent","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class RiddlemasterSphinx translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('separatist voidmage', 'Separatist Voidmage', '08a159153816185848d470ebe16c22d9', 'battle_rule_v1:295f6d55ea5bc08f0e80a60ecf4e1ea3', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_optional":true,"etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SeparatistVoidmage translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('spider-byte, web warden', 'Spider-Byte, Web Warden', '196787a37dabfb3760dd252f2ab94c10', 'battle_rule_v1:6e46258de4dabcd3395dbf2dee1e2368', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"nonland_permanent","etb_remove_effect":"remove_permanent","etb_remove_target":"nonland_permanent","target":"nonland_permanent","target_constraints":{"card_types":["nonland_permanent"]},"target_controller":"any","target_count":1,"trigger":"enters_battlefield","up_to_count":true,"xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"nonland_permanent"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SpiderByteWebWarden translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('stern proctor', 'Stern Proctor', '415f5023face93de34ffc21dd349f183', 'battle_rule_v1:c172fa7ff58746e04d6b4f8971377d4a', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"artifact_or_enchantment","etb_remove_effect":"remove_permanent","etb_remove_target":"artifact_or_enchantment","target":"artifact_or_enchantment","target_constraints":{"card_types":["artifact","enchantment"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"artifact_or_enchantment"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SternProctor translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('surrakar banisher', 'Surrakar Banisher', 'a6fa2bc7f23f9732e426b634020f05df', 'battle_rule_v1:5a0ca4eb4bfd1921c6e830c26749eaff', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_optional":true,"etb_bounce_target":"tapped_creature","etb_remove_effect":"remove_creature","etb_remove_target":"tapped_creature","target":"tapped_creature","target_constraints":{"card_types":["creature"],"tapped_state":"tapped"},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"tapped_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SurrakarBanisher translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('voidwielder', 'Voidwielder', '08a159153816185848d470ebe16c22d9', 'battle_rule_v1:295f6d55ea5bc08f0e80a60ecf4e1ea3', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_optional":true,"etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Voidwielder translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
deprecated AS (
  UPDATE public.card_battle_rules r
  SET
    review_status = 'deprecated',
    execution_status = 'disabled',
    updated_at = now(),
    notes = concat_ws(E'\n', nullif(r.notes, ''), 'XMage batch package: deprecated stale shadow before curated batch rule upsert.')
  FROM proposed p
  WHERE (
        r.normalized_name = p.normalized_name
        OR r.normalized_name LIKE p.normalized_name || ' // %'
      )
    AND p.shadow_handling <> 'preserve_existing_rows'
    AND r.logical_rule_key <> p.logical_rule_key
  RETURNING r.*
)
SELECT count(*) AS deprecated_shadow_rows FROM deprecated;

WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('aether adept', 'Aether Adept', '80dffbcb668db400babd48af1e4e9667', 'battle_rule_v1:d8d9647e557e324a29e260afaf2e51fe', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AetherAdept translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('angler drake', 'Angler Drake', 'b1bb06eaf6d1a0a9c943d686a1d50a01', 'battle_rule_v1:24fd20f36e87387e5e087563f3be1e90', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_optional":true,"etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","flying":true,"keywords":["flying"],"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AnglerDrake translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('aven fogbringer', 'Aven Fogbringer', '407bd126b7ba242429ecbc6416b939db', 'battle_rule_v1:10d8fac1e5b63846033d7839bab6e48e', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"land","etb_remove_effect":"remove_permanent","etb_remove_target":"land","flying":true,"keywords":["flying"],"target":"land","target_constraints":{"card_types":["land"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"land"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AvenFogbringer translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('bigfin bouncer', 'Bigfin Bouncer', 'dfcf28d5e43894395491c58dcbe280c2', 'battle_rule_v1:1a9f0a479dede202f08453d8e9294789', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"opponent"},"target_controller":"opponent","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BigfinBouncer translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('dispersal technician', 'Dispersal Technician', '71a9f2b3e26dac021c5392799a75ed84', 'battle_rule_v1:eb5271e3e1214d5399abd013e7879111', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_optional":true,"etb_bounce_target":"artifact","etb_remove_effect":"remove_permanent","etb_remove_target":"artifact","target":"artifact","target_constraints":{"card_types":["artifact"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"artifact"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class DispersalTechnician translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('exclusion mage', 'Exclusion Mage', 'dfcf28d5e43894395491c58dcbe280c2', 'battle_rule_v1:1a9f0a479dede202f08453d8e9294789', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"opponent"},"target_controller":"opponent","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ExclusionMage translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('glowing anemone', 'Glowing Anemone', '3b901f8a7d868cc2c471766c3fc0a077', 'battle_rule_v1:46f72af38480db246db05647ca909365', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_optional":true,"etb_bounce_target":"land","etb_remove_effect":"remove_permanent","etb_remove_target":"land","target":"land","target_constraints":{"card_types":["land"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"land"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GlowingAnemone translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('iceridge serpent', 'Iceridge Serpent', 'dfcf28d5e43894395491c58dcbe280c2', 'battle_rule_v1:1a9f0a479dede202f08453d8e9294789', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"opponent"},"target_controller":"opponent","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class IceridgeSerpent translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('man-o''-war', 'Man-o''-War', '80dffbcb668db400babd48af1e4e9667', 'battle_rule_v1:d8d9647e557e324a29e260afaf2e51fe', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ManOWar translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('mist raven', 'Mist Raven', '9d19914ae2c408659fabca985c80f7ee', 'battle_rule_v1:f38ecdc92c12a16c51a4bcb6c709ecd3', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","flying":true,"keywords":["flying"],"target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MistRaven translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('peerless ropemaster', 'Peerless Ropemaster', '28e22b0ca1e5320c2bd775ae39efa76b', 'battle_rule_v1:b7bcb54f51fa900014a1503e9a901c69', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"tapped_creature","etb_remove_effect":"remove_creature","etb_remove_target":"tapped_creature","target":"tapped_creature","target_constraints":{"card_types":["creature"],"tapped_state":"tapped"},"target_controller":"any","target_count":1,"trigger":"enters_battlefield","up_to_count":true,"xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"tapped_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PeerlessRopemaster translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('riddlemaster sphinx', 'Riddlemaster Sphinx', '5486c89cfd56ff67762468ac78e76c07', 'battle_rule_v1:4b8d5305977a9d45866ef2aa13fbedc0', '{"_keywords_are_self":true,"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_optional":true,"etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","flying":true,"keywords":["flying"],"target":"creature","target_constraints":{"card_types":["creature"],"controller_scope":"opponent"},"target_controller":"opponent","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class RiddlemasterSphinx translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('separatist voidmage', 'Separatist Voidmage', '08a159153816185848d470ebe16c22d9', 'battle_rule_v1:295f6d55ea5bc08f0e80a60ecf4e1ea3', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_optional":true,"etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SeparatistVoidmage translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('spider-byte, web warden', 'Spider-Byte, Web Warden', '196787a37dabfb3760dd252f2ab94c10', 'battle_rule_v1:6e46258de4dabcd3395dbf2dee1e2368', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"nonland_permanent","etb_remove_effect":"remove_permanent","etb_remove_target":"nonland_permanent","target":"nonland_permanent","target_constraints":{"card_types":["nonland_permanent"]},"target_controller":"any","target_count":1,"trigger":"enters_battlefield","up_to_count":true,"xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"nonland_permanent"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SpiderByteWebWarden translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('stern proctor', 'Stern Proctor', '415f5023face93de34ffc21dd349f183', 'battle_rule_v1:c172fa7ff58746e04d6b4f8971377d4a', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_target":"artifact_or_enchantment","etb_remove_effect":"remove_permanent","etb_remove_target":"artifact_or_enchantment","target":"artifact_or_enchantment","target_constraints":{"card_types":["artifact","enchantment"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"artifact_or_enchantment"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SternProctor translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('surrakar banisher', 'Surrakar Banisher', 'a6fa2bc7f23f9732e426b634020f05df', 'battle_rule_v1:5a0ca4eb4bfd1921c6e830c26749eaff', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_optional":true,"etb_bounce_target":"tapped_creature","etb_remove_effect":"remove_creature","etb_remove_target":"tapped_creature","target":"tapped_creature","target_constraints":{"card_types":["creature"],"tapped_state":"tapped"},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"tapped_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SurrakarBanisher translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('voidwielder', 'Voidwielder', '08a159153816185848d470ebe16c22d9', 'battle_rule_v1:295f6d55ea5bc08f0e80a60ecf4e1ea3', '{"ability_kind":"triggered","battle_model_scope":"xmage_creature_etb_return_target_to_hand_v1","destination":"hand","effect":"creature","etb_bounce_optional":true,"etb_bounce_target":"creature","etb_remove_effect":"remove_creature","etb_remove_target":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"target_controller":"any","trigger":"enters_battlefield","xmage_ability_class":"EntersBattlefieldTriggeredAbility","xmage_effect_class":"ReturnToHandTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Voidwielder translated into ManaLoom runtime scope xmage_creature_etb_return_target_to_hand_v1. This row is package-ready only because the source signature is a narrow creature ETB return target permanent to hand trigger with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
matched_cards AS (
  SELECT
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    c.id AS card_id,
    c.name AS db_card_name
  FROM proposed p
  JOIN public.cards c
    ON (
         lower(c.name) = p.normalized_name
         OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
       )
   AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
),
canonical_target_cards AS (
  SELECT
    p.*,
    min(m.card_id::text)::uuid AS card_id,
    min(m.db_card_name) AS db_card_name
  FROM proposed p
  JOIN matched_cards m
    USING (normalized_name, card_name, oracle_hash)
  GROUP BY
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    p.logical_rule_key,
    p.effect_json,
    p.deck_role_json,
    p.source,
    p.confidence,
    p.review_status,
    p.execution_status,
    p.notes,
    p.shadow_handling
),
upserted AS (
  INSERT INTO public.card_battle_rules (
    normalized_name,
    card_id,
    card_name,
    effect_json,
    deck_role_json,
    source,
    confidence,
    review_status,
    rule_version,
    oracle_hash,
    notes,
    reviewed_by,
    reviewed_at,
    created_at,
    updated_at,
    last_seen_at,
    logical_rule_key,
    execution_status
  )
  SELECT
    normalized_name,
    card_id,
    db_card_name,
    effect_json,
    deck_role_json,
    source,
    confidence,
    review_status,
    2,
    oracle_hash,
    notes,
    'codex-xmage-batch',
    now(),
    now(),
    now(),
    now(),
    logical_rule_key,
    execution_status
  FROM canonical_target_cards
  ON CONFLICT (normalized_name, logical_rule_key) DO UPDATE
  SET
    card_id = EXCLUDED.card_id,
    card_name = EXCLUDED.card_name,
    effect_json = EXCLUDED.effect_json,
    deck_role_json = EXCLUDED.deck_role_json,
    source = EXCLUDED.source,
    confidence = EXCLUDED.confidence,
    review_status = EXCLUDED.review_status,
    rule_version = EXCLUDED.rule_version,
    oracle_hash = EXCLUDED.oracle_hash,
    notes = EXCLUDED.notes,
    reviewed_by = EXCLUDED.reviewed_by,
    reviewed_at = EXCLUDED.reviewed_at,
    updated_at = EXCLUDED.updated_at,
    last_seen_at = EXCLUDED.last_seen_at,
    execution_status = EXCLUDED.execution_status
  RETURNING *
)
SELECT count(*) AS upserted_rows FROM upserted;

COMMIT;
