BEGIN;

CREATE SCHEMA IF NOT EXISTS manaloom_deploy_audit;

CREATE TABLE IF NOT EXISTS manaloom_deploy_audit.pg482_self_add_counters_new_server_20260705_044704 AS
SELECT *
FROM public.card_battle_rules
WHERE normalized_name IN ('carnivorous moss-beast', 'chronomaton', 'energizer', 'hungry megasloth', 'jenara, asura of war', 'jungle delver', 'ruins recluse', 'sledding otter-penguin', 'unholy officiant', 'verdant automaton')
   OR normalized_name LIKE 'carnivorous moss-beast // %'
   OR normalized_name LIKE 'chronomaton // %'
   OR normalized_name LIKE 'energizer // %'
   OR normalized_name LIKE 'hungry megasloth // %'
   OR normalized_name LIKE 'jenara, asura of war // %'
   OR normalized_name LIKE 'jungle delver // %'
   OR normalized_name LIKE 'ruins recluse // %'
   OR normalized_name LIKE 'sledding otter-penguin // %'
   OR normalized_name LIKE 'unholy officiant // %'
   OR normalized_name LIKE 'verdant automaton // %';

DO $$
DECLARE
  v_missing jsonb;
BEGIN
  WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('carnivorous moss-beast', 'Carnivorous Moss-Beast', '49068d66e409b3ed3d3a4f7ca7fd4929', 'battle_rule_v1:8a782138d8d63502af38d50b5968c239', '{"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":["G","G"],"activation_cost_generic":5,"activation_cost_mana":"{5}{G}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CarnivorousMossBeast translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('chronomaton', 'Chronomaton', 'c36a67be5df8f853c60f592d49b5a615', 'battle_rule_v1:88916f73f73e2df515bbef6919805dc5', '{"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Chronomaton translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('energizer', 'Energizer', '5a1a86ec889efb431814a500926fab3d', 'battle_rule_v1:2c56305f71d41d557570b6ee424d7bc1', '{"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{2}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Energizer translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('hungry megasloth', 'Hungry Megasloth', '9dacf6afa99ff17f48850d4d29834bd6', 'battle_rule_v1:5c70a79648cdeb0e669a29f1c875f1db', '{"_keywords_are_self":true,"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{2}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"keywords":["reach"],"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HungryMegasloth translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('jenara, asura of war', 'Jenara, Asura of War', '385de3d6d2637476db28317157b5c511', 'battle_rule_v1:d1c39ea5aafb1d002bc9cf60583c4388', '{"_keywords_are_self":true,"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":["W"],"activation_cost_generic":1,"activation_cost_mana":"{1}{W}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"keywords":["flying"],"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class JenaraAsuraOfWar translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('jungle delver', 'Jungle Delver', '4a2663cf4c2703fd61427c875548ce01', 'battle_rule_v1:233eac8995e59d158cd014a90e5f3a95', '{"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":["G"],"activation_cost_generic":3,"activation_cost_mana":"{3}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class JungleDelver translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('ruins recluse', 'Ruins Recluse', '50b63a239462d9429bc682b0d99e6a5a', 'battle_rule_v1:6fcbbccfc5cacd668296e1e1b787d82b', '{"_keywords_are_self":true,"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":["G"],"activation_cost_generic":3,"activation_cost_mana":"{3}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"keywords":["deathtouch","reach"],"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class RuinsRecluse translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sledding otter-penguin', 'Sledding Otter-Penguin', '5d51caebfd5fb3e38af00985b8024ea9', 'battle_rule_v1:7f62f3608687b28a16eeadafe7efa4c4', '{"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":[],"activation_cost_generic":3,"activation_cost_mana":"{3}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SleddingOtterPenguin translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('unholy officiant', 'Unholy Officiant', '748031dc4868a157d229f5d2d746e0b8', 'battle_rule_v1:314d02cb0db136b0a71adaaffd76e30e', '{"_keywords_are_self":true,"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":["W"],"activation_cost_generic":4,"activation_cost_mana":"{4}{W}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"keywords":["vigilance"],"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class UnholyOfficiant translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('verdant automaton', 'Verdant Automaton', '4a2663cf4c2703fd61427c875548ce01', 'battle_rule_v1:233eac8995e59d158cd014a90e5f3a95', '{"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":["G"],"activation_cost_generic":3,"activation_cost_mana":"{3}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class VerdantAutomaton translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
  counts AS (
    SELECT
      p.card_name,
      p.normalized_name,
      p.oracle_hash,
      count(c.id) AS target_card_rows,
      min(c.id::text)::uuid AS canonical_card_id
    FROM proposed p
    LEFT JOIN public.cards c
      ON (
           lower(c.name) = p.normalized_name
           OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
         )
     AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
    GROUP BY p.card_name, p.normalized_name, p.oracle_hash
  )
  SELECT jsonb_agg(counts ORDER BY card_name)
    INTO v_missing
  FROM counts
  WHERE target_card_rows < 1;

  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION 'XMage batch package abort: expected at least one Oracle-hash-matched card row for every proposed card: %', v_missing;
  END IF;
END $$;

WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('carnivorous moss-beast', 'Carnivorous Moss-Beast', '49068d66e409b3ed3d3a4f7ca7fd4929', 'battle_rule_v1:8a782138d8d63502af38d50b5968c239', '{"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":["G","G"],"activation_cost_generic":5,"activation_cost_mana":"{5}{G}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CarnivorousMossBeast translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('chronomaton', 'Chronomaton', 'c36a67be5df8f853c60f592d49b5a615', 'battle_rule_v1:88916f73f73e2df515bbef6919805dc5', '{"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Chronomaton translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('energizer', 'Energizer', '5a1a86ec889efb431814a500926fab3d', 'battle_rule_v1:2c56305f71d41d557570b6ee424d7bc1', '{"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{2}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Energizer translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('hungry megasloth', 'Hungry Megasloth', '9dacf6afa99ff17f48850d4d29834bd6', 'battle_rule_v1:5c70a79648cdeb0e669a29f1c875f1db', '{"_keywords_are_self":true,"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{2}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"keywords":["reach"],"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HungryMegasloth translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('jenara, asura of war', 'Jenara, Asura of War', '385de3d6d2637476db28317157b5c511', 'battle_rule_v1:d1c39ea5aafb1d002bc9cf60583c4388', '{"_keywords_are_self":true,"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":["W"],"activation_cost_generic":1,"activation_cost_mana":"{1}{W}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"keywords":["flying"],"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class JenaraAsuraOfWar translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('jungle delver', 'Jungle Delver', '4a2663cf4c2703fd61427c875548ce01', 'battle_rule_v1:233eac8995e59d158cd014a90e5f3a95', '{"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":["G"],"activation_cost_generic":3,"activation_cost_mana":"{3}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class JungleDelver translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('ruins recluse', 'Ruins Recluse', '50b63a239462d9429bc682b0d99e6a5a', 'battle_rule_v1:6fcbbccfc5cacd668296e1e1b787d82b', '{"_keywords_are_self":true,"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":["G"],"activation_cost_generic":3,"activation_cost_mana":"{3}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"keywords":["deathtouch","reach"],"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class RuinsRecluse translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sledding otter-penguin', 'Sledding Otter-Penguin', '5d51caebfd5fb3e38af00985b8024ea9', 'battle_rule_v1:7f62f3608687b28a16eeadafe7efa4c4', '{"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":[],"activation_cost_generic":3,"activation_cost_mana":"{3}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SleddingOtterPenguin translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('unholy officiant', 'Unholy Officiant', '748031dc4868a157d229f5d2d746e0b8', 'battle_rule_v1:314d02cb0db136b0a71adaaffd76e30e', '{"_keywords_are_self":true,"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":["W"],"activation_cost_generic":4,"activation_cost_mana":"{4}{W}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"keywords":["vigilance"],"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class UnholyOfficiant translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('verdant automaton', 'Verdant Automaton', '4a2663cf4c2703fd61427c875548ce01', 'battle_rule_v1:233eac8995e59d158cd014a90e5f3a95', '{"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":["G"],"activation_cost_generic":3,"activation_cost_mana":"{3}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class VerdantAutomaton translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
deprecated AS (
  UPDATE public.card_battle_rules r
  SET
    review_status = 'deprecated',
    execution_status = 'disabled',
    updated_at = now(),
    notes = concat_ws(E'\n', nullif(r.notes, ''), 'XMage batch package: deprecated stale shadow before curated batch rule upsert.')
  FROM proposed p
  WHERE (
        r.normalized_name = p.normalized_name
        OR r.normalized_name LIKE p.normalized_name || ' // %'
      )
    AND p.shadow_handling <> 'preserve_existing_rows'
    AND r.logical_rule_key <> p.logical_rule_key
  RETURNING r.*
)
SELECT count(*) AS deprecated_shadow_rows FROM deprecated;

WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('carnivorous moss-beast', 'Carnivorous Moss-Beast', '49068d66e409b3ed3d3a4f7ca7fd4929', 'battle_rule_v1:8a782138d8d63502af38d50b5968c239', '{"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":["G","G"],"activation_cost_generic":5,"activation_cost_mana":"{5}{G}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class CarnivorousMossBeast translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('chronomaton', 'Chronomaton', 'c36a67be5df8f853c60f592d49b5a615', 'battle_rule_v1:88916f73f73e2df515bbef6919805dc5', '{"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Chronomaton translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('energizer', 'Energizer', '5a1a86ec889efb431814a500926fab3d', 'battle_rule_v1:2c56305f71d41d557570b6ee424d7bc1', '{"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{2}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class Energizer translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('hungry megasloth', 'Hungry Megasloth', '9dacf6afa99ff17f48850d4d29834bd6', 'battle_rule_v1:5c70a79648cdeb0e669a29f1c875f1db', '{"_keywords_are_self":true,"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{2}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"keywords":["reach"],"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class HungryMegasloth translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('jenara, asura of war', 'Jenara, Asura of War', '385de3d6d2637476db28317157b5c511', 'battle_rule_v1:d1c39ea5aafb1d002bc9cf60583c4388', '{"_keywords_are_self":true,"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":["W"],"activation_cost_generic":1,"activation_cost_mana":"{1}{W}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"keywords":["flying"],"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class JenaraAsuraOfWar translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('jungle delver', 'Jungle Delver', '4a2663cf4c2703fd61427c875548ce01', 'battle_rule_v1:233eac8995e59d158cd014a90e5f3a95', '{"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":["G"],"activation_cost_generic":3,"activation_cost_mana":"{3}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class JungleDelver translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('ruins recluse', 'Ruins Recluse', '50b63a239462d9429bc682b0d99e6a5a', 'battle_rule_v1:6fcbbccfc5cacd668296e1e1b787d82b', '{"_keywords_are_self":true,"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":["G"],"activation_cost_generic":3,"activation_cost_mana":"{3}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"keywords":["deathtouch","reach"],"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class RuinsRecluse translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('sledding otter-penguin', 'Sledding Otter-Penguin', '5d51caebfd5fb3e38af00985b8024ea9', 'battle_rule_v1:7f62f3608687b28a16eeadafe7efa4c4', '{"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":[],"activation_cost_generic":3,"activation_cost_mana":"{3}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class SleddingOtterPenguin translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('unholy officiant', 'Unholy Officiant', '748031dc4868a157d229f5d2d746e0b8', 'battle_rule_v1:314d02cb0db136b0a71adaaffd76e30e', '{"_keywords_are_self":true,"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":["W"],"activation_cost_generic":4,"activation_cost_mana":"{4}{W}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"keywords":["vigilance"],"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class UnholyOfficiant translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('verdant automaton', 'Verdant Automaton', '4a2663cf4c2703fd61427c875548ce01', 'battle_rule_v1:233eac8995e59d158cd014a90e5f3a95', '{"ability_kind":"activated","activated_add_counters":true,"activated_add_counters_count":1,"activated_add_counters_counter_type":"+1/+1","activated_add_counters_target":"self","activated_battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","activated_effect":"add_counters","activation_cost_colors":["G"],"activation_cost_generic":3,"activation_cost_mana":"{3}{G}","activation_requires_sacrifice":false,"activation_requires_tap":false,"battle_model_scope":"xmage_permanent_simple_activated_self_add_counters_v1","count":1,"counter_count":1,"counter_type":"+1/+1","effect":"creature","instant":false,"sorcery":false,"target":"self","xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"AddCountersSourceEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"self"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class VerdantAutomaton translated into ManaLoom runtime scope xmage_permanent_simple_activated_self_add_counters_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
matched_cards AS (
  SELECT
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    c.id AS card_id,
    c.name AS db_card_name
  FROM proposed p
  JOIN public.cards c
    ON (
         lower(c.name) = p.normalized_name
         OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
       )
   AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
),
canonical_target_cards AS (
  SELECT
    p.*,
    min(m.card_id::text)::uuid AS card_id,
    min(m.db_card_name) AS db_card_name
  FROM proposed p
  JOIN matched_cards m
    USING (normalized_name, card_name, oracle_hash)
  GROUP BY
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    p.logical_rule_key,
    p.effect_json,
    p.deck_role_json,
    p.source,
    p.confidence,
    p.review_status,
    p.execution_status,
    p.notes,
    p.shadow_handling
),
upserted AS (
  INSERT INTO public.card_battle_rules (
    normalized_name,
    card_id,
    card_name,
    effect_json,
    deck_role_json,
    source,
    confidence,
    review_status,
    rule_version,
    oracle_hash,
    notes,
    reviewed_by,
    reviewed_at,
    created_at,
    updated_at,
    last_seen_at,
    logical_rule_key,
    execution_status
  )
  SELECT
    normalized_name,
    card_id,
    db_card_name,
    effect_json,
    deck_role_json,
    source,
    confidence,
    review_status,
    2,
    oracle_hash,
    notes,
    'codex-xmage-batch',
    now(),
    now(),
    now(),
    now(),
    logical_rule_key,
    execution_status
  FROM canonical_target_cards
  ON CONFLICT (normalized_name, logical_rule_key) DO UPDATE
  SET
    card_id = EXCLUDED.card_id,
    card_name = EXCLUDED.card_name,
    effect_json = EXCLUDED.effect_json,
    deck_role_json = EXCLUDED.deck_role_json,
    source = EXCLUDED.source,
    confidence = EXCLUDED.confidence,
    review_status = EXCLUDED.review_status,
    rule_version = EXCLUDED.rule_version,
    oracle_hash = EXCLUDED.oracle_hash,
    notes = EXCLUDED.notes,
    reviewed_by = EXCLUDED.reviewed_by,
    reviewed_at = EXCLUDED.reviewed_at,
    updated_at = EXCLUDED.updated_at,
    last_seen_at = EXCLUDED.last_seen_at,
    execution_status = EXCLUDED.execution_status
  RETURNING *
)
SELECT count(*) AS upserted_rows FROM upserted;

COMMIT;
