BEGIN;

CREATE SCHEMA IF NOT EXISTS manaloom_deploy_audit;

CREATE TABLE IF NOT EXISTS manaloom_deploy_audit.pg611_activated_tap_permanent_new_server_20260707_111500 AS
SELECT *
FROM public.card_battle_rules
WHERE normalized_name IN ('auriok transfixer', 'benalish trapper', 'blinding souleater', 'gideon''s lawkeeper', 'icy manipulator', 'loxodon mystic', 'master decoy', 'minister of impediments', 'ostiary thrull', 'pacification array', 'scepter of dominance')
   OR normalized_name LIKE 'auriok transfixer // %'
   OR normalized_name LIKE 'benalish trapper // %'
   OR normalized_name LIKE 'blinding souleater // %'
   OR normalized_name LIKE 'gideon''s lawkeeper // %'
   OR normalized_name LIKE 'icy manipulator // %'
   OR normalized_name LIKE 'loxodon mystic // %'
   OR normalized_name LIKE 'master decoy // %'
   OR normalized_name LIKE 'minister of impediments // %'
   OR normalized_name LIKE 'ostiary thrull // %'
   OR normalized_name LIKE 'pacification array // %'
   OR normalized_name LIKE 'scepter of dominance // %';

DO $$
DECLARE
  v_missing jsonb;
BEGIN
  WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('auriok transfixer', 'Auriok Transfixer', 'c7268460c632adc5657e28602cb766a8', 'battle_rule_v1:a1ba4a819fe30a7f7bdd0b61eeaf0c09', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"artifact","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"artifact","target_constraints":{"card_types":["artifact"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"artifact","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"artifact","target_constraints":{"card_types":["artifact"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"artifact"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AuriokTransfixer translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('benalish trapper', 'Benalish Trapper', '395ee92e1d81b2dd12ea924bf8824740', 'battle_rule_v1:872ba81bfcbb932c8efaf4d38c65bf95', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BenalishTrapper translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('blinding souleater', 'Blinding Souleater', 'c9011356cc6f198b00b028c021285cfe', 'battle_rule_v1:04f523606e21f77e119ce8bd414e8608', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W/P"],"activation_cost_generic":0,"activation_cost_mana":"{W/P}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W/P"],"activation_cost_generic":0,"activation_cost_mana":"{W/P}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BlindingSouleater translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('gideon''s lawkeeper', 'Gideon''s Lawkeeper', '395ee92e1d81b2dd12ea924bf8824740', 'battle_rule_v1:872ba81bfcbb932c8efaf4d38c65bf95', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GideonsLawkeeper translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('icy manipulator', 'Icy Manipulator', '24f1adf4de51b90f15fd3bd93bd70cc8', 'battle_rule_v1:63e27254b3adc36a05f73af796e69bcd', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"artifact_creature_or_land","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"artifact_creature_or_land","target_constraints":{"target":"artifact_creature_or_land"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"artifact_creature_or_land","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"artifact","target":"artifact_creature_or_land","target_constraints":{"target":"artifact_creature_or_land"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"artifact","target":"artifact_creature_or_land"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class IcyManipulator translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('loxodon mystic', 'Loxodon Mystic', '395ee92e1d81b2dd12ea924bf8824740', 'battle_rule_v1:872ba81bfcbb932c8efaf4d38c65bf95', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class LoxodonMystic translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('master decoy', 'Master Decoy', '395ee92e1d81b2dd12ea924bf8824740', 'battle_rule_v1:872ba81bfcbb932c8efaf4d38c65bf95', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MasterDecoy translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('minister of impediments', 'Minister of Impediments', '25b3d4db9fd3d800227311461850a713', 'battle_rule_v1:60b5e7c8253fdca947c993a4dbd2c228', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MinisterOfImpediments translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('ostiary thrull', 'Ostiary Thrull', '395ee92e1d81b2dd12ea924bf8824740', 'battle_rule_v1:872ba81bfcbb932c8efaf4d38c65bf95', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class OstiaryThrull translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('pacification array', 'Pacification Array', '90f2dc0a2d53d3a5c0b227a6101f35de', 'battle_rule_v1:bc9629927e8092d4cde65b83a60a18b7', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"artifact_or_creature","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{2}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"artifact_or_creature","target_constraints":{"card_types":["artifact","creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"artifact_or_creature","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{2}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"artifact","target":"artifact_or_creature","target_constraints":{"card_types":["artifact","creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"artifact","target":"artifact_or_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PacificationArray translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('scepter of dominance', 'Scepter of Dominance', '04346865443f8ec091f47540bdb58cc2', 'battle_rule_v1:1a0ebc49740451b5fcd9b855dcd8b2d0', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"permanent","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"permanent","target_constraints":{"card_types":["permanent"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"permanent","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"artifact","target":"permanent","target_constraints":{"card_types":["permanent"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"artifact","target":"permanent"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ScepterOfDominance translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
  counts AS (
    SELECT
      p.card_name,
      p.normalized_name,
      p.oracle_hash,
      count(c.id) AS target_card_rows,
      min(c.id::text)::uuid AS canonical_card_id
    FROM proposed p
    LEFT JOIN public.cards c
      ON (
           lower(c.name) = p.normalized_name
           OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
         )
     AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
    GROUP BY p.card_name, p.normalized_name, p.oracle_hash
  )
  SELECT jsonb_agg(counts ORDER BY card_name)
    INTO v_missing
  FROM counts
  WHERE target_card_rows < 1;

  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION 'XMage batch package abort: expected at least one Oracle-hash-matched card row for every proposed card: %', v_missing;
  END IF;
END $$;

WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('auriok transfixer', 'Auriok Transfixer', 'c7268460c632adc5657e28602cb766a8', 'battle_rule_v1:a1ba4a819fe30a7f7bdd0b61eeaf0c09', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"artifact","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"artifact","target_constraints":{"card_types":["artifact"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"artifact","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"artifact","target_constraints":{"card_types":["artifact"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"artifact"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AuriokTransfixer translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('benalish trapper', 'Benalish Trapper', '395ee92e1d81b2dd12ea924bf8824740', 'battle_rule_v1:872ba81bfcbb932c8efaf4d38c65bf95', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BenalishTrapper translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('blinding souleater', 'Blinding Souleater', 'c9011356cc6f198b00b028c021285cfe', 'battle_rule_v1:04f523606e21f77e119ce8bd414e8608', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W/P"],"activation_cost_generic":0,"activation_cost_mana":"{W/P}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W/P"],"activation_cost_generic":0,"activation_cost_mana":"{W/P}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BlindingSouleater translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('gideon''s lawkeeper', 'Gideon''s Lawkeeper', '395ee92e1d81b2dd12ea924bf8824740', 'battle_rule_v1:872ba81bfcbb932c8efaf4d38c65bf95', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GideonsLawkeeper translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('icy manipulator', 'Icy Manipulator', '24f1adf4de51b90f15fd3bd93bd70cc8', 'battle_rule_v1:63e27254b3adc36a05f73af796e69bcd', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"artifact_creature_or_land","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"artifact_creature_or_land","target_constraints":{"target":"artifact_creature_or_land"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"artifact_creature_or_land","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"artifact","target":"artifact_creature_or_land","target_constraints":{"target":"artifact_creature_or_land"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"artifact","target":"artifact_creature_or_land"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class IcyManipulator translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('loxodon mystic', 'Loxodon Mystic', '395ee92e1d81b2dd12ea924bf8824740', 'battle_rule_v1:872ba81bfcbb932c8efaf4d38c65bf95', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class LoxodonMystic translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('master decoy', 'Master Decoy', '395ee92e1d81b2dd12ea924bf8824740', 'battle_rule_v1:872ba81bfcbb932c8efaf4d38c65bf95', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MasterDecoy translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('minister of impediments', 'Minister of Impediments', '25b3d4db9fd3d800227311461850a713', 'battle_rule_v1:60b5e7c8253fdca947c993a4dbd2c228', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MinisterOfImpediments translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('ostiary thrull', 'Ostiary Thrull', '395ee92e1d81b2dd12ea924bf8824740', 'battle_rule_v1:872ba81bfcbb932c8efaf4d38c65bf95', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class OstiaryThrull translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('pacification array', 'Pacification Array', '90f2dc0a2d53d3a5c0b227a6101f35de', 'battle_rule_v1:bc9629927e8092d4cde65b83a60a18b7', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"artifact_or_creature","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{2}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"artifact_or_creature","target_constraints":{"card_types":["artifact","creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"artifact_or_creature","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{2}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"artifact","target":"artifact_or_creature","target_constraints":{"card_types":["artifact","creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"artifact","target":"artifact_or_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PacificationArray translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('scepter of dominance', 'Scepter of Dominance', '04346865443f8ec091f47540bdb58cc2', 'battle_rule_v1:1a0ebc49740451b5fcd9b855dcd8b2d0', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"permanent","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"permanent","target_constraints":{"card_types":["permanent"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"permanent","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"artifact","target":"permanent","target_constraints":{"card_types":["permanent"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"artifact","target":"permanent"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ScepterOfDominance translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
deprecated AS (
  UPDATE public.card_battle_rules r
  SET
    review_status = 'deprecated',
    execution_status = 'disabled',
    updated_at = now(),
    notes = concat_ws(E'\n', nullif(r.notes, ''), 'XMage batch package: deprecated stale shadow before curated batch rule upsert.')
  FROM proposed p
  WHERE (
        r.normalized_name = p.normalized_name
        OR r.normalized_name LIKE p.normalized_name || ' // %'
      )
    AND p.shadow_handling <> 'preserve_existing_rows'
    AND r.logical_rule_key <> p.logical_rule_key
  RETURNING r.*
)
SELECT count(*) AS deprecated_shadow_rows FROM deprecated;

WITH proposed(normalized_name, card_name, oracle_hash, logical_rule_key, effect_json, deck_role_json, source, confidence, review_status, execution_status, notes, shadow_handling) AS (
  VALUES
    ('auriok transfixer', 'Auriok Transfixer', 'c7268460c632adc5657e28602cb766a8', 'battle_rule_v1:a1ba4a819fe30a7f7bdd0b61eeaf0c09', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"artifact","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"artifact","target_constraints":{"card_types":["artifact"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"artifact","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"artifact","target_constraints":{"card_types":["artifact"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"artifact"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class AuriokTransfixer translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('benalish trapper', 'Benalish Trapper', '395ee92e1d81b2dd12ea924bf8824740', 'battle_rule_v1:872ba81bfcbb932c8efaf4d38c65bf95', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BenalishTrapper translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('blinding souleater', 'Blinding Souleater', 'c9011356cc6f198b00b028c021285cfe', 'battle_rule_v1:04f523606e21f77e119ce8bd414e8608', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W/P"],"activation_cost_generic":0,"activation_cost_mana":"{W/P}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W/P"],"activation_cost_generic":0,"activation_cost_mana":"{W/P}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class BlindingSouleater translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('gideon''s lawkeeper', 'Gideon''s Lawkeeper', '395ee92e1d81b2dd12ea924bf8824740', 'battle_rule_v1:872ba81bfcbb932c8efaf4d38c65bf95', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class GideonsLawkeeper translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('icy manipulator', 'Icy Manipulator', '24f1adf4de51b90f15fd3bd93bd70cc8', 'battle_rule_v1:63e27254b3adc36a05f73af796e69bcd', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"artifact_creature_or_land","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"artifact_creature_or_land","target_constraints":{"target":"artifact_creature_or_land"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"artifact_creature_or_land","activation_cost_colors":[],"activation_cost_generic":1,"activation_cost_mana":"{1}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"artifact","target":"artifact_creature_or_land","target_constraints":{"target":"artifact_creature_or_land"},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"artifact","target":"artifact_creature_or_land"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class IcyManipulator translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('loxodon mystic', 'Loxodon Mystic', '395ee92e1d81b2dd12ea924bf8824740', 'battle_rule_v1:872ba81bfcbb932c8efaf4d38c65bf95', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class LoxodonMystic translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('master decoy', 'Master Decoy', '395ee92e1d81b2dd12ea924bf8824740', 'battle_rule_v1:872ba81bfcbb932c8efaf4d38c65bf95', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MasterDecoy translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('minister of impediments', 'Minister of Impediments', '25b3d4db9fd3d800227311461850a713', 'battle_rule_v1:60b5e7c8253fdca947c993a4dbd2c228', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":[],"activation_cost_generic":0,"activation_cost_mana":"{0}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class MinisterOfImpediments translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('ostiary thrull', 'Ostiary Thrull', '395ee92e1d81b2dd12ea924bf8824740', 'battle_rule_v1:872ba81bfcbb932c8efaf4d38c65bf95', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"creature","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"creature","target":"creature","target_constraints":{"card_types":["creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"creature","target":"creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class OstiaryThrull translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('pacification array', 'Pacification Array', '90f2dc0a2d53d3a5c0b227a6101f35de', 'battle_rule_v1:bc9629927e8092d4cde65b83a60a18b7', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"artifact_or_creature","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{2}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"artifact_or_creature","target_constraints":{"card_types":["artifact","creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"artifact_or_creature","activation_cost_colors":[],"activation_cost_generic":2,"activation_cost_mana":"{2}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"artifact","target":"artifact_or_creature","target_constraints":{"card_types":["artifact","creature"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"artifact","target":"artifact_or_creature"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class PacificationArray translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows'),
    ('scepter of dominance', 'Scepter of Dominance', '04346865443f8ec091f47540bdb58cc2', 'battle_rule_v1:1a0ebc49740451b5fcd9b855dcd8b2d0', '{"_activated_rule_effects":[{"ability_kind":"activated","activated_effect":"tap_target","activated_tap_target":"permanent","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"tap_target","target":"permanent","target_constraints":{"card_types":["permanent"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}],"ability_kind":"static_and_activated","activated_battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","activated_effect":"tap_target","activated_tap_target":"permanent","activation_cost_colors":["W"],"activation_cost_generic":0,"activation_cost_mana":"{W}","activation_requires_sacrifice":false,"activation_requires_tap":true,"battle_model_scope":"xmage_permanent_simple_activated_tap_target_v1","effect":"artifact","target":"permanent","target_constraints":{"card_types":["permanent"]},"xmage_ability_class":"SimpleActivatedAbility","xmage_effect_class":"TapTargetEffect"}'::jsonb, '{"category":"unknown","effect":"artifact","target":"permanent"}'::jsonb, 'curated', 0.96, 'verified', 'auto', 'XMage authoritative exact-scope split: local class ScepterOfDominance translated into ManaLoom runtime scope xmage_permanent_simple_activated_tap_target_v1. This row is package-ready only because the source signature is a narrow runtime-backed exact-scope adapter with focused runtime coverage.', 'deprecate_nonmatching_rows')
),
matched_cards AS (
  SELECT
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    c.id AS card_id,
    c.name AS db_card_name
  FROM proposed p
  JOIN public.cards c
    ON (
         lower(c.name) = p.normalized_name
         OR split_part(lower(c.name), ' // ', 1) = p.normalized_name
       )
   AND md5(coalesce(c.oracle_text, '')) = p.oracle_hash
),
canonical_target_cards AS (
  SELECT
    p.*,
    min(m.card_id::text)::uuid AS card_id,
    min(m.db_card_name) AS db_card_name
  FROM proposed p
  JOIN matched_cards m
    USING (normalized_name, card_name, oracle_hash)
  GROUP BY
    p.normalized_name,
    p.card_name,
    p.oracle_hash,
    p.logical_rule_key,
    p.effect_json,
    p.deck_role_json,
    p.source,
    p.confidence,
    p.review_status,
    p.execution_status,
    p.notes,
    p.shadow_handling
),
upserted AS (
  INSERT INTO public.card_battle_rules (
    normalized_name,
    card_id,
    card_name,
    effect_json,
    deck_role_json,
    source,
    confidence,
    review_status,
    rule_version,
    oracle_hash,
    notes,
    reviewed_by,
    reviewed_at,
    created_at,
    updated_at,
    last_seen_at,
    logical_rule_key,
    execution_status
  )
  SELECT
    normalized_name,
    card_id,
    db_card_name,
    effect_json,
    deck_role_json,
    source,
    confidence,
    review_status,
    2,
    oracle_hash,
    notes,
    'codex-xmage-batch',
    now(),
    now(),
    now(),
    now(),
    logical_rule_key,
    execution_status
  FROM canonical_target_cards
  ON CONFLICT (normalized_name, logical_rule_key) DO UPDATE
  SET
    card_id = EXCLUDED.card_id,
    card_name = EXCLUDED.card_name,
    effect_json = EXCLUDED.effect_json,
    deck_role_json = EXCLUDED.deck_role_json,
    source = EXCLUDED.source,
    confidence = EXCLUDED.confidence,
    review_status = EXCLUDED.review_status,
    rule_version = EXCLUDED.rule_version,
    oracle_hash = EXCLUDED.oracle_hash,
    notes = EXCLUDED.notes,
    reviewed_by = EXCLUDED.reviewed_by,
    reviewed_at = EXCLUDED.reviewed_at,
    updated_at = EXCLUDED.updated_at,
    last_seen_at = EXCLUDED.last_seen_at,
    execution_status = EXCLUDED.execution_status
  RETURNING *
)
SELECT count(*) AS upserted_rows FROM upserted;

COMMIT;
